%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_A_STEP_1 != constr_CONST_0x30).
fof(ax1, axiom,
constr_A_STEP_1 != constr_CONST_1).
fof(ax2, axiom,
constr_A_STEP_1 != constr_CONST_2).
fof(ax3, axiom,
constr_A_STEP_1 != constr_CONST_3).
fof(ax4, axiom,
constr_A_STEP_1 != constr_CONST_4).
fof(ax5, axiom,
constr_A_STEP_1 != constr_ZERO).
fof(ax6, axiom,
constr_A_STEP_1 != name_a).
fof(ax7, axiom,
constr_A_STEP_1 != name_b).
fof(ax8, axiom,
constr_A_STEP_1 != name_c).
fof(ax9, axiom,
constr_A_STEP_1 != name_k).
fof(ax10, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax11, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax12, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax13, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax14, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax15, axiom,
constr_CONST_0x30 != name_a).
fof(ax16, axiom,
constr_CONST_0x30 != name_b).
fof(ax17, axiom,
constr_CONST_0x30 != name_c).
fof(ax18, axiom,
constr_CONST_0x30 != name_k).
fof(ax19, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax20, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax21, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax22, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax23, axiom,
constr_CONST_1 != name_a).
fof(ax24, axiom,
constr_CONST_1 != name_b).
fof(ax25, axiom,
constr_CONST_1 != name_c).
fof(ax26, axiom,
constr_CONST_1 != name_k).
fof(ax27, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax28, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax29, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax30, axiom,
constr_CONST_2 != name_a).
fof(ax31, axiom,
constr_CONST_2 != name_b).
fof(ax32, axiom,
constr_CONST_2 != name_c).
fof(ax33, axiom,
constr_CONST_2 != name_k).
fof(ax34, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax35, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax36, axiom,
constr_CONST_3 != name_a).
fof(ax37, axiom,
constr_CONST_3 != name_b).
fof(ax38, axiom,
constr_CONST_3 != name_c).
fof(ax39, axiom,
constr_CONST_3 != name_k).
fof(ax40, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax41, axiom,
constr_CONST_4 != name_a).
fof(ax42, axiom,
constr_CONST_4 != name_b).
fof(ax43, axiom,
constr_CONST_4 != name_c).
fof(ax44, axiom,
constr_CONST_4 != name_k).
fof(ax45, axiom,
constr_ZERO != name_a).
fof(ax46, axiom,
constr_ZERO != name_b).
fof(ax47, axiom,
constr_ZERO != name_c).
fof(ax48, axiom,
constr_ZERO != name_k).
fof(ax49, axiom,
name_a != name_b).
fof(ax50, axiom,
name_a != name_c).
fof(ax51, axiom,
name_a != name_k).
fof(ax52, axiom,
name_b != name_c).
fof(ax53, axiom,
name_b != name_k).
fof(ax54, axiom,
name_c != name_k).
fof(ax55, axiom,
![VAR_X_17, VAR_Y_18] : (constr_split(constr_concat(VAR_X_17, VAR_Y_18)) = tuple_2(VAR_X_17, VAR_Y_18))).
fof(ax56, axiom,
![VAR_U_0X30, VAR_V_14, VAR_X_15, VAR_Y_16] : (constr_concat(constr_xor(VAR_U_0X30, VAR_X_15), constr_xor(VAR_V_14, VAR_Y_16)) = constr_xor(constr_concat(VAR_U_0X30, VAR_V_14), constr_concat(VAR_X_15, VAR_Y_16)))).
fof(ax57, axiom,
![VAR_X_12, VAR_Y_13] : (constr_crc(constr_xor(VAR_X_12, VAR_Y_13)) = constr_xor(constr_crc(VAR_X_12), constr_crc(VAR_Y_13)))).
fof(ax58, axiom,
![VAR_X_11] : (constr_xor(VAR_X_11, VAR_X_11) = constr_ZERO)).
fof(ax59, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, constr_ZERO) = VAR_X_10X30)).
fof(ax60, axiom,
![VAR_X_8, VAR_Y_9] : (constr_xor(VAR_X_8, VAR_Y_9) = constr_xor(VAR_Y_9, VAR_X_8))).
fof(ax61, axiom,
![VAR_X_7, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_7, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_7, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax62, axiom,
![VAR_X_31] : (pred_eq(VAR_X_31, VAR_X_31))).
fof(ax63, axiom,
![VAR_V_38, VAR_V_39] : ((pred_attacker(VAR_V_38) & pred_attacker(VAR_V_39)) => pred_attacker(constr_xor(VAR_V_38, VAR_V_39)))).
fof(ax64, axiom,
pred_attacker(tuple_true)).
fof(ax65, axiom,
![VAR_V_41] : (pred_attacker(VAR_V_41) => pred_attacker(constr_split(VAR_V_41)))).
fof(ax66, axiom,
pred_attacker(tuple_false)).
fof(ax67, axiom,
![VAR_V_44] : (pred_attacker(VAR_V_44) => pred_attacker(constr_crc(VAR_V_44)))).
fof(ax68, axiom,
![VAR_V_47, VAR_V_48] : ((pred_attacker(VAR_V_47) & pred_attacker(VAR_V_48)) => pred_attacker(constr_concat(VAR_V_47, VAR_V_48)))).
fof(ax69, axiom,
pred_attacker(constr_ZERO)).
fof(ax70, axiom,
pred_attacker(constr_CONST_4)).
fof(ax71, axiom,
pred_attacker(constr_CONST_3)).
fof(ax72, axiom,
pred_attacker(constr_CONST_2)).
fof(ax73, axiom,
pred_attacker(constr_CONST_1)).
fof(ax74, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax75, axiom,
pred_attacker(constr_A_STEP_1)).
fof(ax76, axiom,
![VAR_V_56, VAR_V_57, VAR_V_58] : ((pred_attacker(VAR_V_56) & pred_attacker(VAR_V_57) & pred_attacker(VAR_V_58)) => pred_attacker(tuple_3(VAR_V_56, VAR_V_57, VAR_V_58)))).
fof(ax77, axiom,
![VAR_V_71, VAR_V_72, VAR_V_73] : (pred_attacker(tuple_3(VAR_V_71, VAR_V_72, VAR_V_73)) => pred_attacker(VAR_V_71))).
fof(ax78, axiom,
![VAR_V_75, VAR_V_76, VAR_V_77] : (pred_attacker(tuple_3(VAR_V_75, VAR_V_76, VAR_V_77)) => pred_attacker(VAR_V_76))).
fof(ax79, axiom,
![VAR_V_79, VAR_V_80X30, VAR_V_81] : (pred_attacker(tuple_3(VAR_V_79, VAR_V_80X30, VAR_V_81)) => pred_attacker(VAR_V_81))).
fof(ax80, axiom,
![VAR_V_85, VAR_V_86] : ((pred_attacker(VAR_V_85) & pred_attacker(VAR_V_86)) => pred_attacker(tuple_2(VAR_V_85, VAR_V_86)))).
fof(ax81, axiom,
![VAR_V_93, VAR_V_94] : (pred_attacker(tuple_2(VAR_V_93, VAR_V_94)) => pred_attacker(VAR_V_93))).
fof(ax82, axiom,
![VAR_V_96, VAR_V_97] : (pred_attacker(tuple_2(VAR_V_96, VAR_V_97)) => pred_attacker(VAR_V_97))).
fof(ax83, axiom,
![VAR_V_99, VAR_V_10X300X30] : ((pred_mess(VAR_V_10X300X30, VAR_V_99) & pred_attacker(VAR_V_10X300X30)) => pred_attacker(VAR_V_99))).
fof(ax84, axiom,
![VAR_V_10X301, VAR_V_10X302] : ((pred_attacker(VAR_V_10X302) & pred_attacker(VAR_V_10X301)) => pred_mess(VAR_V_10X302, VAR_V_10X301))).
fof(ax85, axiom,
pred_attacker(name_c)).
fof(ax86, axiom,
![VAR_V_10X304] : (pred_equal(VAR_V_10X304, VAR_V_10X304))).
fof(ax87, axiom,
![VAR_V_10X305] : (pred_attacker(name_new0x2Dname(VAR_V_10X305)))).
fof(ax88, axiom,
pred_attacker(tuple_2(tuple_3(name_a, constr_xor(name_a, name_k), constr_xor(name_b, name_k)), constr_A_STEP_1))).
fof(co0, conjecture,
pred_attacker(name_b)).
