%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_A1 != constr_A2).
fof(ax1, axiom,
constr_A1 != constr_B1).
fof(ax2, axiom,
constr_A1 != constr_B2).
fof(ax3, axiom,
constr_A1 != constr_CONST_0x30).
fof(ax4, axiom,
constr_A1 != constr_CONST_1).
fof(ax5, axiom,
constr_A1 != constr_CONST_2).
fof(ax6, axiom,
constr_A1 != constr_CONST_3).
fof(ax7, axiom,
constr_A1 != constr_CONST_4).
fof(ax8, axiom,
constr_A1 != name_c).
fof(ax9, axiom,
constr_A2 != constr_B1).
fof(ax10, axiom,
constr_A2 != constr_B2).
fof(ax11, axiom,
constr_A2 != constr_CONST_0x30).
fof(ax12, axiom,
constr_A2 != constr_CONST_1).
fof(ax13, axiom,
constr_A2 != constr_CONST_2).
fof(ax14, axiom,
constr_A2 != constr_CONST_3).
fof(ax15, axiom,
constr_A2 != constr_CONST_4).
fof(ax16, axiom,
constr_A2 != name_c).
fof(ax17, axiom,
constr_B1 != constr_B2).
fof(ax18, axiom,
constr_B1 != constr_CONST_0x30).
fof(ax19, axiom,
constr_B1 != constr_CONST_1).
fof(ax20, axiom,
constr_B1 != constr_CONST_2).
fof(ax21, axiom,
constr_B1 != constr_CONST_3).
fof(ax22, axiom,
constr_B1 != constr_CONST_4).
fof(ax23, axiom,
constr_B1 != name_c).
fof(ax24, axiom,
constr_B2 != constr_CONST_0x30).
fof(ax25, axiom,
constr_B2 != constr_CONST_1).
fof(ax26, axiom,
constr_B2 != constr_CONST_2).
fof(ax27, axiom,
constr_B2 != constr_CONST_3).
fof(ax28, axiom,
constr_B2 != constr_CONST_4).
fof(ax29, axiom,
constr_B2 != name_c).
fof(ax30, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax31, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax32, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax33, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax34, axiom,
constr_CONST_0x30 != name_c).
fof(ax35, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax36, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax37, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax38, axiom,
constr_CONST_1 != name_c).
fof(ax39, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax40, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax41, axiom,
constr_CONST_2 != name_c).
fof(ax42, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax43, axiom,
constr_CONST_3 != name_c).
fof(ax44, axiom,
constr_CONST_4 != name_c).
fof(ax45, axiom,
![VAR_X_13, VAR_Y_0X30] : (constr_split(constr_concat(VAR_X_13, VAR_Y_0X30)) = tuple_2(VAR_X_13, VAR_Y_0X30))).
fof(ax46, axiom,
![VAR_X0X30_11, VAR_X1_12] : (constr_d_2_get_1(tuple_d(VAR_X0X30_11, VAR_X1_12)) = VAR_X1_12)).
fof(ax47, axiom,
![VAR_X0X30_9, VAR_X1_10X30] : (constr_d_2_get_0x30(tuple_d(VAR_X0X30_9, VAR_X1_10X30)) = VAR_X0X30_9)).
fof(ax48, axiom,
![VAR_X0X30_7, VAR_X1_8] : (constr_tuple_2_get_1(tuple_2(VAR_X0X30_7, VAR_X1_8)) = VAR_X1_8)).
fof(ax49, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30] : (constr_tuple_2_get_0x30(tuple_2(VAR_X0X30_0X30, VAR_X1_0X30)) = VAR_X0X30_0X30)).
fof(ax50, axiom,
![VAR_X_31] : (pred_eq(VAR_X_31, VAR_X_31))).
fof(ax51, axiom,
![VAR_V_37] : (pred_attacker(VAR_V_37) => pred_attacker(constr_tuple_2_get_1(VAR_V_37)))).
fof(ax52, axiom,
![VAR_V_39] : (pred_attacker(VAR_V_39) => pred_attacker(constr_tuple_2_get_0x30(VAR_V_39)))).
fof(ax53, axiom,
pred_attacker(tuple_true)).
fof(ax54, axiom,
![VAR_V_41] : (pred_attacker(VAR_V_41) => pred_attacker(constr_split(VAR_V_41)))).
fof(ax55, axiom,
pred_attacker(tuple_false)).
fof(ax56, axiom,
![VAR_V_44] : (pred_attacker(VAR_V_44) => pred_attacker(constr_d_2_get_1(VAR_V_44)))).
fof(ax57, axiom,
![VAR_V_46] : (pred_attacker(VAR_V_46) => pred_attacker(constr_d_2_get_0x30(VAR_V_46)))).
fof(ax58, axiom,
![VAR_V_49, VAR_V_50X30] : ((pred_attacker(VAR_V_49) & pred_attacker(VAR_V_50X30)) => pred_attacker(tuple_d(VAR_V_49, VAR_V_50X30)))).
fof(ax59, axiom,
![VAR_V_57, VAR_V_58] : (pred_attacker(tuple_d(VAR_V_57, VAR_V_58)) => pred_attacker(VAR_V_57))).
fof(ax60, axiom,
![VAR_V_60X30, VAR_V_61] : (pred_attacker(tuple_d(VAR_V_60X30, VAR_V_61)) => pred_attacker(VAR_V_61))).
fof(ax61, axiom,
![VAR_V_65, VAR_V_66] : ((pred_attacker(VAR_V_65) & pred_attacker(VAR_V_66)) => pred_attacker(constr_concat(VAR_V_65, VAR_V_66)))).
fof(ax62, axiom,
pred_attacker(constr_CONST_4)).
fof(ax63, axiom,
pred_attacker(constr_CONST_3)).
fof(ax64, axiom,
pred_attacker(constr_CONST_2)).
fof(ax65, axiom,
pred_attacker(constr_CONST_1)).
fof(ax66, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax67, axiom,
pred_attacker(constr_B2)).
fof(ax68, axiom,
pred_attacker(constr_B1)).
fof(ax69, axiom,
pred_attacker(constr_A2)).
fof(ax70, axiom,
pred_attacker(constr_A1)).
fof(ax71, axiom,
![VAR_V_75, VAR_V_76, VAR_V_77, VAR_V_78] : ((pred_attacker(VAR_V_75) & pred_attacker(VAR_V_76) & pred_attacker(VAR_V_77) & pred_attacker(VAR_V_78)) => pred_attacker(tuple_4(VAR_V_75, VAR_V_76, VAR_V_77, VAR_V_78)))).
fof(ax72, axiom,
![VAR_V_99, VAR_V_10X300X30, VAR_V_10X301, VAR_V_10X302] : (pred_attacker(tuple_4(VAR_V_99, VAR_V_10X300X30, VAR_V_10X301, VAR_V_10X302)) => pred_attacker(VAR_V_99))).
fof(ax73, axiom,
![VAR_V_10X304, VAR_V_10X305, VAR_V_10X306, VAR_V_10X307] : (pred_attacker(tuple_4(VAR_V_10X304, VAR_V_10X305, VAR_V_10X306, VAR_V_10X307)) => pred_attacker(VAR_V_10X305))).
fof(ax74, axiom,
![VAR_V_10X309, VAR_V_110X30, VAR_V_111, VAR_V_112] : (pred_attacker(tuple_4(VAR_V_10X309, VAR_V_110X30, VAR_V_111, VAR_V_112)) => pred_attacker(VAR_V_111))).
fof(ax75, axiom,
![VAR_V_114, VAR_V_115, VAR_V_116, VAR_V_117] : (pred_attacker(tuple_4(VAR_V_114, VAR_V_115, VAR_V_116, VAR_V_117)) => pred_attacker(VAR_V_117))).
fof(ax76, axiom,
![VAR_V_121, VAR_V_122] : ((pred_attacker(VAR_V_121) & pred_attacker(VAR_V_122)) => pred_attacker(tuple_2(VAR_V_121, VAR_V_122)))).
fof(ax77, axiom,
![VAR_V_129, VAR_V_130X30] : (pred_attacker(tuple_2(VAR_V_129, VAR_V_130X30)) => pred_attacker(VAR_V_129))).
fof(ax78, axiom,
![VAR_V_132, VAR_V_133] : (pred_attacker(tuple_2(VAR_V_132, VAR_V_133)) => pred_attacker(VAR_V_133))).
fof(ax79, axiom,
![VAR_V_135, VAR_V_136] : ((pred_mess(VAR_V_136, VAR_V_135) & pred_attacker(VAR_V_136)) => pred_attacker(VAR_V_135))).
fof(ax80, axiom,
![VAR_V_137, VAR_V_138] : ((pred_attacker(VAR_V_138) & pred_attacker(VAR_V_137)) => pred_mess(VAR_V_138, VAR_V_137))).
fof(ax81, axiom,
pred_attacker(name_c)).
fof(ax82, axiom,
![VAR_V_140X30] : (pred_equal(VAR_V_140X30, VAR_V_140X30))).
fof(ax83, axiom,
![VAR_V_141] : (pred_attacker(name_new0x2Dname(VAR_V_141)))).
fof(ax84, axiom,
![VAR_MSG_183] : (pred_attacker(VAR_MSG_183) => pred_attacker(constr_A1))).
fof(ax85, axiom,
![VAR_MSG_216] : (pred_attacker(VAR_MSG_216) => pred_attacker(constr_B1))).
fof(co0, conjecture,
pred_attacker(tuple_4(constr_A1, constr_A2, constr_B1, constr_B2))).
