%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_A1 != constr_A2).
fof(ax1, axiom,
constr_A1 != constr_B1).
fof(ax2, axiom,
constr_A1 != constr_B2).
fof(ax3, axiom,
constr_A1 != constr_CONST_0x30).
fof(ax4, axiom,
constr_A1 != constr_CONST_1).
fof(ax5, axiom,
constr_A1 != constr_CONST_2).
fof(ax6, axiom,
constr_A1 != constr_CONST_3).
fof(ax7, axiom,
constr_A1 != constr_CONST_4).
fof(ax8, axiom,
constr_A1 != constr_E1).
fof(ax9, axiom,
constr_A1 != constr_E2).
fof(ax10, axiom,
constr_A1 != name_c).
fof(ax11, axiom,
constr_A2 != constr_B1).
fof(ax12, axiom,
constr_A2 != constr_B2).
fof(ax13, axiom,
constr_A2 != constr_CONST_0x30).
fof(ax14, axiom,
constr_A2 != constr_CONST_1).
fof(ax15, axiom,
constr_A2 != constr_CONST_2).
fof(ax16, axiom,
constr_A2 != constr_CONST_3).
fof(ax17, axiom,
constr_A2 != constr_CONST_4).
fof(ax18, axiom,
constr_A2 != constr_E1).
fof(ax19, axiom,
constr_A2 != constr_E2).
fof(ax20, axiom,
constr_A2 != name_c).
fof(ax21, axiom,
constr_B1 != constr_B2).
fof(ax22, axiom,
constr_B1 != constr_CONST_0x30).
fof(ax23, axiom,
constr_B1 != constr_CONST_1).
fof(ax24, axiom,
constr_B1 != constr_CONST_2).
fof(ax25, axiom,
constr_B1 != constr_CONST_3).
fof(ax26, axiom,
constr_B1 != constr_CONST_4).
fof(ax27, axiom,
constr_B1 != constr_E1).
fof(ax28, axiom,
constr_B1 != constr_E2).
fof(ax29, axiom,
constr_B1 != name_c).
fof(ax30, axiom,
constr_B2 != constr_CONST_0x30).
fof(ax31, axiom,
constr_B2 != constr_CONST_1).
fof(ax32, axiom,
constr_B2 != constr_CONST_2).
fof(ax33, axiom,
constr_B2 != constr_CONST_3).
fof(ax34, axiom,
constr_B2 != constr_CONST_4).
fof(ax35, axiom,
constr_B2 != constr_E1).
fof(ax36, axiom,
constr_B2 != constr_E2).
fof(ax37, axiom,
constr_B2 != name_c).
fof(ax38, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax39, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax40, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax41, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax42, axiom,
constr_CONST_0x30 != constr_E1).
fof(ax43, axiom,
constr_CONST_0x30 != constr_E2).
fof(ax44, axiom,
constr_CONST_0x30 != name_c).
fof(ax45, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax46, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax47, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax48, axiom,
constr_CONST_1 != constr_E1).
fof(ax49, axiom,
constr_CONST_1 != constr_E2).
fof(ax50, axiom,
constr_CONST_1 != name_c).
fof(ax51, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax52, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax53, axiom,
constr_CONST_2 != constr_E1).
fof(ax54, axiom,
constr_CONST_2 != constr_E2).
fof(ax55, axiom,
constr_CONST_2 != name_c).
fof(ax56, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax57, axiom,
constr_CONST_3 != constr_E1).
fof(ax58, axiom,
constr_CONST_3 != constr_E2).
fof(ax59, axiom,
constr_CONST_3 != name_c).
fof(ax60, axiom,
constr_CONST_4 != constr_E1).
fof(ax61, axiom,
constr_CONST_4 != constr_E2).
fof(ax62, axiom,
constr_CONST_4 != name_c).
fof(ax63, axiom,
constr_E1 != constr_E2).
fof(ax64, axiom,
constr_E1 != name_c).
fof(ax65, axiom,
constr_E2 != name_c).
fof(ax66, axiom,
![VAR_X_13, VAR_Y_0X30] : (constr_split(constr_concat(VAR_X_13, VAR_Y_0X30)) = tuple_2(VAR_X_13, VAR_Y_0X30))).
fof(ax67, axiom,
![VAR_X0X30_11, VAR_X1_12] : (constr_d_2_get_1(tuple_d(VAR_X0X30_11, VAR_X1_12)) = VAR_X1_12)).
fof(ax68, axiom,
![VAR_X0X30_9, VAR_X1_10X30] : (constr_d_2_get_0x30(tuple_d(VAR_X0X30_9, VAR_X1_10X30)) = VAR_X0X30_9)).
fof(ax69, axiom,
![VAR_X0X30_7, VAR_X1_8] : (constr_tuple_2_get_1(tuple_2(VAR_X0X30_7, VAR_X1_8)) = VAR_X1_8)).
fof(ax70, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30] : (constr_tuple_2_get_0x30(tuple_2(VAR_X0X30_0X30, VAR_X1_0X30)) = VAR_X0X30_0X30)).
fof(ax71, axiom,
![VAR_X_28] : (pred_eq(VAR_X_28, VAR_X_28))).
fof(ax72, axiom,
![VAR_V_34] : (pred_attacker(VAR_V_34) => pred_attacker(constr_tuple_2_get_1(VAR_V_34)))).
fof(ax73, axiom,
![VAR_V_36] : (pred_attacker(VAR_V_36) => pred_attacker(constr_tuple_2_get_0x30(VAR_V_36)))).
fof(ax74, axiom,
pred_attacker(tuple_true)).
fof(ax75, axiom,
![VAR_V_38] : (pred_attacker(VAR_V_38) => pred_attacker(constr_split(VAR_V_38)))).
fof(ax76, axiom,
pred_attacker(tuple_false)).
fof(ax77, axiom,
![VAR_V_41] : (pred_attacker(VAR_V_41) => pred_attacker(constr_d_2_get_1(VAR_V_41)))).
fof(ax78, axiom,
![VAR_V_43] : (pred_attacker(VAR_V_43) => pred_attacker(constr_d_2_get_0x30(VAR_V_43)))).
fof(ax79, axiom,
![VAR_V_46, VAR_V_47] : ((pred_attacker(VAR_V_46) & pred_attacker(VAR_V_47)) => pred_attacker(tuple_d(VAR_V_46, VAR_V_47)))).
fof(ax80, axiom,
![VAR_V_54, VAR_V_55] : (pred_attacker(tuple_d(VAR_V_54, VAR_V_55)) => pred_attacker(VAR_V_54))).
fof(ax81, axiom,
![VAR_V_57, VAR_V_58] : (pred_attacker(tuple_d(VAR_V_57, VAR_V_58)) => pred_attacker(VAR_V_58))).
fof(ax82, axiom,
![VAR_V_62, VAR_V_63] : ((pred_attacker(VAR_V_62) & pred_attacker(VAR_V_63)) => pred_attacker(constr_concat(VAR_V_62, VAR_V_63)))).
fof(ax83, axiom,
pred_attacker(constr_E2)).
fof(ax84, axiom,
pred_attacker(constr_E1)).
fof(ax85, axiom,
pred_attacker(constr_CONST_4)).
fof(ax86, axiom,
pred_attacker(constr_CONST_3)).
fof(ax87, axiom,
pred_attacker(constr_CONST_2)).
fof(ax88, axiom,
pred_attacker(constr_CONST_1)).
fof(ax89, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax90, axiom,
pred_attacker(constr_B2)).
fof(ax91, axiom,
pred_attacker(constr_B1)).
fof(ax92, axiom,
pred_attacker(constr_A2)).
fof(ax93, axiom,
pred_attacker(constr_A1)).
fof(ax94, axiom,
![VAR_V_72, VAR_V_73, VAR_V_74, VAR_V_75] : ((pred_attacker(VAR_V_72) & pred_attacker(VAR_V_73) & pred_attacker(VAR_V_74) & pred_attacker(VAR_V_75)) => pred_attacker(tuple_4(VAR_V_72, VAR_V_73, VAR_V_74, VAR_V_75)))).
fof(ax95, axiom,
![VAR_V_96, VAR_V_97, VAR_V_98, VAR_V_99] : (pred_attacker(tuple_4(VAR_V_96, VAR_V_97, VAR_V_98, VAR_V_99)) => pred_attacker(VAR_V_96))).
fof(ax96, axiom,
![VAR_V_10X301, VAR_V_10X302, VAR_V_10X303, VAR_V_10X304] : (pred_attacker(tuple_4(VAR_V_10X301, VAR_V_10X302, VAR_V_10X303, VAR_V_10X304)) => pred_attacker(VAR_V_10X302))).
fof(ax97, axiom,
![VAR_V_10X306, VAR_V_10X307, VAR_V_10X308, VAR_V_10X309] : (pred_attacker(tuple_4(VAR_V_10X306, VAR_V_10X307, VAR_V_10X308, VAR_V_10X309)) => pred_attacker(VAR_V_10X308))).
fof(ax98, axiom,
![VAR_V_111, VAR_V_112, VAR_V_113, VAR_V_114] : (pred_attacker(tuple_4(VAR_V_111, VAR_V_112, VAR_V_113, VAR_V_114)) => pred_attacker(VAR_V_114))).
fof(ax99, axiom,
![VAR_V_118, VAR_V_119] : ((pred_attacker(VAR_V_118) & pred_attacker(VAR_V_119)) => pred_attacker(tuple_2(VAR_V_118, VAR_V_119)))).
fof(ax100, axiom,
![VAR_V_126, VAR_V_127] : (pred_attacker(tuple_2(VAR_V_126, VAR_V_127)) => pred_attacker(VAR_V_126))).
fof(ax101, axiom,
![VAR_V_129, VAR_V_130X30] : (pred_attacker(tuple_2(VAR_V_129, VAR_V_130X30)) => pred_attacker(VAR_V_130X30))).
fof(ax102, axiom,
![VAR_V_132, VAR_V_133] : ((pred_mess(VAR_V_133, VAR_V_132) & pred_attacker(VAR_V_133)) => pred_attacker(VAR_V_132))).
fof(ax103, axiom,
![VAR_V_134, VAR_V_135] : ((pred_attacker(VAR_V_135) & pred_attacker(VAR_V_134)) => pred_mess(VAR_V_135, VAR_V_134))).
fof(ax104, axiom,
pred_attacker(name_c)).
fof(ax105, axiom,
![VAR_V_137] : (pred_equal(VAR_V_137, VAR_V_137))).
fof(ax106, axiom,
![VAR_V_138] : (pred_attacker(name_new0x2Dname(VAR_V_138)))).
fof(ax107, axiom,
![VAR_MSG_180X30] : ((pred_eq(constr_tuple_2_get_1(constr_tuple_2_get_1(constr_split(VAR_MSG_180X30))), constr_E2) & pred_eq(constr_tuple_2_get_0x30(constr_split(VAR_MSG_180X30)), constr_E1) & pred_attacker(VAR_MSG_180X30)) => pred_attacker(constr_A1))).
fof(ax108, axiom,
![VAR_MSG_182] : ((pred_eq(constr_tuple_2_get_0x30(constr_split(VAR_MSG_182)), constr_E1) & pred_attacker(VAR_MSG_182)) => pred_attacker(constr_A2))).
fof(ax109, axiom,
![VAR_MSG_185] : (pred_attacker(VAR_MSG_185) => pred_attacker(constr_A2))).
fof(ax110, axiom,
![VAR_MSG_215] : ((pred_eq(constr_d_2_get_1(constr_d_2_get_1(VAR_MSG_215)), constr_E2) & pred_eq(constr_d_2_get_0x30(VAR_MSG_215), constr_E1) & pred_attacker(VAR_MSG_215)) => pred_attacker(constr_B1))).
fof(ax111, axiom,
![VAR_MSG_217] : ((pred_eq(constr_d_2_get_0x30(VAR_MSG_217), constr_E1) & pred_attacker(VAR_MSG_217)) => pred_attacker(constr_B2))).
fof(ax112, axiom,
![VAR_MSG_220X30] : (pred_attacker(VAR_MSG_220X30) => pred_attacker(constr_B2))).
fof(co0, conjecture,
pred_attacker(tuple_4(constr_A1, constr_A2, constr_B1, constr_B2))).
