%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax5, axiom,
constr_CONST_0x30 != constr_client_A_STEP_1).
fof(ax6, axiom,
constr_CONST_0x30 != constr_client_A_STEP_2).
fof(ax7, axiom,
constr_CONST_0x30 != constr_client_B_STEP_1).
fof(ax8, axiom,
constr_CONST_0x30 != constr_client_B_STEP_2).
fof(ax9, axiom,
constr_CONST_0x30 != constr_client_C_STEP_1).
fof(ax10, axiom,
constr_CONST_0x30 != constr_client_C_STEP_2).
fof(ax11, axiom,
constr_CONST_0x30 != constr_client_C_STEP_3).
fof(ax12, axiom,
constr_CONST_0x30 != constr_client_C_STEP_4).
fof(ax13, axiom,
constr_CONST_0x30 != constr_server_S_STEP_1).
fof(ax14, axiom,
constr_CONST_0x30 != name_A).
fof(ax15, axiom,
constr_CONST_0x30 != name_B).
fof(ax16, axiom,
constr_CONST_0x30 != name_C).
fof(ax17, axiom,
constr_CONST_0x30 != name_Kab_40x30).
fof(ax18, axiom,
constr_CONST_0x30 != name_Kas).
fof(ax19, axiom,
constr_CONST_0x30 != name_Kbc_41).
fof(ax20, axiom,
constr_CONST_0x30 != name_Kbs).
fof(ax21, axiom,
constr_CONST_0x30 != name_Kcs).
fof(ax22, axiom,
constr_CONST_0x30 != name_Na).
fof(ax23, axiom,
constr_CONST_0x30 != name_S).
fof(ax24, axiom,
constr_CONST_0x30 != name_c).
fof(ax25, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax26, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax27, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax28, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax29, axiom,
constr_CONST_1 != constr_client_A_STEP_1).
fof(ax30, axiom,
constr_CONST_1 != constr_client_A_STEP_2).
fof(ax31, axiom,
constr_CONST_1 != constr_client_B_STEP_1).
fof(ax32, axiom,
constr_CONST_1 != constr_client_B_STEP_2).
fof(ax33, axiom,
constr_CONST_1 != constr_client_C_STEP_1).
fof(ax34, axiom,
constr_CONST_1 != constr_client_C_STEP_2).
fof(ax35, axiom,
constr_CONST_1 != constr_client_C_STEP_3).
fof(ax36, axiom,
constr_CONST_1 != constr_client_C_STEP_4).
fof(ax37, axiom,
constr_CONST_1 != constr_server_S_STEP_1).
fof(ax38, axiom,
constr_CONST_1 != name_A).
fof(ax39, axiom,
constr_CONST_1 != name_B).
fof(ax40, axiom,
constr_CONST_1 != name_C).
fof(ax41, axiom,
constr_CONST_1 != name_Kab_40x30).
fof(ax42, axiom,
constr_CONST_1 != name_Kas).
fof(ax43, axiom,
constr_CONST_1 != name_Kbc_41).
fof(ax44, axiom,
constr_CONST_1 != name_Kbs).
fof(ax45, axiom,
constr_CONST_1 != name_Kcs).
fof(ax46, axiom,
constr_CONST_1 != name_Na).
fof(ax47, axiom,
constr_CONST_1 != name_S).
fof(ax48, axiom,
constr_CONST_1 != name_c).
fof(ax49, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax50, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax51, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax52, axiom,
constr_CONST_2 != constr_client_A_STEP_1).
fof(ax53, axiom,
constr_CONST_2 != constr_client_A_STEP_2).
fof(ax54, axiom,
constr_CONST_2 != constr_client_B_STEP_1).
fof(ax55, axiom,
constr_CONST_2 != constr_client_B_STEP_2).
fof(ax56, axiom,
constr_CONST_2 != constr_client_C_STEP_1).
fof(ax57, axiom,
constr_CONST_2 != constr_client_C_STEP_2).
fof(ax58, axiom,
constr_CONST_2 != constr_client_C_STEP_3).
fof(ax59, axiom,
constr_CONST_2 != constr_client_C_STEP_4).
fof(ax60, axiom,
constr_CONST_2 != constr_server_S_STEP_1).
fof(ax61, axiom,
constr_CONST_2 != name_A).
fof(ax62, axiom,
constr_CONST_2 != name_B).
fof(ax63, axiom,
constr_CONST_2 != name_C).
fof(ax64, axiom,
constr_CONST_2 != name_Kab_40x30).
fof(ax65, axiom,
constr_CONST_2 != name_Kas).
fof(ax66, axiom,
constr_CONST_2 != name_Kbc_41).
fof(ax67, axiom,
constr_CONST_2 != name_Kbs).
fof(ax68, axiom,
constr_CONST_2 != name_Kcs).
fof(ax69, axiom,
constr_CONST_2 != name_Na).
fof(ax70, axiom,
constr_CONST_2 != name_S).
fof(ax71, axiom,
constr_CONST_2 != name_c).
fof(ax72, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax73, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax74, axiom,
constr_CONST_3 != constr_client_A_STEP_1).
fof(ax75, axiom,
constr_CONST_3 != constr_client_A_STEP_2).
fof(ax76, axiom,
constr_CONST_3 != constr_client_B_STEP_1).
fof(ax77, axiom,
constr_CONST_3 != constr_client_B_STEP_2).
fof(ax78, axiom,
constr_CONST_3 != constr_client_C_STEP_1).
fof(ax79, axiom,
constr_CONST_3 != constr_client_C_STEP_2).
fof(ax80, axiom,
constr_CONST_3 != constr_client_C_STEP_3).
fof(ax81, axiom,
constr_CONST_3 != constr_client_C_STEP_4).
fof(ax82, axiom,
constr_CONST_3 != constr_server_S_STEP_1).
fof(ax83, axiom,
constr_CONST_3 != name_A).
fof(ax84, axiom,
constr_CONST_3 != name_B).
fof(ax85, axiom,
constr_CONST_3 != name_C).
fof(ax86, axiom,
constr_CONST_3 != name_Kab_40x30).
fof(ax87, axiom,
constr_CONST_3 != name_Kas).
fof(ax88, axiom,
constr_CONST_3 != name_Kbc_41).
fof(ax89, axiom,
constr_CONST_3 != name_Kbs).
fof(ax90, axiom,
constr_CONST_3 != name_Kcs).
fof(ax91, axiom,
constr_CONST_3 != name_Na).
fof(ax92, axiom,
constr_CONST_3 != name_S).
fof(ax93, axiom,
constr_CONST_3 != name_c).
fof(ax94, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax95, axiom,
constr_CONST_4 != constr_client_A_STEP_1).
fof(ax96, axiom,
constr_CONST_4 != constr_client_A_STEP_2).
fof(ax97, axiom,
constr_CONST_4 != constr_client_B_STEP_1).
fof(ax98, axiom,
constr_CONST_4 != constr_client_B_STEP_2).
fof(ax99, axiom,
constr_CONST_4 != constr_client_C_STEP_1).
fof(ax100, axiom,
constr_CONST_4 != constr_client_C_STEP_2).
fof(ax101, axiom,
constr_CONST_4 != constr_client_C_STEP_3).
fof(ax102, axiom,
constr_CONST_4 != constr_client_C_STEP_4).
fof(ax103, axiom,
constr_CONST_4 != constr_server_S_STEP_1).
fof(ax104, axiom,
constr_CONST_4 != name_A).
fof(ax105, axiom,
constr_CONST_4 != name_B).
fof(ax106, axiom,
constr_CONST_4 != name_C).
fof(ax107, axiom,
constr_CONST_4 != name_Kab_40x30).
fof(ax108, axiom,
constr_CONST_4 != name_Kas).
fof(ax109, axiom,
constr_CONST_4 != name_Kbc_41).
fof(ax110, axiom,
constr_CONST_4 != name_Kbs).
fof(ax111, axiom,
constr_CONST_4 != name_Kcs).
fof(ax112, axiom,
constr_CONST_4 != name_Na).
fof(ax113, axiom,
constr_CONST_4 != name_S).
fof(ax114, axiom,
constr_CONST_4 != name_c).
fof(ax115, axiom,
constr_ZERO != constr_client_A_STEP_1).
fof(ax116, axiom,
constr_ZERO != constr_client_A_STEP_2).
fof(ax117, axiom,
constr_ZERO != constr_client_B_STEP_1).
fof(ax118, axiom,
constr_ZERO != constr_client_B_STEP_2).
fof(ax119, axiom,
constr_ZERO != constr_client_C_STEP_1).
fof(ax120, axiom,
constr_ZERO != constr_client_C_STEP_2).
fof(ax121, axiom,
constr_ZERO != constr_client_C_STEP_3).
fof(ax122, axiom,
constr_ZERO != constr_client_C_STEP_4).
fof(ax123, axiom,
constr_ZERO != constr_server_S_STEP_1).
fof(ax124, axiom,
constr_ZERO != name_A).
fof(ax125, axiom,
constr_ZERO != name_B).
fof(ax126, axiom,
constr_ZERO != name_C).
fof(ax127, axiom,
constr_ZERO != name_Kab_40x30).
fof(ax128, axiom,
constr_ZERO != name_Kas).
fof(ax129, axiom,
constr_ZERO != name_Kbc_41).
fof(ax130, axiom,
constr_ZERO != name_Kbs).
fof(ax131, axiom,
constr_ZERO != name_Kcs).
fof(ax132, axiom,
constr_ZERO != name_Na).
fof(ax133, axiom,
constr_ZERO != name_S).
fof(ax134, axiom,
constr_ZERO != name_c).
fof(ax135, axiom,
constr_client_A_STEP_1 != constr_client_A_STEP_2).
fof(ax136, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_1).
fof(ax137, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_2).
fof(ax138, axiom,
constr_client_A_STEP_1 != constr_client_C_STEP_1).
fof(ax139, axiom,
constr_client_A_STEP_1 != constr_client_C_STEP_2).
fof(ax140, axiom,
constr_client_A_STEP_1 != constr_client_C_STEP_3).
fof(ax141, axiom,
constr_client_A_STEP_1 != constr_client_C_STEP_4).
fof(ax142, axiom,
constr_client_A_STEP_1 != constr_server_S_STEP_1).
fof(ax143, axiom,
constr_client_A_STEP_1 != name_A).
fof(ax144, axiom,
constr_client_A_STEP_1 != name_B).
fof(ax145, axiom,
constr_client_A_STEP_1 != name_C).
fof(ax146, axiom,
constr_client_A_STEP_1 != name_Kab_40x30).
fof(ax147, axiom,
constr_client_A_STEP_1 != name_Kas).
fof(ax148, axiom,
constr_client_A_STEP_1 != name_Kbc_41).
fof(ax149, axiom,
constr_client_A_STEP_1 != name_Kbs).
fof(ax150, axiom,
constr_client_A_STEP_1 != name_Kcs).
fof(ax151, axiom,
constr_client_A_STEP_1 != name_Na).
fof(ax152, axiom,
constr_client_A_STEP_1 != name_S).
fof(ax153, axiom,
constr_client_A_STEP_1 != name_c).
fof(ax154, axiom,
constr_client_A_STEP_2 != constr_client_B_STEP_1).
fof(ax155, axiom,
constr_client_A_STEP_2 != constr_client_B_STEP_2).
fof(ax156, axiom,
constr_client_A_STEP_2 != constr_client_C_STEP_1).
fof(ax157, axiom,
constr_client_A_STEP_2 != constr_client_C_STEP_2).
fof(ax158, axiom,
constr_client_A_STEP_2 != constr_client_C_STEP_3).
fof(ax159, axiom,
constr_client_A_STEP_2 != constr_client_C_STEP_4).
fof(ax160, axiom,
constr_client_A_STEP_2 != constr_server_S_STEP_1).
fof(ax161, axiom,
constr_client_A_STEP_2 != name_A).
fof(ax162, axiom,
constr_client_A_STEP_2 != name_B).
fof(ax163, axiom,
constr_client_A_STEP_2 != name_C).
fof(ax164, axiom,
constr_client_A_STEP_2 != name_Kab_40x30).
fof(ax165, axiom,
constr_client_A_STEP_2 != name_Kas).
fof(ax166, axiom,
constr_client_A_STEP_2 != name_Kbc_41).
fof(ax167, axiom,
constr_client_A_STEP_2 != name_Kbs).
fof(ax168, axiom,
constr_client_A_STEP_2 != name_Kcs).
fof(ax169, axiom,
constr_client_A_STEP_2 != name_Na).
fof(ax170, axiom,
constr_client_A_STEP_2 != name_S).
fof(ax171, axiom,
constr_client_A_STEP_2 != name_c).
fof(ax172, axiom,
constr_client_B_STEP_1 != constr_client_B_STEP_2).
fof(ax173, axiom,
constr_client_B_STEP_1 != constr_client_C_STEP_1).
fof(ax174, axiom,
constr_client_B_STEP_1 != constr_client_C_STEP_2).
fof(ax175, axiom,
constr_client_B_STEP_1 != constr_client_C_STEP_3).
fof(ax176, axiom,
constr_client_B_STEP_1 != constr_client_C_STEP_4).
fof(ax177, axiom,
constr_client_B_STEP_1 != constr_server_S_STEP_1).
fof(ax178, axiom,
constr_client_B_STEP_1 != name_A).
fof(ax179, axiom,
constr_client_B_STEP_1 != name_B).
fof(ax180, axiom,
constr_client_B_STEP_1 != name_C).
fof(ax181, axiom,
constr_client_B_STEP_1 != name_Kab_40x30).
fof(ax182, axiom,
constr_client_B_STEP_1 != name_Kas).
fof(ax183, axiom,
constr_client_B_STEP_1 != name_Kbc_41).
fof(ax184, axiom,
constr_client_B_STEP_1 != name_Kbs).
fof(ax185, axiom,
constr_client_B_STEP_1 != name_Kcs).
fof(ax186, axiom,
constr_client_B_STEP_1 != name_Na).
fof(ax187, axiom,
constr_client_B_STEP_1 != name_S).
fof(ax188, axiom,
constr_client_B_STEP_1 != name_c).
fof(ax189, axiom,
constr_client_B_STEP_2 != constr_client_C_STEP_1).
fof(ax190, axiom,
constr_client_B_STEP_2 != constr_client_C_STEP_2).
fof(ax191, axiom,
constr_client_B_STEP_2 != constr_client_C_STEP_3).
fof(ax192, axiom,
constr_client_B_STEP_2 != constr_client_C_STEP_4).
fof(ax193, axiom,
constr_client_B_STEP_2 != constr_server_S_STEP_1).
fof(ax194, axiom,
constr_client_B_STEP_2 != name_A).
fof(ax195, axiom,
constr_client_B_STEP_2 != name_B).
fof(ax196, axiom,
constr_client_B_STEP_2 != name_C).
fof(ax197, axiom,
constr_client_B_STEP_2 != name_Kab_40x30).
fof(ax198, axiom,
constr_client_B_STEP_2 != name_Kas).
fof(ax199, axiom,
constr_client_B_STEP_2 != name_Kbc_41).
fof(ax200, axiom,
constr_client_B_STEP_2 != name_Kbs).
fof(ax201, axiom,
constr_client_B_STEP_2 != name_Kcs).
fof(ax202, axiom,
constr_client_B_STEP_2 != name_Na).
fof(ax203, axiom,
constr_client_B_STEP_2 != name_S).
fof(ax204, axiom,
constr_client_B_STEP_2 != name_c).
fof(ax205, axiom,
constr_client_C_STEP_1 != constr_client_C_STEP_2).
fof(ax206, axiom,
constr_client_C_STEP_1 != constr_client_C_STEP_3).
fof(ax207, axiom,
constr_client_C_STEP_1 != constr_client_C_STEP_4).
fof(ax208, axiom,
constr_client_C_STEP_1 != constr_server_S_STEP_1).
fof(ax209, axiom,
constr_client_C_STEP_1 != name_A).
fof(ax210, axiom,
constr_client_C_STEP_1 != name_B).
fof(ax211, axiom,
constr_client_C_STEP_1 != name_C).
fof(ax212, axiom,
constr_client_C_STEP_1 != name_Kab_40x30).
fof(ax213, axiom,
constr_client_C_STEP_1 != name_Kas).
fof(ax214, axiom,
constr_client_C_STEP_1 != name_Kbc_41).
fof(ax215, axiom,
constr_client_C_STEP_1 != name_Kbs).
fof(ax216, axiom,
constr_client_C_STEP_1 != name_Kcs).
fof(ax217, axiom,
constr_client_C_STEP_1 != name_Na).
fof(ax218, axiom,
constr_client_C_STEP_1 != name_S).
fof(ax219, axiom,
constr_client_C_STEP_1 != name_c).
fof(ax220, axiom,
constr_client_C_STEP_2 != constr_client_C_STEP_3).
fof(ax221, axiom,
constr_client_C_STEP_2 != constr_client_C_STEP_4).
fof(ax222, axiom,
constr_client_C_STEP_2 != constr_server_S_STEP_1).
fof(ax223, axiom,
constr_client_C_STEP_2 != name_A).
fof(ax224, axiom,
constr_client_C_STEP_2 != name_B).
fof(ax225, axiom,
constr_client_C_STEP_2 != name_C).
fof(ax226, axiom,
constr_client_C_STEP_2 != name_Kab_40x30).
fof(ax227, axiom,
constr_client_C_STEP_2 != name_Kas).
fof(ax228, axiom,
constr_client_C_STEP_2 != name_Kbc_41).
fof(ax229, axiom,
constr_client_C_STEP_2 != name_Kbs).
fof(ax230, axiom,
constr_client_C_STEP_2 != name_Kcs).
fof(ax231, axiom,
constr_client_C_STEP_2 != name_Na).
fof(ax232, axiom,
constr_client_C_STEP_2 != name_S).
fof(ax233, axiom,
constr_client_C_STEP_2 != name_c).
fof(ax234, axiom,
constr_client_C_STEP_3 != constr_client_C_STEP_4).
fof(ax235, axiom,
constr_client_C_STEP_3 != constr_server_S_STEP_1).
fof(ax236, axiom,
constr_client_C_STEP_3 != name_A).
fof(ax237, axiom,
constr_client_C_STEP_3 != name_B).
fof(ax238, axiom,
constr_client_C_STEP_3 != name_C).
fof(ax239, axiom,
constr_client_C_STEP_3 != name_Kab_40x30).
fof(ax240, axiom,
constr_client_C_STEP_3 != name_Kas).
fof(ax241, axiom,
constr_client_C_STEP_3 != name_Kbc_41).
fof(ax242, axiom,
constr_client_C_STEP_3 != name_Kbs).
fof(ax243, axiom,
constr_client_C_STEP_3 != name_Kcs).
fof(ax244, axiom,
constr_client_C_STEP_3 != name_Na).
fof(ax245, axiom,
constr_client_C_STEP_3 != name_S).
fof(ax246, axiom,
constr_client_C_STEP_3 != name_c).
fof(ax247, axiom,
constr_client_C_STEP_4 != constr_server_S_STEP_1).
fof(ax248, axiom,
constr_client_C_STEP_4 != name_A).
fof(ax249, axiom,
constr_client_C_STEP_4 != name_B).
fof(ax250, axiom,
constr_client_C_STEP_4 != name_C).
fof(ax251, axiom,
constr_client_C_STEP_4 != name_Kab_40x30).
fof(ax252, axiom,
constr_client_C_STEP_4 != name_Kas).
fof(ax253, axiom,
constr_client_C_STEP_4 != name_Kbc_41).
fof(ax254, axiom,
constr_client_C_STEP_4 != name_Kbs).
fof(ax255, axiom,
constr_client_C_STEP_4 != name_Kcs).
fof(ax256, axiom,
constr_client_C_STEP_4 != name_Na).
fof(ax257, axiom,
constr_client_C_STEP_4 != name_S).
fof(ax258, axiom,
constr_client_C_STEP_4 != name_c).
fof(ax259, axiom,
constr_server_S_STEP_1 != name_A).
fof(ax260, axiom,
constr_server_S_STEP_1 != name_B).
fof(ax261, axiom,
constr_server_S_STEP_1 != name_C).
fof(ax262, axiom,
constr_server_S_STEP_1 != name_Kab_40x30).
fof(ax263, axiom,
constr_server_S_STEP_1 != name_Kas).
fof(ax264, axiom,
constr_server_S_STEP_1 != name_Kbc_41).
fof(ax265, axiom,
constr_server_S_STEP_1 != name_Kbs).
fof(ax266, axiom,
constr_server_S_STEP_1 != name_Kcs).
fof(ax267, axiom,
constr_server_S_STEP_1 != name_Na).
fof(ax268, axiom,
constr_server_S_STEP_1 != name_S).
fof(ax269, axiom,
constr_server_S_STEP_1 != name_c).
fof(ax270, axiom,
name_A != name_B).
fof(ax271, axiom,
name_A != name_C).
fof(ax272, axiom,
name_A != name_Kab_40x30).
fof(ax273, axiom,
name_A != name_Kas).
fof(ax274, axiom,
name_A != name_Kbc_41).
fof(ax275, axiom,
name_A != name_Kbs).
fof(ax276, axiom,
name_A != name_Kcs).
fof(ax277, axiom,
name_A != name_Na).
fof(ax278, axiom,
name_A != name_S).
fof(ax279, axiom,
name_A != name_c).
fof(ax280, axiom,
name_B != name_C).
fof(ax281, axiom,
name_B != name_Kab_40x30).
fof(ax282, axiom,
name_B != name_Kas).
fof(ax283, axiom,
name_B != name_Kbc_41).
fof(ax284, axiom,
name_B != name_Kbs).
fof(ax285, axiom,
name_B != name_Kcs).
fof(ax286, axiom,
name_B != name_Na).
fof(ax287, axiom,
name_B != name_S).
fof(ax288, axiom,
name_B != name_c).
fof(ax289, axiom,
name_C != name_Kab_40x30).
fof(ax290, axiom,
name_C != name_Kas).
fof(ax291, axiom,
name_C != name_Kbc_41).
fof(ax292, axiom,
name_C != name_Kbs).
fof(ax293, axiom,
name_C != name_Kcs).
fof(ax294, axiom,
name_C != name_Na).
fof(ax295, axiom,
name_C != name_S).
fof(ax296, axiom,
name_C != name_c).
fof(ax297, axiom,
name_Kab_40x30 != name_Kas).
fof(ax298, axiom,
name_Kab_40x30 != name_Kbc_41).
fof(ax299, axiom,
name_Kab_40x30 != name_Kbs).
fof(ax300, axiom,
name_Kab_40x30 != name_Kcs).
fof(ax301, axiom,
name_Kab_40x30 != name_Na).
fof(ax302, axiom,
name_Kab_40x30 != name_S).
fof(ax303, axiom,
name_Kab_40x30 != name_c).
fof(ax304, axiom,
name_Kas != name_Kbc_41).
fof(ax305, axiom,
name_Kas != name_Kbs).
fof(ax306, axiom,
name_Kas != name_Kcs).
fof(ax307, axiom,
name_Kas != name_Na).
fof(ax308, axiom,
name_Kas != name_S).
fof(ax309, axiom,
name_Kas != name_c).
fof(ax310, axiom,
name_Kbc_41 != name_Kbs).
fof(ax311, axiom,
name_Kbc_41 != name_Kcs).
fof(ax312, axiom,
name_Kbc_41 != name_Na).
fof(ax313, axiom,
name_Kbc_41 != name_S).
fof(ax314, axiom,
name_Kbc_41 != name_c).
fof(ax315, axiom,
name_Kbs != name_Kcs).
fof(ax316, axiom,
name_Kbs != name_Na).
fof(ax317, axiom,
name_Kbs != name_S).
fof(ax318, axiom,
name_Kbs != name_c).
fof(ax319, axiom,
name_Kcs != name_Na).
fof(ax320, axiom,
name_Kcs != name_S).
fof(ax321, axiom,
name_Kcs != name_c).
fof(ax322, axiom,
name_Na != name_S).
fof(ax323, axiom,
name_Na != name_c).
fof(ax324, axiom,
name_S != name_c).
fof(ax325, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_dec(constr_enc(VAR_M_0X30, VAR_K_0X30), VAR_K_0X30) = VAR_M_0X30)).
fof(ax326, axiom,
![VAR_X1_15, VAR_X2_16, VAR_X3_17, VAR_X4_18, VAR_X5_0X30] : (constr_decon5(constr_con5(VAR_X1_15, VAR_X2_16, VAR_X3_17, VAR_X4_18, VAR_X5_0X30)) = tuple_5(VAR_X1_15, VAR_X2_16, VAR_X3_17, VAR_X4_18, VAR_X5_0X30))).
fof(ax327, axiom,
![VAR_X1_12, VAR_X2_13, VAR_X3_14, VAR_X4_0X30] : (constr_decon4(constr_con4(VAR_X1_12, VAR_X2_13, VAR_X3_14, VAR_X4_0X30)) = tuple_4(VAR_X1_12, VAR_X2_13, VAR_X3_14, VAR_X4_0X30))).
fof(ax328, axiom,
![VAR_X1_0X30, VAR_X2_0X30, VAR_X3_0X30] : (constr_decon3(constr_con3(VAR_X1_0X30, VAR_X2_0X30, VAR_X3_0X30)) = tuple_3(VAR_X1_0X30, VAR_X2_0X30, VAR_X3_0X30))).
fof(ax329, axiom,
![VAR_X_11] : (constr_xor(VAR_X_11, VAR_X_11) = constr_ZERO)).
fof(ax330, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, constr_ZERO) = VAR_X_10X30)).
fof(ax331, axiom,
![VAR_X_8, VAR_Y_9] : (constr_xor(VAR_X_8, VAR_Y_9) = constr_xor(VAR_Y_9, VAR_X_8))).
fof(ax332, axiom,
![VAR_X_7, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_7, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_7, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax333, axiom,
![VAR_X_63] : (pred_eq(VAR_X_63, VAR_X_63))).
fof(ax334, axiom,
![VAR_V_70X30, VAR_V_71] : ((pred_attacker(VAR_V_70X30) & pred_attacker(VAR_V_71)) => pred_attacker(constr_xor(VAR_V_70X30, VAR_V_71)))).
fof(ax335, axiom,
pred_attacker(tuple_true)).
fof(ax336, axiom,
pred_attacker(constr_server_S_STEP_1)).
fof(ax337, axiom,
![VAR_V_75, VAR_V_76] : ((pred_attacker(VAR_V_75) & pred_attacker(VAR_V_76)) => pred_attacker(constr_h(VAR_V_75, VAR_V_76)))).
fof(ax338, axiom,
pred_attacker(tuple_false)).
fof(ax339, axiom,
![VAR_V_79, VAR_V_80X30] : ((pred_attacker(VAR_V_79) & pred_attacker(VAR_V_80X30)) => pred_attacker(constr_enc(VAR_V_79, VAR_V_80X30)))).
fof(ax340, axiom,
![VAR_V_82] : (pred_attacker(VAR_V_82) => pred_attacker(constr_decon5(VAR_V_82)))).
fof(ax341, axiom,
![VAR_V_84] : (pred_attacker(VAR_V_84) => pred_attacker(constr_decon4(VAR_V_84)))).
fof(ax342, axiom,
![VAR_V_86] : (pred_attacker(VAR_V_86) => pred_attacker(constr_decon3(VAR_V_86)))).
fof(ax343, axiom,
![VAR_V_89, VAR_V_90X30] : ((pred_attacker(VAR_V_89) & pred_attacker(VAR_V_90X30)) => pred_attacker(constr_dec(VAR_V_89, VAR_V_90X30)))).
fof(ax344, axiom,
![VAR_V_96, VAR_V_97, VAR_V_98, VAR_V_99, VAR_V_10X300X30] : ((pred_attacker(VAR_V_96) & pred_attacker(VAR_V_97) & pred_attacker(VAR_V_98) & pred_attacker(VAR_V_99) & pred_attacker(VAR_V_10X300X30)) => pred_attacker(constr_con5(VAR_V_96, VAR_V_97, VAR_V_98, VAR_V_99, VAR_V_10X300X30)))).
fof(ax345, axiom,
![VAR_V_10X305, VAR_V_10X306, VAR_V_10X307, VAR_V_10X308] : ((pred_attacker(VAR_V_10X305) & pred_attacker(VAR_V_10X306) & pred_attacker(VAR_V_10X307) & pred_attacker(VAR_V_10X308)) => pred_attacker(constr_con4(VAR_V_10X305, VAR_V_10X306, VAR_V_10X307, VAR_V_10X308)))).
fof(ax346, axiom,
![VAR_V_112, VAR_V_113, VAR_V_114] : ((pred_attacker(VAR_V_112) & pred_attacker(VAR_V_113) & pred_attacker(VAR_V_114)) => pred_attacker(constr_con3(VAR_V_112, VAR_V_113, VAR_V_114)))).
fof(ax347, axiom,
pred_attacker(constr_client_C_STEP_4)).
fof(ax348, axiom,
pred_attacker(constr_client_C_STEP_3)).
fof(ax349, axiom,
pred_attacker(constr_client_C_STEP_2)).
fof(ax350, axiom,
pred_attacker(constr_client_C_STEP_1)).
fof(ax351, axiom,
pred_attacker(constr_client_B_STEP_2)).
fof(ax352, axiom,
pred_attacker(constr_client_B_STEP_1)).
fof(ax353, axiom,
pred_attacker(constr_client_A_STEP_2)).
fof(ax354, axiom,
pred_attacker(constr_client_A_STEP_1)).
fof(ax355, axiom,
pred_attacker(constr_ZERO)).
fof(ax356, axiom,
pred_attacker(constr_CONST_4)).
fof(ax357, axiom,
pred_attacker(constr_CONST_3)).
fof(ax358, axiom,
pred_attacker(constr_CONST_2)).
fof(ax359, axiom,
pred_attacker(constr_CONST_1)).
fof(ax360, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax361, axiom,
![VAR_V_123, VAR_V_124, VAR_V_125, VAR_V_126] : ((pred_attacker(VAR_V_123) & pred_attacker(VAR_V_124) & pred_attacker(VAR_V_125) & pred_attacker(VAR_V_126)) => pred_attacker(tuple_4(VAR_V_123, VAR_V_124, VAR_V_125, VAR_V_126)))).
fof(ax362, axiom,
![VAR_V_147, VAR_V_148, VAR_V_149, VAR_V_150X30] : (pred_attacker(tuple_4(VAR_V_147, VAR_V_148, VAR_V_149, VAR_V_150X30)) => pred_attacker(VAR_V_147))).
fof(ax363, axiom,
![VAR_V_152, VAR_V_153, VAR_V_154, VAR_V_155] : (pred_attacker(tuple_4(VAR_V_152, VAR_V_153, VAR_V_154, VAR_V_155)) => pred_attacker(VAR_V_153))).
fof(ax364, axiom,
![VAR_V_157, VAR_V_158, VAR_V_159, VAR_V_160X30] : (pred_attacker(tuple_4(VAR_V_157, VAR_V_158, VAR_V_159, VAR_V_160X30)) => pred_attacker(VAR_V_159))).
fof(ax365, axiom,
![VAR_V_162, VAR_V_163, VAR_V_164, VAR_V_165] : (pred_attacker(tuple_4(VAR_V_162, VAR_V_163, VAR_V_164, VAR_V_165)) => pred_attacker(VAR_V_165))).
fof(ax366, axiom,
![VAR_V_170X30, VAR_V_171, VAR_V_172] : ((pred_attacker(VAR_V_170X30) & pred_attacker(VAR_V_171) & pred_attacker(VAR_V_172)) => pred_attacker(tuple_3(VAR_V_170X30, VAR_V_171, VAR_V_172)))).
fof(ax367, axiom,
![VAR_V_185, VAR_V_186, VAR_V_187] : (pred_attacker(tuple_3(VAR_V_185, VAR_V_186, VAR_V_187)) => pred_attacker(VAR_V_185))).
fof(ax368, axiom,
![VAR_V_189, VAR_V_190X30, VAR_V_191] : (pred_attacker(tuple_3(VAR_V_189, VAR_V_190X30, VAR_V_191)) => pred_attacker(VAR_V_190X30))).
fof(ax369, axiom,
![VAR_V_193, VAR_V_194, VAR_V_195] : (pred_attacker(tuple_3(VAR_V_193, VAR_V_194, VAR_V_195)) => pred_attacker(VAR_V_195))).
fof(ax370, axiom,
![VAR_V_199, VAR_V_20X300X30] : ((pred_attacker(VAR_V_199) & pred_attacker(VAR_V_20X300X30)) => pred_attacker(tuple_2(VAR_V_199, VAR_V_20X300X30)))).
fof(ax371, axiom,
![VAR_V_20X307, VAR_V_20X308] : (pred_attacker(tuple_2(VAR_V_20X307, VAR_V_20X308)) => pred_attacker(VAR_V_20X307))).
fof(ax372, axiom,
![VAR_V_210X30, VAR_V_211] : (pred_attacker(tuple_2(VAR_V_210X30, VAR_V_211)) => pred_attacker(VAR_V_211))).
fof(ax373, axiom,
![VAR_V_229, VAR_V_230X30, VAR_V_231, VAR_V_232, VAR_V_233, VAR_V_234, VAR_V_235, VAR_V_236, VAR_V_237, VAR_V_238, VAR_V_239, VAR_V_240X30, VAR_V_241, VAR_V_242, VAR_V_243, VAR_V_244] : ((pred_attacker(VAR_V_229) & pred_attacker(VAR_V_230X30) & pred_attacker(VAR_V_231) & pred_attacker(VAR_V_232) & pred_attacker(VAR_V_233) & pred_attacker(VAR_V_234) & pred_attacker(VAR_V_235) & pred_attacker(VAR_V_236) & pred_attacker(VAR_V_237) & pred_attacker(VAR_V_238) & pred_attacker(VAR_V_239) & pred_attacker(VAR_V_240X30) & pred_attacker(VAR_V_241) & pred_attacker(VAR_V_242) & pred_attacker(VAR_V_243) & pred_attacker(VAR_V_244)) => pred_attacker(tuple_16(VAR_V_229, VAR_V_230X30, VAR_V_231, VAR_V_232, VAR_V_233, VAR_V_234, VAR_V_235, VAR_V_236, VAR_V_237, VAR_V_238, VAR_V_239, VAR_V_240X30, VAR_V_241, VAR_V_242, VAR_V_243, VAR_V_244)))).
fof(ax374, axiom,
![VAR_V_517, VAR_V_518, VAR_V_519, VAR_V_520X30, VAR_V_521, VAR_V_522, VAR_V_523, VAR_V_524, VAR_V_525, VAR_V_526, VAR_V_527, VAR_V_528, VAR_V_529, VAR_V_530X30, VAR_V_531, VAR_V_532] : (pred_attacker(tuple_16(VAR_V_517, VAR_V_518, VAR_V_519, VAR_V_520X30, VAR_V_521, VAR_V_522, VAR_V_523, VAR_V_524, VAR_V_525, VAR_V_526, VAR_V_527, VAR_V_528, VAR_V_529, VAR_V_530X30, VAR_V_531, VAR_V_532)) => pred_attacker(VAR_V_517))).
fof(ax375, axiom,
![VAR_V_534, VAR_V_535, VAR_V_536, VAR_V_537, VAR_V_538, VAR_V_539, VAR_V_540X30, VAR_V_541, VAR_V_542, VAR_V_543, VAR_V_544, VAR_V_545, VAR_V_546, VAR_V_547, VAR_V_548, VAR_V_549] : (pred_attacker(tuple_16(VAR_V_534, VAR_V_535, VAR_V_536, VAR_V_537, VAR_V_538, VAR_V_539, VAR_V_540X30, VAR_V_541, VAR_V_542, VAR_V_543, VAR_V_544, VAR_V_545, VAR_V_546, VAR_V_547, VAR_V_548, VAR_V_549)) => pred_attacker(VAR_V_535))).
fof(ax376, axiom,
![VAR_V_551, VAR_V_552, VAR_V_553, VAR_V_554, VAR_V_555, VAR_V_556, VAR_V_557, VAR_V_558, VAR_V_559, VAR_V_560X30, VAR_V_561, VAR_V_562, VAR_V_563, VAR_V_564, VAR_V_565, VAR_V_566] : (pred_attacker(tuple_16(VAR_V_551, VAR_V_552, VAR_V_553, VAR_V_554, VAR_V_555, VAR_V_556, VAR_V_557, VAR_V_558, VAR_V_559, VAR_V_560X30, VAR_V_561, VAR_V_562, VAR_V_563, VAR_V_564, VAR_V_565, VAR_V_566)) => pred_attacker(VAR_V_553))).
fof(ax377, axiom,
![VAR_V_568, VAR_V_569, VAR_V_570X30, VAR_V_571, VAR_V_572, VAR_V_573, VAR_V_574, VAR_V_575, VAR_V_576, VAR_V_577, VAR_V_578, VAR_V_579, VAR_V_580X30, VAR_V_581, VAR_V_582, VAR_V_583] : (pred_attacker(tuple_16(VAR_V_568, VAR_V_569, VAR_V_570X30, VAR_V_571, VAR_V_572, VAR_V_573, VAR_V_574, VAR_V_575, VAR_V_576, VAR_V_577, VAR_V_578, VAR_V_579, VAR_V_580X30, VAR_V_581, VAR_V_582, VAR_V_583)) => pred_attacker(VAR_V_571))).
fof(ax378, axiom,
![VAR_V_585, VAR_V_586, VAR_V_587, VAR_V_588, VAR_V_589, VAR_V_590X30, VAR_V_591, VAR_V_592, VAR_V_593, VAR_V_594, VAR_V_595, VAR_V_596, VAR_V_597, VAR_V_598, VAR_V_599, VAR_V_60X300X30] : (pred_attacker(tuple_16(VAR_V_585, VAR_V_586, VAR_V_587, VAR_V_588, VAR_V_589, VAR_V_590X30, VAR_V_591, VAR_V_592, VAR_V_593, VAR_V_594, VAR_V_595, VAR_V_596, VAR_V_597, VAR_V_598, VAR_V_599, VAR_V_60X300X30)) => pred_attacker(VAR_V_589))).
fof(ax379, axiom,
![VAR_V_60X302, VAR_V_60X303, VAR_V_60X304, VAR_V_60X305, VAR_V_60X306, VAR_V_60X307, VAR_V_60X308, VAR_V_60X309, VAR_V_610X30, VAR_V_611, VAR_V_612, VAR_V_613, VAR_V_614, VAR_V_615, VAR_V_616, VAR_V_617] : (pred_attacker(tuple_16(VAR_V_60X302, VAR_V_60X303, VAR_V_60X304, VAR_V_60X305, VAR_V_60X306, VAR_V_60X307, VAR_V_60X308, VAR_V_60X309, VAR_V_610X30, VAR_V_611, VAR_V_612, VAR_V_613, VAR_V_614, VAR_V_615, VAR_V_616, VAR_V_617)) => pred_attacker(VAR_V_60X307))).
fof(ax380, axiom,
![VAR_V_619, VAR_V_620X30, VAR_V_621, VAR_V_622, VAR_V_623, VAR_V_624, VAR_V_625, VAR_V_626, VAR_V_627, VAR_V_628, VAR_V_629, VAR_V_630X30, VAR_V_631, VAR_V_632, VAR_V_633, VAR_V_634] : (pred_attacker(tuple_16(VAR_V_619, VAR_V_620X30, VAR_V_621, VAR_V_622, VAR_V_623, VAR_V_624, VAR_V_625, VAR_V_626, VAR_V_627, VAR_V_628, VAR_V_629, VAR_V_630X30, VAR_V_631, VAR_V_632, VAR_V_633, VAR_V_634)) => pred_attacker(VAR_V_625))).
fof(ax381, axiom,
![VAR_V_636, VAR_V_637, VAR_V_638, VAR_V_639, VAR_V_640X30, VAR_V_641, VAR_V_642, VAR_V_643, VAR_V_644, VAR_V_645, VAR_V_646, VAR_V_647, VAR_V_648, VAR_V_649, VAR_V_650X30, VAR_V_651] : (pred_attacker(tuple_16(VAR_V_636, VAR_V_637, VAR_V_638, VAR_V_639, VAR_V_640X30, VAR_V_641, VAR_V_642, VAR_V_643, VAR_V_644, VAR_V_645, VAR_V_646, VAR_V_647, VAR_V_648, VAR_V_649, VAR_V_650X30, VAR_V_651)) => pred_attacker(VAR_V_643))).
fof(ax382, axiom,
![VAR_V_653, VAR_V_654, VAR_V_655, VAR_V_656, VAR_V_657, VAR_V_658, VAR_V_659, VAR_V_660X30, VAR_V_661, VAR_V_662, VAR_V_663, VAR_V_664, VAR_V_665, VAR_V_666, VAR_V_667, VAR_V_668] : (pred_attacker(tuple_16(VAR_V_653, VAR_V_654, VAR_V_655, VAR_V_656, VAR_V_657, VAR_V_658, VAR_V_659, VAR_V_660X30, VAR_V_661, VAR_V_662, VAR_V_663, VAR_V_664, VAR_V_665, VAR_V_666, VAR_V_667, VAR_V_668)) => pred_attacker(VAR_V_661))).
fof(ax383, axiom,
![VAR_V_670X30, VAR_V_671, VAR_V_672, VAR_V_673, VAR_V_674, VAR_V_675, VAR_V_676, VAR_V_677, VAR_V_678, VAR_V_679, VAR_V_680X30, VAR_V_681, VAR_V_682, VAR_V_683, VAR_V_684, VAR_V_685] : (pred_attacker(tuple_16(VAR_V_670X30, VAR_V_671, VAR_V_672, VAR_V_673, VAR_V_674, VAR_V_675, VAR_V_676, VAR_V_677, VAR_V_678, VAR_V_679, VAR_V_680X30, VAR_V_681, VAR_V_682, VAR_V_683, VAR_V_684, VAR_V_685)) => pred_attacker(VAR_V_679))).
fof(ax384, axiom,
![VAR_V_687, VAR_V_688, VAR_V_689, VAR_V_690X30, VAR_V_691, VAR_V_692, VAR_V_693, VAR_V_694, VAR_V_695, VAR_V_696, VAR_V_697, VAR_V_698, VAR_V_699, VAR_V_70X300X30, VAR_V_70X301, VAR_V_70X302] : (pred_attacker(tuple_16(VAR_V_687, VAR_V_688, VAR_V_689, VAR_V_690X30, VAR_V_691, VAR_V_692, VAR_V_693, VAR_V_694, VAR_V_695, VAR_V_696, VAR_V_697, VAR_V_698, VAR_V_699, VAR_V_70X300X30, VAR_V_70X301, VAR_V_70X302)) => pred_attacker(VAR_V_697))).
fof(ax385, axiom,
![VAR_V_70X304, VAR_V_70X305, VAR_V_70X306, VAR_V_70X307, VAR_V_70X308, VAR_V_70X309, VAR_V_710X30, VAR_V_711, VAR_V_712, VAR_V_713, VAR_V_714, VAR_V_715, VAR_V_716, VAR_V_717, VAR_V_718, VAR_V_719] : (pred_attacker(tuple_16(VAR_V_70X304, VAR_V_70X305, VAR_V_70X306, VAR_V_70X307, VAR_V_70X308, VAR_V_70X309, VAR_V_710X30, VAR_V_711, VAR_V_712, VAR_V_713, VAR_V_714, VAR_V_715, VAR_V_716, VAR_V_717, VAR_V_718, VAR_V_719)) => pred_attacker(VAR_V_715))).
fof(ax386, axiom,
![VAR_V_721, VAR_V_722, VAR_V_723, VAR_V_724, VAR_V_725, VAR_V_726, VAR_V_727, VAR_V_728, VAR_V_729, VAR_V_730X30, VAR_V_731, VAR_V_732, VAR_V_733, VAR_V_734, VAR_V_735, VAR_V_736] : (pred_attacker(tuple_16(VAR_V_721, VAR_V_722, VAR_V_723, VAR_V_724, VAR_V_725, VAR_V_726, VAR_V_727, VAR_V_728, VAR_V_729, VAR_V_730X30, VAR_V_731, VAR_V_732, VAR_V_733, VAR_V_734, VAR_V_735, VAR_V_736)) => pred_attacker(VAR_V_733))).
fof(ax387, axiom,
![VAR_V_738, VAR_V_739, VAR_V_740X30, VAR_V_741, VAR_V_742, VAR_V_743, VAR_V_744, VAR_V_745, VAR_V_746, VAR_V_747, VAR_V_748, VAR_V_749, VAR_V_750X30, VAR_V_751, VAR_V_752, VAR_V_753] : (pred_attacker(tuple_16(VAR_V_738, VAR_V_739, VAR_V_740X30, VAR_V_741, VAR_V_742, VAR_V_743, VAR_V_744, VAR_V_745, VAR_V_746, VAR_V_747, VAR_V_748, VAR_V_749, VAR_V_750X30, VAR_V_751, VAR_V_752, VAR_V_753)) => pred_attacker(VAR_V_751))).
fof(ax388, axiom,
![VAR_V_755, VAR_V_756, VAR_V_757, VAR_V_758, VAR_V_759, VAR_V_760X30, VAR_V_761, VAR_V_762, VAR_V_763, VAR_V_764, VAR_V_765, VAR_V_766, VAR_V_767, VAR_V_768, VAR_V_769, VAR_V_770X30] : (pred_attacker(tuple_16(VAR_V_755, VAR_V_756, VAR_V_757, VAR_V_758, VAR_V_759, VAR_V_760X30, VAR_V_761, VAR_V_762, VAR_V_763, VAR_V_764, VAR_V_765, VAR_V_766, VAR_V_767, VAR_V_768, VAR_V_769, VAR_V_770X30)) => pred_attacker(VAR_V_769))).
fof(ax389, axiom,
![VAR_V_772, VAR_V_773, VAR_V_774, VAR_V_775, VAR_V_776, VAR_V_777, VAR_V_778, VAR_V_779, VAR_V_780X30, VAR_V_781, VAR_V_782, VAR_V_783, VAR_V_784, VAR_V_785, VAR_V_786, VAR_V_787] : (pred_attacker(tuple_16(VAR_V_772, VAR_V_773, VAR_V_774, VAR_V_775, VAR_V_776, VAR_V_777, VAR_V_778, VAR_V_779, VAR_V_780X30, VAR_V_781, VAR_V_782, VAR_V_783, VAR_V_784, VAR_V_785, VAR_V_786, VAR_V_787)) => pred_attacker(VAR_V_787))).
fof(ax390, axiom,
![VAR_V_80X301, VAR_V_80X302, VAR_V_80X303, VAR_V_80X304, VAR_V_80X305, VAR_V_80X306, VAR_V_80X307, VAR_V_80X308, VAR_V_80X309, VAR_V_810X30, VAR_V_811, VAR_V_812] : ((pred_attacker(VAR_V_80X301) & pred_attacker(VAR_V_80X302) & pred_attacker(VAR_V_80X303) & pred_attacker(VAR_V_80X304) & pred_attacker(VAR_V_80X305) & pred_attacker(VAR_V_80X306) & pred_attacker(VAR_V_80X307) & pred_attacker(VAR_V_80X308) & pred_attacker(VAR_V_80X309) & pred_attacker(VAR_V_810X30) & pred_attacker(VAR_V_811) & pred_attacker(VAR_V_812)) => pred_attacker(tuple_12(VAR_V_80X301, VAR_V_80X302, VAR_V_80X303, VAR_V_80X304, VAR_V_80X305, VAR_V_80X306, VAR_V_80X307, VAR_V_80X308, VAR_V_80X309, VAR_V_810X30, VAR_V_811, VAR_V_812)))).
fof(ax391, axiom,
![VAR_V_969, VAR_V_970X30, VAR_V_971, VAR_V_972, VAR_V_973, VAR_V_974, VAR_V_975, VAR_V_976, VAR_V_977, VAR_V_978, VAR_V_979, VAR_V_980X30] : (pred_attacker(tuple_12(VAR_V_969, VAR_V_970X30, VAR_V_971, VAR_V_972, VAR_V_973, VAR_V_974, VAR_V_975, VAR_V_976, VAR_V_977, VAR_V_978, VAR_V_979, VAR_V_980X30)) => pred_attacker(VAR_V_969))).
fof(ax392, axiom,
![VAR_V_982, VAR_V_983, VAR_V_984, VAR_V_985, VAR_V_986, VAR_V_987, VAR_V_988, VAR_V_989, VAR_V_990X30, VAR_V_991, VAR_V_992, VAR_V_993] : (pred_attacker(tuple_12(VAR_V_982, VAR_V_983, VAR_V_984, VAR_V_985, VAR_V_986, VAR_V_987, VAR_V_988, VAR_V_989, VAR_V_990X30, VAR_V_991, VAR_V_992, VAR_V_993)) => pred_attacker(VAR_V_983))).
fof(ax393, axiom,
![VAR_V_995, VAR_V_996, VAR_V_997, VAR_V_998, VAR_V_999, VAR_V_10X300X300X30, VAR_V_10X300X301, VAR_V_10X300X302, VAR_V_10X300X303, VAR_V_10X300X304, VAR_V_10X300X305, VAR_V_10X300X306] : (pred_attacker(tuple_12(VAR_V_995, VAR_V_996, VAR_V_997, VAR_V_998, VAR_V_999, VAR_V_10X300X300X30, VAR_V_10X300X301, VAR_V_10X300X302, VAR_V_10X300X303, VAR_V_10X300X304, VAR_V_10X300X305, VAR_V_10X300X306)) => pred_attacker(VAR_V_997))).
fof(ax394, axiom,
![VAR_V_10X300X308, VAR_V_10X300X309, VAR_V_10X3010X30, VAR_V_10X3011, VAR_V_10X3012, VAR_V_10X3013, VAR_V_10X3014, VAR_V_10X3015, VAR_V_10X3016, VAR_V_10X3017, VAR_V_10X3018, VAR_V_10X3019] : (pred_attacker(tuple_12(VAR_V_10X300X308, VAR_V_10X300X309, VAR_V_10X3010X30, VAR_V_10X3011, VAR_V_10X3012, VAR_V_10X3013, VAR_V_10X3014, VAR_V_10X3015, VAR_V_10X3016, VAR_V_10X3017, VAR_V_10X3018, VAR_V_10X3019)) => pred_attacker(VAR_V_10X3011))).
fof(ax395, axiom,
![VAR_V_10X3021, VAR_V_10X3022, VAR_V_10X3023, VAR_V_10X3024, VAR_V_10X3025, VAR_V_10X3026, VAR_V_10X3027, VAR_V_10X3028, VAR_V_10X3029, VAR_V_10X3030X30, VAR_V_10X3031, VAR_V_10X3032] : (pred_attacker(tuple_12(VAR_V_10X3021, VAR_V_10X3022, VAR_V_10X3023, VAR_V_10X3024, VAR_V_10X3025, VAR_V_10X3026, VAR_V_10X3027, VAR_V_10X3028, VAR_V_10X3029, VAR_V_10X3030X30, VAR_V_10X3031, VAR_V_10X3032)) => pred_attacker(VAR_V_10X3025))).
fof(ax396, axiom,
![VAR_V_10X3034, VAR_V_10X3035, VAR_V_10X3036, VAR_V_10X3037, VAR_V_10X3038, VAR_V_10X3039, VAR_V_10X3040X30, VAR_V_10X3041, VAR_V_10X3042, VAR_V_10X3043, VAR_V_10X3044, VAR_V_10X3045] : (pred_attacker(tuple_12(VAR_V_10X3034, VAR_V_10X3035, VAR_V_10X3036, VAR_V_10X3037, VAR_V_10X3038, VAR_V_10X3039, VAR_V_10X3040X30, VAR_V_10X3041, VAR_V_10X3042, VAR_V_10X3043, VAR_V_10X3044, VAR_V_10X3045)) => pred_attacker(VAR_V_10X3039))).
fof(ax397, axiom,
![VAR_V_10X3047, VAR_V_10X3048, VAR_V_10X3049, VAR_V_10X3050X30, VAR_V_10X3051, VAR_V_10X3052, VAR_V_10X3053, VAR_V_10X3054, VAR_V_10X3055, VAR_V_10X3056, VAR_V_10X3057, VAR_V_10X3058] : (pred_attacker(tuple_12(VAR_V_10X3047, VAR_V_10X3048, VAR_V_10X3049, VAR_V_10X3050X30, VAR_V_10X3051, VAR_V_10X3052, VAR_V_10X3053, VAR_V_10X3054, VAR_V_10X3055, VAR_V_10X3056, VAR_V_10X3057, VAR_V_10X3058)) => pred_attacker(VAR_V_10X3053))).
fof(ax398, axiom,
![VAR_V_10X3060X30, VAR_V_10X3061, VAR_V_10X3062, VAR_V_10X3063, VAR_V_10X3064, VAR_V_10X3065, VAR_V_10X3066, VAR_V_10X3067, VAR_V_10X3068, VAR_V_10X3069, VAR_V_10X3070X30, VAR_V_10X3071] : (pred_attacker(tuple_12(VAR_V_10X3060X30, VAR_V_10X3061, VAR_V_10X3062, VAR_V_10X3063, VAR_V_10X3064, VAR_V_10X3065, VAR_V_10X3066, VAR_V_10X3067, VAR_V_10X3068, VAR_V_10X3069, VAR_V_10X3070X30, VAR_V_10X3071)) => pred_attacker(VAR_V_10X3067))).
fof(ax399, axiom,
![VAR_V_10X3073, VAR_V_10X3074, VAR_V_10X3075, VAR_V_10X3076, VAR_V_10X3077, VAR_V_10X3078, VAR_V_10X3079, VAR_V_10X3080X30, VAR_V_10X3081, VAR_V_10X3082, VAR_V_10X3083, VAR_V_10X3084] : (pred_attacker(tuple_12(VAR_V_10X3073, VAR_V_10X3074, VAR_V_10X3075, VAR_V_10X3076, VAR_V_10X3077, VAR_V_10X3078, VAR_V_10X3079, VAR_V_10X3080X30, VAR_V_10X3081, VAR_V_10X3082, VAR_V_10X3083, VAR_V_10X3084)) => pred_attacker(VAR_V_10X3081))).
fof(ax400, axiom,
![VAR_V_10X3086, VAR_V_10X3087, VAR_V_10X3088, VAR_V_10X3089, VAR_V_10X3090X30, VAR_V_10X3091, VAR_V_10X3092, VAR_V_10X3093, VAR_V_10X3094, VAR_V_10X3095, VAR_V_10X3096, VAR_V_10X3097] : (pred_attacker(tuple_12(VAR_V_10X3086, VAR_V_10X3087, VAR_V_10X3088, VAR_V_10X3089, VAR_V_10X3090X30, VAR_V_10X3091, VAR_V_10X3092, VAR_V_10X3093, VAR_V_10X3094, VAR_V_10X3095, VAR_V_10X3096, VAR_V_10X3097)) => pred_attacker(VAR_V_10X3095))).
fof(ax401, axiom,
![VAR_V_10X3099, VAR_V_110X300X30, VAR_V_110X301, VAR_V_110X302, VAR_V_110X303, VAR_V_110X304, VAR_V_110X305, VAR_V_110X306, VAR_V_110X307, VAR_V_110X308, VAR_V_110X309, VAR_V_1110X30] : (pred_attacker(tuple_12(VAR_V_10X3099, VAR_V_110X300X30, VAR_V_110X301, VAR_V_110X302, VAR_V_110X303, VAR_V_110X304, VAR_V_110X305, VAR_V_110X306, VAR_V_110X307, VAR_V_110X308, VAR_V_110X309, VAR_V_1110X30)) => pred_attacker(VAR_V_110X309))).
fof(ax402, axiom,
![VAR_V_1112, VAR_V_1113, VAR_V_1114, VAR_V_1115, VAR_V_1116, VAR_V_1117, VAR_V_1118, VAR_V_1119, VAR_V_1120X30, VAR_V_1121, VAR_V_1122, VAR_V_1123] : (pred_attacker(tuple_12(VAR_V_1112, VAR_V_1113, VAR_V_1114, VAR_V_1115, VAR_V_1116, VAR_V_1117, VAR_V_1118, VAR_V_1119, VAR_V_1120X30, VAR_V_1121, VAR_V_1122, VAR_V_1123)) => pred_attacker(VAR_V_1123))).
fof(ax403, axiom,
![VAR_V_1130X30, VAR_V_1131, VAR_V_1132, VAR_V_1133, VAR_V_1134] : ((pred_attacker(VAR_V_1130X30) & pred_attacker(VAR_V_1131) & pred_attacker(VAR_V_1132) & pred_attacker(VAR_V_1133) & pred_attacker(VAR_V_1134)) => pred_attacker(tuple_5(VAR_V_1130X30, VAR_V_1131, VAR_V_1132, VAR_V_1133, VAR_V_1134)))).
fof(ax404, axiom,
![VAR_V_1165, VAR_V_1166, VAR_V_1167, VAR_V_1168, VAR_V_1169] : (pred_attacker(tuple_5(VAR_V_1165, VAR_V_1166, VAR_V_1167, VAR_V_1168, VAR_V_1169)) => pred_attacker(VAR_V_1165))).
fof(ax405, axiom,
![VAR_V_1171, VAR_V_1172, VAR_V_1173, VAR_V_1174, VAR_V_1175] : (pred_attacker(tuple_5(VAR_V_1171, VAR_V_1172, VAR_V_1173, VAR_V_1174, VAR_V_1175)) => pred_attacker(VAR_V_1172))).
fof(ax406, axiom,
![VAR_V_1177, VAR_V_1178, VAR_V_1179, VAR_V_1180X30, VAR_V_1181] : (pred_attacker(tuple_5(VAR_V_1177, VAR_V_1178, VAR_V_1179, VAR_V_1180X30, VAR_V_1181)) => pred_attacker(VAR_V_1179))).
fof(ax407, axiom,
![VAR_V_1183, VAR_V_1184, VAR_V_1185, VAR_V_1186, VAR_V_1187] : (pred_attacker(tuple_5(VAR_V_1183, VAR_V_1184, VAR_V_1185, VAR_V_1186, VAR_V_1187)) => pred_attacker(VAR_V_1186))).
fof(ax408, axiom,
![VAR_V_1189, VAR_V_1190X30, VAR_V_1191, VAR_V_1192, VAR_V_1193] : (pred_attacker(tuple_5(VAR_V_1189, VAR_V_1190X30, VAR_V_1191, VAR_V_1192, VAR_V_1193)) => pred_attacker(VAR_V_1193))).
fof(ax409, axiom,
![VAR_V_1195, VAR_V_1196] : ((pred_mess(VAR_V_1196, VAR_V_1195) & pred_attacker(VAR_V_1196)) => pred_attacker(VAR_V_1195))).
fof(ax410, axiom,
![VAR_V_1197, VAR_V_1198] : ((pred_attacker(VAR_V_1198) & pred_attacker(VAR_V_1197)) => pred_mess(VAR_V_1198, VAR_V_1197))).
fof(ax411, axiom,
pred_attacker(name_c)).
fof(ax412, axiom,
pred_attacker(name_S)).
fof(ax413, axiom,
pred_attacker(name_Kcs)).
fof(ax414, axiom,
pred_attacker(name_C)).
fof(ax415, axiom,
pred_attacker(name_B)).
fof(ax416, axiom,
pred_attacker(name_A)).
fof(ax417, axiom,
![VAR_V_120X300X30] : (pred_equal(VAR_V_120X300X30, VAR_V_120X300X30))).
fof(ax418, axiom,
![VAR_V_120X301] : (pred_attacker(name_new0x2Dname(VAR_V_120X301)))).
fof(ax419, axiom,
pred_attacker(tuple_2(tuple_2(constr_h(constr_con3(name_A, name_B, name_Na), name_Kas), tuple_3(name_A, name_B, name_Na)), constr_client_A_STEP_1))).
fof(ax420, axiom,
![VAR_NA_1439, VAR_H_A_B_NA_KAS_1438] : (pred_attacker(tuple_2(VAR_H_A_B_NA_KAS_1438, tuple_3(name_A, name_B, VAR_NA_1439))) => pred_attacker(tuple_2(tuple_2(constr_h(constr_con4(name_B, name_C, name_Nb(VAR_NA_1439, VAR_H_A_B_NA_KAS_1438), constr_con4(VAR_H_A_B_NA_KAS_1438, name_A, name_B, VAR_NA_1439)), name_Kbs), tuple_4(name_B, name_C, name_Nb(VAR_NA_1439, VAR_H_A_B_NA_KAS_1438), tuple_2(VAR_H_A_B_NA_KAS_1438, tuple_3(name_A, name_B, VAR_NA_1439)))), constr_client_B_STEP_1)))).
fof(ax421, axiom,
![VAR_NA_160X306, VAR_NB_160X304, VAR_H_A_B_NA_KAS_160X305, VAR_H_B_C_NB_XA_KBS_160X303] : (pred_attacker(tuple_2(VAR_H_B_C_NB_XA_KBS_160X303, tuple_4(name_B, name_C, VAR_NB_160X304, tuple_2(VAR_H_A_B_NA_KAS_160X305, tuple_3(name_A, name_B, VAR_NA_160X306))))) => pred_attacker(tuple_2(name_Nc(VAR_NA_160X306, VAR_H_A_B_NA_KAS_160X305, VAR_NB_160X304, VAR_H_B_C_NB_XA_KBS_160X303), constr_client_C_STEP_1)))).
fof(ax422, axiom,
![VAR_NA_1759, VAR_NB_1757, VAR_H_A_B_NA_KAS_1758, VAR_H_B_C_NB_XA_KBS_1756] : (pred_attacker(tuple_2(VAR_H_B_C_NB_XA_KBS_1756, tuple_4(name_B, name_C, VAR_NB_1757, tuple_2(VAR_H_A_B_NA_KAS_1758, tuple_3(name_A, name_B, VAR_NA_1759))))) => pred_attacker(tuple_2(tuple_2(constr_h(constr_con4(name_C, name_S, name_Nc(VAR_NA_1759, VAR_H_A_B_NA_KAS_1758, VAR_NB_1757, VAR_H_B_C_NB_XA_KBS_1756), constr_con5(VAR_H_B_C_NB_XA_KBS_1756, name_B, name_C, VAR_NB_1757, constr_con4(VAR_H_A_B_NA_KAS_1758, name_A, name_B, VAR_NA_1759))), name_Kcs), tuple_4(name_C, name_S, name_Nc(VAR_NA_1759, VAR_H_A_B_NA_KAS_1758, VAR_NB_1757, VAR_H_B_C_NB_XA_KBS_1756), tuple_2(VAR_H_B_C_NB_XA_KBS_1756, tuple_4(name_B, name_C, VAR_NB_1757, tuple_2(VAR_H_A_B_NA_KAS_1758, tuple_3(name_A, name_B, VAR_NA_1759)))))), constr_client_C_STEP_2)))).
fof(ax423, axiom,
![VAR_KAB_XOR_H_NA_KAS_180X306, VAR_KAB_XOR_H_NB_KBS_180X308, VAR_KBC_XOR_H_NB_KBS_1810X30, VAR_KBC_XOR_H_NC_KCS_1812, VAR_NA_1817, VAR_NB_1815, VAR_ENC_A_B_NA_KAB_180X307, VAR_ENC_B_A_NB_KAB_180X309, VAR_ENC_B_C_NB_KBC_1811, VAR_ENC_C_B_NC_KBC_1813, VAR_H_A_B_NA_KAS_1816, VAR_H_B_C_NB_XA_KBS_1814] : ((pred_attacker(tuple_16(name_A, name_B, VAR_KAB_XOR_H_NA_KAS_180X306, VAR_ENC_A_B_NA_KAB_180X307, name_B, name_A, VAR_KAB_XOR_H_NB_KBS_180X308, VAR_ENC_B_A_NB_KAB_180X309, name_B, name_C, VAR_KBC_XOR_H_NB_KBS_1810X30, VAR_ENC_B_C_NB_KBC_1811, name_C, name_B, VAR_KBC_XOR_H_NC_KCS_1812, VAR_ENC_C_B_NC_KBC_1813)) & pred_attacker(tuple_2(VAR_H_B_C_NB_XA_KBS_1814, tuple_4(name_B, name_C, VAR_NB_1815, tuple_2(VAR_H_A_B_NA_KAS_1816, tuple_3(name_A, name_B, VAR_NA_1817)))))) => pred_attacker(tuple_2(constr_xor(VAR_KBC_XOR_H_NC_KCS_1812, constr_h(name_Nc(VAR_NA_1817, VAR_H_A_B_NA_KAS_1816, VAR_NB_1815, VAR_H_B_C_NB_XA_KBS_1814), name_Kcs)), constr_client_C_STEP_3)))).
fof(ax424, axiom,
![VAR_NA_2378, VAR_NB_2376, VAR_NC_2374, VAR_H_A_B_NA_KAS_2377, VAR_H_B_C_NB_XA_KBS_2375] : (pred_attacker(tuple_2(constr_h(constr_con4(name_C, name_S, VAR_NC_2374, constr_con5(VAR_H_B_C_NB_XA_KBS_2375, name_B, name_C, VAR_NB_2376, constr_con4(VAR_H_A_B_NA_KAS_2377, name_A, name_B, VAR_NA_2378))), name_Kcs), tuple_4(name_C, name_S, VAR_NC_2374, tuple_2(VAR_H_B_C_NB_XA_KBS_2375, tuple_4(name_B, name_C, VAR_NB_2376, tuple_2(VAR_H_A_B_NA_KAS_2377, tuple_3(name_A, name_B, VAR_NA_2378))))))) => pred_attacker(tuple_2(tuple_16(name_A, name_B, constr_xor(name_Kab_40x30, constr_h(VAR_NA_2378, name_Kas)), constr_enc(constr_con3(name_A, name_B, VAR_NA_2378), name_Kab_40x30), name_B, name_A, constr_xor(name_Kab_40x30, constr_h(VAR_NB_2376, name_Kbs)), constr_enc(constr_con3(name_B, name_A, VAR_NB_2376), name_Kab_40x30), name_B, name_C, constr_xor(name_Kbc_41, constr_h(VAR_NB_2376, name_Kbs)), constr_enc(constr_con3(name_B, name_C, VAR_NB_2376), name_Kbc_41), name_C, name_B, constr_xor(name_Kbc_41, constr_h(VAR_NC_2374, name_Kcs)), constr_enc(constr_con3(name_C, name_B, VAR_NC_2374), name_Kbc_41)), constr_server_S_STEP_1)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
