%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_A_STEP_1 != constr_B_STEP_1).
fof(ax1, axiom,
constr_A_STEP_1 != constr_B_STEP_2).
fof(ax2, axiom,
constr_A_STEP_1 != constr_CONST_0x30).
fof(ax3, axiom,
constr_A_STEP_1 != constr_CONST_1).
fof(ax4, axiom,
constr_A_STEP_1 != constr_CONST_2).
fof(ax5, axiom,
constr_A_STEP_1 != constr_CONST_3).
fof(ax6, axiom,
constr_A_STEP_1 != constr_CONST_4).
fof(ax7, axiom,
constr_A_STEP_1 != constr_C_STEP_1).
fof(ax8, axiom,
constr_A_STEP_1 != constr_C_STEP_2).
fof(ax9, axiom,
constr_A_STEP_1 != constr_C_STEP_3).
fof(ax10, axiom,
constr_A_STEP_1 != constr_C_STEP_4).
fof(ax11, axiom,
constr_A_STEP_1 != constr_S_STEP_1).
fof(ax12, axiom,
constr_A_STEP_1 != constr_ZERO).
fof(ax13, axiom,
constr_A_STEP_1 != name_Kab).
fof(ax14, axiom,
constr_A_STEP_1 != name_Kas).
fof(ax15, axiom,
constr_A_STEP_1 != name_Kbc).
fof(ax16, axiom,
constr_A_STEP_1 != name_Kbs).
fof(ax17, axiom,
constr_A_STEP_1 != name_Kcs).
fof(ax18, axiom,
constr_A_STEP_1 != name_Na).
fof(ax19, axiom,
constr_A_STEP_1 != name_c).
fof(ax20, axiom,
constr_A_STEP_1 != name_idA).
fof(ax21, axiom,
constr_A_STEP_1 != name_idB).
fof(ax22, axiom,
constr_A_STEP_1 != name_idC).
fof(ax23, axiom,
constr_A_STEP_1 != name_idS).
fof(ax24, axiom,
constr_B_STEP_1 != constr_B_STEP_2).
fof(ax25, axiom,
constr_B_STEP_1 != constr_CONST_0x30).
fof(ax26, axiom,
constr_B_STEP_1 != constr_CONST_1).
fof(ax27, axiom,
constr_B_STEP_1 != constr_CONST_2).
fof(ax28, axiom,
constr_B_STEP_1 != constr_CONST_3).
fof(ax29, axiom,
constr_B_STEP_1 != constr_CONST_4).
fof(ax30, axiom,
constr_B_STEP_1 != constr_C_STEP_1).
fof(ax31, axiom,
constr_B_STEP_1 != constr_C_STEP_2).
fof(ax32, axiom,
constr_B_STEP_1 != constr_C_STEP_3).
fof(ax33, axiom,
constr_B_STEP_1 != constr_C_STEP_4).
fof(ax34, axiom,
constr_B_STEP_1 != constr_S_STEP_1).
fof(ax35, axiom,
constr_B_STEP_1 != constr_ZERO).
fof(ax36, axiom,
constr_B_STEP_1 != name_Kab).
fof(ax37, axiom,
constr_B_STEP_1 != name_Kas).
fof(ax38, axiom,
constr_B_STEP_1 != name_Kbc).
fof(ax39, axiom,
constr_B_STEP_1 != name_Kbs).
fof(ax40, axiom,
constr_B_STEP_1 != name_Kcs).
fof(ax41, axiom,
constr_B_STEP_1 != name_Na).
fof(ax42, axiom,
constr_B_STEP_1 != name_c).
fof(ax43, axiom,
constr_B_STEP_1 != name_idA).
fof(ax44, axiom,
constr_B_STEP_1 != name_idB).
fof(ax45, axiom,
constr_B_STEP_1 != name_idC).
fof(ax46, axiom,
constr_B_STEP_1 != name_idS).
fof(ax47, axiom,
constr_B_STEP_2 != constr_CONST_0x30).
fof(ax48, axiom,
constr_B_STEP_2 != constr_CONST_1).
fof(ax49, axiom,
constr_B_STEP_2 != constr_CONST_2).
fof(ax50, axiom,
constr_B_STEP_2 != constr_CONST_3).
fof(ax51, axiom,
constr_B_STEP_2 != constr_CONST_4).
fof(ax52, axiom,
constr_B_STEP_2 != constr_C_STEP_1).
fof(ax53, axiom,
constr_B_STEP_2 != constr_C_STEP_2).
fof(ax54, axiom,
constr_B_STEP_2 != constr_C_STEP_3).
fof(ax55, axiom,
constr_B_STEP_2 != constr_C_STEP_4).
fof(ax56, axiom,
constr_B_STEP_2 != constr_S_STEP_1).
fof(ax57, axiom,
constr_B_STEP_2 != constr_ZERO).
fof(ax58, axiom,
constr_B_STEP_2 != name_Kab).
fof(ax59, axiom,
constr_B_STEP_2 != name_Kas).
fof(ax60, axiom,
constr_B_STEP_2 != name_Kbc).
fof(ax61, axiom,
constr_B_STEP_2 != name_Kbs).
fof(ax62, axiom,
constr_B_STEP_2 != name_Kcs).
fof(ax63, axiom,
constr_B_STEP_2 != name_Na).
fof(ax64, axiom,
constr_B_STEP_2 != name_c).
fof(ax65, axiom,
constr_B_STEP_2 != name_idA).
fof(ax66, axiom,
constr_B_STEP_2 != name_idB).
fof(ax67, axiom,
constr_B_STEP_2 != name_idC).
fof(ax68, axiom,
constr_B_STEP_2 != name_idS).
fof(ax69, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax70, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax71, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax72, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax73, axiom,
constr_CONST_0x30 != constr_C_STEP_1).
fof(ax74, axiom,
constr_CONST_0x30 != constr_C_STEP_2).
fof(ax75, axiom,
constr_CONST_0x30 != constr_C_STEP_3).
fof(ax76, axiom,
constr_CONST_0x30 != constr_C_STEP_4).
fof(ax77, axiom,
constr_CONST_0x30 != constr_S_STEP_1).
fof(ax78, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax79, axiom,
constr_CONST_0x30 != name_Kab).
fof(ax80, axiom,
constr_CONST_0x30 != name_Kas).
fof(ax81, axiom,
constr_CONST_0x30 != name_Kbc).
fof(ax82, axiom,
constr_CONST_0x30 != name_Kbs).
fof(ax83, axiom,
constr_CONST_0x30 != name_Kcs).
fof(ax84, axiom,
constr_CONST_0x30 != name_Na).
fof(ax85, axiom,
constr_CONST_0x30 != name_c).
fof(ax86, axiom,
constr_CONST_0x30 != name_idA).
fof(ax87, axiom,
constr_CONST_0x30 != name_idB).
fof(ax88, axiom,
constr_CONST_0x30 != name_idC).
fof(ax89, axiom,
constr_CONST_0x30 != name_idS).
fof(ax90, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax91, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax92, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax93, axiom,
constr_CONST_1 != constr_C_STEP_1).
fof(ax94, axiom,
constr_CONST_1 != constr_C_STEP_2).
fof(ax95, axiom,
constr_CONST_1 != constr_C_STEP_3).
fof(ax96, axiom,
constr_CONST_1 != constr_C_STEP_4).
fof(ax97, axiom,
constr_CONST_1 != constr_S_STEP_1).
fof(ax98, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax99, axiom,
constr_CONST_1 != name_Kab).
fof(ax100, axiom,
constr_CONST_1 != name_Kas).
fof(ax101, axiom,
constr_CONST_1 != name_Kbc).
fof(ax102, axiom,
constr_CONST_1 != name_Kbs).
fof(ax103, axiom,
constr_CONST_1 != name_Kcs).
fof(ax104, axiom,
constr_CONST_1 != name_Na).
fof(ax105, axiom,
constr_CONST_1 != name_c).
fof(ax106, axiom,
constr_CONST_1 != name_idA).
fof(ax107, axiom,
constr_CONST_1 != name_idB).
fof(ax108, axiom,
constr_CONST_1 != name_idC).
fof(ax109, axiom,
constr_CONST_1 != name_idS).
fof(ax110, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax111, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax112, axiom,
constr_CONST_2 != constr_C_STEP_1).
fof(ax113, axiom,
constr_CONST_2 != constr_C_STEP_2).
fof(ax114, axiom,
constr_CONST_2 != constr_C_STEP_3).
fof(ax115, axiom,
constr_CONST_2 != constr_C_STEP_4).
fof(ax116, axiom,
constr_CONST_2 != constr_S_STEP_1).
fof(ax117, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax118, axiom,
constr_CONST_2 != name_Kab).
fof(ax119, axiom,
constr_CONST_2 != name_Kas).
fof(ax120, axiom,
constr_CONST_2 != name_Kbc).
fof(ax121, axiom,
constr_CONST_2 != name_Kbs).
fof(ax122, axiom,
constr_CONST_2 != name_Kcs).
fof(ax123, axiom,
constr_CONST_2 != name_Na).
fof(ax124, axiom,
constr_CONST_2 != name_c).
fof(ax125, axiom,
constr_CONST_2 != name_idA).
fof(ax126, axiom,
constr_CONST_2 != name_idB).
fof(ax127, axiom,
constr_CONST_2 != name_idC).
fof(ax128, axiom,
constr_CONST_2 != name_idS).
fof(ax129, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax130, axiom,
constr_CONST_3 != constr_C_STEP_1).
fof(ax131, axiom,
constr_CONST_3 != constr_C_STEP_2).
fof(ax132, axiom,
constr_CONST_3 != constr_C_STEP_3).
fof(ax133, axiom,
constr_CONST_3 != constr_C_STEP_4).
fof(ax134, axiom,
constr_CONST_3 != constr_S_STEP_1).
fof(ax135, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax136, axiom,
constr_CONST_3 != name_Kab).
fof(ax137, axiom,
constr_CONST_3 != name_Kas).
fof(ax138, axiom,
constr_CONST_3 != name_Kbc).
fof(ax139, axiom,
constr_CONST_3 != name_Kbs).
fof(ax140, axiom,
constr_CONST_3 != name_Kcs).
fof(ax141, axiom,
constr_CONST_3 != name_Na).
fof(ax142, axiom,
constr_CONST_3 != name_c).
fof(ax143, axiom,
constr_CONST_3 != name_idA).
fof(ax144, axiom,
constr_CONST_3 != name_idB).
fof(ax145, axiom,
constr_CONST_3 != name_idC).
fof(ax146, axiom,
constr_CONST_3 != name_idS).
fof(ax147, axiom,
constr_CONST_4 != constr_C_STEP_1).
fof(ax148, axiom,
constr_CONST_4 != constr_C_STEP_2).
fof(ax149, axiom,
constr_CONST_4 != constr_C_STEP_3).
fof(ax150, axiom,
constr_CONST_4 != constr_C_STEP_4).
fof(ax151, axiom,
constr_CONST_4 != constr_S_STEP_1).
fof(ax152, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax153, axiom,
constr_CONST_4 != name_Kab).
fof(ax154, axiom,
constr_CONST_4 != name_Kas).
fof(ax155, axiom,
constr_CONST_4 != name_Kbc).
fof(ax156, axiom,
constr_CONST_4 != name_Kbs).
fof(ax157, axiom,
constr_CONST_4 != name_Kcs).
fof(ax158, axiom,
constr_CONST_4 != name_Na).
fof(ax159, axiom,
constr_CONST_4 != name_c).
fof(ax160, axiom,
constr_CONST_4 != name_idA).
fof(ax161, axiom,
constr_CONST_4 != name_idB).
fof(ax162, axiom,
constr_CONST_4 != name_idC).
fof(ax163, axiom,
constr_CONST_4 != name_idS).
fof(ax164, axiom,
constr_C_STEP_1 != constr_C_STEP_2).
fof(ax165, axiom,
constr_C_STEP_1 != constr_C_STEP_3).
fof(ax166, axiom,
constr_C_STEP_1 != constr_C_STEP_4).
fof(ax167, axiom,
constr_C_STEP_1 != constr_S_STEP_1).
fof(ax168, axiom,
constr_C_STEP_1 != constr_ZERO).
fof(ax169, axiom,
constr_C_STEP_1 != name_Kab).
fof(ax170, axiom,
constr_C_STEP_1 != name_Kas).
fof(ax171, axiom,
constr_C_STEP_1 != name_Kbc).
fof(ax172, axiom,
constr_C_STEP_1 != name_Kbs).
fof(ax173, axiom,
constr_C_STEP_1 != name_Kcs).
fof(ax174, axiom,
constr_C_STEP_1 != name_Na).
fof(ax175, axiom,
constr_C_STEP_1 != name_c).
fof(ax176, axiom,
constr_C_STEP_1 != name_idA).
fof(ax177, axiom,
constr_C_STEP_1 != name_idB).
fof(ax178, axiom,
constr_C_STEP_1 != name_idC).
fof(ax179, axiom,
constr_C_STEP_1 != name_idS).
fof(ax180, axiom,
constr_C_STEP_2 != constr_C_STEP_3).
fof(ax181, axiom,
constr_C_STEP_2 != constr_C_STEP_4).
fof(ax182, axiom,
constr_C_STEP_2 != constr_S_STEP_1).
fof(ax183, axiom,
constr_C_STEP_2 != constr_ZERO).
fof(ax184, axiom,
constr_C_STEP_2 != name_Kab).
fof(ax185, axiom,
constr_C_STEP_2 != name_Kas).
fof(ax186, axiom,
constr_C_STEP_2 != name_Kbc).
fof(ax187, axiom,
constr_C_STEP_2 != name_Kbs).
fof(ax188, axiom,
constr_C_STEP_2 != name_Kcs).
fof(ax189, axiom,
constr_C_STEP_2 != name_Na).
fof(ax190, axiom,
constr_C_STEP_2 != name_c).
fof(ax191, axiom,
constr_C_STEP_2 != name_idA).
fof(ax192, axiom,
constr_C_STEP_2 != name_idB).
fof(ax193, axiom,
constr_C_STEP_2 != name_idC).
fof(ax194, axiom,
constr_C_STEP_2 != name_idS).
fof(ax195, axiom,
constr_C_STEP_3 != constr_C_STEP_4).
fof(ax196, axiom,
constr_C_STEP_3 != constr_S_STEP_1).
fof(ax197, axiom,
constr_C_STEP_3 != constr_ZERO).
fof(ax198, axiom,
constr_C_STEP_3 != name_Kab).
fof(ax199, axiom,
constr_C_STEP_3 != name_Kas).
fof(ax200, axiom,
constr_C_STEP_3 != name_Kbc).
fof(ax201, axiom,
constr_C_STEP_3 != name_Kbs).
fof(ax202, axiom,
constr_C_STEP_3 != name_Kcs).
fof(ax203, axiom,
constr_C_STEP_3 != name_Na).
fof(ax204, axiom,
constr_C_STEP_3 != name_c).
fof(ax205, axiom,
constr_C_STEP_3 != name_idA).
fof(ax206, axiom,
constr_C_STEP_3 != name_idB).
fof(ax207, axiom,
constr_C_STEP_3 != name_idC).
fof(ax208, axiom,
constr_C_STEP_3 != name_idS).
fof(ax209, axiom,
constr_C_STEP_4 != constr_S_STEP_1).
fof(ax210, axiom,
constr_C_STEP_4 != constr_ZERO).
fof(ax211, axiom,
constr_C_STEP_4 != name_Kab).
fof(ax212, axiom,
constr_C_STEP_4 != name_Kas).
fof(ax213, axiom,
constr_C_STEP_4 != name_Kbc).
fof(ax214, axiom,
constr_C_STEP_4 != name_Kbs).
fof(ax215, axiom,
constr_C_STEP_4 != name_Kcs).
fof(ax216, axiom,
constr_C_STEP_4 != name_Na).
fof(ax217, axiom,
constr_C_STEP_4 != name_c).
fof(ax218, axiom,
constr_C_STEP_4 != name_idA).
fof(ax219, axiom,
constr_C_STEP_4 != name_idB).
fof(ax220, axiom,
constr_C_STEP_4 != name_idC).
fof(ax221, axiom,
constr_C_STEP_4 != name_idS).
fof(ax222, axiom,
constr_S_STEP_1 != constr_ZERO).
fof(ax223, axiom,
constr_S_STEP_1 != name_Kab).
fof(ax224, axiom,
constr_S_STEP_1 != name_Kas).
fof(ax225, axiom,
constr_S_STEP_1 != name_Kbc).
fof(ax226, axiom,
constr_S_STEP_1 != name_Kbs).
fof(ax227, axiom,
constr_S_STEP_1 != name_Kcs).
fof(ax228, axiom,
constr_S_STEP_1 != name_Na).
fof(ax229, axiom,
constr_S_STEP_1 != name_c).
fof(ax230, axiom,
constr_S_STEP_1 != name_idA).
fof(ax231, axiom,
constr_S_STEP_1 != name_idB).
fof(ax232, axiom,
constr_S_STEP_1 != name_idC).
fof(ax233, axiom,
constr_S_STEP_1 != name_idS).
fof(ax234, axiom,
constr_ZERO != name_Kab).
fof(ax235, axiom,
constr_ZERO != name_Kas).
fof(ax236, axiom,
constr_ZERO != name_Kbc).
fof(ax237, axiom,
constr_ZERO != name_Kbs).
fof(ax238, axiom,
constr_ZERO != name_Kcs).
fof(ax239, axiom,
constr_ZERO != name_Na).
fof(ax240, axiom,
constr_ZERO != name_c).
fof(ax241, axiom,
constr_ZERO != name_idA).
fof(ax242, axiom,
constr_ZERO != name_idB).
fof(ax243, axiom,
constr_ZERO != name_idC).
fof(ax244, axiom,
constr_ZERO != name_idS).
fof(ax245, axiom,
name_Kab != name_Kas).
fof(ax246, axiom,
name_Kab != name_Kbc).
fof(ax247, axiom,
name_Kab != name_Kbs).
fof(ax248, axiom,
name_Kab != name_Kcs).
fof(ax249, axiom,
name_Kab != name_Na).
fof(ax250, axiom,
name_Kab != name_c).
fof(ax251, axiom,
name_Kab != name_idA).
fof(ax252, axiom,
name_Kab != name_idB).
fof(ax253, axiom,
name_Kab != name_idC).
fof(ax254, axiom,
name_Kab != name_idS).
fof(ax255, axiom,
name_Kas != name_Kbc).
fof(ax256, axiom,
name_Kas != name_Kbs).
fof(ax257, axiom,
name_Kas != name_Kcs).
fof(ax258, axiom,
name_Kas != name_Na).
fof(ax259, axiom,
name_Kas != name_c).
fof(ax260, axiom,
name_Kas != name_idA).
fof(ax261, axiom,
name_Kas != name_idB).
fof(ax262, axiom,
name_Kas != name_idC).
fof(ax263, axiom,
name_Kas != name_idS).
fof(ax264, axiom,
name_Kbc != name_Kbs).
fof(ax265, axiom,
name_Kbc != name_Kcs).
fof(ax266, axiom,
name_Kbc != name_Na).
fof(ax267, axiom,
name_Kbc != name_c).
fof(ax268, axiom,
name_Kbc != name_idA).
fof(ax269, axiom,
name_Kbc != name_idB).
fof(ax270, axiom,
name_Kbc != name_idC).
fof(ax271, axiom,
name_Kbc != name_idS).
fof(ax272, axiom,
name_Kbs != name_Kcs).
fof(ax273, axiom,
name_Kbs != name_Na).
fof(ax274, axiom,
name_Kbs != name_c).
fof(ax275, axiom,
name_Kbs != name_idA).
fof(ax276, axiom,
name_Kbs != name_idB).
fof(ax277, axiom,
name_Kbs != name_idC).
fof(ax278, axiom,
name_Kbs != name_idS).
fof(ax279, axiom,
name_Kcs != name_Na).
fof(ax280, axiom,
name_Kcs != name_c).
fof(ax281, axiom,
name_Kcs != name_idA).
fof(ax282, axiom,
name_Kcs != name_idB).
fof(ax283, axiom,
name_Kcs != name_idC).
fof(ax284, axiom,
name_Kcs != name_idS).
fof(ax285, axiom,
name_Na != name_c).
fof(ax286, axiom,
name_Na != name_idA).
fof(ax287, axiom,
name_Na != name_idB).
fof(ax288, axiom,
name_Na != name_idC).
fof(ax289, axiom,
name_Na != name_idS).
fof(ax290, axiom,
name_c != name_idA).
fof(ax291, axiom,
name_c != name_idB).
fof(ax292, axiom,
name_c != name_idC).
fof(ax293, axiom,
name_c != name_idS).
fof(ax294, axiom,
name_idA != name_idB).
fof(ax295, axiom,
name_idA != name_idC).
fof(ax296, axiom,
name_idA != name_idS).
fof(ax297, axiom,
name_idB != name_idC).
fof(ax298, axiom,
name_idB != name_idS).
fof(ax299, axiom,
name_idC != name_idS).
fof(ax300, axiom,
![VAR_X_72] : (pred_eq(VAR_X_72, VAR_X_72))).
fof(ax301, axiom,
![VAR_V_79, VAR_V_80X30] : ((pred_attacker(VAR_V_79) & pred_attacker(VAR_V_80X30)) => pred_attacker(constr_xor(VAR_V_79, VAR_V_80X30)))).
fof(ax302, axiom,
pred_attacker(tuple_true)).
fof(ax303, axiom,
![VAR_V_84, VAR_V_85] : ((pred_attacker(VAR_V_84) & pred_attacker(VAR_V_85)) => pred_attacker(constr_h(VAR_V_84, VAR_V_85)))).
fof(ax304, axiom,
pred_attacker(tuple_false)).
fof(ax305, axiom,
![VAR_V_88, VAR_V_89] : ((pred_attacker(VAR_V_88) & pred_attacker(VAR_V_89)) => pred_attacker(constr_enc(VAR_V_88, VAR_V_89)))).
fof(ax306, axiom,
![VAR_X1_90X30, VAR_X2_91, VAR_X3_92, VAR_X4_93, VAR_X5_94] : (pred_attacker(constr_con5(VAR_X1_90X30, VAR_X2_91, VAR_X3_92, VAR_X4_93, VAR_X5_94)) => pred_attacker(tuple_5(VAR_X1_90X30, VAR_X2_91, VAR_X3_92, VAR_X4_93, VAR_X5_94)))).
fof(ax307, axiom,
![VAR_X1_96, VAR_X2_97, VAR_X3_98, VAR_X4_99] : (pred_attacker(constr_con4(VAR_X1_96, VAR_X2_97, VAR_X3_98, VAR_X4_99)) => pred_attacker(tuple_4(VAR_X1_96, VAR_X2_97, VAR_X3_98, VAR_X4_99)))).
fof(ax308, axiom,
![VAR_X1_10X301, VAR_X2_10X302, VAR_X3_10X303] : (pred_attacker(constr_con3(VAR_X1_10X301, VAR_X2_10X302, VAR_X3_10X303)) => pred_attacker(tuple_3(VAR_X1_10X301, VAR_X2_10X302, VAR_X3_10X303)))).
fof(ax309, axiom,
![VAR_X_10X305, VAR_Y_10X306] : ((pred_attacker(constr_enc(VAR_X_10X305, VAR_Y_10X306)) & pred_attacker(VAR_Y_10X306)) => pred_attacker(VAR_X_10X305))).
fof(ax310, axiom,
![VAR_V_116, VAR_V_117, VAR_V_118, VAR_V_119, VAR_V_120X30] : ((pred_attacker(VAR_V_116) & pred_attacker(VAR_V_117) & pred_attacker(VAR_V_118) & pred_attacker(VAR_V_119) & pred_attacker(VAR_V_120X30)) => pred_attacker(constr_con5(VAR_V_116, VAR_V_117, VAR_V_118, VAR_V_119, VAR_V_120X30)))).
fof(ax311, axiom,
![VAR_V_125, VAR_V_126, VAR_V_127, VAR_V_128] : ((pred_attacker(VAR_V_125) & pred_attacker(VAR_V_126) & pred_attacker(VAR_V_127) & pred_attacker(VAR_V_128)) => pred_attacker(constr_con4(VAR_V_125, VAR_V_126, VAR_V_127, VAR_V_128)))).
fof(ax312, axiom,
![VAR_V_132, VAR_V_133, VAR_V_134] : ((pred_attacker(VAR_V_132) & pred_attacker(VAR_V_133) & pred_attacker(VAR_V_134)) => pred_attacker(constr_con3(VAR_V_132, VAR_V_133, VAR_V_134)))).
fof(ax313, axiom,
pred_attacker(constr_ZERO)).
fof(ax314, axiom,
pred_attacker(constr_S_STEP_1)).
fof(ax315, axiom,
pred_attacker(constr_C_STEP_4)).
fof(ax316, axiom,
pred_attacker(constr_C_STEP_3)).
fof(ax317, axiom,
pred_attacker(constr_C_STEP_2)).
fof(ax318, axiom,
pred_attacker(constr_C_STEP_1)).
fof(ax319, axiom,
pred_attacker(constr_CONST_4)).
fof(ax320, axiom,
pred_attacker(constr_CONST_3)).
fof(ax321, axiom,
pred_attacker(constr_CONST_2)).
fof(ax322, axiom,
pred_attacker(constr_CONST_1)).
fof(ax323, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax324, axiom,
pred_attacker(constr_B_STEP_2)).
fof(ax325, axiom,
pred_attacker(constr_B_STEP_1)).
fof(ax326, axiom,
pred_attacker(constr_A_STEP_1)).
fof(ax327, axiom,
![VAR_V_147, VAR_V_148, VAR_V_149, VAR_V_150X30, VAR_V_151, VAR_V_152, VAR_V_153, VAR_V_154] : ((pred_attacker(VAR_V_147) & pred_attacker(VAR_V_148) & pred_attacker(VAR_V_149) & pred_attacker(VAR_V_150X30) & pred_attacker(VAR_V_151) & pred_attacker(VAR_V_152) & pred_attacker(VAR_V_153) & pred_attacker(VAR_V_154)) => pred_attacker(tuple_8(VAR_V_147, VAR_V_148, VAR_V_149, VAR_V_150X30, VAR_V_151, VAR_V_152, VAR_V_153, VAR_V_154)))).
fof(ax328, axiom,
![VAR_V_227, VAR_V_228, VAR_V_229, VAR_V_230X30, VAR_V_231, VAR_V_232, VAR_V_233, VAR_V_234] : (pred_attacker(tuple_8(VAR_V_227, VAR_V_228, VAR_V_229, VAR_V_230X30, VAR_V_231, VAR_V_232, VAR_V_233, VAR_V_234)) => pred_attacker(VAR_V_227))).
fof(ax329, axiom,
![VAR_V_236, VAR_V_237, VAR_V_238, VAR_V_239, VAR_V_240X30, VAR_V_241, VAR_V_242, VAR_V_243] : (pred_attacker(tuple_8(VAR_V_236, VAR_V_237, VAR_V_238, VAR_V_239, VAR_V_240X30, VAR_V_241, VAR_V_242, VAR_V_243)) => pred_attacker(VAR_V_237))).
fof(ax330, axiom,
![VAR_V_245, VAR_V_246, VAR_V_247, VAR_V_248, VAR_V_249, VAR_V_250X30, VAR_V_251, VAR_V_252] : (pred_attacker(tuple_8(VAR_V_245, VAR_V_246, VAR_V_247, VAR_V_248, VAR_V_249, VAR_V_250X30, VAR_V_251, VAR_V_252)) => pred_attacker(VAR_V_247))).
fof(ax331, axiom,
![VAR_V_254, VAR_V_255, VAR_V_256, VAR_V_257, VAR_V_258, VAR_V_259, VAR_V_260X30, VAR_V_261] : (pred_attacker(tuple_8(VAR_V_254, VAR_V_255, VAR_V_256, VAR_V_257, VAR_V_258, VAR_V_259, VAR_V_260X30, VAR_V_261)) => pred_attacker(VAR_V_257))).
fof(ax332, axiom,
![VAR_V_263, VAR_V_264, VAR_V_265, VAR_V_266, VAR_V_267, VAR_V_268, VAR_V_269, VAR_V_270X30] : (pred_attacker(tuple_8(VAR_V_263, VAR_V_264, VAR_V_265, VAR_V_266, VAR_V_267, VAR_V_268, VAR_V_269, VAR_V_270X30)) => pred_attacker(VAR_V_267))).
fof(ax333, axiom,
![VAR_V_272, VAR_V_273, VAR_V_274, VAR_V_275, VAR_V_276, VAR_V_277, VAR_V_278, VAR_V_279] : (pred_attacker(tuple_8(VAR_V_272, VAR_V_273, VAR_V_274, VAR_V_275, VAR_V_276, VAR_V_277, VAR_V_278, VAR_V_279)) => pred_attacker(VAR_V_277))).
fof(ax334, axiom,
![VAR_V_281, VAR_V_282, VAR_V_283, VAR_V_284, VAR_V_285, VAR_V_286, VAR_V_287, VAR_V_288] : (pred_attacker(tuple_8(VAR_V_281, VAR_V_282, VAR_V_283, VAR_V_284, VAR_V_285, VAR_V_286, VAR_V_287, VAR_V_288)) => pred_attacker(VAR_V_287))).
fof(ax335, axiom,
![VAR_V_290X30, VAR_V_291, VAR_V_292, VAR_V_293, VAR_V_294, VAR_V_295, VAR_V_296, VAR_V_297] : (pred_attacker(tuple_8(VAR_V_290X30, VAR_V_291, VAR_V_292, VAR_V_293, VAR_V_294, VAR_V_295, VAR_V_296, VAR_V_297)) => pred_attacker(VAR_V_297))).
fof(ax336, axiom,
![VAR_V_30X303, VAR_V_30X304, VAR_V_30X305, VAR_V_30X306] : ((pred_attacker(VAR_V_30X303) & pred_attacker(VAR_V_30X304) & pred_attacker(VAR_V_30X305) & pred_attacker(VAR_V_30X306)) => pred_attacker(tuple_4(VAR_V_30X303, VAR_V_30X304, VAR_V_30X305, VAR_V_30X306)))).
fof(ax337, axiom,
![VAR_V_327, VAR_V_328, VAR_V_329, VAR_V_330X30] : (pred_attacker(tuple_4(VAR_V_327, VAR_V_328, VAR_V_329, VAR_V_330X30)) => pred_attacker(VAR_V_327))).
fof(ax338, axiom,
![VAR_V_332, VAR_V_333, VAR_V_334, VAR_V_335] : (pred_attacker(tuple_4(VAR_V_332, VAR_V_333, VAR_V_334, VAR_V_335)) => pred_attacker(VAR_V_333))).
fof(ax339, axiom,
![VAR_V_337, VAR_V_338, VAR_V_339, VAR_V_340X30] : (pred_attacker(tuple_4(VAR_V_337, VAR_V_338, VAR_V_339, VAR_V_340X30)) => pred_attacker(VAR_V_339))).
fof(ax340, axiom,
![VAR_V_342, VAR_V_343, VAR_V_344, VAR_V_345] : (pred_attacker(tuple_4(VAR_V_342, VAR_V_343, VAR_V_344, VAR_V_345)) => pred_attacker(VAR_V_345))).
fof(ax341, axiom,
![VAR_V_350X30, VAR_V_351, VAR_V_352] : ((pred_attacker(VAR_V_350X30) & pred_attacker(VAR_V_351) & pred_attacker(VAR_V_352)) => pred_attacker(tuple_3(VAR_V_350X30, VAR_V_351, VAR_V_352)))).
fof(ax342, axiom,
![VAR_V_365, VAR_V_366, VAR_V_367] : (pred_attacker(tuple_3(VAR_V_365, VAR_V_366, VAR_V_367)) => pred_attacker(VAR_V_365))).
fof(ax343, axiom,
![VAR_V_369, VAR_V_370X30, VAR_V_371] : (pred_attacker(tuple_3(VAR_V_369, VAR_V_370X30, VAR_V_371)) => pred_attacker(VAR_V_370X30))).
fof(ax344, axiom,
![VAR_V_373, VAR_V_374, VAR_V_375] : (pred_attacker(tuple_3(VAR_V_373, VAR_V_374, VAR_V_375)) => pred_attacker(VAR_V_375))).
fof(ax345, axiom,
![VAR_V_379, VAR_V_380X30] : ((pred_attacker(VAR_V_379) & pred_attacker(VAR_V_380X30)) => pred_attacker(tuple_2(VAR_V_379, VAR_V_380X30)))).
fof(ax346, axiom,
![VAR_V_387, VAR_V_388] : (pred_attacker(tuple_2(VAR_V_387, VAR_V_388)) => pred_attacker(VAR_V_387))).
fof(ax347, axiom,
![VAR_V_390X30, VAR_V_391] : (pred_attacker(tuple_2(VAR_V_390X30, VAR_V_391)) => pred_attacker(VAR_V_391))).
fof(ax348, axiom,
![VAR_V_40X305, VAR_V_40X306, VAR_V_40X307, VAR_V_40X308, VAR_V_40X309, VAR_V_410X30, VAR_V_411, VAR_V_412, VAR_V_413, VAR_V_414, VAR_V_415, VAR_V_416] : ((pred_attacker(VAR_V_40X305) & pred_attacker(VAR_V_40X306) & pred_attacker(VAR_V_40X307) & pred_attacker(VAR_V_40X308) & pred_attacker(VAR_V_40X309) & pred_attacker(VAR_V_410X30) & pred_attacker(VAR_V_411) & pred_attacker(VAR_V_412) & pred_attacker(VAR_V_413) & pred_attacker(VAR_V_414) & pred_attacker(VAR_V_415) & pred_attacker(VAR_V_416)) => pred_attacker(tuple_12(VAR_V_40X305, VAR_V_40X306, VAR_V_40X307, VAR_V_40X308, VAR_V_40X309, VAR_V_410X30, VAR_V_411, VAR_V_412, VAR_V_413, VAR_V_414, VAR_V_415, VAR_V_416)))).
fof(ax349, axiom,
![VAR_V_573, VAR_V_574, VAR_V_575, VAR_V_576, VAR_V_577, VAR_V_578, VAR_V_579, VAR_V_580X30, VAR_V_581, VAR_V_582, VAR_V_583, VAR_V_584] : (pred_attacker(tuple_12(VAR_V_573, VAR_V_574, VAR_V_575, VAR_V_576, VAR_V_577, VAR_V_578, VAR_V_579, VAR_V_580X30, VAR_V_581, VAR_V_582, VAR_V_583, VAR_V_584)) => pred_attacker(VAR_V_573))).
fof(ax350, axiom,
![VAR_V_586, VAR_V_587, VAR_V_588, VAR_V_589, VAR_V_590X30, VAR_V_591, VAR_V_592, VAR_V_593, VAR_V_594, VAR_V_595, VAR_V_596, VAR_V_597] : (pred_attacker(tuple_12(VAR_V_586, VAR_V_587, VAR_V_588, VAR_V_589, VAR_V_590X30, VAR_V_591, VAR_V_592, VAR_V_593, VAR_V_594, VAR_V_595, VAR_V_596, VAR_V_597)) => pred_attacker(VAR_V_587))).
fof(ax351, axiom,
![VAR_V_599, VAR_V_60X300X30, VAR_V_60X301, VAR_V_60X302, VAR_V_60X303, VAR_V_60X304, VAR_V_60X305, VAR_V_60X306, VAR_V_60X307, VAR_V_60X308, VAR_V_60X309, VAR_V_610X30] : (pred_attacker(tuple_12(VAR_V_599, VAR_V_60X300X30, VAR_V_60X301, VAR_V_60X302, VAR_V_60X303, VAR_V_60X304, VAR_V_60X305, VAR_V_60X306, VAR_V_60X307, VAR_V_60X308, VAR_V_60X309, VAR_V_610X30)) => pred_attacker(VAR_V_60X301))).
fof(ax352, axiom,
![VAR_V_612, VAR_V_613, VAR_V_614, VAR_V_615, VAR_V_616, VAR_V_617, VAR_V_618, VAR_V_619, VAR_V_620X30, VAR_V_621, VAR_V_622, VAR_V_623] : (pred_attacker(tuple_12(VAR_V_612, VAR_V_613, VAR_V_614, VAR_V_615, VAR_V_616, VAR_V_617, VAR_V_618, VAR_V_619, VAR_V_620X30, VAR_V_621, VAR_V_622, VAR_V_623)) => pred_attacker(VAR_V_615))).
fof(ax353, axiom,
![VAR_V_625, VAR_V_626, VAR_V_627, VAR_V_628, VAR_V_629, VAR_V_630X30, VAR_V_631, VAR_V_632, VAR_V_633, VAR_V_634, VAR_V_635, VAR_V_636] : (pred_attacker(tuple_12(VAR_V_625, VAR_V_626, VAR_V_627, VAR_V_628, VAR_V_629, VAR_V_630X30, VAR_V_631, VAR_V_632, VAR_V_633, VAR_V_634, VAR_V_635, VAR_V_636)) => pred_attacker(VAR_V_629))).
fof(ax354, axiom,
![VAR_V_638, VAR_V_639, VAR_V_640X30, VAR_V_641, VAR_V_642, VAR_V_643, VAR_V_644, VAR_V_645, VAR_V_646, VAR_V_647, VAR_V_648, VAR_V_649] : (pred_attacker(tuple_12(VAR_V_638, VAR_V_639, VAR_V_640X30, VAR_V_641, VAR_V_642, VAR_V_643, VAR_V_644, VAR_V_645, VAR_V_646, VAR_V_647, VAR_V_648, VAR_V_649)) => pred_attacker(VAR_V_643))).
fof(ax355, axiom,
![VAR_V_651, VAR_V_652, VAR_V_653, VAR_V_654, VAR_V_655, VAR_V_656, VAR_V_657, VAR_V_658, VAR_V_659, VAR_V_660X30, VAR_V_661, VAR_V_662] : (pred_attacker(tuple_12(VAR_V_651, VAR_V_652, VAR_V_653, VAR_V_654, VAR_V_655, VAR_V_656, VAR_V_657, VAR_V_658, VAR_V_659, VAR_V_660X30, VAR_V_661, VAR_V_662)) => pred_attacker(VAR_V_657))).
fof(ax356, axiom,
![VAR_V_664, VAR_V_665, VAR_V_666, VAR_V_667, VAR_V_668, VAR_V_669, VAR_V_670X30, VAR_V_671, VAR_V_672, VAR_V_673, VAR_V_674, VAR_V_675] : (pred_attacker(tuple_12(VAR_V_664, VAR_V_665, VAR_V_666, VAR_V_667, VAR_V_668, VAR_V_669, VAR_V_670X30, VAR_V_671, VAR_V_672, VAR_V_673, VAR_V_674, VAR_V_675)) => pred_attacker(VAR_V_671))).
fof(ax357, axiom,
![VAR_V_677, VAR_V_678, VAR_V_679, VAR_V_680X30, VAR_V_681, VAR_V_682, VAR_V_683, VAR_V_684, VAR_V_685, VAR_V_686, VAR_V_687, VAR_V_688] : (pred_attacker(tuple_12(VAR_V_677, VAR_V_678, VAR_V_679, VAR_V_680X30, VAR_V_681, VAR_V_682, VAR_V_683, VAR_V_684, VAR_V_685, VAR_V_686, VAR_V_687, VAR_V_688)) => pred_attacker(VAR_V_685))).
fof(ax358, axiom,
![VAR_V_690X30, VAR_V_691, VAR_V_692, VAR_V_693, VAR_V_694, VAR_V_695, VAR_V_696, VAR_V_697, VAR_V_698, VAR_V_699, VAR_V_70X300X30, VAR_V_70X301] : (pred_attacker(tuple_12(VAR_V_690X30, VAR_V_691, VAR_V_692, VAR_V_693, VAR_V_694, VAR_V_695, VAR_V_696, VAR_V_697, VAR_V_698, VAR_V_699, VAR_V_70X300X30, VAR_V_70X301)) => pred_attacker(VAR_V_699))).
fof(ax359, axiom,
![VAR_V_70X303, VAR_V_70X304, VAR_V_70X305, VAR_V_70X306, VAR_V_70X307, VAR_V_70X308, VAR_V_70X309, VAR_V_710X30, VAR_V_711, VAR_V_712, VAR_V_713, VAR_V_714] : (pred_attacker(tuple_12(VAR_V_70X303, VAR_V_70X304, VAR_V_70X305, VAR_V_70X306, VAR_V_70X307, VAR_V_70X308, VAR_V_70X309, VAR_V_710X30, VAR_V_711, VAR_V_712, VAR_V_713, VAR_V_714)) => pred_attacker(VAR_V_713))).
fof(ax360, axiom,
![VAR_V_716, VAR_V_717, VAR_V_718, VAR_V_719, VAR_V_720X30, VAR_V_721, VAR_V_722, VAR_V_723, VAR_V_724, VAR_V_725, VAR_V_726, VAR_V_727] : (pred_attacker(tuple_12(VAR_V_716, VAR_V_717, VAR_V_718, VAR_V_719, VAR_V_720X30, VAR_V_721, VAR_V_722, VAR_V_723, VAR_V_724, VAR_V_725, VAR_V_726, VAR_V_727)) => pred_attacker(VAR_V_727))).
fof(ax361, axiom,
![VAR_V_734, VAR_V_735, VAR_V_736, VAR_V_737, VAR_V_738] : ((pred_attacker(VAR_V_734) & pred_attacker(VAR_V_735) & pred_attacker(VAR_V_736) & pred_attacker(VAR_V_737) & pred_attacker(VAR_V_738)) => pred_attacker(tuple_5(VAR_V_734, VAR_V_735, VAR_V_736, VAR_V_737, VAR_V_738)))).
fof(ax362, axiom,
![VAR_V_769, VAR_V_770X30, VAR_V_771, VAR_V_772, VAR_V_773] : (pred_attacker(tuple_5(VAR_V_769, VAR_V_770X30, VAR_V_771, VAR_V_772, VAR_V_773)) => pred_attacker(VAR_V_769))).
fof(ax363, axiom,
![VAR_V_775, VAR_V_776, VAR_V_777, VAR_V_778, VAR_V_779] : (pred_attacker(tuple_5(VAR_V_775, VAR_V_776, VAR_V_777, VAR_V_778, VAR_V_779)) => pred_attacker(VAR_V_776))).
fof(ax364, axiom,
![VAR_V_781, VAR_V_782, VAR_V_783, VAR_V_784, VAR_V_785] : (pred_attacker(tuple_5(VAR_V_781, VAR_V_782, VAR_V_783, VAR_V_784, VAR_V_785)) => pred_attacker(VAR_V_783))).
fof(ax365, axiom,
![VAR_V_787, VAR_V_788, VAR_V_789, VAR_V_790X30, VAR_V_791] : (pred_attacker(tuple_5(VAR_V_787, VAR_V_788, VAR_V_789, VAR_V_790X30, VAR_V_791)) => pred_attacker(VAR_V_790X30))).
fof(ax366, axiom,
![VAR_V_793, VAR_V_794, VAR_V_795, VAR_V_796, VAR_V_797] : (pred_attacker(tuple_5(VAR_V_793, VAR_V_794, VAR_V_795, VAR_V_796, VAR_V_797)) => pred_attacker(VAR_V_797))).
fof(ax367, axiom,
![VAR_V_80X300X30] : (pred_attacker(VAR_V_80X300X30) => pred_attacker(tuple_1(VAR_V_80X300X30)))).
fof(ax368, axiom,
![VAR_V_80X303] : (pred_attacker(tuple_1(VAR_V_80X303)) => pred_attacker(VAR_V_80X303))).
fof(ax369, axiom,
![VAR_V_80X305, VAR_V_80X306] : ((pred_mess(VAR_V_80X306, VAR_V_80X305) & pred_attacker(VAR_V_80X306)) => pred_attacker(VAR_V_80X305))).
fof(ax370, axiom,
![VAR_V_80X307, VAR_V_80X308] : ((pred_attacker(VAR_V_80X308) & pred_attacker(VAR_V_80X307)) => pred_mess(VAR_V_80X308, VAR_V_80X307))).
fof(ax371, axiom,
pred_attacker(name_idS)).
fof(ax372, axiom,
pred_attacker(name_idC)).
fof(ax373, axiom,
pred_attacker(name_idB)).
fof(ax374, axiom,
pred_attacker(name_idA)).
fof(ax375, axiom,
pred_attacker(name_c)).
fof(ax376, axiom,
pred_attacker(name_Kcs)).
fof(ax377, axiom,
![VAR_V_810X30] : (pred_equal(VAR_V_810X30, VAR_V_810X30))).
fof(ax378, axiom,
![VAR_V_811] : (pred_attacker(name_new0x2Dname(VAR_V_811)))).
fof(ax379, axiom,
pred_attacker(tuple_2(tuple_2(constr_h(constr_con3(name_idA, name_idB, name_Na), name_Kas), tuple_3(name_idA, name_idB, name_Na)), constr_A_STEP_1))).
fof(ax380, axiom,
![VAR_NA_10X3094] : (pred_attacker(tuple_2(constr_h(constr_con3(name_idA, name_idB, VAR_NA_10X3094), name_Kas), tuple_3(name_idA, name_idB, VAR_NA_10X3094))) => pred_attacker(tuple_2(tuple_2(constr_h(constr_con4(name_idB, name_idC, name_Nb(VAR_NA_10X3094, name_idB, name_idA, constr_h(constr_con3(name_idA, name_idB, VAR_NA_10X3094), name_Kas)), constr_con4(constr_h(constr_con3(name_idA, name_idB, VAR_NA_10X3094), name_Kas), name_idA, name_idB, VAR_NA_10X3094)), name_Kbs), tuple_4(name_idB, name_idC, name_Nb(VAR_NA_10X3094, name_idB, name_idA, constr_h(constr_con3(name_idA, name_idB, VAR_NA_10X3094), name_Kas)), tuple_2(constr_h(constr_con3(name_idA, name_idB, VAR_NA_10X3094), name_Kas), tuple_3(name_idA, name_idB, VAR_NA_10X3094)))), constr_B_STEP_1)))).
fof(ax381, axiom,
![VAR_NA_1222, VAR_ENC_IDA_IDB_NA_KAB_1220X30, VAR_XOR_KAB_H_NA_KAS_1219, VAR_XOR_KAB_H_NB_KBS_1221, VAR_XOR_KBC_H_NB_KBS_1223] : ((pred_attacker(tuple_12(name_idA, name_idB, VAR_XOR_KAB_H_NA_KAS_1219, VAR_ENC_IDA_IDB_NA_KAB_1220X30, name_idB, name_idA, VAR_XOR_KAB_H_NB_KBS_1221, constr_enc(constr_con3(name_idB, name_idA, name_Nb(VAR_NA_1222, name_idB, name_idA, constr_h(constr_con3(name_idA, name_idB, VAR_NA_1222), name_Kas))), constr_xor(VAR_XOR_KAB_H_NB_KBS_1221, constr_h(name_Nb(VAR_NA_1222, name_idB, name_idA, constr_h(constr_con3(name_idA, name_idB, VAR_NA_1222), name_Kas)), name_Kbs))), name_idB, name_idC, VAR_XOR_KBC_H_NB_KBS_1223, constr_enc(constr_con3(name_idB, name_idC, name_Nb(VAR_NA_1222, name_idB, name_idA, constr_h(constr_con3(name_idA, name_idB, VAR_NA_1222), name_Kas))), constr_xor(VAR_XOR_KBC_H_NB_KBS_1223, constr_h(name_Nb(VAR_NA_1222, name_idB, name_idA, constr_h(constr_con3(name_idA, name_idB, VAR_NA_1222), name_Kas)), name_Kbs))))) & pred_attacker(tuple_2(constr_h(constr_con3(name_idA, name_idB, VAR_NA_1222), name_Kas), tuple_3(name_idA, name_idB, VAR_NA_1222)))) => pred_attacker(tuple_2(tuple_4(name_idA, name_idB, VAR_XOR_KAB_H_NA_KAS_1219, VAR_ENC_IDA_IDB_NA_KAB_1220X30), constr_B_STEP_2)))).
fof(ax382, axiom,
![VAR_NOUNCE1ST_1473, VAR_NOUNCE2ND_1475, VAR_HSH2ND_1474] : (pred_attacker(tuple_2(constr_h(constr_con4(name_idB, name_idC, VAR_NOUNCE1ST_1473, constr_con4(VAR_HSH2ND_1474, name_idA, name_idB, VAR_NOUNCE2ND_1475)), name_Kbc), tuple_4(name_idB, name_idC, VAR_NOUNCE1ST_1473, tuple_2(VAR_HSH2ND_1474, tuple_3(name_idA, name_idB, VAR_NOUNCE2ND_1475))))) => pred_attacker(tuple_2(name_Nc(VAR_NOUNCE2ND_1475, name_idB, name_idA, VAR_HSH2ND_1474, VAR_NOUNCE1ST_1473, name_idC, name_idB, constr_h(constr_con4(name_idB, name_idC, VAR_NOUNCE1ST_1473, constr_con4(VAR_HSH2ND_1474, name_idA, name_idB, VAR_NOUNCE2ND_1475)), name_Kbc)), constr_C_STEP_1)))).
fof(ax383, axiom,
![VAR_NA_1631, VAR_NB_1629, VAR_HSH2ND_1630X30] : (pred_attacker(tuple_2(constr_h(constr_con4(name_idB, name_idC, VAR_NB_1629, constr_con4(VAR_HSH2ND_1630X30, name_idA, name_idB, VAR_NA_1631)), name_Kbc), tuple_4(name_idB, name_idC, VAR_NB_1629, tuple_2(VAR_HSH2ND_1630X30, tuple_3(name_idA, name_idB, VAR_NA_1631))))) => pred_attacker(tuple_2(tuple_2(constr_h(constr_con4(name_idC, name_idS, name_Nc(VAR_NA_1631, name_idB, name_idA, VAR_HSH2ND_1630X30, VAR_NB_1629, name_idC, name_idB, constr_h(constr_con4(name_idB, name_idC, VAR_NB_1629, constr_con4(VAR_HSH2ND_1630X30, name_idA, name_idB, VAR_NA_1631)), name_Kbc)), tuple_2(constr_h(constr_con4(name_idB, name_idC, VAR_NB_1629, constr_con4(VAR_HSH2ND_1630X30, name_idA, name_idB, VAR_NA_1631)), name_Kbc), tuple_4(name_idB, name_idC, VAR_NB_1629, tuple_2(VAR_HSH2ND_1630X30, tuple_3(name_idA, name_idB, VAR_NA_1631))))), name_Kcs), tuple_4(name_idC, name_idS, name_Nc(VAR_NA_1631, name_idB, name_idA, VAR_HSH2ND_1630X30, VAR_NB_1629, name_idC, name_idB, constr_h(constr_con4(name_idB, name_idC, VAR_NB_1629, constr_con4(VAR_HSH2ND_1630X30, name_idA, name_idB, VAR_NA_1631)), name_Kbc)), tuple_2(constr_h(constr_con4(name_idB, name_idC, VAR_NB_1629, constr_con4(VAR_HSH2ND_1630X30, name_idA, name_idB, VAR_NA_1631)), name_Kbc), tuple_4(name_idB, name_idC, VAR_NB_1629, tuple_2(VAR_HSH2ND_1630X30, tuple_3(name_idA, name_idB, VAR_NA_1631)))))), constr_C_STEP_2)))).
fof(ax384, axiom,
![VAR_NA_1680X30, VAR_NB_1678, VAR_ENC_IDA_IDB_NA_KAB_1671, VAR_ENC_IDB_IDA_NB_KAB_1673, VAR_ENC_IDB_IDC_NB_KBC_1675, VAR_ENC_IDC_IDB_NC_KBC_1677, VAR_HSH2ND_1679, VAR_XOR_KAB_H_NA_KAS_1670X30, VAR_XOR_KAB_H_NB_KBS_1672, VAR_XOR_KBC_H_NB_KBS_1674, VAR_XOR_KBC_H_NC_KCS_1676] : ((pred_attacker(tuple_8(VAR_XOR_KAB_H_NA_KAS_1670X30, VAR_ENC_IDA_IDB_NA_KAB_1671, VAR_XOR_KAB_H_NB_KBS_1672, VAR_ENC_IDB_IDA_NB_KAB_1673, VAR_XOR_KBC_H_NB_KBS_1674, VAR_ENC_IDB_IDC_NB_KBC_1675, VAR_XOR_KBC_H_NC_KCS_1676, VAR_ENC_IDC_IDB_NC_KBC_1677)) & pred_attacker(tuple_2(constr_h(constr_con4(name_idB, name_idC, VAR_NB_1678, constr_con4(VAR_HSH2ND_1679, name_idA, name_idB, VAR_NA_1680X30)), name_Kbc), tuple_4(name_idB, name_idC, VAR_NB_1678, tuple_2(VAR_HSH2ND_1679, tuple_3(name_idA, name_idB, VAR_NA_1680X30)))))) => pred_attacker(tuple_2(constr_xor(VAR_XOR_KBC_H_NC_KCS_1676, constr_h(name_Nc(VAR_NA_1680X30, name_idB, name_idA, VAR_HSH2ND_1679, VAR_NB_1678, name_idC, name_idB, constr_h(constr_con4(name_idB, name_idC, VAR_NB_1678, constr_con4(VAR_HSH2ND_1679, name_idA, name_idB, VAR_NA_1680X30)), name_Kbc)), name_Kcs)), constr_C_STEP_3)))).
fof(ax385, axiom,
![VAR_NA_1765, VAR_NB_1767, VAR_ENC_IDA_IDB_NA_KAB_1759, VAR_ENC_IDB_IDA_NB_KAB_1761, VAR_ENC_IDB_IDC_NB_KBC_1763, VAR_HSH2ND_1766, VAR_XOR_KAB_H_NA_KAS_1758, VAR_XOR_KAB_H_NB_KBS_1760X30, VAR_XOR_KBC_H_NB_KBS_1762, VAR_XOR_KBC_H_NC_KCS_1764] : ((pred_attacker(tuple_8(VAR_XOR_KAB_H_NA_KAS_1758, VAR_ENC_IDA_IDB_NA_KAB_1759, VAR_XOR_KAB_H_NB_KBS_1760X30, VAR_ENC_IDB_IDA_NB_KAB_1761, VAR_XOR_KBC_H_NB_KBS_1762, VAR_ENC_IDB_IDC_NB_KBC_1763, VAR_XOR_KBC_H_NC_KCS_1764, constr_enc(constr_con3(name_idC, name_idB, name_Nc(VAR_NA_1765, name_idB, name_idA, VAR_HSH2ND_1766, VAR_NB_1767, name_idC, name_idB, constr_h(constr_con4(name_idB, name_idC, VAR_NB_1767, constr_con4(VAR_HSH2ND_1766, name_idA, name_idB, VAR_NA_1765)), name_Kbc))), constr_xor(VAR_XOR_KBC_H_NC_KCS_1764, constr_h(name_Nc(VAR_NA_1765, name_idB, name_idA, VAR_HSH2ND_1766, VAR_NB_1767, name_idC, name_idB, constr_h(constr_con4(name_idB, name_idC, VAR_NB_1767, constr_con4(VAR_HSH2ND_1766, name_idA, name_idB, VAR_NA_1765)), name_Kbc)), name_Kcs))))) & pred_attacker(tuple_2(constr_h(constr_con4(name_idB, name_idC, VAR_NB_1767, constr_con4(VAR_HSH2ND_1766, name_idA, name_idB, VAR_NA_1765)), name_Kbc), tuple_4(name_idB, name_idC, VAR_NB_1767, tuple_2(VAR_HSH2ND_1766, tuple_3(name_idA, name_idB, VAR_NA_1765)))))) => pred_attacker(tuple_2(tuple_12(name_idA, name_idB, VAR_XOR_KAB_H_NA_KAS_1758, VAR_ENC_IDA_IDB_NA_KAB_1759, name_idB, name_idA, VAR_XOR_KAB_H_NB_KBS_1760X30, VAR_ENC_IDB_IDA_NB_KAB_1761, name_idB, name_idC, VAR_XOR_KBC_H_NB_KBS_1762, VAR_ENC_IDB_IDC_NB_KBC_1763), constr_C_STEP_4)))).
fof(ax386, axiom,
![VAR_NA_2493, VAR_NB_2491, VAR_NC_2489, VAR_HSH2ND_2490X30, VAR_HSH3RD_2492] : (pred_attacker(tuple_2(constr_h(constr_con4(name_idC, name_idS, VAR_NC_2489, constr_con5(VAR_HSH2ND_2490X30, name_idB, name_idC, VAR_NB_2491, constr_con4(VAR_HSH3RD_2492, name_idA, name_idB, VAR_NA_2493))), name_Kcs), tuple_4(name_idC, name_idS, VAR_NC_2489, tuple_2(VAR_HSH2ND_2490X30, tuple_4(name_idB, name_idC, VAR_NB_2491, tuple_2(VAR_HSH3RD_2492, tuple_3(name_idA, name_idB, VAR_NA_2493))))))) => pred_attacker(tuple_2(tuple_8(constr_xor(name_Kab, constr_h(VAR_NA_2493, name_Kas)), constr_enc(constr_con3(name_idA, name_idB, VAR_NA_2493), name_Kab), constr_xor(name_Kab, constr_h(VAR_NB_2491, name_Kbs)), constr_enc(constr_con3(name_idB, name_idA, VAR_NB_2491), name_Kab), constr_xor(name_Kbc, constr_h(VAR_NB_2491, name_Kbs)), constr_enc(constr_con3(name_idB, name_idC, VAR_NB_2491), name_Kbc), constr_xor(name_Kbc, constr_h(VAR_NC_2489, name_Kcs)), constr_enc(constr_con3(name_idC, name_idB, VAR_NC_2489), name_Kbc)), constr_S_STEP_1)))).
fof(co0, conjecture,
pred_attacker(name_Kab)).
