%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax5, axiom,
constr_CONST_0x30 != name_A).
fof(ax6, axiom,
constr_CONST_0x30 != name_B).
fof(ax7, axiom,
constr_CONST_0x30 != name_C).
fof(ax8, axiom,
constr_CONST_0x30 != name_Kab_39).
fof(ax9, axiom,
constr_CONST_0x30 != name_Kas).
fof(ax10, axiom,
constr_CONST_0x30 != name_Kbc_40x30).
fof(ax11, axiom,
constr_CONST_0x30 != name_Kbs).
fof(ax12, axiom,
constr_CONST_0x30 != name_Kcs).
fof(ax13, axiom,
constr_CONST_0x30 != name_Na).
fof(ax14, axiom,
constr_CONST_0x30 != name_S).
fof(ax15, axiom,
constr_CONST_0x30 != name_c).
fof(ax16, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax17, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax18, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax19, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax20, axiom,
constr_CONST_1 != name_A).
fof(ax21, axiom,
constr_CONST_1 != name_B).
fof(ax22, axiom,
constr_CONST_1 != name_C).
fof(ax23, axiom,
constr_CONST_1 != name_Kab_39).
fof(ax24, axiom,
constr_CONST_1 != name_Kas).
fof(ax25, axiom,
constr_CONST_1 != name_Kbc_40x30).
fof(ax26, axiom,
constr_CONST_1 != name_Kbs).
fof(ax27, axiom,
constr_CONST_1 != name_Kcs).
fof(ax28, axiom,
constr_CONST_1 != name_Na).
fof(ax29, axiom,
constr_CONST_1 != name_S).
fof(ax30, axiom,
constr_CONST_1 != name_c).
fof(ax31, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax32, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax33, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax34, axiom,
constr_CONST_2 != name_A).
fof(ax35, axiom,
constr_CONST_2 != name_B).
fof(ax36, axiom,
constr_CONST_2 != name_C).
fof(ax37, axiom,
constr_CONST_2 != name_Kab_39).
fof(ax38, axiom,
constr_CONST_2 != name_Kas).
fof(ax39, axiom,
constr_CONST_2 != name_Kbc_40x30).
fof(ax40, axiom,
constr_CONST_2 != name_Kbs).
fof(ax41, axiom,
constr_CONST_2 != name_Kcs).
fof(ax42, axiom,
constr_CONST_2 != name_Na).
fof(ax43, axiom,
constr_CONST_2 != name_S).
fof(ax44, axiom,
constr_CONST_2 != name_c).
fof(ax45, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax46, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax47, axiom,
constr_CONST_3 != name_A).
fof(ax48, axiom,
constr_CONST_3 != name_B).
fof(ax49, axiom,
constr_CONST_3 != name_C).
fof(ax50, axiom,
constr_CONST_3 != name_Kab_39).
fof(ax51, axiom,
constr_CONST_3 != name_Kas).
fof(ax52, axiom,
constr_CONST_3 != name_Kbc_40x30).
fof(ax53, axiom,
constr_CONST_3 != name_Kbs).
fof(ax54, axiom,
constr_CONST_3 != name_Kcs).
fof(ax55, axiom,
constr_CONST_3 != name_Na).
fof(ax56, axiom,
constr_CONST_3 != name_S).
fof(ax57, axiom,
constr_CONST_3 != name_c).
fof(ax58, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax59, axiom,
constr_CONST_4 != name_A).
fof(ax60, axiom,
constr_CONST_4 != name_B).
fof(ax61, axiom,
constr_CONST_4 != name_C).
fof(ax62, axiom,
constr_CONST_4 != name_Kab_39).
fof(ax63, axiom,
constr_CONST_4 != name_Kas).
fof(ax64, axiom,
constr_CONST_4 != name_Kbc_40x30).
fof(ax65, axiom,
constr_CONST_4 != name_Kbs).
fof(ax66, axiom,
constr_CONST_4 != name_Kcs).
fof(ax67, axiom,
constr_CONST_4 != name_Na).
fof(ax68, axiom,
constr_CONST_4 != name_S).
fof(ax69, axiom,
constr_CONST_4 != name_c).
fof(ax70, axiom,
constr_ZERO != name_A).
fof(ax71, axiom,
constr_ZERO != name_B).
fof(ax72, axiom,
constr_ZERO != name_C).
fof(ax73, axiom,
constr_ZERO != name_Kab_39).
fof(ax74, axiom,
constr_ZERO != name_Kas).
fof(ax75, axiom,
constr_ZERO != name_Kbc_40x30).
fof(ax76, axiom,
constr_ZERO != name_Kbs).
fof(ax77, axiom,
constr_ZERO != name_Kcs).
fof(ax78, axiom,
constr_ZERO != name_Na).
fof(ax79, axiom,
constr_ZERO != name_S).
fof(ax80, axiom,
constr_ZERO != name_c).
fof(ax81, axiom,
name_A != name_B).
fof(ax82, axiom,
name_A != name_C).
fof(ax83, axiom,
name_A != name_Kab_39).
fof(ax84, axiom,
name_A != name_Kas).
fof(ax85, axiom,
name_A != name_Kbc_40x30).
fof(ax86, axiom,
name_A != name_Kbs).
fof(ax87, axiom,
name_A != name_Kcs).
fof(ax88, axiom,
name_A != name_Na).
fof(ax89, axiom,
name_A != name_S).
fof(ax90, axiom,
name_A != name_c).
fof(ax91, axiom,
name_B != name_C).
fof(ax92, axiom,
name_B != name_Kab_39).
fof(ax93, axiom,
name_B != name_Kas).
fof(ax94, axiom,
name_B != name_Kbc_40x30).
fof(ax95, axiom,
name_B != name_Kbs).
fof(ax96, axiom,
name_B != name_Kcs).
fof(ax97, axiom,
name_B != name_Na).
fof(ax98, axiom,
name_B != name_S).
fof(ax99, axiom,
name_B != name_c).
fof(ax100, axiom,
name_C != name_Kab_39).
fof(ax101, axiom,
name_C != name_Kas).
fof(ax102, axiom,
name_C != name_Kbc_40x30).
fof(ax103, axiom,
name_C != name_Kbs).
fof(ax104, axiom,
name_C != name_Kcs).
fof(ax105, axiom,
name_C != name_Na).
fof(ax106, axiom,
name_C != name_S).
fof(ax107, axiom,
name_C != name_c).
fof(ax108, axiom,
name_Kab_39 != name_Kas).
fof(ax109, axiom,
name_Kab_39 != name_Kbc_40x30).
fof(ax110, axiom,
name_Kab_39 != name_Kbs).
fof(ax111, axiom,
name_Kab_39 != name_Kcs).
fof(ax112, axiom,
name_Kab_39 != name_Na).
fof(ax113, axiom,
name_Kab_39 != name_S).
fof(ax114, axiom,
name_Kab_39 != name_c).
fof(ax115, axiom,
name_Kas != name_Kbc_40x30).
fof(ax116, axiom,
name_Kas != name_Kbs).
fof(ax117, axiom,
name_Kas != name_Kcs).
fof(ax118, axiom,
name_Kas != name_Na).
fof(ax119, axiom,
name_Kas != name_S).
fof(ax120, axiom,
name_Kas != name_c).
fof(ax121, axiom,
name_Kbc_40x30 != name_Kbs).
fof(ax122, axiom,
name_Kbc_40x30 != name_Kcs).
fof(ax123, axiom,
name_Kbc_40x30 != name_Na).
fof(ax124, axiom,
name_Kbc_40x30 != name_S).
fof(ax125, axiom,
name_Kbc_40x30 != name_c).
fof(ax126, axiom,
name_Kbs != name_Kcs).
fof(ax127, axiom,
name_Kbs != name_Na).
fof(ax128, axiom,
name_Kbs != name_S).
fof(ax129, axiom,
name_Kbs != name_c).
fof(ax130, axiom,
name_Kcs != name_Na).
fof(ax131, axiom,
name_Kcs != name_S).
fof(ax132, axiom,
name_Kcs != name_c).
fof(ax133, axiom,
name_Na != name_S).
fof(ax134, axiom,
name_Na != name_c).
fof(ax135, axiom,
name_S != name_c).
fof(ax136, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_dec(constr_enc(VAR_M_0X30, VAR_K_0X30), VAR_K_0X30) = VAR_M_0X30)).
fof(ax137, axiom,
![VAR_X1_14, VAR_X2_15, VAR_X3_16, VAR_X4_17, VAR_X5_0X30] : (constr_decon5(constr_con5(VAR_X1_14, VAR_X2_15, VAR_X3_16, VAR_X4_17, VAR_X5_0X30)) = tuple_5(VAR_X1_14, VAR_X2_15, VAR_X3_16, VAR_X4_17, VAR_X5_0X30))).
fof(ax138, axiom,
![VAR_X1_11, VAR_X2_12, VAR_X3_13, VAR_X4_0X30] : (constr_decon4(constr_con4(VAR_X1_11, VAR_X2_12, VAR_X3_13, VAR_X4_0X30)) = tuple_4(VAR_X1_11, VAR_X2_12, VAR_X3_13, VAR_X4_0X30))).
fof(ax139, axiom,
![VAR_X1_0X30, VAR_X2_0X30, VAR_X3_0X30] : (constr_decon3(constr_con3(VAR_X1_0X30, VAR_X2_0X30, VAR_X3_0X30)) = tuple_3(VAR_X1_0X30, VAR_X2_0X30, VAR_X3_0X30))).
fof(ax140, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, VAR_X_10X30) = constr_ZERO)).
fof(ax141, axiom,
![VAR_X_9] : (constr_xor(VAR_X_9, constr_ZERO) = VAR_X_9)).
fof(ax142, axiom,
![VAR_X_7, VAR_Y_8] : (constr_xor(VAR_X_7, VAR_Y_8) = constr_xor(VAR_Y_8, VAR_X_7))).
fof(ax143, axiom,
![VAR_X_0X30, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_0X30, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_0X30, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax144, axiom,
![VAR_V_66, VAR_V_67] : ((pred_attacker(VAR_V_66) & pred_attacker(VAR_V_67)) => pred_attacker(constr_xor(VAR_V_66, VAR_V_67)))).
fof(ax145, axiom,
pred_attacker(tuple_true)).
fof(ax146, axiom,
![VAR_V_84, VAR_V_85, VAR_V_86, VAR_V_87, VAR_V_88, VAR_V_89, VAR_V_90X30, VAR_V_91, VAR_V_92, VAR_V_93, VAR_V_94, VAR_V_95, VAR_V_96, VAR_V_97, VAR_V_98, VAR_V_99] : ((pred_attacker(VAR_V_84) & pred_attacker(VAR_V_85) & pred_attacker(VAR_V_86) & pred_attacker(VAR_V_87) & pred_attacker(VAR_V_88) & pred_attacker(VAR_V_89) & pred_attacker(VAR_V_90X30) & pred_attacker(VAR_V_91) & pred_attacker(VAR_V_92) & pred_attacker(VAR_V_93) & pred_attacker(VAR_V_94) & pred_attacker(VAR_V_95) & pred_attacker(VAR_V_96) & pred_attacker(VAR_V_97) & pred_attacker(VAR_V_98) & pred_attacker(VAR_V_99)) => pred_attacker(tuple_server_S_out_1(VAR_V_84, VAR_V_85, VAR_V_86, VAR_V_87, VAR_V_88, VAR_V_89, VAR_V_90X30, VAR_V_91, VAR_V_92, VAR_V_93, VAR_V_94, VAR_V_95, VAR_V_96, VAR_V_97, VAR_V_98, VAR_V_99)))).
fof(ax147, axiom,
![VAR_V_372, VAR_V_373, VAR_V_374, VAR_V_375, VAR_V_376, VAR_V_377, VAR_V_378, VAR_V_379, VAR_V_380X30, VAR_V_381, VAR_V_382, VAR_V_383, VAR_V_384, VAR_V_385, VAR_V_386, VAR_V_387] : (pred_attacker(tuple_server_S_out_1(VAR_V_372, VAR_V_373, VAR_V_374, VAR_V_375, VAR_V_376, VAR_V_377, VAR_V_378, VAR_V_379, VAR_V_380X30, VAR_V_381, VAR_V_382, VAR_V_383, VAR_V_384, VAR_V_385, VAR_V_386, VAR_V_387)) => pred_attacker(VAR_V_372))).
fof(ax148, axiom,
![VAR_V_389, VAR_V_390X30, VAR_V_391, VAR_V_392, VAR_V_393, VAR_V_394, VAR_V_395, VAR_V_396, VAR_V_397, VAR_V_398, VAR_V_399, VAR_V_40X300X30, VAR_V_40X301, VAR_V_40X302, VAR_V_40X303, VAR_V_40X304] : (pred_attacker(tuple_server_S_out_1(VAR_V_389, VAR_V_390X30, VAR_V_391, VAR_V_392, VAR_V_393, VAR_V_394, VAR_V_395, VAR_V_396, VAR_V_397, VAR_V_398, VAR_V_399, VAR_V_40X300X30, VAR_V_40X301, VAR_V_40X302, VAR_V_40X303, VAR_V_40X304)) => pred_attacker(VAR_V_390X30))).
fof(ax149, axiom,
![VAR_V_40X306, VAR_V_40X307, VAR_V_40X308, VAR_V_40X309, VAR_V_410X30, VAR_V_411, VAR_V_412, VAR_V_413, VAR_V_414, VAR_V_415, VAR_V_416, VAR_V_417, VAR_V_418, VAR_V_419, VAR_V_420X30, VAR_V_421] : (pred_attacker(tuple_server_S_out_1(VAR_V_40X306, VAR_V_40X307, VAR_V_40X308, VAR_V_40X309, VAR_V_410X30, VAR_V_411, VAR_V_412, VAR_V_413, VAR_V_414, VAR_V_415, VAR_V_416, VAR_V_417, VAR_V_418, VAR_V_419, VAR_V_420X30, VAR_V_421)) => pred_attacker(VAR_V_40X308))).
fof(ax150, axiom,
![VAR_V_423, VAR_V_424, VAR_V_425, VAR_V_426, VAR_V_427, VAR_V_428, VAR_V_429, VAR_V_430X30, VAR_V_431, VAR_V_432, VAR_V_433, VAR_V_434, VAR_V_435, VAR_V_436, VAR_V_437, VAR_V_438] : (pred_attacker(tuple_server_S_out_1(VAR_V_423, VAR_V_424, VAR_V_425, VAR_V_426, VAR_V_427, VAR_V_428, VAR_V_429, VAR_V_430X30, VAR_V_431, VAR_V_432, VAR_V_433, VAR_V_434, VAR_V_435, VAR_V_436, VAR_V_437, VAR_V_438)) => pred_attacker(VAR_V_426))).
fof(ax151, axiom,
![VAR_V_440X30, VAR_V_441, VAR_V_442, VAR_V_443, VAR_V_444, VAR_V_445, VAR_V_446, VAR_V_447, VAR_V_448, VAR_V_449, VAR_V_450X30, VAR_V_451, VAR_V_452, VAR_V_453, VAR_V_454, VAR_V_455] : (pred_attacker(tuple_server_S_out_1(VAR_V_440X30, VAR_V_441, VAR_V_442, VAR_V_443, VAR_V_444, VAR_V_445, VAR_V_446, VAR_V_447, VAR_V_448, VAR_V_449, VAR_V_450X30, VAR_V_451, VAR_V_452, VAR_V_453, VAR_V_454, VAR_V_455)) => pred_attacker(VAR_V_444))).
fof(ax152, axiom,
![VAR_V_457, VAR_V_458, VAR_V_459, VAR_V_460X30, VAR_V_461, VAR_V_462, VAR_V_463, VAR_V_464, VAR_V_465, VAR_V_466, VAR_V_467, VAR_V_468, VAR_V_469, VAR_V_470X30, VAR_V_471, VAR_V_472] : (pred_attacker(tuple_server_S_out_1(VAR_V_457, VAR_V_458, VAR_V_459, VAR_V_460X30, VAR_V_461, VAR_V_462, VAR_V_463, VAR_V_464, VAR_V_465, VAR_V_466, VAR_V_467, VAR_V_468, VAR_V_469, VAR_V_470X30, VAR_V_471, VAR_V_472)) => pred_attacker(VAR_V_462))).
fof(ax153, axiom,
![VAR_V_474, VAR_V_475, VAR_V_476, VAR_V_477, VAR_V_478, VAR_V_479, VAR_V_480X30, VAR_V_481, VAR_V_482, VAR_V_483, VAR_V_484, VAR_V_485, VAR_V_486, VAR_V_487, VAR_V_488, VAR_V_489] : (pred_attacker(tuple_server_S_out_1(VAR_V_474, VAR_V_475, VAR_V_476, VAR_V_477, VAR_V_478, VAR_V_479, VAR_V_480X30, VAR_V_481, VAR_V_482, VAR_V_483, VAR_V_484, VAR_V_485, VAR_V_486, VAR_V_487, VAR_V_488, VAR_V_489)) => pred_attacker(VAR_V_480X30))).
fof(ax154, axiom,
![VAR_V_491, VAR_V_492, VAR_V_493, VAR_V_494, VAR_V_495, VAR_V_496, VAR_V_497, VAR_V_498, VAR_V_499, VAR_V_50X300X30, VAR_V_50X301, VAR_V_50X302, VAR_V_50X303, VAR_V_50X304, VAR_V_50X305, VAR_V_50X306] : (pred_attacker(tuple_server_S_out_1(VAR_V_491, VAR_V_492, VAR_V_493, VAR_V_494, VAR_V_495, VAR_V_496, VAR_V_497, VAR_V_498, VAR_V_499, VAR_V_50X300X30, VAR_V_50X301, VAR_V_50X302, VAR_V_50X303, VAR_V_50X304, VAR_V_50X305, VAR_V_50X306)) => pred_attacker(VAR_V_498))).
fof(ax155, axiom,
![VAR_V_50X308, VAR_V_50X309, VAR_V_510X30, VAR_V_511, VAR_V_512, VAR_V_513, VAR_V_514, VAR_V_515, VAR_V_516, VAR_V_517, VAR_V_518, VAR_V_519, VAR_V_520X30, VAR_V_521, VAR_V_522, VAR_V_523] : (pred_attacker(tuple_server_S_out_1(VAR_V_50X308, VAR_V_50X309, VAR_V_510X30, VAR_V_511, VAR_V_512, VAR_V_513, VAR_V_514, VAR_V_515, VAR_V_516, VAR_V_517, VAR_V_518, VAR_V_519, VAR_V_520X30, VAR_V_521, VAR_V_522, VAR_V_523)) => pred_attacker(VAR_V_516))).
fof(ax156, axiom,
![VAR_V_525, VAR_V_526, VAR_V_527, VAR_V_528, VAR_V_529, VAR_V_530X30, VAR_V_531, VAR_V_532, VAR_V_533, VAR_V_534, VAR_V_535, VAR_V_536, VAR_V_537, VAR_V_538, VAR_V_539, VAR_V_540X30] : (pred_attacker(tuple_server_S_out_1(VAR_V_525, VAR_V_526, VAR_V_527, VAR_V_528, VAR_V_529, VAR_V_530X30, VAR_V_531, VAR_V_532, VAR_V_533, VAR_V_534, VAR_V_535, VAR_V_536, VAR_V_537, VAR_V_538, VAR_V_539, VAR_V_540X30)) => pred_attacker(VAR_V_534))).
fof(ax157, axiom,
![VAR_V_542, VAR_V_543, VAR_V_544, VAR_V_545, VAR_V_546, VAR_V_547, VAR_V_548, VAR_V_549, VAR_V_550X30, VAR_V_551, VAR_V_552, VAR_V_553, VAR_V_554, VAR_V_555, VAR_V_556, VAR_V_557] : (pred_attacker(tuple_server_S_out_1(VAR_V_542, VAR_V_543, VAR_V_544, VAR_V_545, VAR_V_546, VAR_V_547, VAR_V_548, VAR_V_549, VAR_V_550X30, VAR_V_551, VAR_V_552, VAR_V_553, VAR_V_554, VAR_V_555, VAR_V_556, VAR_V_557)) => pred_attacker(VAR_V_552))).
fof(ax158, axiom,
![VAR_V_559, VAR_V_560X30, VAR_V_561, VAR_V_562, VAR_V_563, VAR_V_564, VAR_V_565, VAR_V_566, VAR_V_567, VAR_V_568, VAR_V_569, VAR_V_570X30, VAR_V_571, VAR_V_572, VAR_V_573, VAR_V_574] : (pred_attacker(tuple_server_S_out_1(VAR_V_559, VAR_V_560X30, VAR_V_561, VAR_V_562, VAR_V_563, VAR_V_564, VAR_V_565, VAR_V_566, VAR_V_567, VAR_V_568, VAR_V_569, VAR_V_570X30, VAR_V_571, VAR_V_572, VAR_V_573, VAR_V_574)) => pred_attacker(VAR_V_570X30))).
fof(ax159, axiom,
![VAR_V_576, VAR_V_577, VAR_V_578, VAR_V_579, VAR_V_580X30, VAR_V_581, VAR_V_582, VAR_V_583, VAR_V_584, VAR_V_585, VAR_V_586, VAR_V_587, VAR_V_588, VAR_V_589, VAR_V_590X30, VAR_V_591] : (pred_attacker(tuple_server_S_out_1(VAR_V_576, VAR_V_577, VAR_V_578, VAR_V_579, VAR_V_580X30, VAR_V_581, VAR_V_582, VAR_V_583, VAR_V_584, VAR_V_585, VAR_V_586, VAR_V_587, VAR_V_588, VAR_V_589, VAR_V_590X30, VAR_V_591)) => pred_attacker(VAR_V_588))).
fof(ax160, axiom,
![VAR_V_593, VAR_V_594, VAR_V_595, VAR_V_596, VAR_V_597, VAR_V_598, VAR_V_599, VAR_V_60X300X30, VAR_V_60X301, VAR_V_60X302, VAR_V_60X303, VAR_V_60X304, VAR_V_60X305, VAR_V_60X306, VAR_V_60X307, VAR_V_60X308] : (pred_attacker(tuple_server_S_out_1(VAR_V_593, VAR_V_594, VAR_V_595, VAR_V_596, VAR_V_597, VAR_V_598, VAR_V_599, VAR_V_60X300X30, VAR_V_60X301, VAR_V_60X302, VAR_V_60X303, VAR_V_60X304, VAR_V_60X305, VAR_V_60X306, VAR_V_60X307, VAR_V_60X308)) => pred_attacker(VAR_V_60X306))).
fof(ax161, axiom,
![VAR_V_610X30, VAR_V_611, VAR_V_612, VAR_V_613, VAR_V_614, VAR_V_615, VAR_V_616, VAR_V_617, VAR_V_618, VAR_V_619, VAR_V_620X30, VAR_V_621, VAR_V_622, VAR_V_623, VAR_V_624, VAR_V_625] : (pred_attacker(tuple_server_S_out_1(VAR_V_610X30, VAR_V_611, VAR_V_612, VAR_V_613, VAR_V_614, VAR_V_615, VAR_V_616, VAR_V_617, VAR_V_618, VAR_V_619, VAR_V_620X30, VAR_V_621, VAR_V_622, VAR_V_623, VAR_V_624, VAR_V_625)) => pred_attacker(VAR_V_624))).
fof(ax162, axiom,
![VAR_V_627, VAR_V_628, VAR_V_629, VAR_V_630X30, VAR_V_631, VAR_V_632, VAR_V_633, VAR_V_634, VAR_V_635, VAR_V_636, VAR_V_637, VAR_V_638, VAR_V_639, VAR_V_640X30, VAR_V_641, VAR_V_642] : (pred_attacker(tuple_server_S_out_1(VAR_V_627, VAR_V_628, VAR_V_629, VAR_V_630X30, VAR_V_631, VAR_V_632, VAR_V_633, VAR_V_634, VAR_V_635, VAR_V_636, VAR_V_637, VAR_V_638, VAR_V_639, VAR_V_640X30, VAR_V_641, VAR_V_642)) => pred_attacker(VAR_V_642))).
fof(ax163, axiom,
![VAR_V_646, VAR_V_647] : ((pred_attacker(VAR_V_646) & pred_attacker(VAR_V_647)) => pred_attacker(tuple_server_S_in_1(VAR_V_646, VAR_V_647)))).
fof(ax164, axiom,
![VAR_V_654, VAR_V_655] : (pred_attacker(tuple_server_S_in_1(VAR_V_654, VAR_V_655)) => pred_attacker(VAR_V_654))).
fof(ax165, axiom,
![VAR_V_657, VAR_V_658] : (pred_attacker(tuple_server_S_in_1(VAR_V_657, VAR_V_658)) => pred_attacker(VAR_V_658))).
fof(ax166, axiom,
![VAR_V_663, VAR_V_664] : ((pred_attacker(VAR_V_663) & pred_attacker(VAR_V_664)) => pred_attacker(constr_h(VAR_V_663, VAR_V_664)))).
fof(ax167, axiom,
pred_attacker(tuple_false)).
fof(ax168, axiom,
![VAR_V_667, VAR_V_668] : ((pred_attacker(VAR_V_667) & pred_attacker(VAR_V_668)) => pred_attacker(constr_enc(VAR_V_667, VAR_V_668)))).
fof(ax169, axiom,
![VAR_V_670X30] : (pred_attacker(VAR_V_670X30) => pred_attacker(constr_decon5(VAR_V_670X30)))).
fof(ax170, axiom,
![VAR_V_672] : (pred_attacker(VAR_V_672) => pred_attacker(constr_decon4(VAR_V_672)))).
fof(ax171, axiom,
![VAR_V_674] : (pred_attacker(VAR_V_674) => pred_attacker(constr_decon3(VAR_V_674)))).
fof(ax172, axiom,
![VAR_V_677, VAR_V_678] : ((pred_attacker(VAR_V_677) & pred_attacker(VAR_V_678)) => pred_attacker(constr_dec(VAR_V_677, VAR_V_678)))).
fof(ax173, axiom,
![VAR_V_684, VAR_V_685, VAR_V_686, VAR_V_687, VAR_V_688] : ((pred_attacker(VAR_V_684) & pred_attacker(VAR_V_685) & pred_attacker(VAR_V_686) & pred_attacker(VAR_V_687) & pred_attacker(VAR_V_688)) => pred_attacker(constr_con5(VAR_V_684, VAR_V_685, VAR_V_686, VAR_V_687, VAR_V_688)))).
fof(ax174, axiom,
![VAR_V_693, VAR_V_694, VAR_V_695, VAR_V_696] : ((pred_attacker(VAR_V_693) & pred_attacker(VAR_V_694) & pred_attacker(VAR_V_695) & pred_attacker(VAR_V_696)) => pred_attacker(constr_con4(VAR_V_693, VAR_V_694, VAR_V_695, VAR_V_696)))).
fof(ax175, axiom,
![VAR_V_70X300X30, VAR_V_70X301, VAR_V_70X302] : ((pred_attacker(VAR_V_70X300X30) & pred_attacker(VAR_V_70X301) & pred_attacker(VAR_V_70X302)) => pred_attacker(constr_con3(VAR_V_70X300X30, VAR_V_70X301, VAR_V_70X302)))).
fof(ax176, axiom,
![VAR_V_715, VAR_V_716, VAR_V_717, VAR_V_718, VAR_V_719, VAR_V_720X30, VAR_V_721, VAR_V_722, VAR_V_723, VAR_V_724, VAR_V_725, VAR_V_726] : ((pred_attacker(VAR_V_715) & pred_attacker(VAR_V_716) & pred_attacker(VAR_V_717) & pred_attacker(VAR_V_718) & pred_attacker(VAR_V_719) & pred_attacker(VAR_V_720X30) & pred_attacker(VAR_V_721) & pred_attacker(VAR_V_722) & pred_attacker(VAR_V_723) & pred_attacker(VAR_V_724) & pred_attacker(VAR_V_725) & pred_attacker(VAR_V_726)) => pred_attacker(tuple_client_C_out_4(VAR_V_715, VAR_V_716, VAR_V_717, VAR_V_718, VAR_V_719, VAR_V_720X30, VAR_V_721, VAR_V_722, VAR_V_723, VAR_V_724, VAR_V_725, VAR_V_726)))).
fof(ax177, axiom,
![VAR_V_883, VAR_V_884, VAR_V_885, VAR_V_886, VAR_V_887, VAR_V_888, VAR_V_889, VAR_V_890X30, VAR_V_891, VAR_V_892, VAR_V_893, VAR_V_894] : (pred_attacker(tuple_client_C_out_4(VAR_V_883, VAR_V_884, VAR_V_885, VAR_V_886, VAR_V_887, VAR_V_888, VAR_V_889, VAR_V_890X30, VAR_V_891, VAR_V_892, VAR_V_893, VAR_V_894)) => pred_attacker(VAR_V_883))).
fof(ax178, axiom,
![VAR_V_896, VAR_V_897, VAR_V_898, VAR_V_899, VAR_V_90X300X30, VAR_V_90X301, VAR_V_90X302, VAR_V_90X303, VAR_V_90X304, VAR_V_90X305, VAR_V_90X306, VAR_V_90X307] : (pred_attacker(tuple_client_C_out_4(VAR_V_896, VAR_V_897, VAR_V_898, VAR_V_899, VAR_V_90X300X30, VAR_V_90X301, VAR_V_90X302, VAR_V_90X303, VAR_V_90X304, VAR_V_90X305, VAR_V_90X306, VAR_V_90X307)) => pred_attacker(VAR_V_897))).
fof(ax179, axiom,
![VAR_V_90X309, VAR_V_910X30, VAR_V_911, VAR_V_912, VAR_V_913, VAR_V_914, VAR_V_915, VAR_V_916, VAR_V_917, VAR_V_918, VAR_V_919, VAR_V_920X30] : (pred_attacker(tuple_client_C_out_4(VAR_V_90X309, VAR_V_910X30, VAR_V_911, VAR_V_912, VAR_V_913, VAR_V_914, VAR_V_915, VAR_V_916, VAR_V_917, VAR_V_918, VAR_V_919, VAR_V_920X30)) => pred_attacker(VAR_V_911))).
fof(ax180, axiom,
![VAR_V_922, VAR_V_923, VAR_V_924, VAR_V_925, VAR_V_926, VAR_V_927, VAR_V_928, VAR_V_929, VAR_V_930X30, VAR_V_931, VAR_V_932, VAR_V_933] : (pred_attacker(tuple_client_C_out_4(VAR_V_922, VAR_V_923, VAR_V_924, VAR_V_925, VAR_V_926, VAR_V_927, VAR_V_928, VAR_V_929, VAR_V_930X30, VAR_V_931, VAR_V_932, VAR_V_933)) => pred_attacker(VAR_V_925))).
fof(ax181, axiom,
![VAR_V_935, VAR_V_936, VAR_V_937, VAR_V_938, VAR_V_939, VAR_V_940X30, VAR_V_941, VAR_V_942, VAR_V_943, VAR_V_944, VAR_V_945, VAR_V_946] : (pred_attacker(tuple_client_C_out_4(VAR_V_935, VAR_V_936, VAR_V_937, VAR_V_938, VAR_V_939, VAR_V_940X30, VAR_V_941, VAR_V_942, VAR_V_943, VAR_V_944, VAR_V_945, VAR_V_946)) => pred_attacker(VAR_V_939))).
fof(ax182, axiom,
![VAR_V_948, VAR_V_949, VAR_V_950X30, VAR_V_951, VAR_V_952, VAR_V_953, VAR_V_954, VAR_V_955, VAR_V_956, VAR_V_957, VAR_V_958, VAR_V_959] : (pred_attacker(tuple_client_C_out_4(VAR_V_948, VAR_V_949, VAR_V_950X30, VAR_V_951, VAR_V_952, VAR_V_953, VAR_V_954, VAR_V_955, VAR_V_956, VAR_V_957, VAR_V_958, VAR_V_959)) => pred_attacker(VAR_V_953))).
fof(ax183, axiom,
![VAR_V_961, VAR_V_962, VAR_V_963, VAR_V_964, VAR_V_965, VAR_V_966, VAR_V_967, VAR_V_968, VAR_V_969, VAR_V_970X30, VAR_V_971, VAR_V_972] : (pred_attacker(tuple_client_C_out_4(VAR_V_961, VAR_V_962, VAR_V_963, VAR_V_964, VAR_V_965, VAR_V_966, VAR_V_967, VAR_V_968, VAR_V_969, VAR_V_970X30, VAR_V_971, VAR_V_972)) => pred_attacker(VAR_V_967))).
fof(ax184, axiom,
![VAR_V_974, VAR_V_975, VAR_V_976, VAR_V_977, VAR_V_978, VAR_V_979, VAR_V_980X30, VAR_V_981, VAR_V_982, VAR_V_983, VAR_V_984, VAR_V_985] : (pred_attacker(tuple_client_C_out_4(VAR_V_974, VAR_V_975, VAR_V_976, VAR_V_977, VAR_V_978, VAR_V_979, VAR_V_980X30, VAR_V_981, VAR_V_982, VAR_V_983, VAR_V_984, VAR_V_985)) => pred_attacker(VAR_V_981))).
fof(ax185, axiom,
![VAR_V_987, VAR_V_988, VAR_V_989, VAR_V_990X30, VAR_V_991, VAR_V_992, VAR_V_993, VAR_V_994, VAR_V_995, VAR_V_996, VAR_V_997, VAR_V_998] : (pred_attacker(tuple_client_C_out_4(VAR_V_987, VAR_V_988, VAR_V_989, VAR_V_990X30, VAR_V_991, VAR_V_992, VAR_V_993, VAR_V_994, VAR_V_995, VAR_V_996, VAR_V_997, VAR_V_998)) => pred_attacker(VAR_V_995))).
fof(ax186, axiom,
![VAR_V_10X300X300X30, VAR_V_10X300X301, VAR_V_10X300X302, VAR_V_10X300X303, VAR_V_10X300X304, VAR_V_10X300X305, VAR_V_10X300X306, VAR_V_10X300X307, VAR_V_10X300X308, VAR_V_10X300X309, VAR_V_10X3010X30, VAR_V_10X3011] : (pred_attacker(tuple_client_C_out_4(VAR_V_10X300X300X30, VAR_V_10X300X301, VAR_V_10X300X302, VAR_V_10X300X303, VAR_V_10X300X304, VAR_V_10X300X305, VAR_V_10X300X306, VAR_V_10X300X307, VAR_V_10X300X308, VAR_V_10X300X309, VAR_V_10X3010X30, VAR_V_10X3011)) => pred_attacker(VAR_V_10X300X309))).
fof(ax187, axiom,
![VAR_V_10X3013, VAR_V_10X3014, VAR_V_10X3015, VAR_V_10X3016, VAR_V_10X3017, VAR_V_10X3018, VAR_V_10X3019, VAR_V_10X3020X30, VAR_V_10X3021, VAR_V_10X3022, VAR_V_10X3023, VAR_V_10X3024] : (pred_attacker(tuple_client_C_out_4(VAR_V_10X3013, VAR_V_10X3014, VAR_V_10X3015, VAR_V_10X3016, VAR_V_10X3017, VAR_V_10X3018, VAR_V_10X3019, VAR_V_10X3020X30, VAR_V_10X3021, VAR_V_10X3022, VAR_V_10X3023, VAR_V_10X3024)) => pred_attacker(VAR_V_10X3023))).
fof(ax188, axiom,
![VAR_V_10X3026, VAR_V_10X3027, VAR_V_10X3028, VAR_V_10X3029, VAR_V_10X3030X30, VAR_V_10X3031, VAR_V_10X3032, VAR_V_10X3033, VAR_V_10X3034, VAR_V_10X3035, VAR_V_10X3036, VAR_V_10X3037] : (pred_attacker(tuple_client_C_out_4(VAR_V_10X3026, VAR_V_10X3027, VAR_V_10X3028, VAR_V_10X3029, VAR_V_10X3030X30, VAR_V_10X3031, VAR_V_10X3032, VAR_V_10X3033, VAR_V_10X3034, VAR_V_10X3035, VAR_V_10X3036, VAR_V_10X3037)) => pred_attacker(VAR_V_10X3037))).
fof(ax189, axiom,
![VAR_V_10X3040X30] : (pred_attacker(VAR_V_10X3040X30) => pred_attacker(tuple_client_C_out_3(VAR_V_10X3040X30)))).
fof(ax190, axiom,
![VAR_V_10X3043] : (pred_attacker(tuple_client_C_out_3(VAR_V_10X3043)) => pred_attacker(VAR_V_10X3043))).
fof(ax191, axiom,
![VAR_V_10X3046] : (pred_attacker(VAR_V_10X3046) => pred_attacker(tuple_client_C_out_2(VAR_V_10X3046)))).
fof(ax192, axiom,
![VAR_V_10X3049] : (pred_attacker(tuple_client_C_out_2(VAR_V_10X3049)) => pred_attacker(VAR_V_10X3049))).
fof(ax193, axiom,
![VAR_V_10X3052] : (pred_attacker(VAR_V_10X3052) => pred_attacker(tuple_client_C_out_1(VAR_V_10X3052)))).
fof(ax194, axiom,
![VAR_V_10X3055] : (pred_attacker(tuple_client_C_out_1(VAR_V_10X3055)) => pred_attacker(VAR_V_10X3055))).
fof(ax195, axiom,
![VAR_V_10X3073, VAR_V_10X3074, VAR_V_10X3075, VAR_V_10X3076, VAR_V_10X3077, VAR_V_10X3078, VAR_V_10X3079, VAR_V_10X3080X30, VAR_V_10X3081, VAR_V_10X3082, VAR_V_10X3083, VAR_V_10X3084, VAR_V_10X3085, VAR_V_10X3086, VAR_V_10X3087, VAR_V_10X3088] : ((pred_attacker(VAR_V_10X3073) & pred_attacker(VAR_V_10X3074) & pred_attacker(VAR_V_10X3075) & pred_attacker(VAR_V_10X3076) & pred_attacker(VAR_V_10X3077) & pred_attacker(VAR_V_10X3078) & pred_attacker(VAR_V_10X3079) & pred_attacker(VAR_V_10X3080X30) & pred_attacker(VAR_V_10X3081) & pred_attacker(VAR_V_10X3082) & pred_attacker(VAR_V_10X3083) & pred_attacker(VAR_V_10X3084) & pred_attacker(VAR_V_10X3085) & pred_attacker(VAR_V_10X3086) & pred_attacker(VAR_V_10X3087) & pred_attacker(VAR_V_10X3088)) => pred_attacker(tuple_client_C_in_2(VAR_V_10X3073, VAR_V_10X3074, VAR_V_10X3075, VAR_V_10X3076, VAR_V_10X3077, VAR_V_10X3078, VAR_V_10X3079, VAR_V_10X3080X30, VAR_V_10X3081, VAR_V_10X3082, VAR_V_10X3083, VAR_V_10X3084, VAR_V_10X3085, VAR_V_10X3086, VAR_V_10X3087, VAR_V_10X3088)))).
fof(ax196, axiom,
![VAR_V_1361, VAR_V_1362, VAR_V_1363, VAR_V_1364, VAR_V_1365, VAR_V_1366, VAR_V_1367, VAR_V_1368, VAR_V_1369, VAR_V_1370X30, VAR_V_1371, VAR_V_1372, VAR_V_1373, VAR_V_1374, VAR_V_1375, VAR_V_1376] : (pred_attacker(tuple_client_C_in_2(VAR_V_1361, VAR_V_1362, VAR_V_1363, VAR_V_1364, VAR_V_1365, VAR_V_1366, VAR_V_1367, VAR_V_1368, VAR_V_1369, VAR_V_1370X30, VAR_V_1371, VAR_V_1372, VAR_V_1373, VAR_V_1374, VAR_V_1375, VAR_V_1376)) => pred_attacker(VAR_V_1361))).
fof(ax197, axiom,
![VAR_V_1378, VAR_V_1379, VAR_V_1380X30, VAR_V_1381, VAR_V_1382, VAR_V_1383, VAR_V_1384, VAR_V_1385, VAR_V_1386, VAR_V_1387, VAR_V_1388, VAR_V_1389, VAR_V_1390X30, VAR_V_1391, VAR_V_1392, VAR_V_1393] : (pred_attacker(tuple_client_C_in_2(VAR_V_1378, VAR_V_1379, VAR_V_1380X30, VAR_V_1381, VAR_V_1382, VAR_V_1383, VAR_V_1384, VAR_V_1385, VAR_V_1386, VAR_V_1387, VAR_V_1388, VAR_V_1389, VAR_V_1390X30, VAR_V_1391, VAR_V_1392, VAR_V_1393)) => pred_attacker(VAR_V_1379))).
fof(ax198, axiom,
![VAR_V_1395, VAR_V_1396, VAR_V_1397, VAR_V_1398, VAR_V_1399, VAR_V_140X300X30, VAR_V_140X301, VAR_V_140X302, VAR_V_140X303, VAR_V_140X304, VAR_V_140X305, VAR_V_140X306, VAR_V_140X307, VAR_V_140X308, VAR_V_140X309, VAR_V_1410X30] : (pred_attacker(tuple_client_C_in_2(VAR_V_1395, VAR_V_1396, VAR_V_1397, VAR_V_1398, VAR_V_1399, VAR_V_140X300X30, VAR_V_140X301, VAR_V_140X302, VAR_V_140X303, VAR_V_140X304, VAR_V_140X305, VAR_V_140X306, VAR_V_140X307, VAR_V_140X308, VAR_V_140X309, VAR_V_1410X30)) => pred_attacker(VAR_V_1397))).
fof(ax199, axiom,
![VAR_V_1412, VAR_V_1413, VAR_V_1414, VAR_V_1415, VAR_V_1416, VAR_V_1417, VAR_V_1418, VAR_V_1419, VAR_V_1420X30, VAR_V_1421, VAR_V_1422, VAR_V_1423, VAR_V_1424, VAR_V_1425, VAR_V_1426, VAR_V_1427] : (pred_attacker(tuple_client_C_in_2(VAR_V_1412, VAR_V_1413, VAR_V_1414, VAR_V_1415, VAR_V_1416, VAR_V_1417, VAR_V_1418, VAR_V_1419, VAR_V_1420X30, VAR_V_1421, VAR_V_1422, VAR_V_1423, VAR_V_1424, VAR_V_1425, VAR_V_1426, VAR_V_1427)) => pred_attacker(VAR_V_1415))).
fof(ax200, axiom,
![VAR_V_1429, VAR_V_1430X30, VAR_V_1431, VAR_V_1432, VAR_V_1433, VAR_V_1434, VAR_V_1435, VAR_V_1436, VAR_V_1437, VAR_V_1438, VAR_V_1439, VAR_V_1440X30, VAR_V_1441, VAR_V_1442, VAR_V_1443, VAR_V_1444] : (pred_attacker(tuple_client_C_in_2(VAR_V_1429, VAR_V_1430X30, VAR_V_1431, VAR_V_1432, VAR_V_1433, VAR_V_1434, VAR_V_1435, VAR_V_1436, VAR_V_1437, VAR_V_1438, VAR_V_1439, VAR_V_1440X30, VAR_V_1441, VAR_V_1442, VAR_V_1443, VAR_V_1444)) => pred_attacker(VAR_V_1433))).
fof(ax201, axiom,
![VAR_V_1446, VAR_V_1447, VAR_V_1448, VAR_V_1449, VAR_V_1450X30, VAR_V_1451, VAR_V_1452, VAR_V_1453, VAR_V_1454, VAR_V_1455, VAR_V_1456, VAR_V_1457, VAR_V_1458, VAR_V_1459, VAR_V_1460X30, VAR_V_1461] : (pred_attacker(tuple_client_C_in_2(VAR_V_1446, VAR_V_1447, VAR_V_1448, VAR_V_1449, VAR_V_1450X30, VAR_V_1451, VAR_V_1452, VAR_V_1453, VAR_V_1454, VAR_V_1455, VAR_V_1456, VAR_V_1457, VAR_V_1458, VAR_V_1459, VAR_V_1460X30, VAR_V_1461)) => pred_attacker(VAR_V_1451))).
fof(ax202, axiom,
![VAR_V_1463, VAR_V_1464, VAR_V_1465, VAR_V_1466, VAR_V_1467, VAR_V_1468, VAR_V_1469, VAR_V_1470X30, VAR_V_1471, VAR_V_1472, VAR_V_1473, VAR_V_1474, VAR_V_1475, VAR_V_1476, VAR_V_1477, VAR_V_1478] : (pred_attacker(tuple_client_C_in_2(VAR_V_1463, VAR_V_1464, VAR_V_1465, VAR_V_1466, VAR_V_1467, VAR_V_1468, VAR_V_1469, VAR_V_1470X30, VAR_V_1471, VAR_V_1472, VAR_V_1473, VAR_V_1474, VAR_V_1475, VAR_V_1476, VAR_V_1477, VAR_V_1478)) => pred_attacker(VAR_V_1469))).
fof(ax203, axiom,
![VAR_V_1480X30, VAR_V_1481, VAR_V_1482, VAR_V_1483, VAR_V_1484, VAR_V_1485, VAR_V_1486, VAR_V_1487, VAR_V_1488, VAR_V_1489, VAR_V_1490X30, VAR_V_1491, VAR_V_1492, VAR_V_1493, VAR_V_1494, VAR_V_1495] : (pred_attacker(tuple_client_C_in_2(VAR_V_1480X30, VAR_V_1481, VAR_V_1482, VAR_V_1483, VAR_V_1484, VAR_V_1485, VAR_V_1486, VAR_V_1487, VAR_V_1488, VAR_V_1489, VAR_V_1490X30, VAR_V_1491, VAR_V_1492, VAR_V_1493, VAR_V_1494, VAR_V_1495)) => pred_attacker(VAR_V_1487))).
fof(ax204, axiom,
![VAR_V_1497, VAR_V_1498, VAR_V_1499, VAR_V_150X300X30, VAR_V_150X301, VAR_V_150X302, VAR_V_150X303, VAR_V_150X304, VAR_V_150X305, VAR_V_150X306, VAR_V_150X307, VAR_V_150X308, VAR_V_150X309, VAR_V_1510X30, VAR_V_1511, VAR_V_1512] : (pred_attacker(tuple_client_C_in_2(VAR_V_1497, VAR_V_1498, VAR_V_1499, VAR_V_150X300X30, VAR_V_150X301, VAR_V_150X302, VAR_V_150X303, VAR_V_150X304, VAR_V_150X305, VAR_V_150X306, VAR_V_150X307, VAR_V_150X308, VAR_V_150X309, VAR_V_1510X30, VAR_V_1511, VAR_V_1512)) => pred_attacker(VAR_V_150X305))).
fof(ax205, axiom,
![VAR_V_1514, VAR_V_1515, VAR_V_1516, VAR_V_1517, VAR_V_1518, VAR_V_1519, VAR_V_1520X30, VAR_V_1521, VAR_V_1522, VAR_V_1523, VAR_V_1524, VAR_V_1525, VAR_V_1526, VAR_V_1527, VAR_V_1528, VAR_V_1529] : (pred_attacker(tuple_client_C_in_2(VAR_V_1514, VAR_V_1515, VAR_V_1516, VAR_V_1517, VAR_V_1518, VAR_V_1519, VAR_V_1520X30, VAR_V_1521, VAR_V_1522, VAR_V_1523, VAR_V_1524, VAR_V_1525, VAR_V_1526, VAR_V_1527, VAR_V_1528, VAR_V_1529)) => pred_attacker(VAR_V_1523))).
fof(ax206, axiom,
![VAR_V_1531, VAR_V_1532, VAR_V_1533, VAR_V_1534, VAR_V_1535, VAR_V_1536, VAR_V_1537, VAR_V_1538, VAR_V_1539, VAR_V_1540X30, VAR_V_1541, VAR_V_1542, VAR_V_1543, VAR_V_1544, VAR_V_1545, VAR_V_1546] : (pred_attacker(tuple_client_C_in_2(VAR_V_1531, VAR_V_1532, VAR_V_1533, VAR_V_1534, VAR_V_1535, VAR_V_1536, VAR_V_1537, VAR_V_1538, VAR_V_1539, VAR_V_1540X30, VAR_V_1541, VAR_V_1542, VAR_V_1543, VAR_V_1544, VAR_V_1545, VAR_V_1546)) => pred_attacker(VAR_V_1541))).
fof(ax207, axiom,
![VAR_V_1548, VAR_V_1549, VAR_V_1550X30, VAR_V_1551, VAR_V_1552, VAR_V_1553, VAR_V_1554, VAR_V_1555, VAR_V_1556, VAR_V_1557, VAR_V_1558, VAR_V_1559, VAR_V_1560X30, VAR_V_1561, VAR_V_1562, VAR_V_1563] : (pred_attacker(tuple_client_C_in_2(VAR_V_1548, VAR_V_1549, VAR_V_1550X30, VAR_V_1551, VAR_V_1552, VAR_V_1553, VAR_V_1554, VAR_V_1555, VAR_V_1556, VAR_V_1557, VAR_V_1558, VAR_V_1559, VAR_V_1560X30, VAR_V_1561, VAR_V_1562, VAR_V_1563)) => pred_attacker(VAR_V_1559))).
fof(ax208, axiom,
![VAR_V_1565, VAR_V_1566, VAR_V_1567, VAR_V_1568, VAR_V_1569, VAR_V_1570X30, VAR_V_1571, VAR_V_1572, VAR_V_1573, VAR_V_1574, VAR_V_1575, VAR_V_1576, VAR_V_1577, VAR_V_1578, VAR_V_1579, VAR_V_1580X30] : (pred_attacker(tuple_client_C_in_2(VAR_V_1565, VAR_V_1566, VAR_V_1567, VAR_V_1568, VAR_V_1569, VAR_V_1570X30, VAR_V_1571, VAR_V_1572, VAR_V_1573, VAR_V_1574, VAR_V_1575, VAR_V_1576, VAR_V_1577, VAR_V_1578, VAR_V_1579, VAR_V_1580X30)) => pred_attacker(VAR_V_1577))).
fof(ax209, axiom,
![VAR_V_1582, VAR_V_1583, VAR_V_1584, VAR_V_1585, VAR_V_1586, VAR_V_1587, VAR_V_1588, VAR_V_1589, VAR_V_1590X30, VAR_V_1591, VAR_V_1592, VAR_V_1593, VAR_V_1594, VAR_V_1595, VAR_V_1596, VAR_V_1597] : (pred_attacker(tuple_client_C_in_2(VAR_V_1582, VAR_V_1583, VAR_V_1584, VAR_V_1585, VAR_V_1586, VAR_V_1587, VAR_V_1588, VAR_V_1589, VAR_V_1590X30, VAR_V_1591, VAR_V_1592, VAR_V_1593, VAR_V_1594, VAR_V_1595, VAR_V_1596, VAR_V_1597)) => pred_attacker(VAR_V_1595))).
fof(ax210, axiom,
![VAR_V_1599, VAR_V_160X300X30, VAR_V_160X301, VAR_V_160X302, VAR_V_160X303, VAR_V_160X304, VAR_V_160X305, VAR_V_160X306, VAR_V_160X307, VAR_V_160X308, VAR_V_160X309, VAR_V_1610X30, VAR_V_1611, VAR_V_1612, VAR_V_1613, VAR_V_1614] : (pred_attacker(tuple_client_C_in_2(VAR_V_1599, VAR_V_160X300X30, VAR_V_160X301, VAR_V_160X302, VAR_V_160X303, VAR_V_160X304, VAR_V_160X305, VAR_V_160X306, VAR_V_160X307, VAR_V_160X308, VAR_V_160X309, VAR_V_1610X30, VAR_V_1611, VAR_V_1612, VAR_V_1613, VAR_V_1614)) => pred_attacker(VAR_V_1613))).
fof(ax211, axiom,
![VAR_V_1616, VAR_V_1617, VAR_V_1618, VAR_V_1619, VAR_V_1620X30, VAR_V_1621, VAR_V_1622, VAR_V_1623, VAR_V_1624, VAR_V_1625, VAR_V_1626, VAR_V_1627, VAR_V_1628, VAR_V_1629, VAR_V_1630X30, VAR_V_1631] : (pred_attacker(tuple_client_C_in_2(VAR_V_1616, VAR_V_1617, VAR_V_1618, VAR_V_1619, VAR_V_1620X30, VAR_V_1621, VAR_V_1622, VAR_V_1623, VAR_V_1624, VAR_V_1625, VAR_V_1626, VAR_V_1627, VAR_V_1628, VAR_V_1629, VAR_V_1630X30, VAR_V_1631)) => pred_attacker(VAR_V_1631))).
fof(ax212, axiom,
![VAR_V_1635, VAR_V_1636] : ((pred_attacker(VAR_V_1635) & pred_attacker(VAR_V_1636)) => pred_attacker(tuple_client_C_in_1(VAR_V_1635, VAR_V_1636)))).
fof(ax213, axiom,
![VAR_V_1643, VAR_V_1644] : (pred_attacker(tuple_client_C_in_1(VAR_V_1643, VAR_V_1644)) => pred_attacker(VAR_V_1643))).
fof(ax214, axiom,
![VAR_V_1646, VAR_V_1647] : (pred_attacker(tuple_client_C_in_1(VAR_V_1646, VAR_V_1647)) => pred_attacker(VAR_V_1647))).
fof(ax215, axiom,
![VAR_V_1653, VAR_V_1654, VAR_V_1655, VAR_V_1656] : ((pred_attacker(VAR_V_1653) & pred_attacker(VAR_V_1654) & pred_attacker(VAR_V_1655) & pred_attacker(VAR_V_1656)) => pred_attacker(tuple_client_B_out_2(VAR_V_1653, VAR_V_1654, VAR_V_1655, VAR_V_1656)))).
fof(ax216, axiom,
![VAR_V_1677, VAR_V_1678, VAR_V_1679, VAR_V_1680X30] : (pred_attacker(tuple_client_B_out_2(VAR_V_1677, VAR_V_1678, VAR_V_1679, VAR_V_1680X30)) => pred_attacker(VAR_V_1677))).
fof(ax217, axiom,
![VAR_V_1682, VAR_V_1683, VAR_V_1684, VAR_V_1685] : (pred_attacker(tuple_client_B_out_2(VAR_V_1682, VAR_V_1683, VAR_V_1684, VAR_V_1685)) => pred_attacker(VAR_V_1683))).
fof(ax218, axiom,
![VAR_V_1687, VAR_V_1688, VAR_V_1689, VAR_V_1690X30] : (pred_attacker(tuple_client_B_out_2(VAR_V_1687, VAR_V_1688, VAR_V_1689, VAR_V_1690X30)) => pred_attacker(VAR_V_1689))).
fof(ax219, axiom,
![VAR_V_1692, VAR_V_1693, VAR_V_1694, VAR_V_1695] : (pred_attacker(tuple_client_B_out_2(VAR_V_1692, VAR_V_1693, VAR_V_1694, VAR_V_1695)) => pred_attacker(VAR_V_1695))).
fof(ax220, axiom,
![VAR_V_1698] : (pred_attacker(VAR_V_1698) => pred_attacker(tuple_client_B_out_1(VAR_V_1698)))).
fof(ax221, axiom,
![VAR_V_170X301] : (pred_attacker(tuple_client_B_out_1(VAR_V_170X301)) => pred_attacker(VAR_V_170X301))).
fof(ax222, axiom,
![VAR_V_1715, VAR_V_1716, VAR_V_1717, VAR_V_1718, VAR_V_1719, VAR_V_1720X30, VAR_V_1721, VAR_V_1722, VAR_V_1723, VAR_V_1724, VAR_V_1725, VAR_V_1726] : ((pred_attacker(VAR_V_1715) & pred_attacker(VAR_V_1716) & pred_attacker(VAR_V_1717) & pred_attacker(VAR_V_1718) & pred_attacker(VAR_V_1719) & pred_attacker(VAR_V_1720X30) & pred_attacker(VAR_V_1721) & pred_attacker(VAR_V_1722) & pred_attacker(VAR_V_1723) & pred_attacker(VAR_V_1724) & pred_attacker(VAR_V_1725) & pred_attacker(VAR_V_1726)) => pred_attacker(tuple_client_B_in_2(VAR_V_1715, VAR_V_1716, VAR_V_1717, VAR_V_1718, VAR_V_1719, VAR_V_1720X30, VAR_V_1721, VAR_V_1722, VAR_V_1723, VAR_V_1724, VAR_V_1725, VAR_V_1726)))).
fof(ax223, axiom,
![VAR_V_1883, VAR_V_1884, VAR_V_1885, VAR_V_1886, VAR_V_1887, VAR_V_1888, VAR_V_1889, VAR_V_1890X30, VAR_V_1891, VAR_V_1892, VAR_V_1893, VAR_V_1894] : (pred_attacker(tuple_client_B_in_2(VAR_V_1883, VAR_V_1884, VAR_V_1885, VAR_V_1886, VAR_V_1887, VAR_V_1888, VAR_V_1889, VAR_V_1890X30, VAR_V_1891, VAR_V_1892, VAR_V_1893, VAR_V_1894)) => pred_attacker(VAR_V_1883))).
fof(ax224, axiom,
![VAR_V_1896, VAR_V_1897, VAR_V_1898, VAR_V_1899, VAR_V_190X300X30, VAR_V_190X301, VAR_V_190X302, VAR_V_190X303, VAR_V_190X304, VAR_V_190X305, VAR_V_190X306, VAR_V_190X307] : (pred_attacker(tuple_client_B_in_2(VAR_V_1896, VAR_V_1897, VAR_V_1898, VAR_V_1899, VAR_V_190X300X30, VAR_V_190X301, VAR_V_190X302, VAR_V_190X303, VAR_V_190X304, VAR_V_190X305, VAR_V_190X306, VAR_V_190X307)) => pred_attacker(VAR_V_1897))).
fof(ax225, axiom,
![VAR_V_190X309, VAR_V_1910X30, VAR_V_1911, VAR_V_1912, VAR_V_1913, VAR_V_1914, VAR_V_1915, VAR_V_1916, VAR_V_1917, VAR_V_1918, VAR_V_1919, VAR_V_1920X30] : (pred_attacker(tuple_client_B_in_2(VAR_V_190X309, VAR_V_1910X30, VAR_V_1911, VAR_V_1912, VAR_V_1913, VAR_V_1914, VAR_V_1915, VAR_V_1916, VAR_V_1917, VAR_V_1918, VAR_V_1919, VAR_V_1920X30)) => pred_attacker(VAR_V_1911))).
fof(ax226, axiom,
![VAR_V_1922, VAR_V_1923, VAR_V_1924, VAR_V_1925, VAR_V_1926, VAR_V_1927, VAR_V_1928, VAR_V_1929, VAR_V_1930X30, VAR_V_1931, VAR_V_1932, VAR_V_1933] : (pred_attacker(tuple_client_B_in_2(VAR_V_1922, VAR_V_1923, VAR_V_1924, VAR_V_1925, VAR_V_1926, VAR_V_1927, VAR_V_1928, VAR_V_1929, VAR_V_1930X30, VAR_V_1931, VAR_V_1932, VAR_V_1933)) => pred_attacker(VAR_V_1925))).
fof(ax227, axiom,
![VAR_V_1935, VAR_V_1936, VAR_V_1937, VAR_V_1938, VAR_V_1939, VAR_V_1940X30, VAR_V_1941, VAR_V_1942, VAR_V_1943, VAR_V_1944, VAR_V_1945, VAR_V_1946] : (pred_attacker(tuple_client_B_in_2(VAR_V_1935, VAR_V_1936, VAR_V_1937, VAR_V_1938, VAR_V_1939, VAR_V_1940X30, VAR_V_1941, VAR_V_1942, VAR_V_1943, VAR_V_1944, VAR_V_1945, VAR_V_1946)) => pred_attacker(VAR_V_1939))).
fof(ax228, axiom,
![VAR_V_1948, VAR_V_1949, VAR_V_1950X30, VAR_V_1951, VAR_V_1952, VAR_V_1953, VAR_V_1954, VAR_V_1955, VAR_V_1956, VAR_V_1957, VAR_V_1958, VAR_V_1959] : (pred_attacker(tuple_client_B_in_2(VAR_V_1948, VAR_V_1949, VAR_V_1950X30, VAR_V_1951, VAR_V_1952, VAR_V_1953, VAR_V_1954, VAR_V_1955, VAR_V_1956, VAR_V_1957, VAR_V_1958, VAR_V_1959)) => pred_attacker(VAR_V_1953))).
fof(ax229, axiom,
![VAR_V_1961, VAR_V_1962, VAR_V_1963, VAR_V_1964, VAR_V_1965, VAR_V_1966, VAR_V_1967, VAR_V_1968, VAR_V_1969, VAR_V_1970X30, VAR_V_1971, VAR_V_1972] : (pred_attacker(tuple_client_B_in_2(VAR_V_1961, VAR_V_1962, VAR_V_1963, VAR_V_1964, VAR_V_1965, VAR_V_1966, VAR_V_1967, VAR_V_1968, VAR_V_1969, VAR_V_1970X30, VAR_V_1971, VAR_V_1972)) => pred_attacker(VAR_V_1967))).
fof(ax230, axiom,
![VAR_V_1974, VAR_V_1975, VAR_V_1976, VAR_V_1977, VAR_V_1978, VAR_V_1979, VAR_V_1980X30, VAR_V_1981, VAR_V_1982, VAR_V_1983, VAR_V_1984, VAR_V_1985] : (pred_attacker(tuple_client_B_in_2(VAR_V_1974, VAR_V_1975, VAR_V_1976, VAR_V_1977, VAR_V_1978, VAR_V_1979, VAR_V_1980X30, VAR_V_1981, VAR_V_1982, VAR_V_1983, VAR_V_1984, VAR_V_1985)) => pred_attacker(VAR_V_1981))).
fof(ax231, axiom,
![VAR_V_1987, VAR_V_1988, VAR_V_1989, VAR_V_1990X30, VAR_V_1991, VAR_V_1992, VAR_V_1993, VAR_V_1994, VAR_V_1995, VAR_V_1996, VAR_V_1997, VAR_V_1998] : (pred_attacker(tuple_client_B_in_2(VAR_V_1987, VAR_V_1988, VAR_V_1989, VAR_V_1990X30, VAR_V_1991, VAR_V_1992, VAR_V_1993, VAR_V_1994, VAR_V_1995, VAR_V_1996, VAR_V_1997, VAR_V_1998)) => pred_attacker(VAR_V_1995))).
fof(ax232, axiom,
![VAR_V_20X300X300X30, VAR_V_20X300X301, VAR_V_20X300X302, VAR_V_20X300X303, VAR_V_20X300X304, VAR_V_20X300X305, VAR_V_20X300X306, VAR_V_20X300X307, VAR_V_20X300X308, VAR_V_20X300X309, VAR_V_20X3010X30, VAR_V_20X3011] : (pred_attacker(tuple_client_B_in_2(VAR_V_20X300X300X30, VAR_V_20X300X301, VAR_V_20X300X302, VAR_V_20X300X303, VAR_V_20X300X304, VAR_V_20X300X305, VAR_V_20X300X306, VAR_V_20X300X307, VAR_V_20X300X308, VAR_V_20X300X309, VAR_V_20X3010X30, VAR_V_20X3011)) => pred_attacker(VAR_V_20X300X309))).
fof(ax233, axiom,
![VAR_V_20X3013, VAR_V_20X3014, VAR_V_20X3015, VAR_V_20X3016, VAR_V_20X3017, VAR_V_20X3018, VAR_V_20X3019, VAR_V_20X3020X30, VAR_V_20X3021, VAR_V_20X3022, VAR_V_20X3023, VAR_V_20X3024] : (pred_attacker(tuple_client_B_in_2(VAR_V_20X3013, VAR_V_20X3014, VAR_V_20X3015, VAR_V_20X3016, VAR_V_20X3017, VAR_V_20X3018, VAR_V_20X3019, VAR_V_20X3020X30, VAR_V_20X3021, VAR_V_20X3022, VAR_V_20X3023, VAR_V_20X3024)) => pred_attacker(VAR_V_20X3023))).
fof(ax234, axiom,
![VAR_V_20X3026, VAR_V_20X3027, VAR_V_20X3028, VAR_V_20X3029, VAR_V_20X3030X30, VAR_V_20X3031, VAR_V_20X3032, VAR_V_20X3033, VAR_V_20X3034, VAR_V_20X3035, VAR_V_20X3036, VAR_V_20X3037] : (pred_attacker(tuple_client_B_in_2(VAR_V_20X3026, VAR_V_20X3027, VAR_V_20X3028, VAR_V_20X3029, VAR_V_20X3030X30, VAR_V_20X3031, VAR_V_20X3032, VAR_V_20X3033, VAR_V_20X3034, VAR_V_20X3035, VAR_V_20X3036, VAR_V_20X3037)) => pred_attacker(VAR_V_20X3037))).
fof(ax235, axiom,
![VAR_V_20X3041, VAR_V_20X3042] : ((pred_attacker(VAR_V_20X3041) & pred_attacker(VAR_V_20X3042)) => pred_attacker(tuple_client_B_in_1(VAR_V_20X3041, VAR_V_20X3042)))).
fof(ax236, axiom,
![VAR_V_20X3049, VAR_V_20X3050X30] : (pred_attacker(tuple_client_B_in_1(VAR_V_20X3049, VAR_V_20X3050X30)) => pred_attacker(VAR_V_20X3049))).
fof(ax237, axiom,
![VAR_V_20X3052, VAR_V_20X3053] : (pred_attacker(tuple_client_B_in_1(VAR_V_20X3052, VAR_V_20X3053)) => pred_attacker(VAR_V_20X3053))).
fof(ax238, axiom,
![VAR_V_20X3056] : (pred_attacker(VAR_V_20X3056) => pred_attacker(tuple_client_A_out_2(VAR_V_20X3056)))).
fof(ax239, axiom,
![VAR_V_20X3059] : (pred_attacker(tuple_client_A_out_2(VAR_V_20X3059)) => pred_attacker(VAR_V_20X3059))).
fof(ax240, axiom,
![VAR_V_20X3062] : (pred_attacker(VAR_V_20X3062) => pred_attacker(tuple_client_A_out_1(VAR_V_20X3062)))).
fof(ax241, axiom,
![VAR_V_20X3065] : (pred_attacker(tuple_client_A_out_1(VAR_V_20X3065)) => pred_attacker(VAR_V_20X3065))).
fof(ax242, axiom,
![VAR_V_20X3071, VAR_V_20X3072, VAR_V_20X3073, VAR_V_20X3074] : ((pred_attacker(VAR_V_20X3071) & pred_attacker(VAR_V_20X3072) & pred_attacker(VAR_V_20X3073) & pred_attacker(VAR_V_20X3074)) => pred_attacker(tuple_client_A_in_1(VAR_V_20X3071, VAR_V_20X3072, VAR_V_20X3073, VAR_V_20X3074)))).
fof(ax243, axiom,
![VAR_V_20X3095, VAR_V_20X3096, VAR_V_20X3097, VAR_V_20X3098] : (pred_attacker(tuple_client_A_in_1(VAR_V_20X3095, VAR_V_20X3096, VAR_V_20X3097, VAR_V_20X3098)) => pred_attacker(VAR_V_20X3095))).
fof(ax244, axiom,
![VAR_V_210X300X30, VAR_V_210X301, VAR_V_210X302, VAR_V_210X303] : (pred_attacker(tuple_client_A_in_1(VAR_V_210X300X30, VAR_V_210X301, VAR_V_210X302, VAR_V_210X303)) => pred_attacker(VAR_V_210X301))).
fof(ax245, axiom,
![VAR_V_210X305, VAR_V_210X306, VAR_V_210X307, VAR_V_210X308] : (pred_attacker(tuple_client_A_in_1(VAR_V_210X305, VAR_V_210X306, VAR_V_210X307, VAR_V_210X308)) => pred_attacker(VAR_V_210X307))).
fof(ax246, axiom,
![VAR_V_2110X30, VAR_V_2111, VAR_V_2112, VAR_V_2113] : (pred_attacker(tuple_client_A_in_1(VAR_V_2110X30, VAR_V_2111, VAR_V_2112, VAR_V_2113)) => pred_attacker(VAR_V_2113))).
fof(ax247, axiom,
pred_attacker(constr_ZERO)).
fof(ax248, axiom,
pred_attacker(constr_CONST_4)).
fof(ax249, axiom,
pred_attacker(constr_CONST_3)).
fof(ax250, axiom,
pred_attacker(constr_CONST_2)).
fof(ax251, axiom,
pred_attacker(constr_CONST_1)).
fof(ax252, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax253, axiom,
![VAR_V_2123, VAR_V_2124, VAR_V_2125, VAR_V_2126] : ((pred_attacker(VAR_V_2123) & pred_attacker(VAR_V_2124) & pred_attacker(VAR_V_2125) & pred_attacker(VAR_V_2126)) => pred_attacker(tuple_4(VAR_V_2123, VAR_V_2124, VAR_V_2125, VAR_V_2126)))).
fof(ax254, axiom,
![VAR_V_2147, VAR_V_2148, VAR_V_2149, VAR_V_2150X30] : (pred_attacker(tuple_4(VAR_V_2147, VAR_V_2148, VAR_V_2149, VAR_V_2150X30)) => pred_attacker(VAR_V_2147))).
fof(ax255, axiom,
![VAR_V_2152, VAR_V_2153, VAR_V_2154, VAR_V_2155] : (pred_attacker(tuple_4(VAR_V_2152, VAR_V_2153, VAR_V_2154, VAR_V_2155)) => pred_attacker(VAR_V_2153))).
fof(ax256, axiom,
![VAR_V_2157, VAR_V_2158, VAR_V_2159, VAR_V_2160X30] : (pred_attacker(tuple_4(VAR_V_2157, VAR_V_2158, VAR_V_2159, VAR_V_2160X30)) => pred_attacker(VAR_V_2159))).
fof(ax257, axiom,
![VAR_V_2162, VAR_V_2163, VAR_V_2164, VAR_V_2165] : (pred_attacker(tuple_4(VAR_V_2162, VAR_V_2163, VAR_V_2164, VAR_V_2165)) => pred_attacker(VAR_V_2165))).
fof(ax258, axiom,
![VAR_V_2170X30, VAR_V_2171, VAR_V_2172] : ((pred_attacker(VAR_V_2170X30) & pred_attacker(VAR_V_2171) & pred_attacker(VAR_V_2172)) => pred_attacker(tuple_3(VAR_V_2170X30, VAR_V_2171, VAR_V_2172)))).
fof(ax259, axiom,
![VAR_V_2185, VAR_V_2186, VAR_V_2187] : (pred_attacker(tuple_3(VAR_V_2185, VAR_V_2186, VAR_V_2187)) => pred_attacker(VAR_V_2185))).
fof(ax260, axiom,
![VAR_V_2189, VAR_V_2190X30, VAR_V_2191] : (pred_attacker(tuple_3(VAR_V_2189, VAR_V_2190X30, VAR_V_2191)) => pred_attacker(VAR_V_2190X30))).
fof(ax261, axiom,
![VAR_V_2193, VAR_V_2194, VAR_V_2195] : (pred_attacker(tuple_3(VAR_V_2193, VAR_V_2194, VAR_V_2195)) => pred_attacker(VAR_V_2195))).
fof(ax262, axiom,
![VAR_V_2199, VAR_V_220X300X30] : ((pred_attacker(VAR_V_2199) & pred_attacker(VAR_V_220X300X30)) => pred_attacker(tuple_2(VAR_V_2199, VAR_V_220X300X30)))).
fof(ax263, axiom,
![VAR_V_220X307, VAR_V_220X308] : (pred_attacker(tuple_2(VAR_V_220X307, VAR_V_220X308)) => pred_attacker(VAR_V_220X307))).
fof(ax264, axiom,
![VAR_V_2210X30, VAR_V_2211] : (pred_attacker(tuple_2(VAR_V_2210X30, VAR_V_2211)) => pred_attacker(VAR_V_2211))).
fof(ax265, axiom,
![VAR_V_2218, VAR_V_2219, VAR_V_2220X30, VAR_V_2221, VAR_V_2222] : ((pred_attacker(VAR_V_2218) & pred_attacker(VAR_V_2219) & pred_attacker(VAR_V_2220X30) & pred_attacker(VAR_V_2221) & pred_attacker(VAR_V_2222)) => pred_attacker(tuple_5(VAR_V_2218, VAR_V_2219, VAR_V_2220X30, VAR_V_2221, VAR_V_2222)))).
fof(ax266, axiom,
![VAR_V_2253, VAR_V_2254, VAR_V_2255, VAR_V_2256, VAR_V_2257] : (pred_attacker(tuple_5(VAR_V_2253, VAR_V_2254, VAR_V_2255, VAR_V_2256, VAR_V_2257)) => pred_attacker(VAR_V_2253))).
fof(ax267, axiom,
![VAR_V_2259, VAR_V_2260X30, VAR_V_2261, VAR_V_2262, VAR_V_2263] : (pred_attacker(tuple_5(VAR_V_2259, VAR_V_2260X30, VAR_V_2261, VAR_V_2262, VAR_V_2263)) => pred_attacker(VAR_V_2260X30))).
fof(ax268, axiom,
![VAR_V_2265, VAR_V_2266, VAR_V_2267, VAR_V_2268, VAR_V_2269] : (pred_attacker(tuple_5(VAR_V_2265, VAR_V_2266, VAR_V_2267, VAR_V_2268, VAR_V_2269)) => pred_attacker(VAR_V_2267))).
fof(ax269, axiom,
![VAR_V_2271, VAR_V_2272, VAR_V_2273, VAR_V_2274, VAR_V_2275] : (pred_attacker(tuple_5(VAR_V_2271, VAR_V_2272, VAR_V_2273, VAR_V_2274, VAR_V_2275)) => pred_attacker(VAR_V_2274))).
fof(ax270, axiom,
![VAR_V_2277, VAR_V_2278, VAR_V_2279, VAR_V_2280X30, VAR_V_2281] : (pred_attacker(tuple_5(VAR_V_2277, VAR_V_2278, VAR_V_2279, VAR_V_2280X30, VAR_V_2281)) => pred_attacker(VAR_V_2281))).
fof(ax271, axiom,
![VAR_V_2283, VAR_V_2284] : ((pred_mess(VAR_V_2284, VAR_V_2283) & pred_attacker(VAR_V_2284)) => pred_attacker(VAR_V_2283))).
fof(ax272, axiom,
![VAR_V_2285, VAR_V_2286] : ((pred_attacker(VAR_V_2286) & pred_attacker(VAR_V_2285)) => pred_mess(VAR_V_2286, VAR_V_2285))).
fof(ax273, axiom,
pred_attacker(name_c)).
fof(ax274, axiom,
pred_attacker(name_S)).
fof(ax275, axiom,
pred_attacker(name_Kcs)).
fof(ax276, axiom,
pred_attacker(name_C)).
fof(ax277, axiom,
pred_attacker(name_B)).
fof(ax278, axiom,
pred_attacker(name_A)).
fof(ax279, axiom,
![VAR_V_2288] : (pred_equal(VAR_V_2288, VAR_V_2288))).
fof(ax280, axiom,
![VAR_V_2289] : (pred_attacker(name_new0x2Dname(VAR_V_2289)))).
fof(ax281, axiom,
pred_attacker(tuple_client_A_out_1(tuple_2(constr_h(constr_con3(name_A, name_B, name_Na), name_Kas), tuple_3(name_A, name_B, name_Na))))).
fof(ax282, axiom,
![VAR_NA_2517, VAR_H_A_B_NA_KAS_2516] : (pred_attacker(tuple_client_B_in_1(VAR_H_A_B_NA_KAS_2516, tuple_3(name_A, name_B, VAR_NA_2517))) => pred_attacker(tuple_client_B_out_1(tuple_2(constr_h(constr_con4(name_B, name_C, name_Nb(VAR_NA_2517, VAR_H_A_B_NA_KAS_2516), constr_con4(VAR_H_A_B_NA_KAS_2516, name_A, name_B, VAR_NA_2517)), name_Kbs), tuple_4(name_B, name_C, name_Nb(VAR_NA_2517, VAR_H_A_B_NA_KAS_2516), tuple_2(VAR_H_A_B_NA_KAS_2516, tuple_3(name_A, name_B, VAR_NA_2517)))))))).
fof(ax283, axiom,
![VAR_NA_2678, VAR_NB_2676, VAR_H_A_B_NA_KAS_2677, VAR_H_B_C_NB_XA_KBS_2675] : (pred_attacker(tuple_client_C_in_1(VAR_H_B_C_NB_XA_KBS_2675, tuple_4(name_B, name_C, VAR_NB_2676, tuple_2(VAR_H_A_B_NA_KAS_2677, tuple_3(name_A, name_B, VAR_NA_2678))))) => pred_attacker(tuple_client_C_out_1(name_Nc(VAR_NA_2678, VAR_H_A_B_NA_KAS_2677, VAR_NB_2676, VAR_H_B_C_NB_XA_KBS_2675))))).
fof(ax284, axiom,
![VAR_NA_2825, VAR_NB_2823, VAR_H_A_B_NA_KAS_2824, VAR_H_B_C_NB_XA_KBS_2822] : (pred_attacker(tuple_client_C_in_1(VAR_H_B_C_NB_XA_KBS_2822, tuple_4(name_B, name_C, VAR_NB_2823, tuple_2(VAR_H_A_B_NA_KAS_2824, tuple_3(name_A, name_B, VAR_NA_2825))))) => pred_attacker(tuple_client_C_out_2(tuple_2(constr_h(constr_con4(name_C, name_S, name_Nc(VAR_NA_2825, VAR_H_A_B_NA_KAS_2824, VAR_NB_2823, VAR_H_B_C_NB_XA_KBS_2822), constr_con5(VAR_H_B_C_NB_XA_KBS_2822, name_B, name_C, VAR_NB_2823, constr_con4(VAR_H_A_B_NA_KAS_2824, name_A, name_B, VAR_NA_2825))), name_Kcs), tuple_4(name_C, name_S, name_Nc(VAR_NA_2825, VAR_H_A_B_NA_KAS_2824, VAR_NB_2823, VAR_H_B_C_NB_XA_KBS_2822), tuple_2(VAR_H_B_C_NB_XA_KBS_2822, tuple_4(name_B, name_C, VAR_NB_2823, tuple_2(VAR_H_A_B_NA_KAS_2824, tuple_3(name_A, name_B, VAR_NA_2825)))))))))).
fof(ax285, axiom,
![VAR_KAB_XOR_H_NA_KAS_2866, VAR_KAB_XOR_H_NB_KBS_2868, VAR_KBC_XOR_H_NB_KBS_2870X30, VAR_KBC_XOR_H_NC_KCS_2872, VAR_NA_2877, VAR_NB_2875, VAR_ENC_A_B_NA_KAB_2867, VAR_ENC_B_A_NB_KAB_2869, VAR_ENC_B_C_NB_KBC_2871, VAR_ENC_C_B_NC_KBC_2873, VAR_H_A_B_NA_KAS_2876, VAR_H_B_C_NB_XA_KBS_2874] : ((pred_attacker(tuple_client_C_in_2(name_A, name_B, VAR_KAB_XOR_H_NA_KAS_2866, VAR_ENC_A_B_NA_KAB_2867, name_B, name_A, VAR_KAB_XOR_H_NB_KBS_2868, VAR_ENC_B_A_NB_KAB_2869, name_B, name_C, VAR_KBC_XOR_H_NB_KBS_2870X30, VAR_ENC_B_C_NB_KBC_2871, name_C, name_B, VAR_KBC_XOR_H_NC_KCS_2872, VAR_ENC_C_B_NC_KBC_2873)) & pred_attacker(tuple_client_C_in_1(VAR_H_B_C_NB_XA_KBS_2874, tuple_4(name_B, name_C, VAR_NB_2875, tuple_2(VAR_H_A_B_NA_KAS_2876, tuple_3(name_A, name_B, VAR_NA_2877)))))) => pred_attacker(tuple_client_C_out_3(constr_xor(VAR_KBC_XOR_H_NC_KCS_2872, constr_h(name_Nc(VAR_NA_2877, VAR_H_A_B_NA_KAS_2876, VAR_NB_2875, VAR_H_B_C_NB_XA_KBS_2874), name_Kcs)))))).
fof(ax286, axiom,
![VAR_NA_3428, VAR_NB_3426, VAR_NC_3424, VAR_H_A_B_NA_KAS_3427, VAR_H_B_C_NB_XA_KBS_3425] : (pred_attacker(tuple_server_S_in_1(constr_h(constr_con4(name_C, name_S, VAR_NC_3424, constr_con5(VAR_H_B_C_NB_XA_KBS_3425, name_B, name_C, VAR_NB_3426, constr_con4(VAR_H_A_B_NA_KAS_3427, name_A, name_B, VAR_NA_3428))), name_Kcs), tuple_4(name_C, name_S, VAR_NC_3424, tuple_2(VAR_H_B_C_NB_XA_KBS_3425, tuple_4(name_B, name_C, VAR_NB_3426, tuple_2(VAR_H_A_B_NA_KAS_3427, tuple_3(name_A, name_B, VAR_NA_3428))))))) => pred_attacker(tuple_server_S_out_1(name_A, name_B, constr_xor(name_Kab_39, constr_h(VAR_NA_3428, name_Kas)), constr_enc(constr_con3(name_A, name_B, VAR_NA_3428), name_Kab_39), name_B, name_A, constr_xor(name_Kab_39, constr_h(VAR_NB_3426, name_Kbs)), constr_enc(constr_con3(name_B, name_A, VAR_NB_3426), name_Kab_39), name_B, name_C, constr_xor(name_Kbc_40x30, constr_h(VAR_NB_3426, name_Kbs)), constr_enc(constr_con3(name_B, name_C, VAR_NB_3426), name_Kbc_40x30), name_C, name_B, constr_xor(name_Kbc_40x30, constr_h(VAR_NC_3424, name_Kcs)), constr_enc(constr_con3(name_C, name_B, VAR_NC_3424), name_Kbc_40x30))))).
fof(co0, conjecture,
pred_attacker(name_objective)).
