%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax5, axiom,
constr_CONST_0x30 != name_Kab).
fof(ax6, axiom,
constr_CONST_0x30 != name_Kas).
fof(ax7, axiom,
constr_CONST_0x30 != name_Kbc).
fof(ax8, axiom,
constr_CONST_0x30 != name_Kbs).
fof(ax9, axiom,
constr_CONST_0x30 != name_Kcs).
fof(ax10, axiom,
constr_CONST_0x30 != name_Na).
fof(ax11, axiom,
constr_CONST_0x30 != name_c).
fof(ax12, axiom,
constr_CONST_0x30 != name_idA).
fof(ax13, axiom,
constr_CONST_0x30 != name_idB).
fof(ax14, axiom,
constr_CONST_0x30 != name_idC).
fof(ax15, axiom,
constr_CONST_0x30 != name_idS).
fof(ax16, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax17, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax18, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax19, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax20, axiom,
constr_CONST_1 != name_Kab).
fof(ax21, axiom,
constr_CONST_1 != name_Kas).
fof(ax22, axiom,
constr_CONST_1 != name_Kbc).
fof(ax23, axiom,
constr_CONST_1 != name_Kbs).
fof(ax24, axiom,
constr_CONST_1 != name_Kcs).
fof(ax25, axiom,
constr_CONST_1 != name_Na).
fof(ax26, axiom,
constr_CONST_1 != name_c).
fof(ax27, axiom,
constr_CONST_1 != name_idA).
fof(ax28, axiom,
constr_CONST_1 != name_idB).
fof(ax29, axiom,
constr_CONST_1 != name_idC).
fof(ax30, axiom,
constr_CONST_1 != name_idS).
fof(ax31, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax32, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax33, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax34, axiom,
constr_CONST_2 != name_Kab).
fof(ax35, axiom,
constr_CONST_2 != name_Kas).
fof(ax36, axiom,
constr_CONST_2 != name_Kbc).
fof(ax37, axiom,
constr_CONST_2 != name_Kbs).
fof(ax38, axiom,
constr_CONST_2 != name_Kcs).
fof(ax39, axiom,
constr_CONST_2 != name_Na).
fof(ax40, axiom,
constr_CONST_2 != name_c).
fof(ax41, axiom,
constr_CONST_2 != name_idA).
fof(ax42, axiom,
constr_CONST_2 != name_idB).
fof(ax43, axiom,
constr_CONST_2 != name_idC).
fof(ax44, axiom,
constr_CONST_2 != name_idS).
fof(ax45, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax46, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax47, axiom,
constr_CONST_3 != name_Kab).
fof(ax48, axiom,
constr_CONST_3 != name_Kas).
fof(ax49, axiom,
constr_CONST_3 != name_Kbc).
fof(ax50, axiom,
constr_CONST_3 != name_Kbs).
fof(ax51, axiom,
constr_CONST_3 != name_Kcs).
fof(ax52, axiom,
constr_CONST_3 != name_Na).
fof(ax53, axiom,
constr_CONST_3 != name_c).
fof(ax54, axiom,
constr_CONST_3 != name_idA).
fof(ax55, axiom,
constr_CONST_3 != name_idB).
fof(ax56, axiom,
constr_CONST_3 != name_idC).
fof(ax57, axiom,
constr_CONST_3 != name_idS).
fof(ax58, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax59, axiom,
constr_CONST_4 != name_Kab).
fof(ax60, axiom,
constr_CONST_4 != name_Kas).
fof(ax61, axiom,
constr_CONST_4 != name_Kbc).
fof(ax62, axiom,
constr_CONST_4 != name_Kbs).
fof(ax63, axiom,
constr_CONST_4 != name_Kcs).
fof(ax64, axiom,
constr_CONST_4 != name_Na).
fof(ax65, axiom,
constr_CONST_4 != name_c).
fof(ax66, axiom,
constr_CONST_4 != name_idA).
fof(ax67, axiom,
constr_CONST_4 != name_idB).
fof(ax68, axiom,
constr_CONST_4 != name_idC).
fof(ax69, axiom,
constr_CONST_4 != name_idS).
fof(ax70, axiom,
constr_ZERO != name_Kab).
fof(ax71, axiom,
constr_ZERO != name_Kas).
fof(ax72, axiom,
constr_ZERO != name_Kbc).
fof(ax73, axiom,
constr_ZERO != name_Kbs).
fof(ax74, axiom,
constr_ZERO != name_Kcs).
fof(ax75, axiom,
constr_ZERO != name_Na).
fof(ax76, axiom,
constr_ZERO != name_c).
fof(ax77, axiom,
constr_ZERO != name_idA).
fof(ax78, axiom,
constr_ZERO != name_idB).
fof(ax79, axiom,
constr_ZERO != name_idC).
fof(ax80, axiom,
constr_ZERO != name_idS).
fof(ax81, axiom,
name_Kab != name_Kas).
fof(ax82, axiom,
name_Kab != name_Kbc).
fof(ax83, axiom,
name_Kab != name_Kbs).
fof(ax84, axiom,
name_Kab != name_Kcs).
fof(ax85, axiom,
name_Kab != name_Na).
fof(ax86, axiom,
name_Kab != name_c).
fof(ax87, axiom,
name_Kab != name_idA).
fof(ax88, axiom,
name_Kab != name_idB).
fof(ax89, axiom,
name_Kab != name_idC).
fof(ax90, axiom,
name_Kab != name_idS).
fof(ax91, axiom,
name_Kas != name_Kbc).
fof(ax92, axiom,
name_Kas != name_Kbs).
fof(ax93, axiom,
name_Kas != name_Kcs).
fof(ax94, axiom,
name_Kas != name_Na).
fof(ax95, axiom,
name_Kas != name_c).
fof(ax96, axiom,
name_Kas != name_idA).
fof(ax97, axiom,
name_Kas != name_idB).
fof(ax98, axiom,
name_Kas != name_idC).
fof(ax99, axiom,
name_Kas != name_idS).
fof(ax100, axiom,
name_Kbc != name_Kbs).
fof(ax101, axiom,
name_Kbc != name_Kcs).
fof(ax102, axiom,
name_Kbc != name_Na).
fof(ax103, axiom,
name_Kbc != name_c).
fof(ax104, axiom,
name_Kbc != name_idA).
fof(ax105, axiom,
name_Kbc != name_idB).
fof(ax106, axiom,
name_Kbc != name_idC).
fof(ax107, axiom,
name_Kbc != name_idS).
fof(ax108, axiom,
name_Kbs != name_Kcs).
fof(ax109, axiom,
name_Kbs != name_Na).
fof(ax110, axiom,
name_Kbs != name_c).
fof(ax111, axiom,
name_Kbs != name_idA).
fof(ax112, axiom,
name_Kbs != name_idB).
fof(ax113, axiom,
name_Kbs != name_idC).
fof(ax114, axiom,
name_Kbs != name_idS).
fof(ax115, axiom,
name_Kcs != name_Na).
fof(ax116, axiom,
name_Kcs != name_c).
fof(ax117, axiom,
name_Kcs != name_idA).
fof(ax118, axiom,
name_Kcs != name_idB).
fof(ax119, axiom,
name_Kcs != name_idC).
fof(ax120, axiom,
name_Kcs != name_idS).
fof(ax121, axiom,
name_Na != name_c).
fof(ax122, axiom,
name_Na != name_idA).
fof(ax123, axiom,
name_Na != name_idB).
fof(ax124, axiom,
name_Na != name_idC).
fof(ax125, axiom,
name_Na != name_idS).
fof(ax126, axiom,
name_c != name_idA).
fof(ax127, axiom,
name_c != name_idB).
fof(ax128, axiom,
name_c != name_idC).
fof(ax129, axiom,
name_c != name_idS).
fof(ax130, axiom,
name_idA != name_idB).
fof(ax131, axiom,
name_idA != name_idC).
fof(ax132, axiom,
name_idA != name_idS).
fof(ax133, axiom,
name_idB != name_idC).
fof(ax134, axiom,
name_idB != name_idS).
fof(ax135, axiom,
name_idC != name_idS).
fof(ax136, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_dec(constr_enc(VAR_M_0X30, VAR_K_0X30), VAR_K_0X30) = VAR_M_0X30)).
fof(ax137, axiom,
![VAR_V_93, VAR_V_94] : ((pred_attacker(VAR_V_93) & pred_attacker(VAR_V_94)) => pred_attacker(constr_xor(VAR_V_93, VAR_V_94)))).
fof(ax138, axiom,
pred_attacker(tuple_true)).
fof(ax139, axiom,
![VAR_V_98, VAR_V_99] : ((pred_attacker(VAR_V_98) & pred_attacker(VAR_V_99)) => pred_attacker(constr_h(VAR_V_98, VAR_V_99)))).
fof(ax140, axiom,
pred_attacker(tuple_false)).
fof(ax141, axiom,
![VAR_V_10X302, VAR_V_10X303] : ((pred_attacker(VAR_V_10X302) & pred_attacker(VAR_V_10X303)) => pred_attacker(constr_enc(VAR_V_10X302, VAR_V_10X303)))).
fof(ax142, axiom,
![VAR_X1_10X305, VAR_X2_10X306, VAR_X3_10X307, VAR_X4_10X308, VAR_X5_10X309] : (pred_attacker(constr_con5(VAR_X1_10X305, VAR_X2_10X306, VAR_X3_10X307, VAR_X4_10X308, VAR_X5_10X309)) => pred_attacker(tuple_5(VAR_X1_10X305, VAR_X2_10X306, VAR_X3_10X307, VAR_X4_10X308, VAR_X5_10X309)))).
fof(ax143, axiom,
![VAR_X1_111, VAR_X2_112, VAR_X3_113, VAR_X4_114] : (pred_attacker(constr_con4(VAR_X1_111, VAR_X2_112, VAR_X3_113, VAR_X4_114)) => pred_attacker(tuple_4(VAR_X1_111, VAR_X2_112, VAR_X3_113, VAR_X4_114)))).
fof(ax144, axiom,
![VAR_X1_116, VAR_X2_117, VAR_X3_118] : (pred_attacker(constr_con3(VAR_X1_116, VAR_X2_117, VAR_X3_118)) => pred_attacker(tuple_3(VAR_X1_116, VAR_X2_117, VAR_X3_118)))).
fof(ax145, axiom,
![VAR_V_121, VAR_V_122] : ((pred_attacker(VAR_V_121) & pred_attacker(VAR_V_122)) => pred_attacker(constr_dec(VAR_V_121, VAR_V_122)))).
fof(ax146, axiom,
![VAR_V_128, VAR_V_129, VAR_V_130X30, VAR_V_131, VAR_V_132] : ((pred_attacker(VAR_V_128) & pred_attacker(VAR_V_129) & pred_attacker(VAR_V_130X30) & pred_attacker(VAR_V_131) & pred_attacker(VAR_V_132)) => pred_attacker(constr_con5(VAR_V_128, VAR_V_129, VAR_V_130X30, VAR_V_131, VAR_V_132)))).
fof(ax147, axiom,
![VAR_V_137, VAR_V_138, VAR_V_139, VAR_V_140X30] : ((pred_attacker(VAR_V_137) & pred_attacker(VAR_V_138) & pred_attacker(VAR_V_139) & pred_attacker(VAR_V_140X30)) => pred_attacker(constr_con4(VAR_V_137, VAR_V_138, VAR_V_139, VAR_V_140X30)))).
fof(ax148, axiom,
![VAR_V_144, VAR_V_145, VAR_V_146] : ((pred_attacker(VAR_V_144) & pred_attacker(VAR_V_145) & pred_attacker(VAR_V_146)) => pred_attacker(constr_con3(VAR_V_144, VAR_V_145, VAR_V_146)))).
fof(ax149, axiom,
pred_attacker(constr_ZERO)).
fof(ax150, axiom,
![VAR_V_155, VAR_V_156, VAR_V_157, VAR_V_158, VAR_V_159, VAR_V_160X30, VAR_V_161, VAR_V_162] : ((pred_attacker(VAR_V_155) & pred_attacker(VAR_V_156) & pred_attacker(VAR_V_157) & pred_attacker(VAR_V_158) & pred_attacker(VAR_V_159) & pred_attacker(VAR_V_160X30) & pred_attacker(VAR_V_161) & pred_attacker(VAR_V_162)) => pred_attacker(tuple_S_out_2(VAR_V_155, VAR_V_156, VAR_V_157, VAR_V_158, VAR_V_159, VAR_V_160X30, VAR_V_161, VAR_V_162)))).
fof(ax151, axiom,
![VAR_V_235, VAR_V_236, VAR_V_237, VAR_V_238, VAR_V_239, VAR_V_240X30, VAR_V_241, VAR_V_242] : (pred_attacker(tuple_S_out_2(VAR_V_235, VAR_V_236, VAR_V_237, VAR_V_238, VAR_V_239, VAR_V_240X30, VAR_V_241, VAR_V_242)) => pred_attacker(VAR_V_235))).
fof(ax152, axiom,
![VAR_V_244, VAR_V_245, VAR_V_246, VAR_V_247, VAR_V_248, VAR_V_249, VAR_V_250X30, VAR_V_251] : (pred_attacker(tuple_S_out_2(VAR_V_244, VAR_V_245, VAR_V_246, VAR_V_247, VAR_V_248, VAR_V_249, VAR_V_250X30, VAR_V_251)) => pred_attacker(VAR_V_245))).
fof(ax153, axiom,
![VAR_V_253, VAR_V_254, VAR_V_255, VAR_V_256, VAR_V_257, VAR_V_258, VAR_V_259, VAR_V_260X30] : (pred_attacker(tuple_S_out_2(VAR_V_253, VAR_V_254, VAR_V_255, VAR_V_256, VAR_V_257, VAR_V_258, VAR_V_259, VAR_V_260X30)) => pred_attacker(VAR_V_255))).
fof(ax154, axiom,
![VAR_V_262, VAR_V_263, VAR_V_264, VAR_V_265, VAR_V_266, VAR_V_267, VAR_V_268, VAR_V_269] : (pred_attacker(tuple_S_out_2(VAR_V_262, VAR_V_263, VAR_V_264, VAR_V_265, VAR_V_266, VAR_V_267, VAR_V_268, VAR_V_269)) => pred_attacker(VAR_V_265))).
fof(ax155, axiom,
![VAR_V_271, VAR_V_272, VAR_V_273, VAR_V_274, VAR_V_275, VAR_V_276, VAR_V_277, VAR_V_278] : (pred_attacker(tuple_S_out_2(VAR_V_271, VAR_V_272, VAR_V_273, VAR_V_274, VAR_V_275, VAR_V_276, VAR_V_277, VAR_V_278)) => pred_attacker(VAR_V_275))).
fof(ax156, axiom,
![VAR_V_280X30, VAR_V_281, VAR_V_282, VAR_V_283, VAR_V_284, VAR_V_285, VAR_V_286, VAR_V_287] : (pred_attacker(tuple_S_out_2(VAR_V_280X30, VAR_V_281, VAR_V_282, VAR_V_283, VAR_V_284, VAR_V_285, VAR_V_286, VAR_V_287)) => pred_attacker(VAR_V_285))).
fof(ax157, axiom,
![VAR_V_289, VAR_V_290X30, VAR_V_291, VAR_V_292, VAR_V_293, VAR_V_294, VAR_V_295, VAR_V_296] : (pred_attacker(tuple_S_out_2(VAR_V_289, VAR_V_290X30, VAR_V_291, VAR_V_292, VAR_V_293, VAR_V_294, VAR_V_295, VAR_V_296)) => pred_attacker(VAR_V_295))).
fof(ax158, axiom,
![VAR_V_298, VAR_V_299, VAR_V_30X300X30, VAR_V_30X301, VAR_V_30X302, VAR_V_30X303, VAR_V_30X304, VAR_V_30X305] : (pred_attacker(tuple_S_out_2(VAR_V_298, VAR_V_299, VAR_V_30X300X30, VAR_V_30X301, VAR_V_30X302, VAR_V_30X303, VAR_V_30X304, VAR_V_30X305)) => pred_attacker(VAR_V_30X305))).
fof(ax159, axiom,
![VAR_V_30X309, VAR_V_310X30] : ((pred_attacker(VAR_V_30X309) & pred_attacker(VAR_V_310X30)) => pred_attacker(tuple_S_in_1(VAR_V_30X309, VAR_V_310X30)))).
fof(ax160, axiom,
![VAR_V_317, VAR_V_318] : (pred_attacker(tuple_S_in_1(VAR_V_317, VAR_V_318)) => pred_attacker(VAR_V_317))).
fof(ax161, axiom,
![VAR_V_320X30, VAR_V_321] : (pred_attacker(tuple_S_in_1(VAR_V_320X30, VAR_V_321)) => pred_attacker(VAR_V_321))).
fof(ax162, axiom,
![VAR_V_335, VAR_V_336, VAR_V_337, VAR_V_338, VAR_V_339, VAR_V_340X30, VAR_V_341, VAR_V_342, VAR_V_343, VAR_V_344, VAR_V_345, VAR_V_346] : ((pred_attacker(VAR_V_335) & pred_attacker(VAR_V_336) & pred_attacker(VAR_V_337) & pred_attacker(VAR_V_338) & pred_attacker(VAR_V_339) & pred_attacker(VAR_V_340X30) & pred_attacker(VAR_V_341) & pred_attacker(VAR_V_342) & pred_attacker(VAR_V_343) & pred_attacker(VAR_V_344) & pred_attacker(VAR_V_345) & pred_attacker(VAR_V_346)) => pred_attacker(tuple_C_out_6(VAR_V_335, VAR_V_336, VAR_V_337, VAR_V_338, VAR_V_339, VAR_V_340X30, VAR_V_341, VAR_V_342, VAR_V_343, VAR_V_344, VAR_V_345, VAR_V_346)))).
fof(ax163, axiom,
![VAR_V_50X303, VAR_V_50X304, VAR_V_50X305, VAR_V_50X306, VAR_V_50X307, VAR_V_50X308, VAR_V_50X309, VAR_V_510X30, VAR_V_511, VAR_V_512, VAR_V_513, VAR_V_514] : (pred_attacker(tuple_C_out_6(VAR_V_50X303, VAR_V_50X304, VAR_V_50X305, VAR_V_50X306, VAR_V_50X307, VAR_V_50X308, VAR_V_50X309, VAR_V_510X30, VAR_V_511, VAR_V_512, VAR_V_513, VAR_V_514)) => pred_attacker(VAR_V_50X303))).
fof(ax164, axiom,
![VAR_V_516, VAR_V_517, VAR_V_518, VAR_V_519, VAR_V_520X30, VAR_V_521, VAR_V_522, VAR_V_523, VAR_V_524, VAR_V_525, VAR_V_526, VAR_V_527] : (pred_attacker(tuple_C_out_6(VAR_V_516, VAR_V_517, VAR_V_518, VAR_V_519, VAR_V_520X30, VAR_V_521, VAR_V_522, VAR_V_523, VAR_V_524, VAR_V_525, VAR_V_526, VAR_V_527)) => pred_attacker(VAR_V_517))).
fof(ax165, axiom,
![VAR_V_529, VAR_V_530X30, VAR_V_531, VAR_V_532, VAR_V_533, VAR_V_534, VAR_V_535, VAR_V_536, VAR_V_537, VAR_V_538, VAR_V_539, VAR_V_540X30] : (pred_attacker(tuple_C_out_6(VAR_V_529, VAR_V_530X30, VAR_V_531, VAR_V_532, VAR_V_533, VAR_V_534, VAR_V_535, VAR_V_536, VAR_V_537, VAR_V_538, VAR_V_539, VAR_V_540X30)) => pred_attacker(VAR_V_531))).
fof(ax166, axiom,
![VAR_V_542, VAR_V_543, VAR_V_544, VAR_V_545, VAR_V_546, VAR_V_547, VAR_V_548, VAR_V_549, VAR_V_550X30, VAR_V_551, VAR_V_552, VAR_V_553] : (pred_attacker(tuple_C_out_6(VAR_V_542, VAR_V_543, VAR_V_544, VAR_V_545, VAR_V_546, VAR_V_547, VAR_V_548, VAR_V_549, VAR_V_550X30, VAR_V_551, VAR_V_552, VAR_V_553)) => pred_attacker(VAR_V_545))).
fof(ax167, axiom,
![VAR_V_555, VAR_V_556, VAR_V_557, VAR_V_558, VAR_V_559, VAR_V_560X30, VAR_V_561, VAR_V_562, VAR_V_563, VAR_V_564, VAR_V_565, VAR_V_566] : (pred_attacker(tuple_C_out_6(VAR_V_555, VAR_V_556, VAR_V_557, VAR_V_558, VAR_V_559, VAR_V_560X30, VAR_V_561, VAR_V_562, VAR_V_563, VAR_V_564, VAR_V_565, VAR_V_566)) => pred_attacker(VAR_V_559))).
fof(ax168, axiom,
![VAR_V_568, VAR_V_569, VAR_V_570X30, VAR_V_571, VAR_V_572, VAR_V_573, VAR_V_574, VAR_V_575, VAR_V_576, VAR_V_577, VAR_V_578, VAR_V_579] : (pred_attacker(tuple_C_out_6(VAR_V_568, VAR_V_569, VAR_V_570X30, VAR_V_571, VAR_V_572, VAR_V_573, VAR_V_574, VAR_V_575, VAR_V_576, VAR_V_577, VAR_V_578, VAR_V_579)) => pred_attacker(VAR_V_573))).
fof(ax169, axiom,
![VAR_V_581, VAR_V_582, VAR_V_583, VAR_V_584, VAR_V_585, VAR_V_586, VAR_V_587, VAR_V_588, VAR_V_589, VAR_V_590X30, VAR_V_591, VAR_V_592] : (pred_attacker(tuple_C_out_6(VAR_V_581, VAR_V_582, VAR_V_583, VAR_V_584, VAR_V_585, VAR_V_586, VAR_V_587, VAR_V_588, VAR_V_589, VAR_V_590X30, VAR_V_591, VAR_V_592)) => pred_attacker(VAR_V_587))).
fof(ax170, axiom,
![VAR_V_594, VAR_V_595, VAR_V_596, VAR_V_597, VAR_V_598, VAR_V_599, VAR_V_60X300X30, VAR_V_60X301, VAR_V_60X302, VAR_V_60X303, VAR_V_60X304, VAR_V_60X305] : (pred_attacker(tuple_C_out_6(VAR_V_594, VAR_V_595, VAR_V_596, VAR_V_597, VAR_V_598, VAR_V_599, VAR_V_60X300X30, VAR_V_60X301, VAR_V_60X302, VAR_V_60X303, VAR_V_60X304, VAR_V_60X305)) => pred_attacker(VAR_V_60X301))).
fof(ax171, axiom,
![VAR_V_60X307, VAR_V_60X308, VAR_V_60X309, VAR_V_610X30, VAR_V_611, VAR_V_612, VAR_V_613, VAR_V_614, VAR_V_615, VAR_V_616, VAR_V_617, VAR_V_618] : (pred_attacker(tuple_C_out_6(VAR_V_60X307, VAR_V_60X308, VAR_V_60X309, VAR_V_610X30, VAR_V_611, VAR_V_612, VAR_V_613, VAR_V_614, VAR_V_615, VAR_V_616, VAR_V_617, VAR_V_618)) => pred_attacker(VAR_V_615))).
fof(ax172, axiom,
![VAR_V_620X30, VAR_V_621, VAR_V_622, VAR_V_623, VAR_V_624, VAR_V_625, VAR_V_626, VAR_V_627, VAR_V_628, VAR_V_629, VAR_V_630X30, VAR_V_631] : (pred_attacker(tuple_C_out_6(VAR_V_620X30, VAR_V_621, VAR_V_622, VAR_V_623, VAR_V_624, VAR_V_625, VAR_V_626, VAR_V_627, VAR_V_628, VAR_V_629, VAR_V_630X30, VAR_V_631)) => pred_attacker(VAR_V_629))).
fof(ax173, axiom,
![VAR_V_633, VAR_V_634, VAR_V_635, VAR_V_636, VAR_V_637, VAR_V_638, VAR_V_639, VAR_V_640X30, VAR_V_641, VAR_V_642, VAR_V_643, VAR_V_644] : (pred_attacker(tuple_C_out_6(VAR_V_633, VAR_V_634, VAR_V_635, VAR_V_636, VAR_V_637, VAR_V_638, VAR_V_639, VAR_V_640X30, VAR_V_641, VAR_V_642, VAR_V_643, VAR_V_644)) => pred_attacker(VAR_V_643))).
fof(ax174, axiom,
![VAR_V_646, VAR_V_647, VAR_V_648, VAR_V_649, VAR_V_650X30, VAR_V_651, VAR_V_652, VAR_V_653, VAR_V_654, VAR_V_655, VAR_V_656, VAR_V_657] : (pred_attacker(tuple_C_out_6(VAR_V_646, VAR_V_647, VAR_V_648, VAR_V_649, VAR_V_650X30, VAR_V_651, VAR_V_652, VAR_V_653, VAR_V_654, VAR_V_655, VAR_V_656, VAR_V_657)) => pred_attacker(VAR_V_657))).
fof(ax175, axiom,
![VAR_V_660X30] : (pred_attacker(VAR_V_660X30) => pred_attacker(tuple_C_out_5(VAR_V_660X30)))).
fof(ax176, axiom,
![VAR_V_663] : (pred_attacker(tuple_C_out_5(VAR_V_663)) => pred_attacker(VAR_V_663))).
fof(ax177, axiom,
![VAR_V_666] : (pred_attacker(VAR_V_666) => pred_attacker(tuple_C_out_3(VAR_V_666)))).
fof(ax178, axiom,
![VAR_V_669] : (pred_attacker(tuple_C_out_3(VAR_V_669)) => pred_attacker(VAR_V_669))).
fof(ax179, axiom,
![VAR_V_672] : (pred_attacker(VAR_V_672) => pred_attacker(tuple_C_out_2(VAR_V_672)))).
fof(ax180, axiom,
![VAR_V_675] : (pred_attacker(tuple_C_out_2(VAR_V_675)) => pred_attacker(VAR_V_675))).
fof(ax181, axiom,
![VAR_V_685, VAR_V_686, VAR_V_687, VAR_V_688, VAR_V_689, VAR_V_690X30, VAR_V_691, VAR_V_692] : ((pred_attacker(VAR_V_685) & pred_attacker(VAR_V_686) & pred_attacker(VAR_V_687) & pred_attacker(VAR_V_688) & pred_attacker(VAR_V_689) & pred_attacker(VAR_V_690X30) & pred_attacker(VAR_V_691) & pred_attacker(VAR_V_692)) => pred_attacker(tuple_C_in_4(VAR_V_685, VAR_V_686, VAR_V_687, VAR_V_688, VAR_V_689, VAR_V_690X30, VAR_V_691, VAR_V_692)))).
fof(ax182, axiom,
![VAR_V_765, VAR_V_766, VAR_V_767, VAR_V_768, VAR_V_769, VAR_V_770X30, VAR_V_771, VAR_V_772] : (pred_attacker(tuple_C_in_4(VAR_V_765, VAR_V_766, VAR_V_767, VAR_V_768, VAR_V_769, VAR_V_770X30, VAR_V_771, VAR_V_772)) => pred_attacker(VAR_V_765))).
fof(ax183, axiom,
![VAR_V_774, VAR_V_775, VAR_V_776, VAR_V_777, VAR_V_778, VAR_V_779, VAR_V_780X30, VAR_V_781] : (pred_attacker(tuple_C_in_4(VAR_V_774, VAR_V_775, VAR_V_776, VAR_V_777, VAR_V_778, VAR_V_779, VAR_V_780X30, VAR_V_781)) => pred_attacker(VAR_V_775))).
fof(ax184, axiom,
![VAR_V_783, VAR_V_784, VAR_V_785, VAR_V_786, VAR_V_787, VAR_V_788, VAR_V_789, VAR_V_790X30] : (pred_attacker(tuple_C_in_4(VAR_V_783, VAR_V_784, VAR_V_785, VAR_V_786, VAR_V_787, VAR_V_788, VAR_V_789, VAR_V_790X30)) => pred_attacker(VAR_V_785))).
fof(ax185, axiom,
![VAR_V_792, VAR_V_793, VAR_V_794, VAR_V_795, VAR_V_796, VAR_V_797, VAR_V_798, VAR_V_799] : (pred_attacker(tuple_C_in_4(VAR_V_792, VAR_V_793, VAR_V_794, VAR_V_795, VAR_V_796, VAR_V_797, VAR_V_798, VAR_V_799)) => pred_attacker(VAR_V_795))).
fof(ax186, axiom,
![VAR_V_80X301, VAR_V_80X302, VAR_V_80X303, VAR_V_80X304, VAR_V_80X305, VAR_V_80X306, VAR_V_80X307, VAR_V_80X308] : (pred_attacker(tuple_C_in_4(VAR_V_80X301, VAR_V_80X302, VAR_V_80X303, VAR_V_80X304, VAR_V_80X305, VAR_V_80X306, VAR_V_80X307, VAR_V_80X308)) => pred_attacker(VAR_V_80X305))).
fof(ax187, axiom,
![VAR_V_810X30, VAR_V_811, VAR_V_812, VAR_V_813, VAR_V_814, VAR_V_815, VAR_V_816, VAR_V_817] : (pred_attacker(tuple_C_in_4(VAR_V_810X30, VAR_V_811, VAR_V_812, VAR_V_813, VAR_V_814, VAR_V_815, VAR_V_816, VAR_V_817)) => pred_attacker(VAR_V_815))).
fof(ax188, axiom,
![VAR_V_819, VAR_V_820X30, VAR_V_821, VAR_V_822, VAR_V_823, VAR_V_824, VAR_V_825, VAR_V_826] : (pred_attacker(tuple_C_in_4(VAR_V_819, VAR_V_820X30, VAR_V_821, VAR_V_822, VAR_V_823, VAR_V_824, VAR_V_825, VAR_V_826)) => pred_attacker(VAR_V_825))).
fof(ax189, axiom,
![VAR_V_828, VAR_V_829, VAR_V_830X30, VAR_V_831, VAR_V_832, VAR_V_833, VAR_V_834, VAR_V_835] : (pred_attacker(tuple_C_in_4(VAR_V_828, VAR_V_829, VAR_V_830X30, VAR_V_831, VAR_V_832, VAR_V_833, VAR_V_834, VAR_V_835)) => pred_attacker(VAR_V_835))).
fof(ax190, axiom,
![VAR_V_839, VAR_V_840X30] : ((pred_attacker(VAR_V_839) & pred_attacker(VAR_V_840X30)) => pred_attacker(tuple_C_in_1(VAR_V_839, VAR_V_840X30)))).
fof(ax191, axiom,
![VAR_V_847, VAR_V_848] : (pred_attacker(tuple_C_in_1(VAR_V_847, VAR_V_848)) => pred_attacker(VAR_V_847))).
fof(ax192, axiom,
![VAR_V_850X30, VAR_V_851] : (pred_attacker(tuple_C_in_1(VAR_V_850X30, VAR_V_851)) => pred_attacker(VAR_V_851))).
fof(ax193, axiom,
pred_attacker(constr_CONST_4)).
fof(ax194, axiom,
pred_attacker(constr_CONST_3)).
fof(ax195, axiom,
pred_attacker(constr_CONST_2)).
fof(ax196, axiom,
pred_attacker(constr_CONST_1)).
fof(ax197, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax198, axiom,
![VAR_V_857, VAR_V_858, VAR_V_859, VAR_V_860X30] : ((pred_attacker(VAR_V_857) & pred_attacker(VAR_V_858) & pred_attacker(VAR_V_859) & pred_attacker(VAR_V_860X30)) => pred_attacker(tuple_B_out_4(VAR_V_857, VAR_V_858, VAR_V_859, VAR_V_860X30)))).
fof(ax199, axiom,
![VAR_V_881, VAR_V_882, VAR_V_883, VAR_V_884] : (pred_attacker(tuple_B_out_4(VAR_V_881, VAR_V_882, VAR_V_883, VAR_V_884)) => pred_attacker(VAR_V_881))).
fof(ax200, axiom,
![VAR_V_886, VAR_V_887, VAR_V_888, VAR_V_889] : (pred_attacker(tuple_B_out_4(VAR_V_886, VAR_V_887, VAR_V_888, VAR_V_889)) => pred_attacker(VAR_V_887))).
fof(ax201, axiom,
![VAR_V_891, VAR_V_892, VAR_V_893, VAR_V_894] : (pred_attacker(tuple_B_out_4(VAR_V_891, VAR_V_892, VAR_V_893, VAR_V_894)) => pred_attacker(VAR_V_893))).
fof(ax202, axiom,
![VAR_V_896, VAR_V_897, VAR_V_898, VAR_V_899] : (pred_attacker(tuple_B_out_4(VAR_V_896, VAR_V_897, VAR_V_898, VAR_V_899)) => pred_attacker(VAR_V_899))).
fof(ax203, axiom,
![VAR_V_90X302] : (pred_attacker(VAR_V_90X302) => pred_attacker(tuple_B_out_2(VAR_V_90X302)))).
fof(ax204, axiom,
![VAR_V_90X305] : (pred_attacker(tuple_B_out_2(VAR_V_90X305)) => pred_attacker(VAR_V_90X305))).
fof(ax205, axiom,
![VAR_V_919, VAR_V_920X30, VAR_V_921, VAR_V_922, VAR_V_923, VAR_V_924, VAR_V_925, VAR_V_926, VAR_V_927, VAR_V_928, VAR_V_929, VAR_V_930X30] : ((pred_attacker(VAR_V_919) & pred_attacker(VAR_V_920X30) & pred_attacker(VAR_V_921) & pred_attacker(VAR_V_922) & pred_attacker(VAR_V_923) & pred_attacker(VAR_V_924) & pred_attacker(VAR_V_925) & pred_attacker(VAR_V_926) & pred_attacker(VAR_V_927) & pred_attacker(VAR_V_928) & pred_attacker(VAR_V_929) & pred_attacker(VAR_V_930X30)) => pred_attacker(tuple_B_in_3(VAR_V_919, VAR_V_920X30, VAR_V_921, VAR_V_922, VAR_V_923, VAR_V_924, VAR_V_925, VAR_V_926, VAR_V_927, VAR_V_928, VAR_V_929, VAR_V_930X30)))).
fof(ax206, axiom,
![VAR_V_10X3087, VAR_V_10X3088, VAR_V_10X3089, VAR_V_10X3090X30, VAR_V_10X3091, VAR_V_10X3092, VAR_V_10X3093, VAR_V_10X3094, VAR_V_10X3095, VAR_V_10X3096, VAR_V_10X3097, VAR_V_10X3098] : (pred_attacker(tuple_B_in_3(VAR_V_10X3087, VAR_V_10X3088, VAR_V_10X3089, VAR_V_10X3090X30, VAR_V_10X3091, VAR_V_10X3092, VAR_V_10X3093, VAR_V_10X3094, VAR_V_10X3095, VAR_V_10X3096, VAR_V_10X3097, VAR_V_10X3098)) => pred_attacker(VAR_V_10X3087))).
fof(ax207, axiom,
![VAR_V_110X300X30, VAR_V_110X301, VAR_V_110X302, VAR_V_110X303, VAR_V_110X304, VAR_V_110X305, VAR_V_110X306, VAR_V_110X307, VAR_V_110X308, VAR_V_110X309, VAR_V_1110X30, VAR_V_1111] : (pred_attacker(tuple_B_in_3(VAR_V_110X300X30, VAR_V_110X301, VAR_V_110X302, VAR_V_110X303, VAR_V_110X304, VAR_V_110X305, VAR_V_110X306, VAR_V_110X307, VAR_V_110X308, VAR_V_110X309, VAR_V_1110X30, VAR_V_1111)) => pred_attacker(VAR_V_110X301))).
fof(ax208, axiom,
![VAR_V_1113, VAR_V_1114, VAR_V_1115, VAR_V_1116, VAR_V_1117, VAR_V_1118, VAR_V_1119, VAR_V_1120X30, VAR_V_1121, VAR_V_1122, VAR_V_1123, VAR_V_1124] : (pred_attacker(tuple_B_in_3(VAR_V_1113, VAR_V_1114, VAR_V_1115, VAR_V_1116, VAR_V_1117, VAR_V_1118, VAR_V_1119, VAR_V_1120X30, VAR_V_1121, VAR_V_1122, VAR_V_1123, VAR_V_1124)) => pred_attacker(VAR_V_1115))).
fof(ax209, axiom,
![VAR_V_1126, VAR_V_1127, VAR_V_1128, VAR_V_1129, VAR_V_1130X30, VAR_V_1131, VAR_V_1132, VAR_V_1133, VAR_V_1134, VAR_V_1135, VAR_V_1136, VAR_V_1137] : (pred_attacker(tuple_B_in_3(VAR_V_1126, VAR_V_1127, VAR_V_1128, VAR_V_1129, VAR_V_1130X30, VAR_V_1131, VAR_V_1132, VAR_V_1133, VAR_V_1134, VAR_V_1135, VAR_V_1136, VAR_V_1137)) => pred_attacker(VAR_V_1129))).
fof(ax210, axiom,
![VAR_V_1139, VAR_V_1140X30, VAR_V_1141, VAR_V_1142, VAR_V_1143, VAR_V_1144, VAR_V_1145, VAR_V_1146, VAR_V_1147, VAR_V_1148, VAR_V_1149, VAR_V_1150X30] : (pred_attacker(tuple_B_in_3(VAR_V_1139, VAR_V_1140X30, VAR_V_1141, VAR_V_1142, VAR_V_1143, VAR_V_1144, VAR_V_1145, VAR_V_1146, VAR_V_1147, VAR_V_1148, VAR_V_1149, VAR_V_1150X30)) => pred_attacker(VAR_V_1143))).
fof(ax211, axiom,
![VAR_V_1152, VAR_V_1153, VAR_V_1154, VAR_V_1155, VAR_V_1156, VAR_V_1157, VAR_V_1158, VAR_V_1159, VAR_V_1160X30, VAR_V_1161, VAR_V_1162, VAR_V_1163] : (pred_attacker(tuple_B_in_3(VAR_V_1152, VAR_V_1153, VAR_V_1154, VAR_V_1155, VAR_V_1156, VAR_V_1157, VAR_V_1158, VAR_V_1159, VAR_V_1160X30, VAR_V_1161, VAR_V_1162, VAR_V_1163)) => pred_attacker(VAR_V_1157))).
fof(ax212, axiom,
![VAR_V_1165, VAR_V_1166, VAR_V_1167, VAR_V_1168, VAR_V_1169, VAR_V_1170X30, VAR_V_1171, VAR_V_1172, VAR_V_1173, VAR_V_1174, VAR_V_1175, VAR_V_1176] : (pred_attacker(tuple_B_in_3(VAR_V_1165, VAR_V_1166, VAR_V_1167, VAR_V_1168, VAR_V_1169, VAR_V_1170X30, VAR_V_1171, VAR_V_1172, VAR_V_1173, VAR_V_1174, VAR_V_1175, VAR_V_1176)) => pred_attacker(VAR_V_1171))).
fof(ax213, axiom,
![VAR_V_1178, VAR_V_1179, VAR_V_1180X30, VAR_V_1181, VAR_V_1182, VAR_V_1183, VAR_V_1184, VAR_V_1185, VAR_V_1186, VAR_V_1187, VAR_V_1188, VAR_V_1189] : (pred_attacker(tuple_B_in_3(VAR_V_1178, VAR_V_1179, VAR_V_1180X30, VAR_V_1181, VAR_V_1182, VAR_V_1183, VAR_V_1184, VAR_V_1185, VAR_V_1186, VAR_V_1187, VAR_V_1188, VAR_V_1189)) => pred_attacker(VAR_V_1185))).
fof(ax214, axiom,
![VAR_V_1191, VAR_V_1192, VAR_V_1193, VAR_V_1194, VAR_V_1195, VAR_V_1196, VAR_V_1197, VAR_V_1198, VAR_V_1199, VAR_V_120X300X30, VAR_V_120X301, VAR_V_120X302] : (pred_attacker(tuple_B_in_3(VAR_V_1191, VAR_V_1192, VAR_V_1193, VAR_V_1194, VAR_V_1195, VAR_V_1196, VAR_V_1197, VAR_V_1198, VAR_V_1199, VAR_V_120X300X30, VAR_V_120X301, VAR_V_120X302)) => pred_attacker(VAR_V_1199))).
fof(ax215, axiom,
![VAR_V_120X304, VAR_V_120X305, VAR_V_120X306, VAR_V_120X307, VAR_V_120X308, VAR_V_120X309, VAR_V_1210X30, VAR_V_1211, VAR_V_1212, VAR_V_1213, VAR_V_1214, VAR_V_1215] : (pred_attacker(tuple_B_in_3(VAR_V_120X304, VAR_V_120X305, VAR_V_120X306, VAR_V_120X307, VAR_V_120X308, VAR_V_120X309, VAR_V_1210X30, VAR_V_1211, VAR_V_1212, VAR_V_1213, VAR_V_1214, VAR_V_1215)) => pred_attacker(VAR_V_1213))).
fof(ax216, axiom,
![VAR_V_1217, VAR_V_1218, VAR_V_1219, VAR_V_1220X30, VAR_V_1221, VAR_V_1222, VAR_V_1223, VAR_V_1224, VAR_V_1225, VAR_V_1226, VAR_V_1227, VAR_V_1228] : (pred_attacker(tuple_B_in_3(VAR_V_1217, VAR_V_1218, VAR_V_1219, VAR_V_1220X30, VAR_V_1221, VAR_V_1222, VAR_V_1223, VAR_V_1224, VAR_V_1225, VAR_V_1226, VAR_V_1227, VAR_V_1228)) => pred_attacker(VAR_V_1227))).
fof(ax217, axiom,
![VAR_V_1230X30, VAR_V_1231, VAR_V_1232, VAR_V_1233, VAR_V_1234, VAR_V_1235, VAR_V_1236, VAR_V_1237, VAR_V_1238, VAR_V_1239, VAR_V_1240X30, VAR_V_1241] : (pred_attacker(tuple_B_in_3(VAR_V_1230X30, VAR_V_1231, VAR_V_1232, VAR_V_1233, VAR_V_1234, VAR_V_1235, VAR_V_1236, VAR_V_1237, VAR_V_1238, VAR_V_1239, VAR_V_1240X30, VAR_V_1241)) => pred_attacker(VAR_V_1241))).
fof(ax218, axiom,
![VAR_V_1245, VAR_V_1246] : ((pred_attacker(VAR_V_1245) & pred_attacker(VAR_V_1246)) => pred_attacker(tuple_B_in_1(VAR_V_1245, VAR_V_1246)))).
fof(ax219, axiom,
![VAR_V_1253, VAR_V_1254] : (pred_attacker(tuple_B_in_1(VAR_V_1253, VAR_V_1254)) => pred_attacker(VAR_V_1253))).
fof(ax220, axiom,
![VAR_V_1256, VAR_V_1257] : (pred_attacker(tuple_B_in_1(VAR_V_1256, VAR_V_1257)) => pred_attacker(VAR_V_1257))).
fof(ax221, axiom,
![VAR_V_1260X30] : (pred_attacker(VAR_V_1260X30) => pred_attacker(tuple_A_out_1(VAR_V_1260X30)))).
fof(ax222, axiom,
![VAR_V_1263] : (pred_attacker(tuple_A_out_1(VAR_V_1263)) => pred_attacker(VAR_V_1263))).
fof(ax223, axiom,
![VAR_V_1269, VAR_V_1270X30, VAR_V_1271, VAR_V_1272] : ((pred_attacker(VAR_V_1269) & pred_attacker(VAR_V_1270X30) & pred_attacker(VAR_V_1271) & pred_attacker(VAR_V_1272)) => pred_attacker(tuple_A_in_2(VAR_V_1269, VAR_V_1270X30, VAR_V_1271, VAR_V_1272)))).
fof(ax224, axiom,
![VAR_V_1293, VAR_V_1294, VAR_V_1295, VAR_V_1296] : (pred_attacker(tuple_A_in_2(VAR_V_1293, VAR_V_1294, VAR_V_1295, VAR_V_1296)) => pred_attacker(VAR_V_1293))).
fof(ax225, axiom,
![VAR_V_1298, VAR_V_1299, VAR_V_130X300X30, VAR_V_130X301] : (pred_attacker(tuple_A_in_2(VAR_V_1298, VAR_V_1299, VAR_V_130X300X30, VAR_V_130X301)) => pred_attacker(VAR_V_1299))).
fof(ax226, axiom,
![VAR_V_130X303, VAR_V_130X304, VAR_V_130X305, VAR_V_130X306] : (pred_attacker(tuple_A_in_2(VAR_V_130X303, VAR_V_130X304, VAR_V_130X305, VAR_V_130X306)) => pred_attacker(VAR_V_130X305))).
fof(ax227, axiom,
![VAR_V_130X308, VAR_V_130X309, VAR_V_1310X30, VAR_V_1311] : (pred_attacker(tuple_A_in_2(VAR_V_130X308, VAR_V_130X309, VAR_V_1310X30, VAR_V_1311)) => pred_attacker(VAR_V_1311))).
fof(ax228, axiom,
![VAR_V_1321, VAR_V_1322, VAR_V_1323, VAR_V_1324] : ((pred_attacker(VAR_V_1321) & pred_attacker(VAR_V_1322) & pred_attacker(VAR_V_1323) & pred_attacker(VAR_V_1324)) => pred_attacker(tuple_4(VAR_V_1321, VAR_V_1322, VAR_V_1323, VAR_V_1324)))).
fof(ax229, axiom,
![VAR_V_1345, VAR_V_1346, VAR_V_1347, VAR_V_1348] : (pred_attacker(tuple_4(VAR_V_1345, VAR_V_1346, VAR_V_1347, VAR_V_1348)) => pred_attacker(VAR_V_1345))).
fof(ax230, axiom,
![VAR_V_1350X30, VAR_V_1351, VAR_V_1352, VAR_V_1353] : (pred_attacker(tuple_4(VAR_V_1350X30, VAR_V_1351, VAR_V_1352, VAR_V_1353)) => pred_attacker(VAR_V_1351))).
fof(ax231, axiom,
![VAR_V_1355, VAR_V_1356, VAR_V_1357, VAR_V_1358] : (pred_attacker(tuple_4(VAR_V_1355, VAR_V_1356, VAR_V_1357, VAR_V_1358)) => pred_attacker(VAR_V_1357))).
fof(ax232, axiom,
![VAR_V_1360X30, VAR_V_1361, VAR_V_1362, VAR_V_1363] : (pred_attacker(tuple_4(VAR_V_1360X30, VAR_V_1361, VAR_V_1362, VAR_V_1363)) => pred_attacker(VAR_V_1363))).
fof(ax233, axiom,
![VAR_V_1368, VAR_V_1369, VAR_V_1370X30] : ((pred_attacker(VAR_V_1368) & pred_attacker(VAR_V_1369) & pred_attacker(VAR_V_1370X30)) => pred_attacker(tuple_3(VAR_V_1368, VAR_V_1369, VAR_V_1370X30)))).
fof(ax234, axiom,
![VAR_V_1383, VAR_V_1384, VAR_V_1385] : (pred_attacker(tuple_3(VAR_V_1383, VAR_V_1384, VAR_V_1385)) => pred_attacker(VAR_V_1383))).
fof(ax235, axiom,
![VAR_V_1387, VAR_V_1388, VAR_V_1389] : (pred_attacker(tuple_3(VAR_V_1387, VAR_V_1388, VAR_V_1389)) => pred_attacker(VAR_V_1388))).
fof(ax236, axiom,
![VAR_V_1391, VAR_V_1392, VAR_V_1393] : (pred_attacker(tuple_3(VAR_V_1391, VAR_V_1392, VAR_V_1393)) => pred_attacker(VAR_V_1393))).
fof(ax237, axiom,
![VAR_V_1397, VAR_V_1398] : ((pred_attacker(VAR_V_1397) & pred_attacker(VAR_V_1398)) => pred_attacker(tuple_2(VAR_V_1397, VAR_V_1398)))).
fof(ax238, axiom,
![VAR_V_140X305, VAR_V_140X306] : (pred_attacker(tuple_2(VAR_V_140X305, VAR_V_140X306)) => pred_attacker(VAR_V_140X305))).
fof(ax239, axiom,
![VAR_V_140X308, VAR_V_140X309] : (pred_attacker(tuple_2(VAR_V_140X308, VAR_V_140X309)) => pred_attacker(VAR_V_140X309))).
fof(ax240, axiom,
![VAR_V_1416, VAR_V_1417, VAR_V_1418, VAR_V_1419, VAR_V_1420X30] : ((pred_attacker(VAR_V_1416) & pred_attacker(VAR_V_1417) & pred_attacker(VAR_V_1418) & pred_attacker(VAR_V_1419) & pred_attacker(VAR_V_1420X30)) => pred_attacker(tuple_5(VAR_V_1416, VAR_V_1417, VAR_V_1418, VAR_V_1419, VAR_V_1420X30)))).
fof(ax241, axiom,
![VAR_V_1451, VAR_V_1452, VAR_V_1453, VAR_V_1454, VAR_V_1455] : (pred_attacker(tuple_5(VAR_V_1451, VAR_V_1452, VAR_V_1453, VAR_V_1454, VAR_V_1455)) => pred_attacker(VAR_V_1451))).
fof(ax242, axiom,
![VAR_V_1457, VAR_V_1458, VAR_V_1459, VAR_V_1460X30, VAR_V_1461] : (pred_attacker(tuple_5(VAR_V_1457, VAR_V_1458, VAR_V_1459, VAR_V_1460X30, VAR_V_1461)) => pred_attacker(VAR_V_1458))).
fof(ax243, axiom,
![VAR_V_1463, VAR_V_1464, VAR_V_1465, VAR_V_1466, VAR_V_1467] : (pred_attacker(tuple_5(VAR_V_1463, VAR_V_1464, VAR_V_1465, VAR_V_1466, VAR_V_1467)) => pred_attacker(VAR_V_1465))).
fof(ax244, axiom,
![VAR_V_1469, VAR_V_1470X30, VAR_V_1471, VAR_V_1472, VAR_V_1473] : (pred_attacker(tuple_5(VAR_V_1469, VAR_V_1470X30, VAR_V_1471, VAR_V_1472, VAR_V_1473)) => pred_attacker(VAR_V_1472))).
fof(ax245, axiom,
![VAR_V_1475, VAR_V_1476, VAR_V_1477, VAR_V_1478, VAR_V_1479] : (pred_attacker(tuple_5(VAR_V_1475, VAR_V_1476, VAR_V_1477, VAR_V_1478, VAR_V_1479)) => pred_attacker(VAR_V_1479))).
fof(ax246, axiom,
![VAR_V_1482] : (pred_attacker(VAR_V_1482) => pred_attacker(tuple_1(VAR_V_1482)))).
fof(ax247, axiom,
![VAR_V_1485] : (pred_attacker(tuple_1(VAR_V_1485)) => pred_attacker(VAR_V_1485))).
fof(ax248, axiom,
![VAR_V_1487, VAR_V_1488] : ((pred_mess(VAR_V_1488, VAR_V_1487) & pred_attacker(VAR_V_1488)) => pred_attacker(VAR_V_1487))).
fof(ax249, axiom,
![VAR_V_1489, VAR_V_1490X30] : ((pred_attacker(VAR_V_1490X30) & pred_attacker(VAR_V_1489)) => pred_mess(VAR_V_1490X30, VAR_V_1489))).
fof(ax250, axiom,
pred_attacker(name_idS)).
fof(ax251, axiom,
pred_attacker(name_idC)).
fof(ax252, axiom,
pred_attacker(name_idB)).
fof(ax253, axiom,
pred_attacker(name_idA)).
fof(ax254, axiom,
pred_attacker(name_c)).
fof(ax255, axiom,
pred_attacker(name_Kcs)).
fof(ax256, axiom,
![VAR_V_1492] : (pred_equal(VAR_V_1492, VAR_V_1492))).
fof(ax257, axiom,
![VAR_V_1493] : (pred_attacker(name_new0x2Dname(VAR_V_1493)))).
fof(ax258, axiom,
pred_attacker(tuple_A_out_1(tuple_2(constr_h(constr_con3(name_idA, name_idB, name_Na), name_Kas), tuple_3(name_idA, name_idB, name_Na))))).
fof(ax259, axiom,
![VAR_NA_1766] : (pred_attacker(tuple_B_in_1(constr_h(constr_con3(name_idA, name_idB, VAR_NA_1766), name_Kas), tuple_3(name_idA, name_idB, VAR_NA_1766))) => pred_attacker(tuple_B_out_2(tuple_2(constr_h(constr_con4(name_idB, name_idC, name_Nb(VAR_NA_1766, name_idB, name_idA, constr_h(constr_con3(name_idA, name_idB, VAR_NA_1766), name_Kas)), constr_con4(constr_h(constr_con3(name_idA, name_idB, VAR_NA_1766), name_Kas), name_idA, name_idB, VAR_NA_1766)), name_Kbs), tuple_4(name_idB, name_idC, name_Nb(VAR_NA_1766, name_idB, name_idA, constr_h(constr_con3(name_idA, name_idB, VAR_NA_1766), name_Kas)), tuple_2(constr_h(constr_con3(name_idA, name_idB, VAR_NA_1766), name_Kas), tuple_3(name_idA, name_idB, VAR_NA_1766)))))))).
fof(ax260, axiom,
![VAR_NOUNCE1ST_20X3028, VAR_NOUNCE2ND_20X3030X30, VAR_HSH2ND_20X3029] : (pred_attacker(tuple_C_in_1(constr_h(constr_con4(name_idB, name_idC, VAR_NOUNCE1ST_20X3028, constr_con4(VAR_HSH2ND_20X3029, name_idA, name_idB, VAR_NOUNCE2ND_20X3030X30)), name_Kbc), tuple_4(name_idB, name_idC, VAR_NOUNCE1ST_20X3028, tuple_2(VAR_HSH2ND_20X3029, tuple_3(name_idA, name_idB, VAR_NOUNCE2ND_20X3030X30))))) => pred_attacker(tuple_C_out_2(name_Nc(VAR_NOUNCE2ND_20X3030X30, name_idB, name_idA, VAR_HSH2ND_20X3029, VAR_NOUNCE1ST_20X3028, name_idC, name_idB, constr_h(constr_con4(name_idB, name_idC, VAR_NOUNCE1ST_20X3028, constr_con4(VAR_HSH2ND_20X3029, name_idA, name_idB, VAR_NOUNCE2ND_20X3030X30)), name_Kbc)))))).
fof(ax261, axiom,
![VAR_NA_2180X30, VAR_NB_2178, VAR_HSH2ND_2179] : (pred_attacker(tuple_C_in_1(constr_h(constr_con4(name_idB, name_idC, VAR_NB_2178, constr_con4(VAR_HSH2ND_2179, name_idA, name_idB, VAR_NA_2180X30)), name_Kbc), tuple_4(name_idB, name_idC, VAR_NB_2178, tuple_2(VAR_HSH2ND_2179, tuple_3(name_idA, name_idB, VAR_NA_2180X30))))) => pred_attacker(tuple_C_out_3(tuple_2(constr_h(constr_con4(name_idC, name_idS, name_Nc(VAR_NA_2180X30, name_idB, name_idA, VAR_HSH2ND_2179, VAR_NB_2178, name_idC, name_idB, constr_h(constr_con4(name_idB, name_idC, VAR_NB_2178, constr_con4(VAR_HSH2ND_2179, name_idA, name_idB, VAR_NA_2180X30)), name_Kbc)), tuple_2(constr_h(constr_con4(name_idB, name_idC, VAR_NB_2178, constr_con4(VAR_HSH2ND_2179, name_idA, name_idB, VAR_NA_2180X30)), name_Kbc), tuple_4(name_idB, name_idC, VAR_NB_2178, tuple_2(VAR_HSH2ND_2179, tuple_3(name_idA, name_idB, VAR_NA_2180X30))))), name_Kcs), tuple_4(name_idC, name_idS, name_Nc(VAR_NA_2180X30, name_idB, name_idA, VAR_HSH2ND_2179, VAR_NB_2178, name_idC, name_idB, constr_h(constr_con4(name_idB, name_idC, VAR_NB_2178, constr_con4(VAR_HSH2ND_2179, name_idA, name_idB, VAR_NA_2180X30)), name_Kbc)), tuple_2(constr_h(constr_con4(name_idB, name_idC, VAR_NB_2178, constr_con4(VAR_HSH2ND_2179, name_idA, name_idB, VAR_NA_2180X30)), name_Kbc), tuple_4(name_idB, name_idC, VAR_NB_2178, tuple_2(VAR_HSH2ND_2179, tuple_3(name_idA, name_idB, VAR_NA_2180X30)))))))))).
fof(ax262, axiom,
![VAR_NA_2223, VAR_NB_2221, VAR_ENC_IDA_IDB_NA_KAB_2214, VAR_ENC_IDB_IDA_NB_KAB_2216, VAR_ENC_IDB_IDC_NB_KBC_2218, VAR_ENC_IDC_IDB_NC_KBC_2220X30, VAR_HSH2ND_2222, VAR_XOR_KAB_H_NA_KAS_2213, VAR_XOR_KAB_H_NB_KBS_2215, VAR_XOR_KBC_H_NB_KBS_2217, VAR_XOR_KBC_H_NC_KCS_2219] : ((pred_attacker(tuple_C_in_4(VAR_XOR_KAB_H_NA_KAS_2213, VAR_ENC_IDA_IDB_NA_KAB_2214, VAR_XOR_KAB_H_NB_KBS_2215, VAR_ENC_IDB_IDA_NB_KAB_2216, VAR_XOR_KBC_H_NB_KBS_2217, VAR_ENC_IDB_IDC_NB_KBC_2218, VAR_XOR_KBC_H_NC_KCS_2219, VAR_ENC_IDC_IDB_NC_KBC_2220X30)) & pred_attacker(tuple_C_in_1(constr_h(constr_con4(name_idB, name_idC, VAR_NB_2221, constr_con4(VAR_HSH2ND_2222, name_idA, name_idB, VAR_NA_2223)), name_Kbc), tuple_4(name_idB, name_idC, VAR_NB_2221, tuple_2(VAR_HSH2ND_2222, tuple_3(name_idA, name_idB, VAR_NA_2223)))))) => pred_attacker(tuple_C_out_5(constr_xor(VAR_XOR_KBC_H_NC_KCS_2219, constr_h(name_Nc(VAR_NA_2223, name_idB, name_idA, VAR_HSH2ND_2222, VAR_NB_2221, name_idC, name_idB, constr_h(constr_con4(name_idB, name_idC, VAR_NB_2221, constr_con4(VAR_HSH2ND_2222, name_idA, name_idB, VAR_NA_2223)), name_Kbc)), name_Kcs)))))).
fof(ax263, axiom,
![VAR_NA_2820X30, VAR_NB_2818, VAR_NC_2816, VAR_HSH2ND_2817, VAR_HSH3RD_2819] : (pred_attacker(tuple_S_in_1(constr_h(constr_con4(name_idC, name_idS, VAR_NC_2816, constr_con5(VAR_HSH2ND_2817, name_idB, name_idC, VAR_NB_2818, constr_con4(VAR_HSH3RD_2819, name_idA, name_idB, VAR_NA_2820X30))), name_Kcs), tuple_4(name_idC, name_idS, VAR_NC_2816, tuple_2(VAR_HSH2ND_2817, tuple_4(name_idB, name_idC, VAR_NB_2818, tuple_2(VAR_HSH3RD_2819, tuple_3(name_idA, name_idB, VAR_NA_2820X30))))))) => pred_attacker(tuple_S_out_2(constr_xor(name_Kab, constr_h(VAR_NA_2820X30, name_Kas)), constr_enc(constr_con3(name_idA, name_idB, VAR_NA_2820X30), name_Kab), constr_xor(name_Kab, constr_h(VAR_NB_2818, name_Kbs)), constr_enc(constr_con3(name_idB, name_idA, VAR_NB_2818), name_Kab), constr_xor(name_Kbc, constr_h(VAR_NB_2818, name_Kbs)), constr_enc(constr_con3(name_idB, name_idC, VAR_NB_2818), name_Kbc), constr_xor(name_Kbc, constr_h(VAR_NC_2816, name_Kcs)), constr_enc(constr_con3(name_idC, name_idB, VAR_NC_2816), name_Kbc))))).
fof(co0, conjecture,
pred_attacker(name_Kab)).
