%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_QUERY).
fof(ax5, axiom,
constr_CONST_0x30 != constr_R_STEP_1).
fof(ax6, axiom,
constr_CONST_0x30 != constr_R_STEP_2).
fof(ax7, axiom,
constr_CONST_0x30 != constr_R_STEP_3).
fof(ax8, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax9, axiom,
constr_CONST_0x30 != constr_sess_1_STEP_1).
fof(ax10, axiom,
constr_CONST_0x30 != constr_sess_1_STEP_2).
fof(ax11, axiom,
constr_CONST_0x30 != constr_sess_1_STEP_3).
fof(ax12, axiom,
constr_CONST_0x30 != name_ID).
fof(ax13, axiom,
constr_CONST_0x30 != name_c).
fof(ax14, axiom,
constr_CONST_0x30 != name_k).
fof(ax15, axiom,
constr_CONST_0x30 != name_objective).
fof(ax16, axiom,
constr_CONST_0x30 != name_r1).
fof(ax17, axiom,
constr_CONST_0x30 != name_r1_s1).
fof(ax18, axiom,
constr_CONST_0x30 != name_r2_s1).
fof(ax19, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax20, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax21, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax22, axiom,
constr_CONST_1 != constr_QUERY).
fof(ax23, axiom,
constr_CONST_1 != constr_R_STEP_1).
fof(ax24, axiom,
constr_CONST_1 != constr_R_STEP_2).
fof(ax25, axiom,
constr_CONST_1 != constr_R_STEP_3).
fof(ax26, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax27, axiom,
constr_CONST_1 != constr_sess_1_STEP_1).
fof(ax28, axiom,
constr_CONST_1 != constr_sess_1_STEP_2).
fof(ax29, axiom,
constr_CONST_1 != constr_sess_1_STEP_3).
fof(ax30, axiom,
constr_CONST_1 != name_ID).
fof(ax31, axiom,
constr_CONST_1 != name_c).
fof(ax32, axiom,
constr_CONST_1 != name_k).
fof(ax33, axiom,
constr_CONST_1 != name_objective).
fof(ax34, axiom,
constr_CONST_1 != name_r1).
fof(ax35, axiom,
constr_CONST_1 != name_r1_s1).
fof(ax36, axiom,
constr_CONST_1 != name_r2_s1).
fof(ax37, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax38, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax39, axiom,
constr_CONST_2 != constr_QUERY).
fof(ax40, axiom,
constr_CONST_2 != constr_R_STEP_1).
fof(ax41, axiom,
constr_CONST_2 != constr_R_STEP_2).
fof(ax42, axiom,
constr_CONST_2 != constr_R_STEP_3).
fof(ax43, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax44, axiom,
constr_CONST_2 != constr_sess_1_STEP_1).
fof(ax45, axiom,
constr_CONST_2 != constr_sess_1_STEP_2).
fof(ax46, axiom,
constr_CONST_2 != constr_sess_1_STEP_3).
fof(ax47, axiom,
constr_CONST_2 != name_ID).
fof(ax48, axiom,
constr_CONST_2 != name_c).
fof(ax49, axiom,
constr_CONST_2 != name_k).
fof(ax50, axiom,
constr_CONST_2 != name_objective).
fof(ax51, axiom,
constr_CONST_2 != name_r1).
fof(ax52, axiom,
constr_CONST_2 != name_r1_s1).
fof(ax53, axiom,
constr_CONST_2 != name_r2_s1).
fof(ax54, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax55, axiom,
constr_CONST_3 != constr_QUERY).
fof(ax56, axiom,
constr_CONST_3 != constr_R_STEP_1).
fof(ax57, axiom,
constr_CONST_3 != constr_R_STEP_2).
fof(ax58, axiom,
constr_CONST_3 != constr_R_STEP_3).
fof(ax59, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax60, axiom,
constr_CONST_3 != constr_sess_1_STEP_1).
fof(ax61, axiom,
constr_CONST_3 != constr_sess_1_STEP_2).
fof(ax62, axiom,
constr_CONST_3 != constr_sess_1_STEP_3).
fof(ax63, axiom,
constr_CONST_3 != name_ID).
fof(ax64, axiom,
constr_CONST_3 != name_c).
fof(ax65, axiom,
constr_CONST_3 != name_k).
fof(ax66, axiom,
constr_CONST_3 != name_objective).
fof(ax67, axiom,
constr_CONST_3 != name_r1).
fof(ax68, axiom,
constr_CONST_3 != name_r1_s1).
fof(ax69, axiom,
constr_CONST_3 != name_r2_s1).
fof(ax70, axiom,
constr_CONST_4 != constr_QUERY).
fof(ax71, axiom,
constr_CONST_4 != constr_R_STEP_1).
fof(ax72, axiom,
constr_CONST_4 != constr_R_STEP_2).
fof(ax73, axiom,
constr_CONST_4 != constr_R_STEP_3).
fof(ax74, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax75, axiom,
constr_CONST_4 != constr_sess_1_STEP_1).
fof(ax76, axiom,
constr_CONST_4 != constr_sess_1_STEP_2).
fof(ax77, axiom,
constr_CONST_4 != constr_sess_1_STEP_3).
fof(ax78, axiom,
constr_CONST_4 != name_ID).
fof(ax79, axiom,
constr_CONST_4 != name_c).
fof(ax80, axiom,
constr_CONST_4 != name_k).
fof(ax81, axiom,
constr_CONST_4 != name_objective).
fof(ax82, axiom,
constr_CONST_4 != name_r1).
fof(ax83, axiom,
constr_CONST_4 != name_r1_s1).
fof(ax84, axiom,
constr_CONST_4 != name_r2_s1).
fof(ax85, axiom,
constr_QUERY != constr_R_STEP_1).
fof(ax86, axiom,
constr_QUERY != constr_R_STEP_2).
fof(ax87, axiom,
constr_QUERY != constr_R_STEP_3).
fof(ax88, axiom,
constr_QUERY != constr_ZERO).
fof(ax89, axiom,
constr_QUERY != constr_sess_1_STEP_1).
fof(ax90, axiom,
constr_QUERY != constr_sess_1_STEP_2).
fof(ax91, axiom,
constr_QUERY != constr_sess_1_STEP_3).
fof(ax92, axiom,
constr_QUERY != name_ID).
fof(ax93, axiom,
constr_QUERY != name_c).
fof(ax94, axiom,
constr_QUERY != name_k).
fof(ax95, axiom,
constr_QUERY != name_objective).
fof(ax96, axiom,
constr_QUERY != name_r1).
fof(ax97, axiom,
constr_QUERY != name_r1_s1).
fof(ax98, axiom,
constr_QUERY != name_r2_s1).
fof(ax99, axiom,
constr_R_STEP_1 != constr_R_STEP_2).
fof(ax100, axiom,
constr_R_STEP_1 != constr_R_STEP_3).
fof(ax101, axiom,
constr_R_STEP_1 != constr_ZERO).
fof(ax102, axiom,
constr_R_STEP_1 != constr_sess_1_STEP_1).
fof(ax103, axiom,
constr_R_STEP_1 != constr_sess_1_STEP_2).
fof(ax104, axiom,
constr_R_STEP_1 != constr_sess_1_STEP_3).
fof(ax105, axiom,
constr_R_STEP_1 != name_ID).
fof(ax106, axiom,
constr_R_STEP_1 != name_c).
fof(ax107, axiom,
constr_R_STEP_1 != name_k).
fof(ax108, axiom,
constr_R_STEP_1 != name_objective).
fof(ax109, axiom,
constr_R_STEP_1 != name_r1).
fof(ax110, axiom,
constr_R_STEP_1 != name_r1_s1).
fof(ax111, axiom,
constr_R_STEP_1 != name_r2_s1).
fof(ax112, axiom,
constr_R_STEP_2 != constr_R_STEP_3).
fof(ax113, axiom,
constr_R_STEP_2 != constr_ZERO).
fof(ax114, axiom,
constr_R_STEP_2 != constr_sess_1_STEP_1).
fof(ax115, axiom,
constr_R_STEP_2 != constr_sess_1_STEP_2).
fof(ax116, axiom,
constr_R_STEP_2 != constr_sess_1_STEP_3).
fof(ax117, axiom,
constr_R_STEP_2 != name_ID).
fof(ax118, axiom,
constr_R_STEP_2 != name_c).
fof(ax119, axiom,
constr_R_STEP_2 != name_k).
fof(ax120, axiom,
constr_R_STEP_2 != name_objective).
fof(ax121, axiom,
constr_R_STEP_2 != name_r1).
fof(ax122, axiom,
constr_R_STEP_2 != name_r1_s1).
fof(ax123, axiom,
constr_R_STEP_2 != name_r2_s1).
fof(ax124, axiom,
constr_R_STEP_3 != constr_ZERO).
fof(ax125, axiom,
constr_R_STEP_3 != constr_sess_1_STEP_1).
fof(ax126, axiom,
constr_R_STEP_3 != constr_sess_1_STEP_2).
fof(ax127, axiom,
constr_R_STEP_3 != constr_sess_1_STEP_3).
fof(ax128, axiom,
constr_R_STEP_3 != name_ID).
fof(ax129, axiom,
constr_R_STEP_3 != name_c).
fof(ax130, axiom,
constr_R_STEP_3 != name_k).
fof(ax131, axiom,
constr_R_STEP_3 != name_objective).
fof(ax132, axiom,
constr_R_STEP_3 != name_r1).
fof(ax133, axiom,
constr_R_STEP_3 != name_r1_s1).
fof(ax134, axiom,
constr_R_STEP_3 != name_r2_s1).
fof(ax135, axiom,
constr_ZERO != constr_sess_1_STEP_1).
fof(ax136, axiom,
constr_ZERO != constr_sess_1_STEP_2).
fof(ax137, axiom,
constr_ZERO != constr_sess_1_STEP_3).
fof(ax138, axiom,
constr_ZERO != name_ID).
fof(ax139, axiom,
constr_ZERO != name_c).
fof(ax140, axiom,
constr_ZERO != name_k).
fof(ax141, axiom,
constr_ZERO != name_objective).
fof(ax142, axiom,
constr_ZERO != name_r1).
fof(ax143, axiom,
constr_ZERO != name_r1_s1).
fof(ax144, axiom,
constr_ZERO != name_r2_s1).
fof(ax145, axiom,
constr_sess_1_STEP_1 != constr_sess_1_STEP_2).
fof(ax146, axiom,
constr_sess_1_STEP_1 != constr_sess_1_STEP_3).
fof(ax147, axiom,
constr_sess_1_STEP_1 != name_ID).
fof(ax148, axiom,
constr_sess_1_STEP_1 != name_c).
fof(ax149, axiom,
constr_sess_1_STEP_1 != name_k).
fof(ax150, axiom,
constr_sess_1_STEP_1 != name_objective).
fof(ax151, axiom,
constr_sess_1_STEP_1 != name_r1).
fof(ax152, axiom,
constr_sess_1_STEP_1 != name_r1_s1).
fof(ax153, axiom,
constr_sess_1_STEP_1 != name_r2_s1).
fof(ax154, axiom,
constr_sess_1_STEP_2 != constr_sess_1_STEP_3).
fof(ax155, axiom,
constr_sess_1_STEP_2 != name_ID).
fof(ax156, axiom,
constr_sess_1_STEP_2 != name_c).
fof(ax157, axiom,
constr_sess_1_STEP_2 != name_k).
fof(ax158, axiom,
constr_sess_1_STEP_2 != name_objective).
fof(ax159, axiom,
constr_sess_1_STEP_2 != name_r1).
fof(ax160, axiom,
constr_sess_1_STEP_2 != name_r1_s1).
fof(ax161, axiom,
constr_sess_1_STEP_2 != name_r2_s1).
fof(ax162, axiom,
constr_sess_1_STEP_3 != name_ID).
fof(ax163, axiom,
constr_sess_1_STEP_3 != name_c).
fof(ax164, axiom,
constr_sess_1_STEP_3 != name_k).
fof(ax165, axiom,
constr_sess_1_STEP_3 != name_objective).
fof(ax166, axiom,
constr_sess_1_STEP_3 != name_r1).
fof(ax167, axiom,
constr_sess_1_STEP_3 != name_r1_s1).
fof(ax168, axiom,
constr_sess_1_STEP_3 != name_r2_s1).
fof(ax169, axiom,
name_ID != name_c).
fof(ax170, axiom,
name_ID != name_k).
fof(ax171, axiom,
name_ID != name_objective).
fof(ax172, axiom,
name_ID != name_r1).
fof(ax173, axiom,
name_ID != name_r1_s1).
fof(ax174, axiom,
name_ID != name_r2_s1).
fof(ax175, axiom,
name_c != name_k).
fof(ax176, axiom,
name_c != name_objective).
fof(ax177, axiom,
name_c != name_r1).
fof(ax178, axiom,
name_c != name_r1_s1).
fof(ax179, axiom,
name_c != name_r2_s1).
fof(ax180, axiom,
name_k != name_objective).
fof(ax181, axiom,
name_k != name_r1).
fof(ax182, axiom,
name_k != name_r1_s1).
fof(ax183, axiom,
name_k != name_r2_s1).
fof(ax184, axiom,
name_objective != name_r1).
fof(ax185, axiom,
name_objective != name_r1_s1).
fof(ax186, axiom,
name_objective != name_r2_s1).
fof(ax187, axiom,
name_r1 != name_r1_s1).
fof(ax188, axiom,
name_r1 != name_r2_s1).
fof(ax189, axiom,
name_r1_s1 != name_r2_s1).
fof(ax190, axiom,
![VAR_X_11] : (constr_xor(VAR_X_11, VAR_X_11) = constr_ZERO)).
fof(ax191, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, constr_ZERO) = VAR_X_10X30)).
fof(ax192, axiom,
![VAR_X_8, VAR_Y_9] : (constr_xor(VAR_X_8, VAR_Y_9) = constr_xor(VAR_Y_9, VAR_X_8))).
fof(ax193, axiom,
![VAR_X_7, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_7, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_7, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax194, axiom,
![VAR_X_26] : (pred_eq(VAR_X_26, VAR_X_26))).
fof(ax195, axiom,
![VAR_V_33, VAR_V_34] : ((pred_attacker(VAR_V_33) & pred_attacker(VAR_V_34)) => pred_attacker(constr_xor(VAR_V_33, VAR_V_34)))).
fof(ax196, axiom,
pred_attacker(tuple_true)).
fof(ax197, axiom,
![VAR_V_36] : (pred_attacker(VAR_V_36) => pred_attacker(constr_split_R(VAR_V_36)))).
fof(ax198, axiom,
![VAR_V_38] : (pred_attacker(VAR_V_38) => pred_attacker(constr_split_L(VAR_V_38)))).
fof(ax199, axiom,
pred_attacker(constr_sess_1_STEP_3)).
fof(ax200, axiom,
pred_attacker(constr_sess_1_STEP_2)).
fof(ax201, axiom,
pred_attacker(constr_sess_1_STEP_1)).
fof(ax202, axiom,
![VAR_V_41, VAR_V_42] : ((pred_attacker(VAR_V_41) & pred_attacker(VAR_V_42)) => pred_attacker(constr_rotate(VAR_V_41, VAR_V_42)))).
fof(ax203, axiom,
![VAR_V_45] : (pred_attacker(VAR_V_45) => pred_attacker(constr_h(VAR_V_45)))).
fof(ax204, axiom,
pred_attacker(tuple_false)).
fof(ax205, axiom,
pred_attacker(constr_ZERO)).
fof(ax206, axiom,
pred_attacker(constr_R_STEP_3)).
fof(ax207, axiom,
pred_attacker(constr_R_STEP_2)).
fof(ax208, axiom,
pred_attacker(constr_R_STEP_1)).
fof(ax209, axiom,
pred_attacker(constr_QUERY)).
fof(ax210, axiom,
pred_attacker(constr_CONST_4)).
fof(ax211, axiom,
pred_attacker(constr_CONST_3)).
fof(ax212, axiom,
pred_attacker(constr_CONST_2)).
fof(ax213, axiom,
pred_attacker(constr_CONST_1)).
fof(ax214, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax215, axiom,
![VAR_V_52, VAR_V_53] : ((pred_attacker(VAR_V_52) & pred_attacker(VAR_V_53)) => pred_attacker(tuple_2(VAR_V_52, VAR_V_53)))).
fof(ax216, axiom,
![VAR_V_60X30, VAR_V_61] : (pred_attacker(tuple_2(VAR_V_60X30, VAR_V_61)) => pred_attacker(VAR_V_60X30))).
fof(ax217, axiom,
![VAR_V_63, VAR_V_64] : (pred_attacker(tuple_2(VAR_V_63, VAR_V_64)) => pred_attacker(VAR_V_64))).
fof(ax218, axiom,
![VAR_V_66, VAR_V_67] : ((pred_mess(VAR_V_67, VAR_V_66) & pred_attacker(VAR_V_67)) => pred_attacker(VAR_V_66))).
fof(ax219, axiom,
![VAR_V_68, VAR_V_69] : ((pred_attacker(VAR_V_69) & pred_attacker(VAR_V_68)) => pred_mess(VAR_V_69, VAR_V_68))).
fof(ax220, axiom,
pred_attacker(name_c)).
fof(ax221, axiom,
![VAR_V_71] : (pred_equal(VAR_V_71, VAR_V_71))).
fof(ax222, axiom,
![VAR_V_72] : (pred_attacker(name_new0x2Dname(VAR_V_72)))).
fof(ax223, axiom,
pred_attacker(tuple_2(name_r1_s1, constr_sess_1_STEP_1))).
fof(ax224, axiom,
pred_attacker(tuple_2(tuple_2(name_r2_s1, constr_split_L(constr_xor(constr_rotate(name_ID, constr_h(constr_xor(constr_xor(name_r1_s1, name_r2_s1), name_k))), constr_h(constr_xor(constr_xor(name_r1_s1, name_r2_s1), name_k))))), constr_sess_1_STEP_2))).
fof(ax225, axiom,
pred_attacker(tuple_2(constr_split_R(constr_xor(constr_rotate(name_ID, constr_h(constr_xor(constr_xor(name_r1_s1, name_r2_s1), name_k))), constr_h(constr_xor(constr_xor(name_r1_s1, name_r2_s1), name_k)))), constr_sess_1_STEP_3))).
fof(ax226, axiom,
pred_attacker(tuple_2(tuple_2(constr_QUERY, name_r1), constr_R_STEP_1))).
fof(ax227, axiom,
![VAR_R2_281] : (pred_attacker(tuple_2(VAR_R2_281, constr_split_L(constr_xor(constr_rotate(name_ID, constr_h(constr_xor(constr_xor(name_r1, VAR_R2_281), name_k))), constr_h(constr_xor(constr_xor(name_r1, VAR_R2_281), name_k)))))) => pred_attacker(tuple_2(constr_split_R(constr_xor(constr_rotate(name_ID, constr_h(constr_xor(constr_xor(name_r1, VAR_R2_281), name_k))), constr_h(constr_xor(constr_xor(name_r1, VAR_R2_281), name_k)))), constr_R_STEP_2)))).
fof(ax228, axiom,
![VAR_R2_293] : (pred_attacker(tuple_2(VAR_R2_293, constr_split_L(constr_xor(constr_rotate(name_ID, constr_h(constr_xor(constr_xor(name_r1, VAR_R2_293), name_k))), constr_h(constr_xor(constr_xor(name_r1, VAR_R2_293), name_k)))))) => pred_attacker(tuple_2(name_objective, constr_R_STEP_3)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
