%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_QUERY).
fof(ax5, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax6, axiom,
constr_CONST_0x30 != name_ID).
fof(ax7, axiom,
constr_CONST_0x30 != name_c).
fof(ax8, axiom,
constr_CONST_0x30 != name_k).
fof(ax9, axiom,
constr_CONST_0x30 != name_objective).
fof(ax10, axiom,
constr_CONST_0x30 != name_r1).
fof(ax11, axiom,
constr_CONST_0x30 != name_r1_s1).
fof(ax12, axiom,
constr_CONST_0x30 != name_r2_s1).
fof(ax13, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax14, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax15, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax16, axiom,
constr_CONST_1 != constr_QUERY).
fof(ax17, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax18, axiom,
constr_CONST_1 != name_ID).
fof(ax19, axiom,
constr_CONST_1 != name_c).
fof(ax20, axiom,
constr_CONST_1 != name_k).
fof(ax21, axiom,
constr_CONST_1 != name_objective).
fof(ax22, axiom,
constr_CONST_1 != name_r1).
fof(ax23, axiom,
constr_CONST_1 != name_r1_s1).
fof(ax24, axiom,
constr_CONST_1 != name_r2_s1).
fof(ax25, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax26, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax27, axiom,
constr_CONST_2 != constr_QUERY).
fof(ax28, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax29, axiom,
constr_CONST_2 != name_ID).
fof(ax30, axiom,
constr_CONST_2 != name_c).
fof(ax31, axiom,
constr_CONST_2 != name_k).
fof(ax32, axiom,
constr_CONST_2 != name_objective).
fof(ax33, axiom,
constr_CONST_2 != name_r1).
fof(ax34, axiom,
constr_CONST_2 != name_r1_s1).
fof(ax35, axiom,
constr_CONST_2 != name_r2_s1).
fof(ax36, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax37, axiom,
constr_CONST_3 != constr_QUERY).
fof(ax38, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax39, axiom,
constr_CONST_3 != name_ID).
fof(ax40, axiom,
constr_CONST_3 != name_c).
fof(ax41, axiom,
constr_CONST_3 != name_k).
fof(ax42, axiom,
constr_CONST_3 != name_objective).
fof(ax43, axiom,
constr_CONST_3 != name_r1).
fof(ax44, axiom,
constr_CONST_3 != name_r1_s1).
fof(ax45, axiom,
constr_CONST_3 != name_r2_s1).
fof(ax46, axiom,
constr_CONST_4 != constr_QUERY).
fof(ax47, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax48, axiom,
constr_CONST_4 != name_ID).
fof(ax49, axiom,
constr_CONST_4 != name_c).
fof(ax50, axiom,
constr_CONST_4 != name_k).
fof(ax51, axiom,
constr_CONST_4 != name_objective).
fof(ax52, axiom,
constr_CONST_4 != name_r1).
fof(ax53, axiom,
constr_CONST_4 != name_r1_s1).
fof(ax54, axiom,
constr_CONST_4 != name_r2_s1).
fof(ax55, axiom,
constr_QUERY != constr_ZERO).
fof(ax56, axiom,
constr_QUERY != name_ID).
fof(ax57, axiom,
constr_QUERY != name_c).
fof(ax58, axiom,
constr_QUERY != name_k).
fof(ax59, axiom,
constr_QUERY != name_objective).
fof(ax60, axiom,
constr_QUERY != name_r1).
fof(ax61, axiom,
constr_QUERY != name_r1_s1).
fof(ax62, axiom,
constr_QUERY != name_r2_s1).
fof(ax63, axiom,
constr_ZERO != name_ID).
fof(ax64, axiom,
constr_ZERO != name_c).
fof(ax65, axiom,
constr_ZERO != name_k).
fof(ax66, axiom,
constr_ZERO != name_objective).
fof(ax67, axiom,
constr_ZERO != name_r1).
fof(ax68, axiom,
constr_ZERO != name_r1_s1).
fof(ax69, axiom,
constr_ZERO != name_r2_s1).
fof(ax70, axiom,
name_ID != name_c).
fof(ax71, axiom,
name_ID != name_k).
fof(ax72, axiom,
name_ID != name_objective).
fof(ax73, axiom,
name_ID != name_r1).
fof(ax74, axiom,
name_ID != name_r1_s1).
fof(ax75, axiom,
name_ID != name_r2_s1).
fof(ax76, axiom,
name_c != name_k).
fof(ax77, axiom,
name_c != name_objective).
fof(ax78, axiom,
name_c != name_r1).
fof(ax79, axiom,
name_c != name_r1_s1).
fof(ax80, axiom,
name_c != name_r2_s1).
fof(ax81, axiom,
name_k != name_objective).
fof(ax82, axiom,
name_k != name_r1).
fof(ax83, axiom,
name_k != name_r1_s1).
fof(ax84, axiom,
name_k != name_r2_s1).
fof(ax85, axiom,
name_objective != name_r1).
fof(ax86, axiom,
name_objective != name_r1_s1).
fof(ax87, axiom,
name_objective != name_r2_s1).
fof(ax88, axiom,
name_r1 != name_r1_s1).
fof(ax89, axiom,
name_r1 != name_r2_s1).
fof(ax90, axiom,
name_r1_s1 != name_r2_s1).
fof(ax91, axiom,
![VAR_X_11] : (constr_xor(VAR_X_11, VAR_X_11) = constr_ZERO)).
fof(ax92, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, constr_ZERO) = VAR_X_10X30)).
fof(ax93, axiom,
![VAR_X_8, VAR_Y_9] : (constr_xor(VAR_X_8, VAR_Y_9) = constr_xor(VAR_Y_9, VAR_X_8))).
fof(ax94, axiom,
![VAR_X_7, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_7, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_7, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax95, axiom,
![VAR_X_26] : (pred_eq(VAR_X_26, VAR_X_26))).
fof(ax96, axiom,
![VAR_V_33, VAR_V_34] : ((pred_attacker(VAR_V_33) & pred_attacker(VAR_V_34)) => pred_attacker(constr_xor(VAR_V_33, VAR_V_34)))).
fof(ax97, axiom,
pred_attacker(tuple_true)).
fof(ax98, axiom,
![VAR_V_36] : (pred_attacker(VAR_V_36) => pred_attacker(constr_split_R(VAR_V_36)))).
fof(ax99, axiom,
![VAR_V_38] : (pred_attacker(VAR_V_38) => pred_attacker(constr_split_L(VAR_V_38)))).
fof(ax100, axiom,
![VAR_V_41, VAR_V_42] : ((pred_attacker(VAR_V_41) & pred_attacker(VAR_V_42)) => pred_attacker(constr_rotate(VAR_V_41, VAR_V_42)))).
fof(ax101, axiom,
![VAR_V_45] : (pred_attacker(VAR_V_45) => pred_attacker(constr_h(VAR_V_45)))).
fof(ax102, axiom,
pred_attacker(tuple_false)).
fof(ax103, axiom,
pred_attacker(constr_ZERO)).
fof(ax104, axiom,
pred_attacker(constr_QUERY)).
fof(ax105, axiom,
pred_attacker(constr_CONST_4)).
fof(ax106, axiom,
pred_attacker(constr_CONST_3)).
fof(ax107, axiom,
pred_attacker(constr_CONST_2)).
fof(ax108, axiom,
pred_attacker(constr_CONST_1)).
fof(ax109, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax110, axiom,
![VAR_V_52, VAR_V_53] : ((pred_attacker(VAR_V_52) & pred_attacker(VAR_V_53)) => pred_attacker(tuple_2(VAR_V_52, VAR_V_53)))).
fof(ax111, axiom,
![VAR_V_60X30, VAR_V_61] : (pred_attacker(tuple_2(VAR_V_60X30, VAR_V_61)) => pred_attacker(VAR_V_60X30))).
fof(ax112, axiom,
![VAR_V_63, VAR_V_64] : (pred_attacker(tuple_2(VAR_V_63, VAR_V_64)) => pred_attacker(VAR_V_64))).
fof(ax113, axiom,
![VAR_V_66, VAR_V_67] : ((pred_mess(VAR_V_67, VAR_V_66) & pred_attacker(VAR_V_67)) => pred_attacker(VAR_V_66))).
fof(ax114, axiom,
![VAR_V_68, VAR_V_69] : ((pred_attacker(VAR_V_69) & pred_attacker(VAR_V_68)) => pred_mess(VAR_V_69, VAR_V_68))).
fof(ax115, axiom,
pred_attacker(name_c)).
fof(ax116, axiom,
![VAR_V_71] : (pred_equal(VAR_V_71, VAR_V_71))).
fof(ax117, axiom,
![VAR_V_72] : (pred_attacker(name_new0x2Dname(VAR_V_72)))).
fof(ax118, axiom,
pred_attacker(name_r1_s1)).
fof(ax119, axiom,
pred_attacker(tuple_2(name_r2_s1, constr_split_L(constr_xor(constr_rotate(name_ID, constr_h(constr_xor(constr_xor(name_r1_s1, name_r2_s1), name_k))), constr_h(constr_xor(constr_xor(name_r1_s1, name_r2_s1), name_k))))))).
fof(ax120, axiom,
pred_attacker(constr_split_R(constr_xor(constr_rotate(name_ID, constr_h(constr_xor(constr_xor(name_r1_s1, name_r2_s1), name_k))), constr_h(constr_xor(constr_xor(name_r1_s1, name_r2_s1), name_k)))))).
fof(ax121, axiom,
pred_attacker(tuple_2(constr_QUERY, name_r1))).
fof(ax122, axiom,
![VAR_R2_233] : (pred_attacker(tuple_2(VAR_R2_233, constr_split_L(constr_xor(constr_rotate(name_ID, constr_h(constr_xor(constr_xor(name_r1, VAR_R2_233), name_k))), constr_h(constr_xor(constr_xor(name_r1, VAR_R2_233), name_k)))))) => pred_attacker(constr_split_R(constr_xor(constr_rotate(name_ID, constr_h(constr_xor(constr_xor(name_r1, VAR_R2_233), name_k))), constr_h(constr_xor(constr_xor(name_r1, VAR_R2_233), name_k))))))).
fof(ax123, axiom,
![VAR_R2_235] : (pred_attacker(tuple_2(VAR_R2_235, constr_split_L(constr_xor(constr_rotate(name_ID, constr_h(constr_xor(constr_xor(name_r1, VAR_R2_235), name_k))), constr_h(constr_xor(constr_xor(name_r1, VAR_R2_235), name_k)))))) => pred_attacker(name_objective))).
fof(co0, conjecture,
pred_attacker(name_objective)).
