%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_client_B_STEP_1).
fof(ax5, axiom,
constr_CONST_0x30 != constr_server_S_STEP_1).
fof(ax6, axiom,
constr_CONST_0x30 != constr_server_S_STEP_2).
fof(ax7, axiom,
constr_CONST_0x30 != name_A).
fof(ax8, axiom,
constr_CONST_0x30 != name_B).
fof(ax9, axiom,
constr_CONST_0x30 != name_I).
fof(ax10, axiom,
constr_CONST_0x30 != name_Kas).
fof(ax11, axiom,
constr_CONST_0x30 != name_Kbs).
fof(ax12, axiom,
constr_CONST_0x30 != name_c).
fof(ax13, axiom,
constr_CONST_0x30 != name_objective).
fof(ax14, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax15, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax16, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax17, axiom,
constr_CONST_1 != constr_client_B_STEP_1).
fof(ax18, axiom,
constr_CONST_1 != constr_server_S_STEP_1).
fof(ax19, axiom,
constr_CONST_1 != constr_server_S_STEP_2).
fof(ax20, axiom,
constr_CONST_1 != name_A).
fof(ax21, axiom,
constr_CONST_1 != name_B).
fof(ax22, axiom,
constr_CONST_1 != name_I).
fof(ax23, axiom,
constr_CONST_1 != name_Kas).
fof(ax24, axiom,
constr_CONST_1 != name_Kbs).
fof(ax25, axiom,
constr_CONST_1 != name_c).
fof(ax26, axiom,
constr_CONST_1 != name_objective).
fof(ax27, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax28, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax29, axiom,
constr_CONST_2 != constr_client_B_STEP_1).
fof(ax30, axiom,
constr_CONST_2 != constr_server_S_STEP_1).
fof(ax31, axiom,
constr_CONST_2 != constr_server_S_STEP_2).
fof(ax32, axiom,
constr_CONST_2 != name_A).
fof(ax33, axiom,
constr_CONST_2 != name_B).
fof(ax34, axiom,
constr_CONST_2 != name_I).
fof(ax35, axiom,
constr_CONST_2 != name_Kas).
fof(ax36, axiom,
constr_CONST_2 != name_Kbs).
fof(ax37, axiom,
constr_CONST_2 != name_c).
fof(ax38, axiom,
constr_CONST_2 != name_objective).
fof(ax39, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax40, axiom,
constr_CONST_3 != constr_client_B_STEP_1).
fof(ax41, axiom,
constr_CONST_3 != constr_server_S_STEP_1).
fof(ax42, axiom,
constr_CONST_3 != constr_server_S_STEP_2).
fof(ax43, axiom,
constr_CONST_3 != name_A).
fof(ax44, axiom,
constr_CONST_3 != name_B).
fof(ax45, axiom,
constr_CONST_3 != name_I).
fof(ax46, axiom,
constr_CONST_3 != name_Kas).
fof(ax47, axiom,
constr_CONST_3 != name_Kbs).
fof(ax48, axiom,
constr_CONST_3 != name_c).
fof(ax49, axiom,
constr_CONST_3 != name_objective).
fof(ax50, axiom,
constr_CONST_4 != constr_client_B_STEP_1).
fof(ax51, axiom,
constr_CONST_4 != constr_server_S_STEP_1).
fof(ax52, axiom,
constr_CONST_4 != constr_server_S_STEP_2).
fof(ax53, axiom,
constr_CONST_4 != name_A).
fof(ax54, axiom,
constr_CONST_4 != name_B).
fof(ax55, axiom,
constr_CONST_4 != name_I).
fof(ax56, axiom,
constr_CONST_4 != name_Kas).
fof(ax57, axiom,
constr_CONST_4 != name_Kbs).
fof(ax58, axiom,
constr_CONST_4 != name_c).
fof(ax59, axiom,
constr_CONST_4 != name_objective).
fof(ax60, axiom,
constr_client_B_STEP_1 != constr_server_S_STEP_1).
fof(ax61, axiom,
constr_client_B_STEP_1 != constr_server_S_STEP_2).
fof(ax62, axiom,
constr_client_B_STEP_1 != name_A).
fof(ax63, axiom,
constr_client_B_STEP_1 != name_B).
fof(ax64, axiom,
constr_client_B_STEP_1 != name_I).
fof(ax65, axiom,
constr_client_B_STEP_1 != name_Kas).
fof(ax66, axiom,
constr_client_B_STEP_1 != name_Kbs).
fof(ax67, axiom,
constr_client_B_STEP_1 != name_c).
fof(ax68, axiom,
constr_client_B_STEP_1 != name_objective).
fof(ax69, axiom,
constr_server_S_STEP_1 != constr_server_S_STEP_2).
fof(ax70, axiom,
constr_server_S_STEP_1 != name_A).
fof(ax71, axiom,
constr_server_S_STEP_1 != name_B).
fof(ax72, axiom,
constr_server_S_STEP_1 != name_I).
fof(ax73, axiom,
constr_server_S_STEP_1 != name_Kas).
fof(ax74, axiom,
constr_server_S_STEP_1 != name_Kbs).
fof(ax75, axiom,
constr_server_S_STEP_1 != name_c).
fof(ax76, axiom,
constr_server_S_STEP_1 != name_objective).
fof(ax77, axiom,
constr_server_S_STEP_2 != name_A).
fof(ax78, axiom,
constr_server_S_STEP_2 != name_B).
fof(ax79, axiom,
constr_server_S_STEP_2 != name_I).
fof(ax80, axiom,
constr_server_S_STEP_2 != name_Kas).
fof(ax81, axiom,
constr_server_S_STEP_2 != name_Kbs).
fof(ax82, axiom,
constr_server_S_STEP_2 != name_c).
fof(ax83, axiom,
constr_server_S_STEP_2 != name_objective).
fof(ax84, axiom,
name_A != name_B).
fof(ax85, axiom,
name_A != name_I).
fof(ax86, axiom,
name_A != name_Kas).
fof(ax87, axiom,
name_A != name_Kbs).
fof(ax88, axiom,
name_A != name_c).
fof(ax89, axiom,
name_A != name_objective).
fof(ax90, axiom,
name_B != name_I).
fof(ax91, axiom,
name_B != name_Kas).
fof(ax92, axiom,
name_B != name_Kbs).
fof(ax93, axiom,
name_B != name_c).
fof(ax94, axiom,
name_B != name_objective).
fof(ax95, axiom,
name_I != name_Kas).
fof(ax96, axiom,
name_I != name_Kbs).
fof(ax97, axiom,
name_I != name_c).
fof(ax98, axiom,
name_I != name_objective).
fof(ax99, axiom,
name_Kas != name_Kbs).
fof(ax100, axiom,
name_Kas != name_c).
fof(ax101, axiom,
name_Kas != name_objective).
fof(ax102, axiom,
name_Kbs != name_c).
fof(ax103, axiom,
name_Kbs != name_objective).
fof(ax104, axiom,
name_c != name_objective).
fof(ax105, axiom,
![VAR_K_50X30, VAR_X0X30_46, VAR_X1_47, VAR_X2_48, VAR_X3_49] : (constr_cbc_dec_4(constr_cbc_enc_4(VAR_X0X30_46, VAR_X1_47, VAR_X2_48, VAR_X3_49, VAR_K_50X30), VAR_K_50X30) = tuple_4(VAR_X0X30_46, VAR_X1_47, VAR_X2_48, VAR_X3_49))).
fof(ax106, axiom,
![VAR_K_45, VAR_X0X30_42, VAR_X1_43, VAR_X2_44] : (constr_cbc_dec_3(constr_cbc_enc_3(VAR_X0X30_42, VAR_X1_43, VAR_X2_44, VAR_K_45), VAR_K_45) = tuple_3(VAR_X0X30_42, VAR_X1_43, VAR_X2_44))).
fof(ax107, axiom,
![VAR_K_41, VAR_X0X30_39, VAR_X1_40X30] : (constr_cbc_dec_2(constr_cbc_enc_2(VAR_X0X30_39, VAR_X1_40X30, VAR_K_41), VAR_K_41) = tuple_2(VAR_X0X30_39, VAR_X1_40X30))).
fof(ax108, axiom,
![VAR_K_38, VAR_X0X30_37] : (constr_cbc_dec_1(constr_cbc_enc_1(VAR_X0X30_37, VAR_K_38), VAR_K_38) = VAR_X0X30_37)).
fof(ax109, axiom,
![VAR_K_36, VAR_X0X30_32, VAR_X1_33, VAR_X2_34, VAR_X3_35] : (constr_cbc_4_get_3_prefixes(constr_cbc_enc_4(VAR_X0X30_32, VAR_X1_33, VAR_X2_34, VAR_X3_35, VAR_K_36)) = constr_cbc_enc_3(VAR_X0X30_32, VAR_X1_33, VAR_X2_34, VAR_K_36))).
fof(ax110, axiom,
![VAR_K_31, VAR_X0X30_27, VAR_X1_28, VAR_X2_29, VAR_X3_30X30] : (constr_cbc_4_get_2_prefixes(constr_cbc_enc_4(VAR_X0X30_27, VAR_X1_28, VAR_X2_29, VAR_X3_30X30, VAR_K_31)) = constr_cbc_enc_2(VAR_X0X30_27, VAR_X1_28, VAR_K_31))).
fof(ax111, axiom,
![VAR_K_26, VAR_X0X30_23, VAR_X1_24, VAR_X2_25, VAR_X3_0X30] : (constr_cbc_4_get_1_prefixes(constr_cbc_enc_4(VAR_X0X30_23, VAR_X1_24, VAR_X2_25, VAR_X3_0X30, VAR_K_26)) = constr_cbc_enc_1(VAR_X0X30_23, VAR_K_26))).
fof(ax112, axiom,
![VAR_K_22, VAR_X0X30_19, VAR_X1_20X30, VAR_X2_21] : (constr_cbc_3_get_2_prefixes(constr_cbc_enc_3(VAR_X0X30_19, VAR_X1_20X30, VAR_X2_21, VAR_K_22)) = constr_cbc_enc_2(VAR_X0X30_19, VAR_X1_20X30, VAR_K_22))).
fof(ax113, axiom,
![VAR_K_18, VAR_X0X30_15, VAR_X1_16, VAR_X2_17] : (constr_cbc_3_get_1_prefixes(constr_cbc_enc_3(VAR_X0X30_15, VAR_X1_16, VAR_X2_17, VAR_K_18)) = constr_cbc_enc_1(VAR_X0X30_15, VAR_K_18))).
fof(ax114, axiom,
![VAR_K_0X30, VAR_X0X30_13, VAR_X1_14] : (constr_cbc_2_get_1_prefixes(constr_cbc_enc_2(VAR_X0X30_13, VAR_X1_14, VAR_K_0X30)) = constr_cbc_enc_1(VAR_X0X30_13, VAR_K_0X30))).
fof(ax115, axiom,
![VAR_X0X30_10X30, VAR_X1_11, VAR_X2_12] : (constr_tuple_3_get_2(tuple_3(VAR_X0X30_10X30, VAR_X1_11, VAR_X2_12)) = VAR_X2_12)).
fof(ax116, axiom,
![VAR_X0X30_7, VAR_X1_8, VAR_X2_9] : (constr_tuple_3_get_1(tuple_3(VAR_X0X30_7, VAR_X1_8, VAR_X2_9)) = VAR_X1_8)).
fof(ax117, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30, VAR_X2_0X30] : (constr_tuple_3_get_0x30(tuple_3(VAR_X0X30_0X30, VAR_X1_0X30, VAR_X2_0X30)) = VAR_X0X30_0X30)).
fof(ax118, axiom,
![VAR_X_67] : (pred_eq(VAR_X_67, VAR_X_67))).
fof(ax119, axiom,
![VAR_V_73] : (pred_attacker(VAR_V_73) => pred_attacker(constr_tuple_3_get_2(VAR_V_73)))).
fof(ax120, axiom,
![VAR_V_75] : (pred_attacker(VAR_V_75) => pred_attacker(constr_tuple_3_get_1(VAR_V_75)))).
fof(ax121, axiom,
![VAR_V_77] : (pred_attacker(VAR_V_77) => pred_attacker(constr_tuple_3_get_0x30(VAR_V_77)))).
fof(ax122, axiom,
pred_attacker(tuple_true)).
fof(ax123, axiom,
pred_attacker(constr_server_S_STEP_2)).
fof(ax124, axiom,
pred_attacker(constr_server_S_STEP_1)).
fof(ax125, axiom,
pred_attacker(tuple_false)).
fof(ax126, axiom,
pred_attacker(constr_client_B_STEP_1)).
fof(ax127, axiom,
![VAR_V_84, VAR_V_85, VAR_V_86, VAR_V_87, VAR_V_88] : ((pred_attacker(VAR_V_84) & pred_attacker(VAR_V_85) & pred_attacker(VAR_V_86) & pred_attacker(VAR_V_87) & pred_attacker(VAR_V_88)) => pred_attacker(constr_cbc_enc_4(VAR_V_84, VAR_V_85, VAR_V_86, VAR_V_87, VAR_V_88)))).
fof(ax128, axiom,
![VAR_V_93, VAR_V_94, VAR_V_95, VAR_V_96] : ((pred_attacker(VAR_V_93) & pred_attacker(VAR_V_94) & pred_attacker(VAR_V_95) & pred_attacker(VAR_V_96)) => pred_attacker(constr_cbc_enc_3(VAR_V_93, VAR_V_94, VAR_V_95, VAR_V_96)))).
fof(ax129, axiom,
![VAR_V_10X300X30, VAR_V_10X301, VAR_V_10X302] : ((pred_attacker(VAR_V_10X300X30) & pred_attacker(VAR_V_10X301) & pred_attacker(VAR_V_10X302)) => pred_attacker(constr_cbc_enc_2(VAR_V_10X300X30, VAR_V_10X301, VAR_V_10X302)))).
fof(ax130, axiom,
![VAR_V_10X305, VAR_V_10X306] : ((pred_attacker(VAR_V_10X305) & pred_attacker(VAR_V_10X306)) => pred_attacker(constr_cbc_enc_1(VAR_V_10X305, VAR_V_10X306)))).
fof(ax131, axiom,
![VAR_V_10X309, VAR_V_110X30] : ((pred_attacker(VAR_V_10X309) & pred_attacker(VAR_V_110X30)) => pred_attacker(constr_cbc_dec_4(VAR_V_10X309, VAR_V_110X30)))).
fof(ax132, axiom,
![VAR_V_113, VAR_V_114] : ((pred_attacker(VAR_V_113) & pred_attacker(VAR_V_114)) => pred_attacker(constr_cbc_dec_3(VAR_V_113, VAR_V_114)))).
fof(ax133, axiom,
![VAR_V_117, VAR_V_118] : ((pred_attacker(VAR_V_117) & pred_attacker(VAR_V_118)) => pred_attacker(constr_cbc_dec_2(VAR_V_117, VAR_V_118)))).
fof(ax134, axiom,
![VAR_V_121, VAR_V_122] : ((pred_attacker(VAR_V_121) & pred_attacker(VAR_V_122)) => pred_attacker(constr_cbc_dec_1(VAR_V_121, VAR_V_122)))).
fof(ax135, axiom,
![VAR_V_124] : (pred_attacker(VAR_V_124) => pred_attacker(constr_cbc_4_get_3_prefixes(VAR_V_124)))).
fof(ax136, axiom,
![VAR_V_126] : (pred_attacker(VAR_V_126) => pred_attacker(constr_cbc_4_get_2_prefixes(VAR_V_126)))).
fof(ax137, axiom,
![VAR_V_128] : (pred_attacker(VAR_V_128) => pred_attacker(constr_cbc_4_get_1_prefixes(VAR_V_128)))).
fof(ax138, axiom,
![VAR_V_130X30] : (pred_attacker(VAR_V_130X30) => pred_attacker(constr_cbc_3_get_2_prefixes(VAR_V_130X30)))).
fof(ax139, axiom,
![VAR_V_132] : (pred_attacker(VAR_V_132) => pred_attacker(constr_cbc_3_get_1_prefixes(VAR_V_132)))).
fof(ax140, axiom,
![VAR_V_134] : (pred_attacker(VAR_V_134) => pred_attacker(constr_cbc_2_get_1_prefixes(VAR_V_134)))).
fof(ax141, axiom,
pred_attacker(constr_CONST_4)).
fof(ax142, axiom,
pred_attacker(constr_CONST_3)).
fof(ax143, axiom,
pred_attacker(constr_CONST_2)).
fof(ax144, axiom,
pred_attacker(constr_CONST_1)).
fof(ax145, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax146, axiom,
![VAR_V_143, VAR_V_144, VAR_V_145, VAR_V_146] : ((pred_attacker(VAR_V_143) & pred_attacker(VAR_V_144) & pred_attacker(VAR_V_145) & pred_attacker(VAR_V_146)) => pred_attacker(tuple_4(VAR_V_143, VAR_V_144, VAR_V_145, VAR_V_146)))).
fof(ax147, axiom,
![VAR_V_167, VAR_V_168, VAR_V_169, VAR_V_170X30] : (pred_attacker(tuple_4(VAR_V_167, VAR_V_168, VAR_V_169, VAR_V_170X30)) => pred_attacker(VAR_V_167))).
fof(ax148, axiom,
![VAR_V_172, VAR_V_173, VAR_V_174, VAR_V_175] : (pred_attacker(tuple_4(VAR_V_172, VAR_V_173, VAR_V_174, VAR_V_175)) => pred_attacker(VAR_V_173))).
fof(ax149, axiom,
![VAR_V_177, VAR_V_178, VAR_V_179, VAR_V_180X30] : (pred_attacker(tuple_4(VAR_V_177, VAR_V_178, VAR_V_179, VAR_V_180X30)) => pred_attacker(VAR_V_179))).
fof(ax150, axiom,
![VAR_V_182, VAR_V_183, VAR_V_184, VAR_V_185] : (pred_attacker(tuple_4(VAR_V_182, VAR_V_183, VAR_V_184, VAR_V_185)) => pred_attacker(VAR_V_185))).
fof(ax151, axiom,
![VAR_V_190X30, VAR_V_191, VAR_V_192] : ((pred_attacker(VAR_V_190X30) & pred_attacker(VAR_V_191) & pred_attacker(VAR_V_192)) => pred_attacker(tuple_3(VAR_V_190X30, VAR_V_191, VAR_V_192)))).
fof(ax152, axiom,
![VAR_V_20X305, VAR_V_20X306, VAR_V_20X307] : (pred_attacker(tuple_3(VAR_V_20X305, VAR_V_20X306, VAR_V_20X307)) => pred_attacker(VAR_V_20X305))).
fof(ax153, axiom,
![VAR_V_20X309, VAR_V_210X30, VAR_V_211] : (pred_attacker(tuple_3(VAR_V_20X309, VAR_V_210X30, VAR_V_211)) => pred_attacker(VAR_V_210X30))).
fof(ax154, axiom,
![VAR_V_213, VAR_V_214, VAR_V_215] : (pred_attacker(tuple_3(VAR_V_213, VAR_V_214, VAR_V_215)) => pred_attacker(VAR_V_215))).
fof(ax155, axiom,
![VAR_V_219, VAR_V_220X30] : ((pred_attacker(VAR_V_219) & pred_attacker(VAR_V_220X30)) => pred_attacker(tuple_2(VAR_V_219, VAR_V_220X30)))).
fof(ax156, axiom,
![VAR_V_227, VAR_V_228] : (pred_attacker(tuple_2(VAR_V_227, VAR_V_228)) => pred_attacker(VAR_V_227))).
fof(ax157, axiom,
![VAR_V_230X30, VAR_V_231] : (pred_attacker(tuple_2(VAR_V_230X30, VAR_V_231)) => pred_attacker(VAR_V_231))).
fof(ax158, axiom,
![VAR_V_233, VAR_V_234] : ((pred_mess(VAR_V_234, VAR_V_233) & pred_attacker(VAR_V_234)) => pred_attacker(VAR_V_233))).
fof(ax159, axiom,
![VAR_V_235, VAR_V_236] : ((pred_attacker(VAR_V_236) & pred_attacker(VAR_V_235)) => pred_mess(VAR_V_236, VAR_V_235))).
fof(ax160, axiom,
pred_attacker(name_c)).
fof(ax161, axiom,
pred_attacker(name_I)).
fof(ax162, axiom,
pred_attacker(name_B)).
fof(ax163, axiom,
pred_attacker(name_A)).
fof(ax164, axiom,
![VAR_V_238] : (pred_equal(VAR_V_238, VAR_V_238))).
fof(ax165, axiom,
![VAR_V_239] : (pred_attacker(name_new0x2Dname(VAR_V_239)))).
fof(ax166, axiom,
![VAR_ENC_A_KAB_T_293] : ((pred_eq(name_A, constr_tuple_3_get_0x30(constr_cbc_dec_3(VAR_ENC_A_KAB_T_293, name_Kbs))) & pred_attacker(VAR_ENC_A_KAB_T_293)) => pred_attacker(tuple_2(name_objective, constr_client_B_STEP_1)))).
fof(ax167, axiom,
![VAR_0X40SID_357] : (pred_attacker(tuple_2(name_A, name_B)) => pred_attacker(tuple_2(constr_cbc_enc_4(name_B, name_Kab_54(VAR_0X40SID_357), name_T_55(VAR_0X40SID_357), constr_cbc_enc_3(name_A, name_Kab_54(VAR_0X40SID_357), name_T_55(VAR_0X40SID_357), name_Kbs), name_Kas), constr_server_S_STEP_2)))).
fof(ax168, axiom,
![VAR_0X40SID_537] : (pred_attacker(tuple_2(name_B, name_A)) => pred_attacker(tuple_2(constr_cbc_enc_4(name_A, name_Kab_54(VAR_0X40SID_537), name_T_55(VAR_0X40SID_537), constr_cbc_enc_3(name_B, name_Kab_54(VAR_0X40SID_537), name_T_55(VAR_0X40SID_537), name_Kas), name_Kbs), constr_server_S_STEP_1)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
