%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_A_STEP_1 != constr_A_STEP_2).
fof(ax1, axiom,
constr_A_STEP_1 != constr_A_STEP_3).
fof(ax2, axiom,
constr_A_STEP_1 != constr_B_STEP_1).
fof(ax3, axiom,
constr_A_STEP_1 != constr_CONST_0x30).
fof(ax4, axiom,
constr_A_STEP_1 != constr_CONST_1).
fof(ax5, axiom,
constr_A_STEP_1 != constr_CONST_2).
fof(ax6, axiom,
constr_A_STEP_1 != constr_CONST_3).
fof(ax7, axiom,
constr_A_STEP_1 != constr_CONST_4).
fof(ax8, axiom,
constr_A_STEP_1 != name_G_9).
fof(ax9, axiom,
constr_A_STEP_1 != name_Na).
fof(ax10, axiom,
constr_A_STEP_1 != name_Nb).
fof(ax11, axiom,
constr_A_STEP_1 != name_P_8).
fof(ax12, axiom,
constr_A_STEP_1 != name_c).
fof(ax13, axiom,
constr_A_STEP_1 != name_objective).
fof(ax14, axiom,
constr_A_STEP_2 != constr_A_STEP_3).
fof(ax15, axiom,
constr_A_STEP_2 != constr_B_STEP_1).
fof(ax16, axiom,
constr_A_STEP_2 != constr_CONST_0x30).
fof(ax17, axiom,
constr_A_STEP_2 != constr_CONST_1).
fof(ax18, axiom,
constr_A_STEP_2 != constr_CONST_2).
fof(ax19, axiom,
constr_A_STEP_2 != constr_CONST_3).
fof(ax20, axiom,
constr_A_STEP_2 != constr_CONST_4).
fof(ax21, axiom,
constr_A_STEP_2 != name_G_9).
fof(ax22, axiom,
constr_A_STEP_2 != name_Na).
fof(ax23, axiom,
constr_A_STEP_2 != name_Nb).
fof(ax24, axiom,
constr_A_STEP_2 != name_P_8).
fof(ax25, axiom,
constr_A_STEP_2 != name_c).
fof(ax26, axiom,
constr_A_STEP_2 != name_objective).
fof(ax27, axiom,
constr_A_STEP_3 != constr_B_STEP_1).
fof(ax28, axiom,
constr_A_STEP_3 != constr_CONST_0x30).
fof(ax29, axiom,
constr_A_STEP_3 != constr_CONST_1).
fof(ax30, axiom,
constr_A_STEP_3 != constr_CONST_2).
fof(ax31, axiom,
constr_A_STEP_3 != constr_CONST_3).
fof(ax32, axiom,
constr_A_STEP_3 != constr_CONST_4).
fof(ax33, axiom,
constr_A_STEP_3 != name_G_9).
fof(ax34, axiom,
constr_A_STEP_3 != name_Na).
fof(ax35, axiom,
constr_A_STEP_3 != name_Nb).
fof(ax36, axiom,
constr_A_STEP_3 != name_P_8).
fof(ax37, axiom,
constr_A_STEP_3 != name_c).
fof(ax38, axiom,
constr_A_STEP_3 != name_objective).
fof(ax39, axiom,
constr_B_STEP_1 != constr_CONST_0x30).
fof(ax40, axiom,
constr_B_STEP_1 != constr_CONST_1).
fof(ax41, axiom,
constr_B_STEP_1 != constr_CONST_2).
fof(ax42, axiom,
constr_B_STEP_1 != constr_CONST_3).
fof(ax43, axiom,
constr_B_STEP_1 != constr_CONST_4).
fof(ax44, axiom,
constr_B_STEP_1 != name_G_9).
fof(ax45, axiom,
constr_B_STEP_1 != name_Na).
fof(ax46, axiom,
constr_B_STEP_1 != name_Nb).
fof(ax47, axiom,
constr_B_STEP_1 != name_P_8).
fof(ax48, axiom,
constr_B_STEP_1 != name_c).
fof(ax49, axiom,
constr_B_STEP_1 != name_objective).
fof(ax50, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax51, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax52, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax53, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax54, axiom,
constr_CONST_0x30 != name_G_9).
fof(ax55, axiom,
constr_CONST_0x30 != name_Na).
fof(ax56, axiom,
constr_CONST_0x30 != name_Nb).
fof(ax57, axiom,
constr_CONST_0x30 != name_P_8).
fof(ax58, axiom,
constr_CONST_0x30 != name_c).
fof(ax59, axiom,
constr_CONST_0x30 != name_objective).
fof(ax60, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax61, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax62, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax63, axiom,
constr_CONST_1 != name_G_9).
fof(ax64, axiom,
constr_CONST_1 != name_Na).
fof(ax65, axiom,
constr_CONST_1 != name_Nb).
fof(ax66, axiom,
constr_CONST_1 != name_P_8).
fof(ax67, axiom,
constr_CONST_1 != name_c).
fof(ax68, axiom,
constr_CONST_1 != name_objective).
fof(ax69, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax70, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax71, axiom,
constr_CONST_2 != name_G_9).
fof(ax72, axiom,
constr_CONST_2 != name_Na).
fof(ax73, axiom,
constr_CONST_2 != name_Nb).
fof(ax74, axiom,
constr_CONST_2 != name_P_8).
fof(ax75, axiom,
constr_CONST_2 != name_c).
fof(ax76, axiom,
constr_CONST_2 != name_objective).
fof(ax77, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax78, axiom,
constr_CONST_3 != name_G_9).
fof(ax79, axiom,
constr_CONST_3 != name_Na).
fof(ax80, axiom,
constr_CONST_3 != name_Nb).
fof(ax81, axiom,
constr_CONST_3 != name_P_8).
fof(ax82, axiom,
constr_CONST_3 != name_c).
fof(ax83, axiom,
constr_CONST_3 != name_objective).
fof(ax84, axiom,
constr_CONST_4 != name_G_9).
fof(ax85, axiom,
constr_CONST_4 != name_Na).
fof(ax86, axiom,
constr_CONST_4 != name_Nb).
fof(ax87, axiom,
constr_CONST_4 != name_P_8).
fof(ax88, axiom,
constr_CONST_4 != name_c).
fof(ax89, axiom,
constr_CONST_4 != name_objective).
fof(ax90, axiom,
name_G_9 != name_Na).
fof(ax91, axiom,
name_G_9 != name_Nb).
fof(ax92, axiom,
name_G_9 != name_P_8).
fof(ax93, axiom,
name_G_9 != name_c).
fof(ax94, axiom,
name_G_9 != name_objective).
fof(ax95, axiom,
name_Na != name_Nb).
fof(ax96, axiom,
name_Na != name_P_8).
fof(ax97, axiom,
name_Na != name_c).
fof(ax98, axiom,
name_Na != name_objective).
fof(ax99, axiom,
name_Nb != name_P_8).
fof(ax100, axiom,
name_Nb != name_c).
fof(ax101, axiom,
name_Nb != name_objective).
fof(ax102, axiom,
name_P_8 != name_c).
fof(ax103, axiom,
name_P_8 != name_objective).
fof(ax104, axiom,
name_c != name_objective).
fof(ax105, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_dec(constr_enc(VAR_M_0X30, VAR_K_0X30), VAR_K_0X30) = VAR_M_0X30)).
fof(ax106, axiom,
![VAR_G_0X30, VAR_P_0X30, VAR_X_7, VAR_Y_0X30] : (constr_mod(constr_exp(constr_exp(VAR_G_0X30, VAR_X_7), VAR_Y_0X30), VAR_P_0X30) = constr_mod(constr_exp(constr_exp(VAR_G_0X30, VAR_Y_0X30), VAR_X_7), VAR_P_0X30))).
fof(ax107, axiom,
![VAR_X_26] : (pred_eq(VAR_X_26, VAR_X_26))).
fof(ax108, axiom,
pred_attacker(tuple_true)).
fof(ax109, axiom,
![VAR_V_34, VAR_V_35] : ((pred_attacker(VAR_V_34) & pred_attacker(VAR_V_35)) => pred_attacker(constr_mod(VAR_V_34, VAR_V_35)))).
fof(ax110, axiom,
pred_attacker(tuple_false)).
fof(ax111, axiom,
![VAR_V_38, VAR_V_39] : ((pred_attacker(VAR_V_38) & pred_attacker(VAR_V_39)) => pred_attacker(constr_exp(VAR_V_38, VAR_V_39)))).
fof(ax112, axiom,
![VAR_V_42, VAR_V_43] : ((pred_attacker(VAR_V_42) & pred_attacker(VAR_V_43)) => pred_attacker(constr_enc(VAR_V_42, VAR_V_43)))).
fof(ax113, axiom,
![VAR_V_46, VAR_V_47] : ((pred_attacker(VAR_V_46) & pred_attacker(VAR_V_47)) => pred_attacker(constr_dec(VAR_V_46, VAR_V_47)))).
fof(ax114, axiom,
pred_attacker(constr_CONST_4)).
fof(ax115, axiom,
pred_attacker(constr_CONST_3)).
fof(ax116, axiom,
pred_attacker(constr_CONST_2)).
fof(ax117, axiom,
pred_attacker(constr_CONST_1)).
fof(ax118, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax119, axiom,
pred_attacker(constr_B_STEP_1)).
fof(ax120, axiom,
pred_attacker(constr_A_STEP_3)).
fof(ax121, axiom,
pred_attacker(constr_A_STEP_2)).
fof(ax122, axiom,
pred_attacker(constr_A_STEP_1)).
fof(ax123, axiom,
![VAR_V_54, VAR_V_55] : ((pred_attacker(VAR_V_54) & pred_attacker(VAR_V_55)) => pred_attacker(tuple_2(VAR_V_54, VAR_V_55)))).
fof(ax124, axiom,
![VAR_V_62, VAR_V_63] : (pred_attacker(tuple_2(VAR_V_62, VAR_V_63)) => pred_attacker(VAR_V_62))).
fof(ax125, axiom,
![VAR_V_65, VAR_V_66] : (pred_attacker(tuple_2(VAR_V_65, VAR_V_66)) => pred_attacker(VAR_V_66))).
fof(ax126, axiom,
![VAR_V_68, VAR_V_69] : ((pred_mess(VAR_V_69, VAR_V_68) & pred_attacker(VAR_V_69)) => pred_attacker(VAR_V_68))).
fof(ax127, axiom,
![VAR_V_70X30, VAR_V_71] : ((pred_attacker(VAR_V_71) & pred_attacker(VAR_V_70X30)) => pred_mess(VAR_V_71, VAR_V_70X30))).
fof(ax128, axiom,
pred_attacker(name_c)).
fof(ax129, axiom,
![VAR_V_73] : (pred_equal(VAR_V_73, VAR_V_73))).
fof(ax130, axiom,
![VAR_V_74] : (pred_attacker(name_new0x2Dname(VAR_V_74)))).
fof(ax131, axiom,
pred_attacker(tuple_2(tuple_2(name_P_8, name_G_9), constr_A_STEP_1))).
fof(ax132, axiom,
pred_attacker(tuple_2(constr_mod(constr_exp(name_G_9, name_Na), name_P_8), constr_A_STEP_2))).
fof(ax133, axiom,
![VAR_B_164] : (pred_attacker(VAR_B_164) => pred_attacker(tuple_2(constr_enc(name_objective, constr_mod(constr_exp(VAR_B_164, name_Na), name_P_8)), constr_A_STEP_3)))).
fof(ax134, axiom,
![VAR_A_20X303, VAR_G_20X305, VAR_P_20X304] : ((pred_attacker(VAR_A_20X303) & pred_attacker(tuple_2(VAR_P_20X304, VAR_G_20X305))) => pred_attacker(tuple_2(constr_mod(constr_exp(VAR_G_20X305, name_Nb), VAR_P_20X304), constr_B_STEP_1)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
