%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_STEP_1).
fof(ax5, axiom,
constr_CONST_0x30 != constr_STEP_2).
fof(ax6, axiom,
constr_CONST_0x30 != constr_g).
fof(ax7, axiom,
constr_CONST_0x30 != constr_p0x30_STEP_1).
fof(ax8, axiom,
constr_CONST_0x30 != constr_p0x30_STEP_2).
fof(ax9, axiom,
constr_CONST_0x30 != constr_p1_STEP_1).
fof(ax10, axiom,
constr_CONST_0x30 != name_c).
fof(ax11, axiom,
constr_CONST_0x30 != name_s).
fof(ax12, axiom,
constr_CONST_0x30 != name_skA).
fof(ax13, axiom,
constr_CONST_0x30 != name_skB).
fof(ax14, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax15, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax16, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax17, axiom,
constr_CONST_1 != constr_STEP_1).
fof(ax18, axiom,
constr_CONST_1 != constr_STEP_2).
fof(ax19, axiom,
constr_CONST_1 != constr_g).
fof(ax20, axiom,
constr_CONST_1 != constr_p0x30_STEP_1).
fof(ax21, axiom,
constr_CONST_1 != constr_p0x30_STEP_2).
fof(ax22, axiom,
constr_CONST_1 != constr_p1_STEP_1).
fof(ax23, axiom,
constr_CONST_1 != name_c).
fof(ax24, axiom,
constr_CONST_1 != name_s).
fof(ax25, axiom,
constr_CONST_1 != name_skA).
fof(ax26, axiom,
constr_CONST_1 != name_skB).
fof(ax27, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax28, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax29, axiom,
constr_CONST_2 != constr_STEP_1).
fof(ax30, axiom,
constr_CONST_2 != constr_STEP_2).
fof(ax31, axiom,
constr_CONST_2 != constr_g).
fof(ax32, axiom,
constr_CONST_2 != constr_p0x30_STEP_1).
fof(ax33, axiom,
constr_CONST_2 != constr_p0x30_STEP_2).
fof(ax34, axiom,
constr_CONST_2 != constr_p1_STEP_1).
fof(ax35, axiom,
constr_CONST_2 != name_c).
fof(ax36, axiom,
constr_CONST_2 != name_s).
fof(ax37, axiom,
constr_CONST_2 != name_skA).
fof(ax38, axiom,
constr_CONST_2 != name_skB).
fof(ax39, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax40, axiom,
constr_CONST_3 != constr_STEP_1).
fof(ax41, axiom,
constr_CONST_3 != constr_STEP_2).
fof(ax42, axiom,
constr_CONST_3 != constr_g).
fof(ax43, axiom,
constr_CONST_3 != constr_p0x30_STEP_1).
fof(ax44, axiom,
constr_CONST_3 != constr_p0x30_STEP_2).
fof(ax45, axiom,
constr_CONST_3 != constr_p1_STEP_1).
fof(ax46, axiom,
constr_CONST_3 != name_c).
fof(ax47, axiom,
constr_CONST_3 != name_s).
fof(ax48, axiom,
constr_CONST_3 != name_skA).
fof(ax49, axiom,
constr_CONST_3 != name_skB).
fof(ax50, axiom,
constr_CONST_4 != constr_STEP_1).
fof(ax51, axiom,
constr_CONST_4 != constr_STEP_2).
fof(ax52, axiom,
constr_CONST_4 != constr_g).
fof(ax53, axiom,
constr_CONST_4 != constr_p0x30_STEP_1).
fof(ax54, axiom,
constr_CONST_4 != constr_p0x30_STEP_2).
fof(ax55, axiom,
constr_CONST_4 != constr_p1_STEP_1).
fof(ax56, axiom,
constr_CONST_4 != name_c).
fof(ax57, axiom,
constr_CONST_4 != name_s).
fof(ax58, axiom,
constr_CONST_4 != name_skA).
fof(ax59, axiom,
constr_CONST_4 != name_skB).
fof(ax60, axiom,
constr_STEP_1 != constr_STEP_2).
fof(ax61, axiom,
constr_STEP_1 != constr_g).
fof(ax62, axiom,
constr_STEP_1 != constr_p0x30_STEP_1).
fof(ax63, axiom,
constr_STEP_1 != constr_p0x30_STEP_2).
fof(ax64, axiom,
constr_STEP_1 != constr_p1_STEP_1).
fof(ax65, axiom,
constr_STEP_1 != name_c).
fof(ax66, axiom,
constr_STEP_1 != name_s).
fof(ax67, axiom,
constr_STEP_1 != name_skA).
fof(ax68, axiom,
constr_STEP_1 != name_skB).
fof(ax69, axiom,
constr_STEP_2 != constr_g).
fof(ax70, axiom,
constr_STEP_2 != constr_p0x30_STEP_1).
fof(ax71, axiom,
constr_STEP_2 != constr_p0x30_STEP_2).
fof(ax72, axiom,
constr_STEP_2 != constr_p1_STEP_1).
fof(ax73, axiom,
constr_STEP_2 != name_c).
fof(ax74, axiom,
constr_STEP_2 != name_s).
fof(ax75, axiom,
constr_STEP_2 != name_skA).
fof(ax76, axiom,
constr_STEP_2 != name_skB).
fof(ax77, axiom,
constr_g != constr_p0x30_STEP_1).
fof(ax78, axiom,
constr_g != constr_p0x30_STEP_2).
fof(ax79, axiom,
constr_g != constr_p1_STEP_1).
fof(ax80, axiom,
constr_g != name_c).
fof(ax81, axiom,
constr_g != name_s).
fof(ax82, axiom,
constr_g != name_skA).
fof(ax83, axiom,
constr_g != name_skB).
fof(ax84, axiom,
constr_p0x30_STEP_1 != constr_p0x30_STEP_2).
fof(ax85, axiom,
constr_p0x30_STEP_1 != constr_p1_STEP_1).
fof(ax86, axiom,
constr_p0x30_STEP_1 != name_c).
fof(ax87, axiom,
constr_p0x30_STEP_1 != name_s).
fof(ax88, axiom,
constr_p0x30_STEP_1 != name_skA).
fof(ax89, axiom,
constr_p0x30_STEP_1 != name_skB).
fof(ax90, axiom,
constr_p0x30_STEP_2 != constr_p1_STEP_1).
fof(ax91, axiom,
constr_p0x30_STEP_2 != name_c).
fof(ax92, axiom,
constr_p0x30_STEP_2 != name_s).
fof(ax93, axiom,
constr_p0x30_STEP_2 != name_skA).
fof(ax94, axiom,
constr_p0x30_STEP_2 != name_skB).
fof(ax95, axiom,
constr_p1_STEP_1 != name_c).
fof(ax96, axiom,
constr_p1_STEP_1 != name_s).
fof(ax97, axiom,
constr_p1_STEP_1 != name_skA).
fof(ax98, axiom,
constr_p1_STEP_1 != name_skB).
fof(ax99, axiom,
name_c != name_s).
fof(ax100, axiom,
name_c != name_skA).
fof(ax101, axiom,
name_c != name_skB).
fof(ax102, axiom,
name_s != name_skA).
fof(ax103, axiom,
name_s != name_skB).
fof(ax104, axiom,
name_skA != name_skB).
fof(ax105, axiom,
![VAR_X_25, VAR_Y_26] : (constr_exp(constr_exp(constr_g, VAR_X_25), VAR_Y_26) = constr_exp(constr_exp(constr_g, VAR_Y_26), VAR_X_25))).
fof(ax106, axiom,
![VAR_X_59] : (pred_eq(VAR_X_59, VAR_X_59))).
fof(ax107, axiom,
pred_attacker(tuple_true)).
fof(ax108, axiom,
![VAR_V_66, VAR_V_67] : ((pred_attacker(VAR_V_66) & pred_attacker(VAR_V_67)) => pred_attacker(constr_sign(VAR_V_66, VAR_V_67)))).
fof(ax109, axiom,
![VAR_V_69] : (pred_attacker(VAR_V_69) => pred_attacker(constr_pk(VAR_V_69)))).
fof(ax110, axiom,
pred_attacker(constr_p1_STEP_1)).
fof(ax111, axiom,
pred_attacker(constr_p0x30_STEP_2)).
fof(ax112, axiom,
pred_attacker(constr_p0x30_STEP_1)).
fof(ax113, axiom,
![VAR_K_73, VAR_M_72] : (pred_attacker(constr_sign(VAR_M_72, VAR_K_73)) => pred_attacker(VAR_M_72))).
fof(ax114, axiom,
pred_attacker(constr_g)).
fof(ax115, axiom,
pred_attacker(tuple_false)).
fof(ax116, axiom,
![VAR_V_76, VAR_V_77] : ((pred_attacker(VAR_V_76) & pred_attacker(VAR_V_77)) => pred_attacker(constr_exp(VAR_V_76, VAR_V_77)))).
fof(ax117, axiom,
![VAR_V_80X30, VAR_V_81] : ((pred_attacker(VAR_V_80X30) & pred_attacker(VAR_V_81)) => pred_attacker(constr_enc(VAR_V_80X30, VAR_V_81)))).
fof(ax118, axiom,
![VAR_X_86, VAR_Y_87] : ((pred_attacker(constr_enc(VAR_X_86, VAR_Y_87)) & pred_attacker(VAR_Y_87)) => pred_attacker(VAR_X_86))).
fof(ax119, axiom,
pred_attacker(constr_STEP_2)).
fof(ax120, axiom,
pred_attacker(constr_STEP_1)).
fof(ax121, axiom,
pred_attacker(constr_CONST_4)).
fof(ax122, axiom,
pred_attacker(constr_CONST_3)).
fof(ax123, axiom,
pred_attacker(constr_CONST_2)).
fof(ax124, axiom,
pred_attacker(constr_CONST_1)).
fof(ax125, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax126, axiom,
![VAR_V_10X300X30, VAR_V_10X301] : ((pred_attacker(VAR_V_10X300X30) & pred_attacker(VAR_V_10X301)) => pred_attacker(tuple_2(VAR_V_10X300X30, VAR_V_10X301)))).
fof(ax127, axiom,
![VAR_V_10X308, VAR_V_10X309] : (pred_attacker(tuple_2(VAR_V_10X308, VAR_V_10X309)) => pred_attacker(VAR_V_10X308))).
fof(ax128, axiom,
![VAR_V_111, VAR_V_112] : (pred_attacker(tuple_2(VAR_V_111, VAR_V_112)) => pred_attacker(VAR_V_112))).
fof(ax129, axiom,
![VAR_V_115] : (pred_attacker(VAR_V_115) => pred_attacker(tuple_1(VAR_V_115)))).
fof(ax130, axiom,
![VAR_V_118] : (pred_attacker(tuple_1(VAR_V_118)) => pred_attacker(VAR_V_118))).
fof(ax131, axiom,
![VAR_V_120X30, VAR_V_121] : ((pred_mess(VAR_V_121, VAR_V_120X30) & pred_attacker(VAR_V_121)) => pred_attacker(VAR_V_120X30))).
fof(ax132, axiom,
![VAR_V_122, VAR_V_123] : ((pred_attacker(VAR_V_123) & pred_attacker(VAR_V_122)) => pred_mess(VAR_V_123, VAR_V_122))).
fof(ax133, axiom,
pred_attacker(name_c)).
fof(ax134, axiom,
![VAR_V_125] : (pred_equal(VAR_V_125, VAR_V_125))).
fof(ax135, axiom,
![VAR_V_126] : (pred_attacker(name_new0x2Dname(VAR_V_126)))).
fof(ax136, axiom,
pred_attacker(tuple_2(constr_pk(name_skA), constr_STEP_1))).
fof(ax137, axiom,
pred_attacker(tuple_2(constr_pk(name_skB), constr_STEP_2))).
fof(ax138, axiom,
![VAR_0X40SID_197, VAR_PKX_196] : (pred_attacker(VAR_PKX_196) => pred_attacker(tuple_2(tuple_2(constr_sign(constr_exp(constr_g, name_n0x30(VAR_PKX_196, VAR_0X40SID_197)), name_skA), constr_pk(name_skA)), constr_p0x30_STEP_1)))).
fof(ax139, axiom,
![VAR_0X40SID_252, VAR_X1_251] : ((pred_attacker(constr_sign(VAR_X1_251, name_skB)) & pred_attacker(constr_pk(name_skB))) => pred_attacker(tuple_2(constr_enc(name_s, constr_exp(VAR_X1_251, name_n0x30(constr_pk(name_skB), VAR_0X40SID_252))), constr_p0x30_STEP_2)))).
fof(ax140, axiom,
![VAR_0X40SID_320X30, VAR_K_319, VAR_X0X30_318] : (pred_attacker(tuple_2(constr_sign(VAR_X0X30_318, VAR_K_319), constr_pk(VAR_K_319))) => pred_attacker(tuple_2(constr_sign(constr_exp(constr_g, name_n1(constr_pk(VAR_K_319), constr_sign(VAR_X0X30_318, VAR_K_319), VAR_0X40SID_320X30)), name_skB), constr_p1_STEP_1)))).
fof(co0, conjecture,
pred_attacker(name_s)).
