%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_A != constr_CONST_0x30).
fof(ax1, axiom,
constr_A != constr_CONST_1).
fof(ax2, axiom,
constr_A != constr_CONST_2).
fof(ax3, axiom,
constr_A != constr_CONST_3).
fof(ax4, axiom,
constr_A != constr_CONST_4).
fof(ax5, axiom,
constr_A != constr_STEP_1).
fof(ax6, axiom,
constr_A != constr_client_A_STEP_1).
fof(ax7, axiom,
constr_A != constr_client_A_STEP_2).
fof(ax8, axiom,
constr_A != constr_key_retrieval_server_STEP_1).
fof(ax9, axiom,
constr_A != name_E).
fof(ax10, axiom,
constr_A != name_c).
fof(ax11, axiom,
constr_A != name_objective).
fof(ax12, axiom,
constr_A != name_skA).
fof(ax13, axiom,
constr_A != name_skS).
fof(ax14, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax15, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax16, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax17, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax18, axiom,
constr_CONST_0x30 != constr_STEP_1).
fof(ax19, axiom,
constr_CONST_0x30 != constr_client_A_STEP_1).
fof(ax20, axiom,
constr_CONST_0x30 != constr_client_A_STEP_2).
fof(ax21, axiom,
constr_CONST_0x30 != constr_key_retrieval_server_STEP_1).
fof(ax22, axiom,
constr_CONST_0x30 != name_E).
fof(ax23, axiom,
constr_CONST_0x30 != name_c).
fof(ax24, axiom,
constr_CONST_0x30 != name_objective).
fof(ax25, axiom,
constr_CONST_0x30 != name_skA).
fof(ax26, axiom,
constr_CONST_0x30 != name_skS).
fof(ax27, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax28, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax29, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax30, axiom,
constr_CONST_1 != constr_STEP_1).
fof(ax31, axiom,
constr_CONST_1 != constr_client_A_STEP_1).
fof(ax32, axiom,
constr_CONST_1 != constr_client_A_STEP_2).
fof(ax33, axiom,
constr_CONST_1 != constr_key_retrieval_server_STEP_1).
fof(ax34, axiom,
constr_CONST_1 != name_E).
fof(ax35, axiom,
constr_CONST_1 != name_c).
fof(ax36, axiom,
constr_CONST_1 != name_objective).
fof(ax37, axiom,
constr_CONST_1 != name_skA).
fof(ax38, axiom,
constr_CONST_1 != name_skS).
fof(ax39, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax40, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax41, axiom,
constr_CONST_2 != constr_STEP_1).
fof(ax42, axiom,
constr_CONST_2 != constr_client_A_STEP_1).
fof(ax43, axiom,
constr_CONST_2 != constr_client_A_STEP_2).
fof(ax44, axiom,
constr_CONST_2 != constr_key_retrieval_server_STEP_1).
fof(ax45, axiom,
constr_CONST_2 != name_E).
fof(ax46, axiom,
constr_CONST_2 != name_c).
fof(ax47, axiom,
constr_CONST_2 != name_objective).
fof(ax48, axiom,
constr_CONST_2 != name_skA).
fof(ax49, axiom,
constr_CONST_2 != name_skS).
fof(ax50, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax51, axiom,
constr_CONST_3 != constr_STEP_1).
fof(ax52, axiom,
constr_CONST_3 != constr_client_A_STEP_1).
fof(ax53, axiom,
constr_CONST_3 != constr_client_A_STEP_2).
fof(ax54, axiom,
constr_CONST_3 != constr_key_retrieval_server_STEP_1).
fof(ax55, axiom,
constr_CONST_3 != name_E).
fof(ax56, axiom,
constr_CONST_3 != name_c).
fof(ax57, axiom,
constr_CONST_3 != name_objective).
fof(ax58, axiom,
constr_CONST_3 != name_skA).
fof(ax59, axiom,
constr_CONST_3 != name_skS).
fof(ax60, axiom,
constr_CONST_4 != constr_STEP_1).
fof(ax61, axiom,
constr_CONST_4 != constr_client_A_STEP_1).
fof(ax62, axiom,
constr_CONST_4 != constr_client_A_STEP_2).
fof(ax63, axiom,
constr_CONST_4 != constr_key_retrieval_server_STEP_1).
fof(ax64, axiom,
constr_CONST_4 != name_E).
fof(ax65, axiom,
constr_CONST_4 != name_c).
fof(ax66, axiom,
constr_CONST_4 != name_objective).
fof(ax67, axiom,
constr_CONST_4 != name_skA).
fof(ax68, axiom,
constr_CONST_4 != name_skS).
fof(ax69, axiom,
constr_STEP_1 != constr_client_A_STEP_1).
fof(ax70, axiom,
constr_STEP_1 != constr_client_A_STEP_2).
fof(ax71, axiom,
constr_STEP_1 != constr_key_retrieval_server_STEP_1).
fof(ax72, axiom,
constr_STEP_1 != name_E).
fof(ax73, axiom,
constr_STEP_1 != name_c).
fof(ax74, axiom,
constr_STEP_1 != name_objective).
fof(ax75, axiom,
constr_STEP_1 != name_skA).
fof(ax76, axiom,
constr_STEP_1 != name_skS).
fof(ax77, axiom,
constr_client_A_STEP_1 != constr_client_A_STEP_2).
fof(ax78, axiom,
constr_client_A_STEP_1 != constr_key_retrieval_server_STEP_1).
fof(ax79, axiom,
constr_client_A_STEP_1 != name_E).
fof(ax80, axiom,
constr_client_A_STEP_1 != name_c).
fof(ax81, axiom,
constr_client_A_STEP_1 != name_objective).
fof(ax82, axiom,
constr_client_A_STEP_1 != name_skA).
fof(ax83, axiom,
constr_client_A_STEP_1 != name_skS).
fof(ax84, axiom,
constr_client_A_STEP_2 != constr_key_retrieval_server_STEP_1).
fof(ax85, axiom,
constr_client_A_STEP_2 != name_E).
fof(ax86, axiom,
constr_client_A_STEP_2 != name_c).
fof(ax87, axiom,
constr_client_A_STEP_2 != name_objective).
fof(ax88, axiom,
constr_client_A_STEP_2 != name_skA).
fof(ax89, axiom,
constr_client_A_STEP_2 != name_skS).
fof(ax90, axiom,
constr_key_retrieval_server_STEP_1 != name_E).
fof(ax91, axiom,
constr_key_retrieval_server_STEP_1 != name_c).
fof(ax92, axiom,
constr_key_retrieval_server_STEP_1 != name_objective).
fof(ax93, axiom,
constr_key_retrieval_server_STEP_1 != name_skA).
fof(ax94, axiom,
constr_key_retrieval_server_STEP_1 != name_skS).
fof(ax95, axiom,
name_E != name_c).
fof(ax96, axiom,
name_E != name_objective).
fof(ax97, axiom,
name_E != name_skA).
fof(ax98, axiom,
name_E != name_skS).
fof(ax99, axiom,
name_c != name_objective).
fof(ax100, axiom,
name_c != name_skA).
fof(ax101, axiom,
name_c != name_skS).
fof(ax102, axiom,
name_objective != name_skA).
fof(ax103, axiom,
name_objective != name_skS).
fof(ax104, axiom,
name_skA != name_skS).
fof(ax105, axiom,
![VAR_K_17, VAR_M_16] : (constr_adec(constr_aenc(VAR_M_16, constr_pkey(VAR_K_17)), VAR_K_17) = VAR_M_16)).
fof(ax106, axiom,
![VAR_K_15, VAR_M_14] : (constr_dec(constr_enc(VAR_M_14, VAR_K_15), VAR_K_15) = VAR_M_14)).
fof(ax107, axiom,
![VAR_K_13, VAR_M_12] : (constr_getmess(constr_sign(VAR_M_12, VAR_K_13)) = VAR_M_12)).
fof(ax108, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_checksign(constr_sign(VAR_M_0X30, VAR_K_0X30), constr_pkey(VAR_K_0X30)) = VAR_M_0X30)).
fof(ax109, axiom,
![VAR_K_11, VAR_M_10X30] : (constr_checksign(constr_sign(VAR_M_10X30, VAR_K_11), constr_pkey(VAR_K_11)) = VAR_M_10X30)).
fof(ax110, axiom,
![VAR_X_9] : (constr_xor(constr_A, VAR_X_9) = VAR_X_9)).
fof(ax111, axiom,
![VAR_X0X30_7, VAR_X1_8] : (constr_tuple_2_get_1(tuple_2(VAR_X0X30_7, VAR_X1_8)) = VAR_X1_8)).
fof(ax112, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30] : (constr_tuple_2_get_0x30(tuple_2(VAR_X0X30_0X30, VAR_X1_0X30)) = VAR_X0X30_0X30)).
fof(ax113, axiom,
![VAR_X_33] : (pred_eq(VAR_X_33, VAR_X_33))).
fof(ax114, axiom,
![VAR_V_40X30, VAR_V_41] : ((pred_attacker(VAR_V_40X30) & pred_attacker(VAR_V_41)) => pred_attacker(constr_xor(VAR_V_40X30, VAR_V_41)))).
fof(ax115, axiom,
![VAR_V_43] : (pred_attacker(VAR_V_43) => pred_attacker(constr_tuple_2_get_1(VAR_V_43)))).
fof(ax116, axiom,
![VAR_V_45] : (pred_attacker(VAR_V_45) => pred_attacker(constr_tuple_2_get_0x30(VAR_V_45)))).
fof(ax117, axiom,
pred_attacker(tuple_true)).
fof(ax118, axiom,
![VAR_V_47] : (pred_attacker(VAR_V_47) => pred_attacker(constr_test(VAR_V_47)))).
fof(ax119, axiom,
![VAR_V_50X30, VAR_V_51] : ((pred_attacker(VAR_V_50X30) & pred_attacker(VAR_V_51)) => pred_attacker(constr_sign(VAR_V_50X30, VAR_V_51)))).
fof(ax120, axiom,
![VAR_V_53] : (pred_attacker(VAR_V_53) => pred_attacker(constr_pkey(VAR_V_53)))).
fof(ax121, axiom,
pred_attacker(constr_key_retrieval_server_STEP_1)).
fof(ax122, axiom,
![VAR_V_56] : (pred_attacker(VAR_V_56) => pred_attacker(constr_getmess(VAR_V_56)))).
fof(ax123, axiom,
pred_attacker(tuple_false)).
fof(ax124, axiom,
![VAR_V_59, VAR_V_60X30] : ((pred_attacker(VAR_V_59) & pred_attacker(VAR_V_60X30)) => pred_attacker(constr_enc(VAR_V_59, VAR_V_60X30)))).
fof(ax125, axiom,
![VAR_V_63, VAR_V_64] : ((pred_attacker(VAR_V_63) & pred_attacker(VAR_V_64)) => pred_attacker(constr_dec(VAR_V_63, VAR_V_64)))).
fof(ax126, axiom,
pred_attacker(constr_client_A_STEP_2)).
fof(ax127, axiom,
pred_attacker(constr_client_A_STEP_1)).
fof(ax128, axiom,
![VAR_V_67, VAR_V_68] : ((pred_attacker(VAR_V_67) & pred_attacker(VAR_V_68)) => pred_attacker(constr_checksign(VAR_V_67, VAR_V_68)))).
fof(ax129, axiom,
![VAR_V_71, VAR_V_72] : ((pred_attacker(VAR_V_71) & pred_attacker(VAR_V_72)) => pred_attacker(constr_aenc(VAR_V_71, VAR_V_72)))).
fof(ax130, axiom,
![VAR_V_75, VAR_V_76] : ((pred_attacker(VAR_V_75) & pred_attacker(VAR_V_76)) => pred_attacker(constr_adec(VAR_V_75, VAR_V_76)))).
fof(ax131, axiom,
pred_attacker(constr_STEP_1)).
fof(ax132, axiom,
pred_attacker(constr_CONST_4)).
fof(ax133, axiom,
pred_attacker(constr_CONST_3)).
fof(ax134, axiom,
pred_attacker(constr_CONST_2)).
fof(ax135, axiom,
pred_attacker(constr_CONST_1)).
fof(ax136, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax137, axiom,
pred_attacker(constr_A)).
fof(ax138, axiom,
![VAR_V_83, VAR_V_84] : ((pred_attacker(VAR_V_83) & pred_attacker(VAR_V_84)) => pred_attacker(tuple_2(VAR_V_83, VAR_V_84)))).
fof(ax139, axiom,
![VAR_V_91, VAR_V_92] : (pred_attacker(tuple_2(VAR_V_91, VAR_V_92)) => pred_attacker(VAR_V_91))).
fof(ax140, axiom,
![VAR_V_94, VAR_V_95] : (pred_attacker(tuple_2(VAR_V_94, VAR_V_95)) => pred_attacker(VAR_V_95))).
fof(ax141, axiom,
![VAR_V_97, VAR_V_98] : ((pred_mess(VAR_V_98, VAR_V_97) & pred_attacker(VAR_V_98)) => pred_attacker(VAR_V_97))).
fof(ax142, axiom,
![VAR_V_99, VAR_V_10X300X30] : ((pred_attacker(VAR_V_10X300X30) & pred_attacker(VAR_V_99)) => pred_mess(VAR_V_10X300X30, VAR_V_99))).
fof(ax143, axiom,
pred_attacker(name_c)).
fof(ax144, axiom,
pred_attacker(name_E)).
fof(ax145, axiom,
![VAR_V_10X302] : (pred_equal(VAR_V_10X302, VAR_V_10X302))).
fof(ax146, axiom,
![VAR_V_10X303] : (pred_attacker(name_new0x2Dname(VAR_V_10X303)))).
fof(ax147, axiom,
pred_table(tuple_keys(constr_A, constr_pkey(name_skA)))).
fof(ax148, axiom,
pred_attacker(tuple_2(constr_pkey(name_skS), constr_STEP_1))).
fof(ax149, axiom,
![VAR_T_163] : (pred_attacker(VAR_T_163) => pred_attacker(tuple_2(tuple_2(constr_A, VAR_T_163), constr_client_A_STEP_1)))).
fof(ax150, axiom,
![VAR_T_217, VAR_SIGN_PKT_T_216] : ((pred_eq(constr_tuple_2_get_1(constr_checksign(VAR_SIGN_PKT_T_216, constr_pkey(name_skS))), VAR_T_217) & pred_attacker(VAR_SIGN_PKT_T_216) & pred_attacker(VAR_T_217)) => pred_attacker(tuple_2(constr_aenc(name_objective, constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_PKT_T_216, constr_pkey(name_skS)))), constr_client_A_STEP_2)))).
fof(ax151, axiom,
![VAR_DST_259, VAR_PKDST_260X30, VAR_SRC_261] : ((pred_table(tuple_keys(VAR_DST_259, VAR_PKDST_260X30)) & pred_attacker(tuple_2(VAR_SRC_261, VAR_DST_259))) => pred_attacker(tuple_2(constr_sign(tuple_2(VAR_PKDST_260X30, VAR_DST_259), name_skS), constr_key_retrieval_server_STEP_1)))).
fof(ax152, axiom,
![VAR_H_291, VAR_PKH_292] : ((VAR_H_291 != constr_A & pred_attacker(tuple_2(VAR_H_291, VAR_PKH_292))) => pred_table(tuple_keys(VAR_H_291, VAR_PKH_292)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
