%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_A != constr_CONST_0x30).
fof(ax1, axiom,
constr_A != constr_CONST_1).
fof(ax2, axiom,
constr_A != constr_CONST_2).
fof(ax3, axiom,
constr_A != constr_CONST_3).
fof(ax4, axiom,
constr_A != constr_CONST_4).
fof(ax5, axiom,
constr_A != name_E).
fof(ax6, axiom,
constr_A != name_c).
fof(ax7, axiom,
constr_A != name_objective).
fof(ax8, axiom,
constr_A != name_skA).
fof(ax9, axiom,
constr_A != name_skS).
fof(ax10, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax11, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax12, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax13, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax14, axiom,
constr_CONST_0x30 != name_E).
fof(ax15, axiom,
constr_CONST_0x30 != name_c).
fof(ax16, axiom,
constr_CONST_0x30 != name_objective).
fof(ax17, axiom,
constr_CONST_0x30 != name_skA).
fof(ax18, axiom,
constr_CONST_0x30 != name_skS).
fof(ax19, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax20, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax21, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax22, axiom,
constr_CONST_1 != name_E).
fof(ax23, axiom,
constr_CONST_1 != name_c).
fof(ax24, axiom,
constr_CONST_1 != name_objective).
fof(ax25, axiom,
constr_CONST_1 != name_skA).
fof(ax26, axiom,
constr_CONST_1 != name_skS).
fof(ax27, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax28, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax29, axiom,
constr_CONST_2 != name_E).
fof(ax30, axiom,
constr_CONST_2 != name_c).
fof(ax31, axiom,
constr_CONST_2 != name_objective).
fof(ax32, axiom,
constr_CONST_2 != name_skA).
fof(ax33, axiom,
constr_CONST_2 != name_skS).
fof(ax34, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax35, axiom,
constr_CONST_3 != name_E).
fof(ax36, axiom,
constr_CONST_3 != name_c).
fof(ax37, axiom,
constr_CONST_3 != name_objective).
fof(ax38, axiom,
constr_CONST_3 != name_skA).
fof(ax39, axiom,
constr_CONST_3 != name_skS).
fof(ax40, axiom,
constr_CONST_4 != name_E).
fof(ax41, axiom,
constr_CONST_4 != name_c).
fof(ax42, axiom,
constr_CONST_4 != name_objective).
fof(ax43, axiom,
constr_CONST_4 != name_skA).
fof(ax44, axiom,
constr_CONST_4 != name_skS).
fof(ax45, axiom,
name_E != name_c).
fof(ax46, axiom,
name_E != name_objective).
fof(ax47, axiom,
name_E != name_skA).
fof(ax48, axiom,
name_E != name_skS).
fof(ax49, axiom,
name_c != name_objective).
fof(ax50, axiom,
name_c != name_skA).
fof(ax51, axiom,
name_c != name_skS).
fof(ax52, axiom,
name_objective != name_skA).
fof(ax53, axiom,
name_objective != name_skS).
fof(ax54, axiom,
name_skA != name_skS).
fof(ax55, axiom,
![VAR_K_17, VAR_M_16] : (constr_adec(constr_aenc(VAR_M_16, constr_pkey(VAR_K_17)), VAR_K_17) = VAR_M_16)).
fof(ax56, axiom,
![VAR_K_15, VAR_M_14] : (constr_dec(constr_enc(VAR_M_14, VAR_K_15), VAR_K_15) = VAR_M_14)).
fof(ax57, axiom,
![VAR_K_13, VAR_M_12] : (constr_getmess(constr_sign(VAR_M_12, VAR_K_13)) = VAR_M_12)).
fof(ax58, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_checksign(constr_sign(VAR_M_0X30, VAR_K_0X30), constr_pkey(VAR_K_0X30)) = VAR_M_0X30)).
fof(ax59, axiom,
![VAR_K_11, VAR_M_10X30] : (constr_checksign(constr_sign(VAR_M_10X30, VAR_K_11), constr_pkey(VAR_K_11)) = VAR_M_10X30)).
fof(ax60, axiom,
![VAR_X_9] : (constr_xor(constr_A, VAR_X_9) = VAR_X_9)).
fof(ax61, axiom,
![VAR_X0X30_7, VAR_X1_8] : (constr_tuple_2_get_0x30_bitstring(tuple_2(VAR_X0X30_7, VAR_X1_8)) = VAR_X0X30_7)).
fof(ax62, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30] : (constr_tuple_2_get_1(tuple_2(VAR_X0X30_0X30, VAR_X1_0X30)) = VAR_X1_0X30)).
fof(ax63, axiom,
![VAR_X_33, VAR_Y_34] : (pred_eq_bitstring_bitstring(VAR_X_33, VAR_Y_34))).
fof(ax64, axiom,
![VAR_V_41, VAR_V_42] : ((pred_attacker(VAR_V_41) & pred_attacker(VAR_V_42)) => pred_attacker(constr_xor(VAR_V_41, VAR_V_42)))).
fof(ax65, axiom,
![VAR_V_44] : (pred_attacker(VAR_V_44) => pred_attacker(constr_tuple_2_get_1(VAR_V_44)))).
fof(ax66, axiom,
![VAR_V_46] : (pred_attacker(VAR_V_46) => pred_attacker(constr_tuple_2_get_0x30_bitstring(VAR_V_46)))).
fof(ax67, axiom,
pred_attacker(tuple_true)).
fof(ax68, axiom,
![VAR_V_48] : (pred_attacker(VAR_V_48) => pred_attacker(constr_test(VAR_V_48)))).
fof(ax69, axiom,
![VAR_V_51, VAR_V_52] : ((pred_attacker(VAR_V_51) & pred_attacker(VAR_V_52)) => pred_attacker(constr_sign(VAR_V_51, VAR_V_52)))).
fof(ax70, axiom,
![VAR_V_54] : (pred_attacker(VAR_V_54) => pred_attacker(constr_pkey(VAR_V_54)))).
fof(ax71, axiom,
![VAR_V_56] : (pred_attacker(VAR_V_56) => pred_attacker(tuple_out_1(VAR_V_56)))).
fof(ax72, axiom,
![VAR_V_59] : (pred_attacker(tuple_out_1(VAR_V_59)) => pred_attacker(VAR_V_59))).
fof(ax73, axiom,
![VAR_V_63] : (pred_attacker(VAR_V_63) => pred_attacker(tuple_key_retrieval_server_out_1(VAR_V_63)))).
fof(ax74, axiom,
![VAR_V_66] : (pred_attacker(tuple_key_retrieval_server_out_1(VAR_V_66)) => pred_attacker(VAR_V_66))).
fof(ax75, axiom,
![VAR_V_70X30, VAR_V_71] : ((pred_attacker(VAR_V_70X30) & pred_attacker(VAR_V_71)) => pred_attacker(tuple_key_retrieval_server_in_1(VAR_V_70X30, VAR_V_71)))).
fof(ax76, axiom,
![VAR_V_78, VAR_V_79] : (pred_attacker(tuple_key_retrieval_server_in_1(VAR_V_78, VAR_V_79)) => pred_attacker(VAR_V_78))).
fof(ax77, axiom,
![VAR_V_81, VAR_V_82] : (pred_attacker(tuple_key_retrieval_server_in_1(VAR_V_81, VAR_V_82)) => pred_attacker(VAR_V_82))).
fof(ax78, axiom,
![VAR_V_86, VAR_V_87] : ((pred_attacker(VAR_V_86) & pred_attacker(VAR_V_87)) => pred_attacker(tuple_key_register_server_in_1(VAR_V_86, VAR_V_87)))).
fof(ax79, axiom,
![VAR_V_94, VAR_V_95] : (pred_attacker(tuple_key_register_server_in_1(VAR_V_94, VAR_V_95)) => pred_attacker(VAR_V_94))).
fof(ax80, axiom,
![VAR_V_97, VAR_V_98] : (pred_attacker(tuple_key_register_server_in_1(VAR_V_97, VAR_V_98)) => pred_attacker(VAR_V_98))).
fof(ax81, axiom,
![VAR_V_10X301] : (pred_attacker(VAR_V_10X301) => pred_attacker(constr_getmess(VAR_V_10X301)))).
fof(ax82, axiom,
pred_attacker(tuple_false)).
fof(ax83, axiom,
![VAR_V_10X304, VAR_V_10X305] : ((pred_attacker(VAR_V_10X304) & pred_attacker(VAR_V_10X305)) => pred_attacker(constr_enc(VAR_V_10X304, VAR_V_10X305)))).
fof(ax84, axiom,
![VAR_V_10X308, VAR_V_10X309] : ((pred_attacker(VAR_V_10X308) & pred_attacker(VAR_V_10X309)) => pred_attacker(constr_dec(VAR_V_10X308, VAR_V_10X309)))).
fof(ax85, axiom,
![VAR_V_111] : (pred_attacker(VAR_V_111) => pred_attacker(tuple_client_A_out_2(VAR_V_111)))).
fof(ax86, axiom,
![VAR_V_114] : (pred_attacker(tuple_client_A_out_2(VAR_V_114)) => pred_attacker(VAR_V_114))).
fof(ax87, axiom,
![VAR_V_118, VAR_V_119] : ((pred_attacker(VAR_V_118) & pred_attacker(VAR_V_119)) => pred_attacker(tuple_client_A_out_1(VAR_V_118, VAR_V_119)))).
fof(ax88, axiom,
![VAR_V_126, VAR_V_127] : (pred_attacker(tuple_client_A_out_1(VAR_V_126, VAR_V_127)) => pred_attacker(VAR_V_126))).
fof(ax89, axiom,
![VAR_V_129, VAR_V_130X30] : (pred_attacker(tuple_client_A_out_1(VAR_V_129, VAR_V_130X30)) => pred_attacker(VAR_V_130X30))).
fof(ax90, axiom,
![VAR_V_133] : (pred_attacker(VAR_V_133) => pred_attacker(tuple_client_A_in_2(VAR_V_133)))).
fof(ax91, axiom,
![VAR_V_136] : (pred_attacker(tuple_client_A_in_2(VAR_V_136)) => pred_attacker(VAR_V_136))).
fof(ax92, axiom,
![VAR_V_139] : (pred_attacker(VAR_V_139) => pred_attacker(tuple_client_A_in_1(VAR_V_139)))).
fof(ax93, axiom,
![VAR_V_142] : (pred_attacker(tuple_client_A_in_1(VAR_V_142)) => pred_attacker(VAR_V_142))).
fof(ax94, axiom,
![VAR_V_146, VAR_V_147] : ((pred_attacker(VAR_V_146) & pred_attacker(VAR_V_147)) => pred_attacker(constr_checksign(VAR_V_146, VAR_V_147)))).
fof(ax95, axiom,
![VAR_V_150X30, VAR_V_151] : ((pred_attacker(VAR_V_150X30) & pred_attacker(VAR_V_151)) => pred_attacker(constr_aenc(VAR_V_150X30, VAR_V_151)))).
fof(ax96, axiom,
![VAR_V_154, VAR_V_155] : ((pred_attacker(VAR_V_154) & pred_attacker(VAR_V_155)) => pred_attacker(constr_adec(VAR_V_154, VAR_V_155)))).
fof(ax97, axiom,
pred_attacker(constr_CONST_4)).
fof(ax98, axiom,
pred_attacker(constr_CONST_3)).
fof(ax99, axiom,
pred_attacker(constr_CONST_2)).
fof(ax100, axiom,
pred_attacker(constr_CONST_1)).
fof(ax101, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax102, axiom,
pred_attacker(constr_A)).
fof(ax103, axiom,
![VAR_V_162, VAR_V_163] : ((pred_attacker(VAR_V_162) & pred_attacker(VAR_V_163)) => pred_attacker(tuple_2(VAR_V_162, VAR_V_163)))).
fof(ax104, axiom,
![VAR_V_170X30, VAR_V_171] : (pred_attacker(tuple_2(VAR_V_170X30, VAR_V_171)) => pred_attacker(VAR_V_170X30))).
fof(ax105, axiom,
![VAR_V_173, VAR_V_174] : (pred_attacker(tuple_2(VAR_V_173, VAR_V_174)) => pred_attacker(VAR_V_174))).
fof(ax106, axiom,
![VAR_V_176, VAR_V_177] : ((pred_mess(VAR_V_177, VAR_V_176) & pred_attacker(VAR_V_177)) => pred_attacker(VAR_V_176))).
fof(ax107, axiom,
![VAR_V_178, VAR_V_179] : ((pred_attacker(VAR_V_179) & pred_attacker(VAR_V_178)) => pred_mess(VAR_V_179, VAR_V_178))).
fof(ax108, axiom,
pred_attacker(name_c)).
fof(ax109, axiom,
pred_attacker(name_E)).
fof(ax110, axiom,
![VAR_V_181] : (pred_equal(VAR_V_181, VAR_V_181))).
fof(ax111, axiom,
![VAR_V_182] : (pred_attacker(name_new0x2Dname(VAR_V_182)))).
fof(ax112, axiom,
pred_table(tuple_keys(constr_A, constr_pkey(name_skA)))).
fof(ax113, axiom,
pred_attacker(tuple_out_1(constr_pkey(name_skS)))).
fof(ax114, axiom,
![VAR_T_228] : (pred_attacker(tuple_client_A_in_1(VAR_T_228)) => pred_attacker(tuple_client_A_out_1(constr_A, VAR_T_228)))).
fof(ax115, axiom,
![VAR_T_275, VAR_SIGN_PKT_T_276] : ((pred_eq_bitstring_bitstring(VAR_T_275, constr_tuple_2_get_1(constr_checksign(VAR_SIGN_PKT_T_276, constr_pkey(name_skS)))) & pred_attacker(tuple_client_A_in_2(VAR_SIGN_PKT_T_276)) & pred_attacker(tuple_client_A_in_1(VAR_T_275))) => pred_attacker(tuple_client_A_out_2(constr_aenc(name_objective, constr_tuple_2_get_0x30_bitstring(constr_checksign(VAR_SIGN_PKT_T_276, constr_pkey(name_skS)))))))).
fof(ax116, axiom,
![VAR_DST_312, VAR_PKDST_313, VAR_SRC_314] : ((pred_table(tuple_keys(VAR_DST_312, VAR_PKDST_313)) & pred_attacker(tuple_key_retrieval_server_in_1(VAR_SRC_314, VAR_DST_312))) => pred_attacker(tuple_key_retrieval_server_out_1(constr_sign(tuple_2(VAR_PKDST_313, VAR_DST_312), name_skS))))).
fof(ax117, axiom,
![VAR_H_342, VAR_PKH_343] : ((VAR_H_342 != constr_A & pred_attacker(tuple_key_register_server_in_1(VAR_H_342, VAR_PKH_343))) => pred_table(tuple_keys(VAR_H_342, VAR_PKH_343)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
