%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax5, axiom,
constr_CONST_0x30 != name_c).
fof(ax6, axiom,
constr_CONST_0x30 != name_k).
fof(ax7, axiom,
constr_CONST_0x30 != name_objective_R).
fof(ax8, axiom,
constr_CONST_0x30 != name_r0x30).
fof(ax9, axiom,
constr_CONST_0x30 != name_r0x30_from_1st).
fof(ax10, axiom,
constr_CONST_0x30 != name_r1_from_1st).
fof(ax11, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax12, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax13, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax14, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax15, axiom,
constr_CONST_1 != name_c).
fof(ax16, axiom,
constr_CONST_1 != name_k).
fof(ax17, axiom,
constr_CONST_1 != name_objective_R).
fof(ax18, axiom,
constr_CONST_1 != name_r0x30).
fof(ax19, axiom,
constr_CONST_1 != name_r0x30_from_1st).
fof(ax20, axiom,
constr_CONST_1 != name_r1_from_1st).
fof(ax21, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax22, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax23, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax24, axiom,
constr_CONST_2 != name_c).
fof(ax25, axiom,
constr_CONST_2 != name_k).
fof(ax26, axiom,
constr_CONST_2 != name_objective_R).
fof(ax27, axiom,
constr_CONST_2 != name_r0x30).
fof(ax28, axiom,
constr_CONST_2 != name_r0x30_from_1st).
fof(ax29, axiom,
constr_CONST_2 != name_r1_from_1st).
fof(ax30, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax31, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax32, axiom,
constr_CONST_3 != name_c).
fof(ax33, axiom,
constr_CONST_3 != name_k).
fof(ax34, axiom,
constr_CONST_3 != name_objective_R).
fof(ax35, axiom,
constr_CONST_3 != name_r0x30).
fof(ax36, axiom,
constr_CONST_3 != name_r0x30_from_1st).
fof(ax37, axiom,
constr_CONST_3 != name_r1_from_1st).
fof(ax38, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax39, axiom,
constr_CONST_4 != name_c).
fof(ax40, axiom,
constr_CONST_4 != name_k).
fof(ax41, axiom,
constr_CONST_4 != name_objective_R).
fof(ax42, axiom,
constr_CONST_4 != name_r0x30).
fof(ax43, axiom,
constr_CONST_4 != name_r0x30_from_1st).
fof(ax44, axiom,
constr_CONST_4 != name_r1_from_1st).
fof(ax45, axiom,
constr_ZERO != name_c).
fof(ax46, axiom,
constr_ZERO != name_k).
fof(ax47, axiom,
constr_ZERO != name_objective_R).
fof(ax48, axiom,
constr_ZERO != name_r0x30).
fof(ax49, axiom,
constr_ZERO != name_r0x30_from_1st).
fof(ax50, axiom,
constr_ZERO != name_r1_from_1st).
fof(ax51, axiom,
name_c != name_k).
fof(ax52, axiom,
name_c != name_objective_R).
fof(ax53, axiom,
name_c != name_r0x30).
fof(ax54, axiom,
name_c != name_r0x30_from_1st).
fof(ax55, axiom,
name_c != name_r1_from_1st).
fof(ax56, axiom,
name_k != name_objective_R).
fof(ax57, axiom,
name_k != name_r0x30).
fof(ax58, axiom,
name_k != name_r0x30_from_1st).
fof(ax59, axiom,
name_k != name_r1_from_1st).
fof(ax60, axiom,
name_objective_R != name_r0x30).
fof(ax61, axiom,
name_objective_R != name_r0x30_from_1st).
fof(ax62, axiom,
name_objective_R != name_r1_from_1st).
fof(ax63, axiom,
name_r0x30 != name_r0x30_from_1st).
fof(ax64, axiom,
name_r0x30 != name_r1_from_1st).
fof(ax65, axiom,
name_r0x30_from_1st != name_r1_from_1st).
fof(ax66, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, VAR_X_10X30) = constr_ZERO)).
fof(ax67, axiom,
![VAR_X_9] : (constr_xor(VAR_X_9, constr_ZERO) = VAR_X_9)).
fof(ax68, axiom,
![VAR_X_7, VAR_Y_8] : (constr_xor(VAR_X_7, VAR_Y_8) = constr_xor(VAR_Y_8, VAR_X_7))).
fof(ax69, axiom,
![VAR_X_0X30, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_0X30, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_0X30, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax70, axiom,
![VAR_V_30X30, VAR_V_31] : ((pred_attacker(VAR_V_30X30) & pred_attacker(VAR_V_31)) => pred_attacker(constr_xor(VAR_V_30X30, VAR_V_31)))).
fof(ax71, axiom,
pred_attacker(tuple_true)).
fof(ax72, axiom,
![VAR_V_34] : (pred_attacker(VAR_V_34) => pred_attacker(tuple_knowledge_from_1st_round_out_3(VAR_V_34)))).
fof(ax73, axiom,
![VAR_V_37] : (pred_attacker(tuple_knowledge_from_1st_round_out_3(VAR_V_37)) => pred_attacker(VAR_V_37))).
fof(ax74, axiom,
![VAR_V_41, VAR_V_42] : ((pred_attacker(VAR_V_41) & pred_attacker(VAR_V_42)) => pred_attacker(tuple_knowledge_from_1st_round_out_2(VAR_V_41, VAR_V_42)))).
fof(ax75, axiom,
![VAR_V_49, VAR_V_50X30] : (pred_attacker(tuple_knowledge_from_1st_round_out_2(VAR_V_49, VAR_V_50X30)) => pred_attacker(VAR_V_49))).
fof(ax76, axiom,
![VAR_V_52, VAR_V_53] : (pred_attacker(tuple_knowledge_from_1st_round_out_2(VAR_V_52, VAR_V_53)) => pred_attacker(VAR_V_53))).
fof(ax77, axiom,
![VAR_V_56] : (pred_attacker(VAR_V_56) => pred_attacker(tuple_knowledge_from_1st_round_out_1(VAR_V_56)))).
fof(ax78, axiom,
![VAR_V_59] : (pred_attacker(tuple_knowledge_from_1st_round_out_1(VAR_V_59)) => pred_attacker(VAR_V_59))).
fof(ax79, axiom,
![VAR_V_62] : (pred_attacker(VAR_V_62) => pred_attacker(constr_h(VAR_V_62)))).
fof(ax80, axiom,
pred_attacker(tuple_false)).
fof(ax81, axiom,
pred_attacker(constr_ZERO)).
fof(ax82, axiom,
![VAR_V_64] : (pred_attacker(VAR_V_64) => pred_attacker(tuple_R_out_4(VAR_V_64)))).
fof(ax83, axiom,
![VAR_V_67] : (pred_attacker(tuple_R_out_4(VAR_V_67)) => pred_attacker(VAR_V_67))).
fof(ax84, axiom,
![VAR_V_70X30] : (pred_attacker(VAR_V_70X30) => pred_attacker(tuple_R_out_3(VAR_V_70X30)))).
fof(ax85, axiom,
![VAR_V_73] : (pred_attacker(tuple_R_out_3(VAR_V_73)) => pred_attacker(VAR_V_73))).
fof(ax86, axiom,
![VAR_V_76] : (pred_attacker(VAR_V_76) => pred_attacker(tuple_R_out_1(VAR_V_76)))).
fof(ax87, axiom,
![VAR_V_79] : (pred_attacker(tuple_R_out_1(VAR_V_79)) => pred_attacker(VAR_V_79))).
fof(ax88, axiom,
![VAR_V_83, VAR_V_84] : ((pred_attacker(VAR_V_83) & pred_attacker(VAR_V_84)) => pred_attacker(tuple_R_in_2(VAR_V_83, VAR_V_84)))).
fof(ax89, axiom,
![VAR_V_91, VAR_V_92] : (pred_attacker(tuple_R_in_2(VAR_V_91, VAR_V_92)) => pred_attacker(VAR_V_91))).
fof(ax90, axiom,
![VAR_V_94, VAR_V_95] : (pred_attacker(tuple_R_in_2(VAR_V_94, VAR_V_95)) => pred_attacker(VAR_V_95))).
fof(ax91, axiom,
pred_attacker(constr_CONST_4)).
fof(ax92, axiom,
pred_attacker(constr_CONST_3)).
fof(ax93, axiom,
pred_attacker(constr_CONST_2)).
fof(ax94, axiom,
pred_attacker(constr_CONST_1)).
fof(ax95, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax96, axiom,
![VAR_V_10X301, VAR_V_10X302] : ((pred_mess(VAR_V_10X302, VAR_V_10X301) & pred_attacker(VAR_V_10X302)) => pred_attacker(VAR_V_10X301))).
fof(ax97, axiom,
![VAR_V_10X303, VAR_V_10X304] : ((pred_attacker(VAR_V_10X304) & pred_attacker(VAR_V_10X303)) => pred_mess(VAR_V_10X304, VAR_V_10X303))).
fof(ax98, axiom,
pred_attacker(name_c)).
fof(ax99, axiom,
![VAR_V_10X306] : (pred_equal(VAR_V_10X306, VAR_V_10X306))).
fof(ax100, axiom,
![VAR_V_10X307] : (pred_attacker(name_new0x2Dname(VAR_V_10X307)))).
fof(ax101, axiom,
pred_attacker(tuple_knowledge_from_1st_round_out_1(name_r0x30_from_1st))).
fof(ax102, axiom,
pred_attacker(tuple_knowledge_from_1st_round_out_2(name_r1_from_1st, constr_h(constr_xor(constr_xor(name_r0x30_from_1st, name_r1_from_1st), name_k))))).
fof(ax103, axiom,
pred_attacker(tuple_knowledge_from_1st_round_out_3(constr_h(constr_xor(constr_xor(constr_h(constr_xor(constr_xor(name_r0x30_from_1st, name_r1_from_1st), name_k)), name_k), name_r0x30_from_1st))))).
fof(ax104, axiom,
pred_attacker(tuple_R_out_1(name_r0x30))).
fof(ax105, axiom,
![VAR_R1_IN_234] : (pred_attacker(tuple_R_in_2(VAR_R1_IN_234, constr_h(constr_xor(constr_xor(name_r0x30, VAR_R1_IN_234), name_k)))) => pred_attacker(tuple_R_out_3(constr_h(constr_xor(constr_xor(constr_h(constr_xor(constr_xor(name_r0x30, VAR_R1_IN_234), name_k)), name_k), name_r0x30)))))).
fof(ax106, axiom,
![VAR_R1_IN_244] : (pred_attacker(tuple_R_in_2(VAR_R1_IN_244, constr_h(constr_xor(constr_xor(name_r0x30, VAR_R1_IN_244), name_k)))) => pred_attacker(tuple_R_out_4(name_objective_R)))).
fof(co0, conjecture,
pred_attacker(name_objective_R)).
