%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_R_STEP_1).
fof(ax5, axiom,
constr_CONST_0x30 != constr_R_STEP_2).
fof(ax6, axiom,
constr_CONST_0x30 != constr_R_STEP_3).
fof(ax7, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax8, axiom,
constr_CONST_0x30 != constr_knowledge_from_1st_round_STEP_1).
fof(ax9, axiom,
constr_CONST_0x30 != constr_knowledge_from_1st_round_STEP_2).
fof(ax10, axiom,
constr_CONST_0x30 != constr_knowledge_from_1st_round_STEP_3).
fof(ax11, axiom,
constr_CONST_0x30 != name_c).
fof(ax12, axiom,
constr_CONST_0x30 != name_k).
fof(ax13, axiom,
constr_CONST_0x30 != name_objective_R).
fof(ax14, axiom,
constr_CONST_0x30 != name_r0x30).
fof(ax15, axiom,
constr_CONST_0x30 != name_r0x30_from_1st).
fof(ax16, axiom,
constr_CONST_0x30 != name_r1_from_1st).
fof(ax17, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax18, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax19, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax20, axiom,
constr_CONST_1 != constr_R_STEP_1).
fof(ax21, axiom,
constr_CONST_1 != constr_R_STEP_2).
fof(ax22, axiom,
constr_CONST_1 != constr_R_STEP_3).
fof(ax23, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax24, axiom,
constr_CONST_1 != constr_knowledge_from_1st_round_STEP_1).
fof(ax25, axiom,
constr_CONST_1 != constr_knowledge_from_1st_round_STEP_2).
fof(ax26, axiom,
constr_CONST_1 != constr_knowledge_from_1st_round_STEP_3).
fof(ax27, axiom,
constr_CONST_1 != name_c).
fof(ax28, axiom,
constr_CONST_1 != name_k).
fof(ax29, axiom,
constr_CONST_1 != name_objective_R).
fof(ax30, axiom,
constr_CONST_1 != name_r0x30).
fof(ax31, axiom,
constr_CONST_1 != name_r0x30_from_1st).
fof(ax32, axiom,
constr_CONST_1 != name_r1_from_1st).
fof(ax33, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax34, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax35, axiom,
constr_CONST_2 != constr_R_STEP_1).
fof(ax36, axiom,
constr_CONST_2 != constr_R_STEP_2).
fof(ax37, axiom,
constr_CONST_2 != constr_R_STEP_3).
fof(ax38, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax39, axiom,
constr_CONST_2 != constr_knowledge_from_1st_round_STEP_1).
fof(ax40, axiom,
constr_CONST_2 != constr_knowledge_from_1st_round_STEP_2).
fof(ax41, axiom,
constr_CONST_2 != constr_knowledge_from_1st_round_STEP_3).
fof(ax42, axiom,
constr_CONST_2 != name_c).
fof(ax43, axiom,
constr_CONST_2 != name_k).
fof(ax44, axiom,
constr_CONST_2 != name_objective_R).
fof(ax45, axiom,
constr_CONST_2 != name_r0x30).
fof(ax46, axiom,
constr_CONST_2 != name_r0x30_from_1st).
fof(ax47, axiom,
constr_CONST_2 != name_r1_from_1st).
fof(ax48, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax49, axiom,
constr_CONST_3 != constr_R_STEP_1).
fof(ax50, axiom,
constr_CONST_3 != constr_R_STEP_2).
fof(ax51, axiom,
constr_CONST_3 != constr_R_STEP_3).
fof(ax52, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax53, axiom,
constr_CONST_3 != constr_knowledge_from_1st_round_STEP_1).
fof(ax54, axiom,
constr_CONST_3 != constr_knowledge_from_1st_round_STEP_2).
fof(ax55, axiom,
constr_CONST_3 != constr_knowledge_from_1st_round_STEP_3).
fof(ax56, axiom,
constr_CONST_3 != name_c).
fof(ax57, axiom,
constr_CONST_3 != name_k).
fof(ax58, axiom,
constr_CONST_3 != name_objective_R).
fof(ax59, axiom,
constr_CONST_3 != name_r0x30).
fof(ax60, axiom,
constr_CONST_3 != name_r0x30_from_1st).
fof(ax61, axiom,
constr_CONST_3 != name_r1_from_1st).
fof(ax62, axiom,
constr_CONST_4 != constr_R_STEP_1).
fof(ax63, axiom,
constr_CONST_4 != constr_R_STEP_2).
fof(ax64, axiom,
constr_CONST_4 != constr_R_STEP_3).
fof(ax65, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax66, axiom,
constr_CONST_4 != constr_knowledge_from_1st_round_STEP_1).
fof(ax67, axiom,
constr_CONST_4 != constr_knowledge_from_1st_round_STEP_2).
fof(ax68, axiom,
constr_CONST_4 != constr_knowledge_from_1st_round_STEP_3).
fof(ax69, axiom,
constr_CONST_4 != name_c).
fof(ax70, axiom,
constr_CONST_4 != name_k).
fof(ax71, axiom,
constr_CONST_4 != name_objective_R).
fof(ax72, axiom,
constr_CONST_4 != name_r0x30).
fof(ax73, axiom,
constr_CONST_4 != name_r0x30_from_1st).
fof(ax74, axiom,
constr_CONST_4 != name_r1_from_1st).
fof(ax75, axiom,
constr_R_STEP_1 != constr_R_STEP_2).
fof(ax76, axiom,
constr_R_STEP_1 != constr_R_STEP_3).
fof(ax77, axiom,
constr_R_STEP_1 != constr_ZERO).
fof(ax78, axiom,
constr_R_STEP_1 != constr_knowledge_from_1st_round_STEP_1).
fof(ax79, axiom,
constr_R_STEP_1 != constr_knowledge_from_1st_round_STEP_2).
fof(ax80, axiom,
constr_R_STEP_1 != constr_knowledge_from_1st_round_STEP_3).
fof(ax81, axiom,
constr_R_STEP_1 != name_c).
fof(ax82, axiom,
constr_R_STEP_1 != name_k).
fof(ax83, axiom,
constr_R_STEP_1 != name_objective_R).
fof(ax84, axiom,
constr_R_STEP_1 != name_r0x30).
fof(ax85, axiom,
constr_R_STEP_1 != name_r0x30_from_1st).
fof(ax86, axiom,
constr_R_STEP_1 != name_r1_from_1st).
fof(ax87, axiom,
constr_R_STEP_2 != constr_R_STEP_3).
fof(ax88, axiom,
constr_R_STEP_2 != constr_ZERO).
fof(ax89, axiom,
constr_R_STEP_2 != constr_knowledge_from_1st_round_STEP_1).
fof(ax90, axiom,
constr_R_STEP_2 != constr_knowledge_from_1st_round_STEP_2).
fof(ax91, axiom,
constr_R_STEP_2 != constr_knowledge_from_1st_round_STEP_3).
fof(ax92, axiom,
constr_R_STEP_2 != name_c).
fof(ax93, axiom,
constr_R_STEP_2 != name_k).
fof(ax94, axiom,
constr_R_STEP_2 != name_objective_R).
fof(ax95, axiom,
constr_R_STEP_2 != name_r0x30).
fof(ax96, axiom,
constr_R_STEP_2 != name_r0x30_from_1st).
fof(ax97, axiom,
constr_R_STEP_2 != name_r1_from_1st).
fof(ax98, axiom,
constr_R_STEP_3 != constr_ZERO).
fof(ax99, axiom,
constr_R_STEP_3 != constr_knowledge_from_1st_round_STEP_1).
fof(ax100, axiom,
constr_R_STEP_3 != constr_knowledge_from_1st_round_STEP_2).
fof(ax101, axiom,
constr_R_STEP_3 != constr_knowledge_from_1st_round_STEP_3).
fof(ax102, axiom,
constr_R_STEP_3 != name_c).
fof(ax103, axiom,
constr_R_STEP_3 != name_k).
fof(ax104, axiom,
constr_R_STEP_3 != name_objective_R).
fof(ax105, axiom,
constr_R_STEP_3 != name_r0x30).
fof(ax106, axiom,
constr_R_STEP_3 != name_r0x30_from_1st).
fof(ax107, axiom,
constr_R_STEP_3 != name_r1_from_1st).
fof(ax108, axiom,
constr_ZERO != constr_knowledge_from_1st_round_STEP_1).
fof(ax109, axiom,
constr_ZERO != constr_knowledge_from_1st_round_STEP_2).
fof(ax110, axiom,
constr_ZERO != constr_knowledge_from_1st_round_STEP_3).
fof(ax111, axiom,
constr_ZERO != name_c).
fof(ax112, axiom,
constr_ZERO != name_k).
fof(ax113, axiom,
constr_ZERO != name_objective_R).
fof(ax114, axiom,
constr_ZERO != name_r0x30).
fof(ax115, axiom,
constr_ZERO != name_r0x30_from_1st).
fof(ax116, axiom,
constr_ZERO != name_r1_from_1st).
fof(ax117, axiom,
constr_knowledge_from_1st_round_STEP_1 != constr_knowledge_from_1st_round_STEP_2).
fof(ax118, axiom,
constr_knowledge_from_1st_round_STEP_1 != constr_knowledge_from_1st_round_STEP_3).
fof(ax119, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_c).
fof(ax120, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_k).
fof(ax121, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_objective_R).
fof(ax122, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_r0x30).
fof(ax123, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_r0x30_from_1st).
fof(ax124, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_r1_from_1st).
fof(ax125, axiom,
constr_knowledge_from_1st_round_STEP_2 != constr_knowledge_from_1st_round_STEP_3).
fof(ax126, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_c).
fof(ax127, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_k).
fof(ax128, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_objective_R).
fof(ax129, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_r0x30).
fof(ax130, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_r0x30_from_1st).
fof(ax131, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_r1_from_1st).
fof(ax132, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_c).
fof(ax133, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_k).
fof(ax134, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_objective_R).
fof(ax135, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_r0x30).
fof(ax136, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_r0x30_from_1st).
fof(ax137, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_r1_from_1st).
fof(ax138, axiom,
name_c != name_k).
fof(ax139, axiom,
name_c != name_objective_R).
fof(ax140, axiom,
name_c != name_r0x30).
fof(ax141, axiom,
name_c != name_r0x30_from_1st).
fof(ax142, axiom,
name_c != name_r1_from_1st).
fof(ax143, axiom,
name_k != name_objective_R).
fof(ax144, axiom,
name_k != name_r0x30).
fof(ax145, axiom,
name_k != name_r0x30_from_1st).
fof(ax146, axiom,
name_k != name_r1_from_1st).
fof(ax147, axiom,
name_objective_R != name_r0x30).
fof(ax148, axiom,
name_objective_R != name_r0x30_from_1st).
fof(ax149, axiom,
name_objective_R != name_r1_from_1st).
fof(ax150, axiom,
name_r0x30 != name_r0x30_from_1st).
fof(ax151, axiom,
name_r0x30 != name_r1_from_1st).
fof(ax152, axiom,
name_r0x30_from_1st != name_r1_from_1st).
fof(ax153, axiom,
![VAR_X_11] : (constr_xor(VAR_X_11, VAR_X_11) = constr_ZERO)).
fof(ax154, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, constr_ZERO) = VAR_X_10X30)).
fof(ax155, axiom,
![VAR_X_8, VAR_Y_9] : (constr_xor(VAR_X_8, VAR_Y_9) = constr_xor(VAR_Y_9, VAR_X_8))).
fof(ax156, axiom,
![VAR_X_7, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_7, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_7, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax157, axiom,
![VAR_X_27] : (pred_eq(VAR_X_27, VAR_X_27))).
fof(ax158, axiom,
![VAR_V_34, VAR_V_35] : ((pred_attacker(VAR_V_34) & pred_attacker(VAR_V_35)) => pred_attacker(constr_xor(VAR_V_34, VAR_V_35)))).
fof(ax159, axiom,
pred_attacker(tuple_true)).
fof(ax160, axiom,
pred_attacker(constr_knowledge_from_1st_round_STEP_3)).
fof(ax161, axiom,
pred_attacker(constr_knowledge_from_1st_round_STEP_2)).
fof(ax162, axiom,
pred_attacker(constr_knowledge_from_1st_round_STEP_1)).
fof(ax163, axiom,
![VAR_V_38] : (pred_attacker(VAR_V_38) => pred_attacker(constr_h(VAR_V_38)))).
fof(ax164, axiom,
pred_attacker(tuple_false)).
fof(ax165, axiom,
pred_attacker(constr_ZERO)).
fof(ax166, axiom,
pred_attacker(constr_R_STEP_3)).
fof(ax167, axiom,
pred_attacker(constr_R_STEP_2)).
fof(ax168, axiom,
pred_attacker(constr_R_STEP_1)).
fof(ax169, axiom,
pred_attacker(constr_CONST_4)).
fof(ax170, axiom,
pred_attacker(constr_CONST_3)).
fof(ax171, axiom,
pred_attacker(constr_CONST_2)).
fof(ax172, axiom,
pred_attacker(constr_CONST_1)).
fof(ax173, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax174, axiom,
![VAR_V_45, VAR_V_46] : ((pred_attacker(VAR_V_45) & pred_attacker(VAR_V_46)) => pred_attacker(tuple_2(VAR_V_45, VAR_V_46)))).
fof(ax175, axiom,
![VAR_V_53, VAR_V_54] : (pred_attacker(tuple_2(VAR_V_53, VAR_V_54)) => pred_attacker(VAR_V_53))).
fof(ax176, axiom,
![VAR_V_56, VAR_V_57] : (pred_attacker(tuple_2(VAR_V_56, VAR_V_57)) => pred_attacker(VAR_V_57))).
fof(ax177, axiom,
![VAR_V_59, VAR_V_60X30] : ((pred_mess(VAR_V_60X30, VAR_V_59) & pred_attacker(VAR_V_60X30)) => pred_attacker(VAR_V_59))).
fof(ax178, axiom,
![VAR_V_61, VAR_V_62] : ((pred_attacker(VAR_V_62) & pred_attacker(VAR_V_61)) => pred_mess(VAR_V_62, VAR_V_61))).
fof(ax179, axiom,
pred_attacker(name_c)).
fof(ax180, axiom,
![VAR_V_64] : (pred_equal(VAR_V_64, VAR_V_64))).
fof(ax181, axiom,
![VAR_V_65] : (pred_attacker(name_new0x2Dname(VAR_V_65)))).
fof(ax182, axiom,
pred_attacker(tuple_2(name_r0x30_from_1st, constr_knowledge_from_1st_round_STEP_1))).
fof(ax183, axiom,
pred_attacker(tuple_2(tuple_2(name_r1_from_1st, constr_h(constr_xor(constr_xor(name_r0x30_from_1st, name_r1_from_1st), name_k))), constr_knowledge_from_1st_round_STEP_2))).
fof(ax184, axiom,
pred_attacker(tuple_2(constr_h(constr_xor(constr_xor(constr_h(constr_xor(constr_xor(name_r0x30_from_1st, name_r1_from_1st), name_k)), name_k), name_r0x30_from_1st)), constr_knowledge_from_1st_round_STEP_3))).
fof(ax185, axiom,
pred_attacker(tuple_2(name_r0x30, constr_R_STEP_1))).
fof(ax186, axiom,
![VAR_R1_IN_224] : (pred_attacker(tuple_2(VAR_R1_IN_224, constr_h(constr_xor(constr_xor(name_r0x30, VAR_R1_IN_224), name_k)))) => pred_attacker(tuple_2(constr_h(constr_xor(constr_xor(constr_h(constr_xor(constr_xor(name_r0x30, VAR_R1_IN_224), name_k)), name_k), name_r0x30)), constr_R_STEP_2)))).
fof(ax187, axiom,
![VAR_R1_IN_240X30] : (pred_attacker(tuple_2(VAR_R1_IN_240X30, constr_h(constr_xor(constr_xor(name_r0x30, VAR_R1_IN_240X30), name_k)))) => pred_attacker(tuple_2(name_objective_R, constr_R_STEP_3)))).
fof(co0, conjecture,
pred_attacker(name_objective_R)).
