%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax5, axiom,
constr_CONST_0x30 != name_c).
fof(ax6, axiom,
constr_CONST_0x30 != name_k0x30).
fof(ax7, axiom,
constr_CONST_0x30 != name_ki).
fof(ax8, axiom,
constr_CONST_0x30 != name_objective).
fof(ax9, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax10, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax11, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax12, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax13, axiom,
constr_CONST_1 != name_c).
fof(ax14, axiom,
constr_CONST_1 != name_k0x30).
fof(ax15, axiom,
constr_CONST_1 != name_ki).
fof(ax16, axiom,
constr_CONST_1 != name_objective).
fof(ax17, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax18, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax19, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax20, axiom,
constr_CONST_2 != name_c).
fof(ax21, axiom,
constr_CONST_2 != name_k0x30).
fof(ax22, axiom,
constr_CONST_2 != name_ki).
fof(ax23, axiom,
constr_CONST_2 != name_objective).
fof(ax24, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax25, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax26, axiom,
constr_CONST_3 != name_c).
fof(ax27, axiom,
constr_CONST_3 != name_k0x30).
fof(ax28, axiom,
constr_CONST_3 != name_ki).
fof(ax29, axiom,
constr_CONST_3 != name_objective).
fof(ax30, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax31, axiom,
constr_CONST_4 != name_c).
fof(ax32, axiom,
constr_CONST_4 != name_k0x30).
fof(ax33, axiom,
constr_CONST_4 != name_ki).
fof(ax34, axiom,
constr_CONST_4 != name_objective).
fof(ax35, axiom,
constr_ZERO != name_c).
fof(ax36, axiom,
constr_ZERO != name_k0x30).
fof(ax37, axiom,
constr_ZERO != name_ki).
fof(ax38, axiom,
constr_ZERO != name_objective).
fof(ax39, axiom,
name_c != name_k0x30).
fof(ax40, axiom,
name_c != name_ki).
fof(ax41, axiom,
name_c != name_objective).
fof(ax42, axiom,
name_k0x30 != name_ki).
fof(ax43, axiom,
name_k0x30 != name_objective).
fof(ax44, axiom,
name_ki != name_objective).
fof(ax45, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, VAR_X_10X30) = constr_ZERO)).
fof(ax46, axiom,
![VAR_X_9] : (constr_xor(VAR_X_9, constr_ZERO) = VAR_X_9)).
fof(ax47, axiom,
![VAR_X_7, VAR_Y_8] : (constr_xor(VAR_X_7, VAR_Y_8) = constr_xor(VAR_Y_8, VAR_X_7))).
fof(ax48, axiom,
![VAR_X_0X30, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_0X30, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_0X30, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax49, axiom,
![VAR_V_29, VAR_V_30X30] : ((pred_attacker(VAR_V_29) & pred_attacker(VAR_V_30X30)) => pred_attacker(constr_xor(VAR_V_29, VAR_V_30X30)))).
fof(ax50, axiom,
pred_attacker(tuple_true)).
fof(ax51, axiom,
![VAR_V_33] : (pred_attacker(VAR_V_33) => pred_attacker(constr_h(VAR_V_33)))).
fof(ax52, axiom,
pred_attacker(tuple_false)).
fof(ax53, axiom,
pred_attacker(constr_ZERO)).
fof(ax54, axiom,
![VAR_V_35] : (pred_attacker(VAR_V_35) => pred_attacker(tuple_T_out_4(VAR_V_35)))).
fof(ax55, axiom,
![VAR_V_38] : (pred_attacker(tuple_T_out_4(VAR_V_38)) => pred_attacker(VAR_V_38))).
fof(ax56, axiom,
![VAR_V_41] : (pred_attacker(VAR_V_41) => pred_attacker(tuple_T_out_2(VAR_V_41)))).
fof(ax57, axiom,
![VAR_V_44] : (pred_attacker(tuple_T_out_2(VAR_V_44)) => pred_attacker(VAR_V_44))).
fof(ax58, axiom,
![VAR_V_48, VAR_V_49] : ((pred_attacker(VAR_V_48) & pred_attacker(VAR_V_49)) => pred_attacker(tuple_T_in_3(VAR_V_48, VAR_V_49)))).
fof(ax59, axiom,
![VAR_V_56, VAR_V_57] : (pred_attacker(tuple_T_in_3(VAR_V_56, VAR_V_57)) => pred_attacker(VAR_V_56))).
fof(ax60, axiom,
![VAR_V_59, VAR_V_60X30] : (pred_attacker(tuple_T_in_3(VAR_V_59, VAR_V_60X30)) => pred_attacker(VAR_V_60X30))).
fof(ax61, axiom,
![VAR_V_63] : (pred_attacker(VAR_V_63) => pred_attacker(tuple_T_in_1(VAR_V_63)))).
fof(ax62, axiom,
![VAR_V_66] : (pred_attacker(tuple_T_in_1(VAR_V_66)) => pred_attacker(VAR_V_66))).
fof(ax63, axiom,
pred_attacker(constr_CONST_4)).
fof(ax64, axiom,
pred_attacker(constr_CONST_3)).
fof(ax65, axiom,
pred_attacker(constr_CONST_2)).
fof(ax66, axiom,
pred_attacker(constr_CONST_1)).
fof(ax67, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax68, axiom,
![VAR_V_72, VAR_V_73] : ((pred_mess(VAR_V_73, VAR_V_72) & pred_attacker(VAR_V_73)) => pred_attacker(VAR_V_72))).
fof(ax69, axiom,
![VAR_V_74, VAR_V_75] : ((pred_attacker(VAR_V_75) & pred_attacker(VAR_V_74)) => pred_mess(VAR_V_75, VAR_V_74))).
fof(ax70, axiom,
pred_attacker(name_c)).
fof(ax71, axiom,
![VAR_V_77] : (pred_equal(VAR_V_77, VAR_V_77))).
fof(ax72, axiom,
![VAR_V_78] : (pred_attacker(name_new0x2Dname(VAR_V_78)))).
fof(ax73, axiom,
![VAR_R_10X308] : (pred_attacker(tuple_T_in_1(VAR_R_10X308)) => pred_attacker(tuple_T_out_2(constr_h(constr_xor(VAR_R_10X308, constr_xor(name_k0x30, name_ki))))))).
fof(ax74, axiom,
![VAR_A_143, VAR_R_144] : ((pred_attacker(tuple_T_in_3(VAR_A_143, constr_h(constr_xor(VAR_A_143, constr_xor(name_k0x30, name_ki))))) & pred_attacker(tuple_T_in_1(VAR_R_144))) => pred_attacker(tuple_T_out_4(name_objective)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
