%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_client_A_STEP_1).
fof(ax5, axiom,
constr_CONST_0x30 != constr_client_A_STEP_2).
fof(ax6, axiom,
constr_CONST_0x30 != constr_client_A_STEP_3).
fof(ax7, axiom,
constr_CONST_0x30 != constr_client_B_STEP_1).
fof(ax8, axiom,
constr_CONST_0x30 != constr_server_S_STEP_1).
fof(ax9, axiom,
constr_CONST_0x30 != name_A).
fof(ax10, axiom,
constr_CONST_0x30 != name_B).
fof(ax11, axiom,
constr_CONST_0x30 != name_I).
fof(ax12, axiom,
constr_CONST_0x30 != name_Kas).
fof(ax13, axiom,
constr_CONST_0x30 != name_Kbs).
fof(ax14, axiom,
constr_CONST_0x30 != name_c).
fof(ax15, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax16, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax17, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax18, axiom,
constr_CONST_1 != constr_client_A_STEP_1).
fof(ax19, axiom,
constr_CONST_1 != constr_client_A_STEP_2).
fof(ax20, axiom,
constr_CONST_1 != constr_client_A_STEP_3).
fof(ax21, axiom,
constr_CONST_1 != constr_client_B_STEP_1).
fof(ax22, axiom,
constr_CONST_1 != constr_server_S_STEP_1).
fof(ax23, axiom,
constr_CONST_1 != name_A).
fof(ax24, axiom,
constr_CONST_1 != name_B).
fof(ax25, axiom,
constr_CONST_1 != name_I).
fof(ax26, axiom,
constr_CONST_1 != name_Kas).
fof(ax27, axiom,
constr_CONST_1 != name_Kbs).
fof(ax28, axiom,
constr_CONST_1 != name_c).
fof(ax29, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax30, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax31, axiom,
constr_CONST_2 != constr_client_A_STEP_1).
fof(ax32, axiom,
constr_CONST_2 != constr_client_A_STEP_2).
fof(ax33, axiom,
constr_CONST_2 != constr_client_A_STEP_3).
fof(ax34, axiom,
constr_CONST_2 != constr_client_B_STEP_1).
fof(ax35, axiom,
constr_CONST_2 != constr_server_S_STEP_1).
fof(ax36, axiom,
constr_CONST_2 != name_A).
fof(ax37, axiom,
constr_CONST_2 != name_B).
fof(ax38, axiom,
constr_CONST_2 != name_I).
fof(ax39, axiom,
constr_CONST_2 != name_Kas).
fof(ax40, axiom,
constr_CONST_2 != name_Kbs).
fof(ax41, axiom,
constr_CONST_2 != name_c).
fof(ax42, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax43, axiom,
constr_CONST_3 != constr_client_A_STEP_1).
fof(ax44, axiom,
constr_CONST_3 != constr_client_A_STEP_2).
fof(ax45, axiom,
constr_CONST_3 != constr_client_A_STEP_3).
fof(ax46, axiom,
constr_CONST_3 != constr_client_B_STEP_1).
fof(ax47, axiom,
constr_CONST_3 != constr_server_S_STEP_1).
fof(ax48, axiom,
constr_CONST_3 != name_A).
fof(ax49, axiom,
constr_CONST_3 != name_B).
fof(ax50, axiom,
constr_CONST_3 != name_I).
fof(ax51, axiom,
constr_CONST_3 != name_Kas).
fof(ax52, axiom,
constr_CONST_3 != name_Kbs).
fof(ax53, axiom,
constr_CONST_3 != name_c).
fof(ax54, axiom,
constr_CONST_4 != constr_client_A_STEP_1).
fof(ax55, axiom,
constr_CONST_4 != constr_client_A_STEP_2).
fof(ax56, axiom,
constr_CONST_4 != constr_client_A_STEP_3).
fof(ax57, axiom,
constr_CONST_4 != constr_client_B_STEP_1).
fof(ax58, axiom,
constr_CONST_4 != constr_server_S_STEP_1).
fof(ax59, axiom,
constr_CONST_4 != name_A).
fof(ax60, axiom,
constr_CONST_4 != name_B).
fof(ax61, axiom,
constr_CONST_4 != name_I).
fof(ax62, axiom,
constr_CONST_4 != name_Kas).
fof(ax63, axiom,
constr_CONST_4 != name_Kbs).
fof(ax64, axiom,
constr_CONST_4 != name_c).
fof(ax65, axiom,
constr_client_A_STEP_1 != constr_client_A_STEP_2).
fof(ax66, axiom,
constr_client_A_STEP_1 != constr_client_A_STEP_3).
fof(ax67, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_1).
fof(ax68, axiom,
constr_client_A_STEP_1 != constr_server_S_STEP_1).
fof(ax69, axiom,
constr_client_A_STEP_1 != name_A).
fof(ax70, axiom,
constr_client_A_STEP_1 != name_B).
fof(ax71, axiom,
constr_client_A_STEP_1 != name_I).
fof(ax72, axiom,
constr_client_A_STEP_1 != name_Kas).
fof(ax73, axiom,
constr_client_A_STEP_1 != name_Kbs).
fof(ax74, axiom,
constr_client_A_STEP_1 != name_c).
fof(ax75, axiom,
constr_client_A_STEP_2 != constr_client_A_STEP_3).
fof(ax76, axiom,
constr_client_A_STEP_2 != constr_client_B_STEP_1).
fof(ax77, axiom,
constr_client_A_STEP_2 != constr_server_S_STEP_1).
fof(ax78, axiom,
constr_client_A_STEP_2 != name_A).
fof(ax79, axiom,
constr_client_A_STEP_2 != name_B).
fof(ax80, axiom,
constr_client_A_STEP_2 != name_I).
fof(ax81, axiom,
constr_client_A_STEP_2 != name_Kas).
fof(ax82, axiom,
constr_client_A_STEP_2 != name_Kbs).
fof(ax83, axiom,
constr_client_A_STEP_2 != name_c).
fof(ax84, axiom,
constr_client_A_STEP_3 != constr_client_B_STEP_1).
fof(ax85, axiom,
constr_client_A_STEP_3 != constr_server_S_STEP_1).
fof(ax86, axiom,
constr_client_A_STEP_3 != name_A).
fof(ax87, axiom,
constr_client_A_STEP_3 != name_B).
fof(ax88, axiom,
constr_client_A_STEP_3 != name_I).
fof(ax89, axiom,
constr_client_A_STEP_3 != name_Kas).
fof(ax90, axiom,
constr_client_A_STEP_3 != name_Kbs).
fof(ax91, axiom,
constr_client_A_STEP_3 != name_c).
fof(ax92, axiom,
constr_client_B_STEP_1 != constr_server_S_STEP_1).
fof(ax93, axiom,
constr_client_B_STEP_1 != name_A).
fof(ax94, axiom,
constr_client_B_STEP_1 != name_B).
fof(ax95, axiom,
constr_client_B_STEP_1 != name_I).
fof(ax96, axiom,
constr_client_B_STEP_1 != name_Kas).
fof(ax97, axiom,
constr_client_B_STEP_1 != name_Kbs).
fof(ax98, axiom,
constr_client_B_STEP_1 != name_c).
fof(ax99, axiom,
constr_server_S_STEP_1 != name_A).
fof(ax100, axiom,
constr_server_S_STEP_1 != name_B).
fof(ax101, axiom,
constr_server_S_STEP_1 != name_I).
fof(ax102, axiom,
constr_server_S_STEP_1 != name_Kas).
fof(ax103, axiom,
constr_server_S_STEP_1 != name_Kbs).
fof(ax104, axiom,
constr_server_S_STEP_1 != name_c).
fof(ax105, axiom,
name_A != name_B).
fof(ax106, axiom,
name_A != name_I).
fof(ax107, axiom,
name_A != name_Kas).
fof(ax108, axiom,
name_A != name_Kbs).
fof(ax109, axiom,
name_A != name_c).
fof(ax110, axiom,
name_B != name_I).
fof(ax111, axiom,
name_B != name_Kas).
fof(ax112, axiom,
name_B != name_Kbs).
fof(ax113, axiom,
name_B != name_c).
fof(ax114, axiom,
name_I != name_Kas).
fof(ax115, axiom,
name_I != name_Kbs).
fof(ax116, axiom,
name_I != name_c).
fof(ax117, axiom,
name_Kas != name_Kbs).
fof(ax118, axiom,
name_Kas != name_c).
fof(ax119, axiom,
name_Kbs != name_c).
fof(ax120, axiom,
![VAR_K_61, VAR_X0X30_57, VAR_X1_58, VAR_X2_59, VAR_X3_60X30] : (constr_cbc_dec_4(constr_cbc_enc_4(VAR_X0X30_57, VAR_X1_58, VAR_X2_59, VAR_X3_60X30, VAR_K_61), VAR_K_61) = tuple_4(VAR_X0X30_57, VAR_X1_58, VAR_X2_59, VAR_X3_60X30))).
fof(ax121, axiom,
![VAR_K_56, VAR_X0X30_53, VAR_X1_54, VAR_X2_55] : (constr_cbc_dec_3(constr_cbc_enc_3(VAR_X0X30_53, VAR_X1_54, VAR_X2_55, VAR_K_56), VAR_K_56) = tuple_3(VAR_X0X30_53, VAR_X1_54, VAR_X2_55))).
fof(ax122, axiom,
![VAR_K_52, VAR_X0X30_50X30, VAR_X1_51] : (constr_cbc_dec_2(constr_cbc_enc_2(VAR_X0X30_50X30, VAR_X1_51, VAR_K_52), VAR_K_52) = tuple_2(VAR_X0X30_50X30, VAR_X1_51))).
fof(ax123, axiom,
![VAR_K_49, VAR_X0X30_48] : (constr_cbc_dec_1(constr_cbc_enc_1(VAR_X0X30_48, VAR_K_49), VAR_K_49) = VAR_X0X30_48)).
fof(ax124, axiom,
![VAR_K_47, VAR_X0X30_43, VAR_X1_44, VAR_X2_45, VAR_X3_46] : (constr_cbc_4_get_3_prefixes(constr_cbc_enc_4(VAR_X0X30_43, VAR_X1_44, VAR_X2_45, VAR_X3_46, VAR_K_47)) = constr_cbc_enc_3(VAR_X0X30_43, VAR_X1_44, VAR_X2_45, VAR_K_47))).
fof(ax125, axiom,
![VAR_K_42, VAR_X0X30_38, VAR_X1_39, VAR_X2_40X30, VAR_X3_41] : (constr_cbc_4_get_2_prefixes(constr_cbc_enc_4(VAR_X0X30_38, VAR_X1_39, VAR_X2_40X30, VAR_X3_41, VAR_K_42)) = constr_cbc_enc_2(VAR_X0X30_38, VAR_X1_39, VAR_K_42))).
fof(ax126, axiom,
![VAR_K_37, VAR_X0X30_33, VAR_X1_34, VAR_X2_35, VAR_X3_36] : (constr_cbc_4_get_1_prefixes(constr_cbc_enc_4(VAR_X0X30_33, VAR_X1_34, VAR_X2_35, VAR_X3_36, VAR_K_37)) = constr_cbc_enc_1(VAR_X0X30_33, VAR_K_37))).
fof(ax127, axiom,
![VAR_K_32, VAR_X0X30_29, VAR_X1_30X30, VAR_X2_31] : (constr_cbc_3_get_2_prefixes(constr_cbc_enc_3(VAR_X0X30_29, VAR_X1_30X30, VAR_X2_31, VAR_K_32)) = constr_cbc_enc_2(VAR_X0X30_29, VAR_X1_30X30, VAR_K_32))).
fof(ax128, axiom,
![VAR_K_28, VAR_X0X30_25, VAR_X1_26, VAR_X2_27] : (constr_cbc_3_get_1_prefixes(constr_cbc_enc_3(VAR_X0X30_25, VAR_X1_26, VAR_X2_27, VAR_K_28)) = constr_cbc_enc_1(VAR_X0X30_25, VAR_K_28))).
fof(ax129, axiom,
![VAR_K_0X30, VAR_X0X30_23, VAR_X1_24] : (constr_cbc_2_get_1_prefixes(constr_cbc_enc_2(VAR_X0X30_23, VAR_X1_24, VAR_K_0X30)) = constr_cbc_enc_1(VAR_X0X30_23, VAR_K_0X30))).
fof(ax130, axiom,
![VAR_X0X30_19, VAR_X1_20X30, VAR_X2_21, VAR_X3_22] : (constr_tuple_4_get_3(tuple_4(VAR_X0X30_19, VAR_X1_20X30, VAR_X2_21, VAR_X3_22)) = VAR_X3_22)).
fof(ax131, axiom,
![VAR_X0X30_15, VAR_X1_16, VAR_X2_17, VAR_X3_18] : (constr_tuple_4_get_2(tuple_4(VAR_X0X30_15, VAR_X1_16, VAR_X2_17, VAR_X3_18)) = VAR_X2_17)).
fof(ax132, axiom,
![VAR_X0X30_11, VAR_X1_12, VAR_X2_13, VAR_X3_14] : (constr_tuple_4_get_1(tuple_4(VAR_X0X30_11, VAR_X1_12, VAR_X2_13, VAR_X3_14)) = VAR_X1_12)).
fof(ax133, axiom,
![VAR_X0X30_9, VAR_X1_10X30, VAR_X2_0X30, VAR_X3_0X30] : (constr_tuple_4_get_0x30(tuple_4(VAR_X0X30_9, VAR_X1_10X30, VAR_X2_0X30, VAR_X3_0X30)) = VAR_X0X30_9)).
fof(ax134, axiom,
![VAR_X0X30_7, VAR_X1_8] : (constr_tuple_2_get_1(tuple_2(VAR_X0X30_7, VAR_X1_8)) = VAR_X1_8)).
fof(ax135, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30] : (constr_tuple_2_get_0x30(tuple_2(VAR_X0X30_0X30, VAR_X1_0X30)) = VAR_X0X30_0X30)).
fof(ax136, axiom,
![VAR_X_81] : (pred_eq(VAR_X_81, VAR_X_81))).
fof(ax137, axiom,
![VAR_V_87] : (pred_attacker(VAR_V_87) => pred_attacker(constr_tuple_4_get_3(VAR_V_87)))).
fof(ax138, axiom,
![VAR_V_89] : (pred_attacker(VAR_V_89) => pred_attacker(constr_tuple_4_get_2(VAR_V_89)))).
fof(ax139, axiom,
![VAR_V_91] : (pred_attacker(VAR_V_91) => pred_attacker(constr_tuple_4_get_1(VAR_V_91)))).
fof(ax140, axiom,
![VAR_V_93] : (pred_attacker(VAR_V_93) => pred_attacker(constr_tuple_4_get_0x30(VAR_V_93)))).
fof(ax141, axiom,
![VAR_V_95] : (pred_attacker(VAR_V_95) => pred_attacker(constr_tuple_2_get_1(VAR_V_95)))).
fof(ax142, axiom,
![VAR_V_97] : (pred_attacker(VAR_V_97) => pred_attacker(constr_tuple_2_get_0x30(VAR_V_97)))).
fof(ax143, axiom,
pred_attacker(tuple_true)).
fof(ax144, axiom,
![VAR_V_99] : (pred_attacker(VAR_V_99) => pred_attacker(tuple_succ(VAR_V_99)))).
fof(ax145, axiom,
![VAR_V_10X302] : (pred_attacker(tuple_succ(VAR_V_10X302)) => pred_attacker(VAR_V_10X302))).
fof(ax146, axiom,
pred_attacker(constr_server_S_STEP_1)).
fof(ax147, axiom,
pred_attacker(tuple_false)).
fof(ax148, axiom,
pred_attacker(constr_client_B_STEP_1)).
fof(ax149, axiom,
pred_attacker(constr_client_A_STEP_3)).
fof(ax150, axiom,
pred_attacker(constr_client_A_STEP_2)).
fof(ax151, axiom,
pred_attacker(constr_client_A_STEP_1)).
fof(ax152, axiom,
![VAR_V_110X30, VAR_V_111, VAR_V_112, VAR_V_113, VAR_V_114] : ((pred_attacker(VAR_V_110X30) & pred_attacker(VAR_V_111) & pred_attacker(VAR_V_112) & pred_attacker(VAR_V_113) & pred_attacker(VAR_V_114)) => pred_attacker(constr_cbc_enc_4(VAR_V_110X30, VAR_V_111, VAR_V_112, VAR_V_113, VAR_V_114)))).
fof(ax153, axiom,
![VAR_V_119, VAR_V_120X30, VAR_V_121, VAR_V_122] : ((pred_attacker(VAR_V_119) & pred_attacker(VAR_V_120X30) & pred_attacker(VAR_V_121) & pred_attacker(VAR_V_122)) => pred_attacker(constr_cbc_enc_3(VAR_V_119, VAR_V_120X30, VAR_V_121, VAR_V_122)))).
fof(ax154, axiom,
![VAR_V_126, VAR_V_127, VAR_V_128] : ((pred_attacker(VAR_V_126) & pred_attacker(VAR_V_127) & pred_attacker(VAR_V_128)) => pred_attacker(constr_cbc_enc_2(VAR_V_126, VAR_V_127, VAR_V_128)))).
fof(ax155, axiom,
![VAR_V_131, VAR_V_132] : ((pred_attacker(VAR_V_131) & pred_attacker(VAR_V_132)) => pred_attacker(constr_cbc_enc_1(VAR_V_131, VAR_V_132)))).
fof(ax156, axiom,
![VAR_V_135, VAR_V_136] : ((pred_attacker(VAR_V_135) & pred_attacker(VAR_V_136)) => pred_attacker(constr_cbc_dec_4(VAR_V_135, VAR_V_136)))).
fof(ax157, axiom,
![VAR_V_139, VAR_V_140X30] : ((pred_attacker(VAR_V_139) & pred_attacker(VAR_V_140X30)) => pred_attacker(constr_cbc_dec_3(VAR_V_139, VAR_V_140X30)))).
fof(ax158, axiom,
![VAR_V_143, VAR_V_144] : ((pred_attacker(VAR_V_143) & pred_attacker(VAR_V_144)) => pred_attacker(constr_cbc_dec_2(VAR_V_143, VAR_V_144)))).
fof(ax159, axiom,
![VAR_V_147, VAR_V_148] : ((pred_attacker(VAR_V_147) & pred_attacker(VAR_V_148)) => pred_attacker(constr_cbc_dec_1(VAR_V_147, VAR_V_148)))).
fof(ax160, axiom,
![VAR_V_150X30] : (pred_attacker(VAR_V_150X30) => pred_attacker(constr_cbc_4_get_3_prefixes(VAR_V_150X30)))).
fof(ax161, axiom,
![VAR_V_152] : (pred_attacker(VAR_V_152) => pred_attacker(constr_cbc_4_get_2_prefixes(VAR_V_152)))).
fof(ax162, axiom,
![VAR_V_154] : (pred_attacker(VAR_V_154) => pred_attacker(constr_cbc_4_get_1_prefixes(VAR_V_154)))).
fof(ax163, axiom,
![VAR_V_156] : (pred_attacker(VAR_V_156) => pred_attacker(constr_cbc_3_get_2_prefixes(VAR_V_156)))).
fof(ax164, axiom,
![VAR_V_158] : (pred_attacker(VAR_V_158) => pred_attacker(constr_cbc_3_get_1_prefixes(VAR_V_158)))).
fof(ax165, axiom,
![VAR_V_160X30] : (pred_attacker(VAR_V_160X30) => pred_attacker(constr_cbc_2_get_1_prefixes(VAR_V_160X30)))).
fof(ax166, axiom,
pred_attacker(constr_CONST_4)).
fof(ax167, axiom,
pred_attacker(constr_CONST_3)).
fof(ax168, axiom,
pred_attacker(constr_CONST_2)).
fof(ax169, axiom,
pred_attacker(constr_CONST_1)).
fof(ax170, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax171, axiom,
![VAR_V_169, VAR_V_170X30, VAR_V_171, VAR_V_172] : ((pred_attacker(VAR_V_169) & pred_attacker(VAR_V_170X30) & pred_attacker(VAR_V_171) & pred_attacker(VAR_V_172)) => pred_attacker(tuple_4(VAR_V_169, VAR_V_170X30, VAR_V_171, VAR_V_172)))).
fof(ax172, axiom,
![VAR_V_193, VAR_V_194, VAR_V_195, VAR_V_196] : (pred_attacker(tuple_4(VAR_V_193, VAR_V_194, VAR_V_195, VAR_V_196)) => pred_attacker(VAR_V_193))).
fof(ax173, axiom,
![VAR_V_198, VAR_V_199, VAR_V_20X300X30, VAR_V_20X301] : (pred_attacker(tuple_4(VAR_V_198, VAR_V_199, VAR_V_20X300X30, VAR_V_20X301)) => pred_attacker(VAR_V_199))).
fof(ax174, axiom,
![VAR_V_20X303, VAR_V_20X304, VAR_V_20X305, VAR_V_20X306] : (pred_attacker(tuple_4(VAR_V_20X303, VAR_V_20X304, VAR_V_20X305, VAR_V_20X306)) => pred_attacker(VAR_V_20X305))).
fof(ax175, axiom,
![VAR_V_20X308, VAR_V_20X309, VAR_V_210X30, VAR_V_211] : (pred_attacker(tuple_4(VAR_V_20X308, VAR_V_20X309, VAR_V_210X30, VAR_V_211)) => pred_attacker(VAR_V_211))).
fof(ax176, axiom,
![VAR_V_216, VAR_V_217, VAR_V_218] : ((pred_attacker(VAR_V_216) & pred_attacker(VAR_V_217) & pred_attacker(VAR_V_218)) => pred_attacker(tuple_3(VAR_V_216, VAR_V_217, VAR_V_218)))).
fof(ax177, axiom,
![VAR_V_231, VAR_V_232, VAR_V_233] : (pred_attacker(tuple_3(VAR_V_231, VAR_V_232, VAR_V_233)) => pred_attacker(VAR_V_231))).
fof(ax178, axiom,
![VAR_V_235, VAR_V_236, VAR_V_237] : (pred_attacker(tuple_3(VAR_V_235, VAR_V_236, VAR_V_237)) => pred_attacker(VAR_V_236))).
fof(ax179, axiom,
![VAR_V_239, VAR_V_240X30, VAR_V_241] : (pred_attacker(tuple_3(VAR_V_239, VAR_V_240X30, VAR_V_241)) => pred_attacker(VAR_V_241))).
fof(ax180, axiom,
![VAR_V_245, VAR_V_246] : ((pred_attacker(VAR_V_245) & pred_attacker(VAR_V_246)) => pred_attacker(tuple_2(VAR_V_245, VAR_V_246)))).
fof(ax181, axiom,
![VAR_V_253, VAR_V_254] : (pred_attacker(tuple_2(VAR_V_253, VAR_V_254)) => pred_attacker(VAR_V_253))).
fof(ax182, axiom,
![VAR_V_256, VAR_V_257] : (pred_attacker(tuple_2(VAR_V_256, VAR_V_257)) => pred_attacker(VAR_V_257))).
fof(ax183, axiom,
![VAR_V_259, VAR_V_260X30] : ((pred_mess(VAR_V_260X30, VAR_V_259) & pred_attacker(VAR_V_260X30)) => pred_attacker(VAR_V_259))).
fof(ax184, axiom,
![VAR_V_261, VAR_V_262] : ((pred_attacker(VAR_V_262) & pred_attacker(VAR_V_261)) => pred_mess(VAR_V_262, VAR_V_261))).
fof(ax185, axiom,
pred_attacker(name_c)).
fof(ax186, axiom,
pred_attacker(name_I)).
fof(ax187, axiom,
pred_attacker(name_B)).
fof(ax188, axiom,
pred_attacker(name_A)).
fof(ax189, axiom,
![VAR_V_264] : (pred_equal(VAR_V_264, VAR_V_264))).
fof(ax190, axiom,
![VAR_V_265] : (pred_attacker(name_new0x2Dname(VAR_V_265)))).
fof(ax191, axiom,
![VAR_0X40SID_287] : (pred_attacker(tuple_2(tuple_3(name_A, name_B, name_Na(VAR_0X40SID_287)), constr_client_A_STEP_1)))).
fof(ax192, axiom,
![VAR_0X40SID_364, VAR_ENC_NA_B_ENC_KAB_A_363] : ((pred_eq(constr_tuple_4_get_1(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_363, name_Kas)), name_B) & pred_eq(constr_tuple_4_get_0x30(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_363, name_Kas)), name_Na(VAR_0X40SID_364)) & pred_attacker(VAR_ENC_NA_B_ENC_KAB_A_363)) => pred_attacker(tuple_2(constr_tuple_4_get_3(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_363, name_Kas)), constr_client_A_STEP_2)))).
fof(ax193, axiom,
![VAR_0X40SID_40X302, VAR_ENC_NA_B_ENC_KAB_A_40X301, VAR_ENC_NB_40X300X30] : ((pred_attacker(VAR_ENC_NB_40X300X30) & pred_eq(constr_tuple_4_get_1(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_40X301, name_Kas)), name_B) & pred_eq(constr_tuple_4_get_0x30(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_40X301, name_Kas)), name_Na(VAR_0X40SID_40X302)) & pred_attacker(VAR_ENC_NA_B_ENC_KAB_A_40X301)) => pred_attacker(tuple_2(constr_cbc_enc_1(tuple_succ(constr_cbc_dec_1(VAR_ENC_NB_40X300X30, constr_tuple_4_get_2(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_40X301, name_Kas)))), constr_tuple_4_get_2(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_40X301, name_Kas))), constr_client_A_STEP_3)))).
fof(ax194, axiom,
![VAR_0X40SID_466, VAR_ENC_KAB_A_465] : ((pred_eq(constr_tuple_2_get_1(constr_cbc_dec_2(VAR_ENC_KAB_A_465, name_Kbs)), name_A) & pred_attacker(VAR_ENC_KAB_A_465)) => pred_attacker(tuple_2(constr_cbc_enc_1(name_Nb_62(VAR_0X40SID_466), constr_tuple_2_get_0x30(constr_cbc_dec_2(VAR_ENC_KAB_A_465, name_Kbs))), constr_client_B_STEP_1)))).
fof(ax195, axiom,
![VAR_0X40SID_542, VAR_A_539, VAR_B_540X30, VAR_NA_541] : (pred_attacker(tuple_3(VAR_A_539, VAR_B_540X30, VAR_NA_541)) => pred_attacker(tuple_2(constr_cbc_enc_4(VAR_NA_541, VAR_B_540X30, name_Kab_65(VAR_0X40SID_542), constr_cbc_enc_2(name_Kab_65(VAR_0X40SID_542), VAR_A_539, name_Kbs), name_Kas), constr_server_S_STEP_1)))).
fof(co0, conjecture,
pred_attacker(name_Kab_65(VAR_V_571))).
