%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != name_A).
fof(ax5, axiom,
constr_CONST_0x30 != name_B).
fof(ax6, axiom,
constr_CONST_0x30 != name_I).
fof(ax7, axiom,
constr_CONST_0x30 != name_Kas).
fof(ax8, axiom,
constr_CONST_0x30 != name_Kbs).
fof(ax9, axiom,
constr_CONST_0x30 != name_c).
fof(ax10, axiom,
constr_CONST_0x30 != name_objective).
fof(ax11, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax12, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax13, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax14, axiom,
constr_CONST_1 != name_A).
fof(ax15, axiom,
constr_CONST_1 != name_B).
fof(ax16, axiom,
constr_CONST_1 != name_I).
fof(ax17, axiom,
constr_CONST_1 != name_Kas).
fof(ax18, axiom,
constr_CONST_1 != name_Kbs).
fof(ax19, axiom,
constr_CONST_1 != name_c).
fof(ax20, axiom,
constr_CONST_1 != name_objective).
fof(ax21, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax22, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax23, axiom,
constr_CONST_2 != name_A).
fof(ax24, axiom,
constr_CONST_2 != name_B).
fof(ax25, axiom,
constr_CONST_2 != name_I).
fof(ax26, axiom,
constr_CONST_2 != name_Kas).
fof(ax27, axiom,
constr_CONST_2 != name_Kbs).
fof(ax28, axiom,
constr_CONST_2 != name_c).
fof(ax29, axiom,
constr_CONST_2 != name_objective).
fof(ax30, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax31, axiom,
constr_CONST_3 != name_A).
fof(ax32, axiom,
constr_CONST_3 != name_B).
fof(ax33, axiom,
constr_CONST_3 != name_I).
fof(ax34, axiom,
constr_CONST_3 != name_Kas).
fof(ax35, axiom,
constr_CONST_3 != name_Kbs).
fof(ax36, axiom,
constr_CONST_3 != name_c).
fof(ax37, axiom,
constr_CONST_3 != name_objective).
fof(ax38, axiom,
constr_CONST_4 != name_A).
fof(ax39, axiom,
constr_CONST_4 != name_B).
fof(ax40, axiom,
constr_CONST_4 != name_I).
fof(ax41, axiom,
constr_CONST_4 != name_Kas).
fof(ax42, axiom,
constr_CONST_4 != name_Kbs).
fof(ax43, axiom,
constr_CONST_4 != name_c).
fof(ax44, axiom,
constr_CONST_4 != name_objective).
fof(ax45, axiom,
name_A != name_B).
fof(ax46, axiom,
name_A != name_I).
fof(ax47, axiom,
name_A != name_Kas).
fof(ax48, axiom,
name_A != name_Kbs).
fof(ax49, axiom,
name_A != name_c).
fof(ax50, axiom,
name_A != name_objective).
fof(ax51, axiom,
name_B != name_I).
fof(ax52, axiom,
name_B != name_Kas).
fof(ax53, axiom,
name_B != name_Kbs).
fof(ax54, axiom,
name_B != name_c).
fof(ax55, axiom,
name_B != name_objective).
fof(ax56, axiom,
name_I != name_Kas).
fof(ax57, axiom,
name_I != name_Kbs).
fof(ax58, axiom,
name_I != name_c).
fof(ax59, axiom,
name_I != name_objective).
fof(ax60, axiom,
name_Kas != name_Kbs).
fof(ax61, axiom,
name_Kas != name_c).
fof(ax62, axiom,
name_Kas != name_objective).
fof(ax63, axiom,
name_Kbs != name_c).
fof(ax64, axiom,
name_Kbs != name_objective).
fof(ax65, axiom,
name_c != name_objective).
fof(ax66, axiom,
![VAR_K_62, VAR_X0X30_58, VAR_X1_59, VAR_X2_60X30, VAR_X3_61] : (constr_cbc_dec_4(constr_cbc_enc_4(VAR_X0X30_58, VAR_X1_59, VAR_X2_60X30, VAR_X3_61, VAR_K_62), VAR_K_62) = tuple_4(VAR_X0X30_58, VAR_X1_59, VAR_X2_60X30, VAR_X3_61))).
fof(ax67, axiom,
![VAR_K_57, VAR_X0X30_54, VAR_X1_55, VAR_X2_56] : (constr_cbc_dec_3(constr_cbc_enc_3(VAR_X0X30_54, VAR_X1_55, VAR_X2_56, VAR_K_57), VAR_K_57) = tuple_3(VAR_X0X30_54, VAR_X1_55, VAR_X2_56))).
fof(ax68, axiom,
![VAR_K_53, VAR_X0X30_51, VAR_X1_52] : (constr_cbc_dec_2(constr_cbc_enc_2(VAR_X0X30_51, VAR_X1_52, VAR_K_53), VAR_K_53) = tuple_2(VAR_X0X30_51, VAR_X1_52))).
fof(ax69, axiom,
![VAR_K_50X30, VAR_X0X30_49] : (constr_cbc_dec_1(constr_cbc_enc_1(VAR_X0X30_49, VAR_K_50X30), VAR_K_50X30) = VAR_X0X30_49)).
fof(ax70, axiom,
![VAR_K_48, VAR_X0X30_44, VAR_X1_45, VAR_X2_46, VAR_X3_47] : (constr_cbc_4_get_3_prefixes(constr_cbc_enc_4(VAR_X0X30_44, VAR_X1_45, VAR_X2_46, VAR_X3_47, VAR_K_48)) = constr_cbc_enc_3(VAR_X0X30_44, VAR_X1_45, VAR_X2_46, VAR_K_48))).
fof(ax71, axiom,
![VAR_K_43, VAR_X0X30_39, VAR_X1_40X30, VAR_X2_41, VAR_X3_42] : (constr_cbc_4_get_2_prefixes(constr_cbc_enc_4(VAR_X0X30_39, VAR_X1_40X30, VAR_X2_41, VAR_X3_42, VAR_K_43)) = constr_cbc_enc_2(VAR_X0X30_39, VAR_X1_40X30, VAR_K_43))).
fof(ax72, axiom,
![VAR_K_38, VAR_X0X30_34, VAR_X1_35, VAR_X2_36, VAR_X3_37] : (constr_cbc_4_get_1_prefixes(constr_cbc_enc_4(VAR_X0X30_34, VAR_X1_35, VAR_X2_36, VAR_X3_37, VAR_K_38)) = constr_cbc_enc_1(VAR_X0X30_34, VAR_K_38))).
fof(ax73, axiom,
![VAR_K_33, VAR_X0X30_30X30, VAR_X1_31, VAR_X2_32] : (constr_cbc_3_get_2_prefixes(constr_cbc_enc_3(VAR_X0X30_30X30, VAR_X1_31, VAR_X2_32, VAR_K_33)) = constr_cbc_enc_2(VAR_X0X30_30X30, VAR_X1_31, VAR_K_33))).
fof(ax74, axiom,
![VAR_K_29, VAR_X0X30_26, VAR_X1_27, VAR_X2_28] : (constr_cbc_3_get_1_prefixes(constr_cbc_enc_3(VAR_X0X30_26, VAR_X1_27, VAR_X2_28, VAR_K_29)) = constr_cbc_enc_1(VAR_X0X30_26, VAR_K_29))).
fof(ax75, axiom,
![VAR_K_25, VAR_X0X30_23, VAR_X1_24] : (constr_cbc_2_get_1_prefixes(constr_cbc_enc_2(VAR_X0X30_23, VAR_X1_24, VAR_K_25)) = constr_cbc_enc_1(VAR_X0X30_23, VAR_K_25))).
fof(ax76, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_dec(constr_enc(VAR_M_0X30, VAR_K_0X30), VAR_K_0X30) = VAR_M_0X30)).
fof(ax77, axiom,
![VAR_X0X30_19, VAR_X1_20X30, VAR_X2_21, VAR_X3_22] : (constr_tuple_4_get_3_bitstring(tuple_4(VAR_X0X30_19, VAR_X1_20X30, VAR_X2_21, VAR_X3_22)) = VAR_X3_22)).
fof(ax78, axiom,
![VAR_X0X30_15, VAR_X1_16, VAR_X2_17, VAR_X3_18] : (constr_tuple_4_get_2_bitstring(tuple_4(VAR_X0X30_15, VAR_X1_16, VAR_X2_17, VAR_X3_18)) = VAR_X2_17)).
fof(ax79, axiom,
![VAR_X0X30_13, VAR_X1_14] : (constr_tuple_2_get_0x30_bitstring(tuple_2(VAR_X0X30_13, VAR_X1_14)) = VAR_X0X30_13)).
fof(ax80, axiom,
![VAR_X0X30_9, VAR_X1_10X30, VAR_X2_11, VAR_X3_12] : (constr_tuple_4_get_1(tuple_4(VAR_X0X30_9, VAR_X1_10X30, VAR_X2_11, VAR_X3_12)) = VAR_X1_10X30)).
fof(ax81, axiom,
![VAR_X0X30_7, VAR_X1_8, VAR_X2_0X30, VAR_X3_0X30] : (constr_tuple_4_get_0x30(tuple_4(VAR_X0X30_7, VAR_X1_8, VAR_X2_0X30, VAR_X3_0X30)) = VAR_X0X30_7)).
fof(ax82, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30] : (constr_tuple_2_get_1(tuple_2(VAR_X0X30_0X30, VAR_X1_0X30)) = VAR_X1_0X30)).
fof(ax83, axiom,
![VAR_X_81, VAR_Y_82] : (pred_eq_bitstring_bitstring(VAR_X_81, VAR_Y_82))).
fof(ax84, axiom,
![VAR_V_88] : (pred_attacker(VAR_V_88) => pred_attacker(constr_tuple_4_get_3_bitstring(VAR_V_88)))).
fof(ax85, axiom,
![VAR_V_90X30] : (pred_attacker(VAR_V_90X30) => pred_attacker(constr_tuple_4_get_2_bitstring(VAR_V_90X30)))).
fof(ax86, axiom,
![VAR_V_92] : (pred_attacker(VAR_V_92) => pred_attacker(constr_tuple_4_get_1(VAR_V_92)))).
fof(ax87, axiom,
![VAR_V_94] : (pred_attacker(VAR_V_94) => pred_attacker(constr_tuple_4_get_0x30(VAR_V_94)))).
fof(ax88, axiom,
![VAR_V_96] : (pred_attacker(VAR_V_96) => pred_attacker(constr_tuple_2_get_1(VAR_V_96)))).
fof(ax89, axiom,
![VAR_V_98] : (pred_attacker(VAR_V_98) => pred_attacker(constr_tuple_2_get_0x30_bitstring(VAR_V_98)))).
fof(ax90, axiom,
pred_attacker(tuple_true)).
fof(ax91, axiom,
![VAR_V_10X300X30] : (pred_attacker(VAR_V_10X300X30) => pred_attacker(tuple_succ(VAR_V_10X300X30)))).
fof(ax92, axiom,
![VAR_V_10X303] : (pred_attacker(tuple_succ(VAR_V_10X303)) => pred_attacker(VAR_V_10X303))).
fof(ax93, axiom,
![VAR_V_10X306] : (pred_attacker(VAR_V_10X306) => pred_attacker(tuple_server_S_out_2(VAR_V_10X306)))).
fof(ax94, axiom,
![VAR_V_10X309] : (pred_attacker(tuple_server_S_out_2(VAR_V_10X309)) => pred_attacker(VAR_V_10X309))).
fof(ax95, axiom,
![VAR_V_114, VAR_V_115, VAR_V_116] : ((pred_attacker(VAR_V_114) & pred_attacker(VAR_V_115) & pred_attacker(VAR_V_116)) => pred_attacker(tuple_server_S_in_1(VAR_V_114, VAR_V_115, VAR_V_116)))).
fof(ax96, axiom,
![VAR_V_129, VAR_V_130X30, VAR_V_131] : (pred_attacker(tuple_server_S_in_1(VAR_V_129, VAR_V_130X30, VAR_V_131)) => pred_attacker(VAR_V_129))).
fof(ax97, axiom,
![VAR_V_133, VAR_V_134, VAR_V_135] : (pred_attacker(tuple_server_S_in_1(VAR_V_133, VAR_V_134, VAR_V_135)) => pred_attacker(VAR_V_134))).
fof(ax98, axiom,
![VAR_V_137, VAR_V_138, VAR_V_139] : (pred_attacker(tuple_server_S_in_1(VAR_V_137, VAR_V_138, VAR_V_139)) => pred_attacker(VAR_V_139))).
fof(ax99, axiom,
pred_attacker(tuple_false)).
fof(ax100, axiom,
![VAR_V_144, VAR_V_145] : ((pred_attacker(VAR_V_144) & pred_attacker(VAR_V_145)) => pred_attacker(constr_enc(VAR_V_144, VAR_V_145)))).
fof(ax101, axiom,
![VAR_V_148, VAR_V_149] : ((pred_attacker(VAR_V_148) & pred_attacker(VAR_V_149)) => pred_attacker(constr_dec(VAR_V_148, VAR_V_149)))).
fof(ax102, axiom,
![VAR_V_151] : (pred_attacker(VAR_V_151) => pred_attacker(tuple_client_B_out_2(VAR_V_151)))).
fof(ax103, axiom,
![VAR_V_154] : (pred_attacker(tuple_client_B_out_2(VAR_V_154)) => pred_attacker(VAR_V_154))).
fof(ax104, axiom,
![VAR_V_157] : (pred_attacker(VAR_V_157) => pred_attacker(tuple_client_B_in_3(VAR_V_157)))).
fof(ax105, axiom,
![VAR_V_160X30] : (pred_attacker(tuple_client_B_in_3(VAR_V_160X30)) => pred_attacker(VAR_V_160X30))).
fof(ax106, axiom,
![VAR_V_163] : (pred_attacker(VAR_V_163) => pred_attacker(tuple_client_B_in_1(VAR_V_163)))).
fof(ax107, axiom,
![VAR_V_166] : (pred_attacker(tuple_client_B_in_1(VAR_V_166)) => pred_attacker(VAR_V_166))).
fof(ax108, axiom,
![VAR_V_169] : (pred_attacker(VAR_V_169) => pred_attacker(tuple_client_A_out_9(VAR_V_169)))).
fof(ax109, axiom,
![VAR_V_172] : (pred_attacker(tuple_client_A_out_9(VAR_V_172)) => pred_attacker(VAR_V_172))).
fof(ax110, axiom,
![VAR_V_175] : (pred_attacker(VAR_V_175) => pred_attacker(tuple_client_A_out_7(VAR_V_175)))).
fof(ax111, axiom,
![VAR_V_178] : (pred_attacker(tuple_client_A_out_7(VAR_V_178)) => pred_attacker(VAR_V_178))).
fof(ax112, axiom,
![VAR_V_181] : (pred_attacker(VAR_V_181) => pred_attacker(tuple_client_A_out_5(VAR_V_181)))).
fof(ax113, axiom,
![VAR_V_184] : (pred_attacker(tuple_client_A_out_5(VAR_V_184)) => pred_attacker(VAR_V_184))).
fof(ax114, axiom,
![VAR_V_187] : (pred_attacker(VAR_V_187) => pred_attacker(tuple_client_A_out_3(VAR_V_187)))).
fof(ax115, axiom,
![VAR_V_190X30] : (pred_attacker(tuple_client_A_out_3(VAR_V_190X30)) => pred_attacker(VAR_V_190X30))).
fof(ax116, axiom,
![VAR_V_195, VAR_V_196, VAR_V_197] : ((pred_attacker(VAR_V_195) & pred_attacker(VAR_V_196) & pred_attacker(VAR_V_197)) => pred_attacker(tuple_client_A_out_1(VAR_V_195, VAR_V_196, VAR_V_197)))).
fof(ax117, axiom,
![VAR_V_210X30, VAR_V_211, VAR_V_212] : (pred_attacker(tuple_client_A_out_1(VAR_V_210X30, VAR_V_211, VAR_V_212)) => pred_attacker(VAR_V_210X30))).
fof(ax118, axiom,
![VAR_V_214, VAR_V_215, VAR_V_216] : (pred_attacker(tuple_client_A_out_1(VAR_V_214, VAR_V_215, VAR_V_216)) => pred_attacker(VAR_V_215))).
fof(ax119, axiom,
![VAR_V_218, VAR_V_219, VAR_V_220X30] : (pred_attacker(tuple_client_A_out_1(VAR_V_218, VAR_V_219, VAR_V_220X30)) => pred_attacker(VAR_V_220X30))).
fof(ax120, axiom,
![VAR_V_223] : (pred_attacker(VAR_V_223) => pred_attacker(tuple_client_A_in_8(VAR_V_223)))).
fof(ax121, axiom,
![VAR_V_226] : (pred_attacker(tuple_client_A_in_8(VAR_V_226)) => pred_attacker(VAR_V_226))).
fof(ax122, axiom,
![VAR_V_229] : (pred_attacker(VAR_V_229) => pred_attacker(tuple_client_A_in_6(VAR_V_229)))).
fof(ax123, axiom,
![VAR_V_232] : (pred_attacker(tuple_client_A_in_6(VAR_V_232)) => pred_attacker(VAR_V_232))).
fof(ax124, axiom,
![VAR_V_235] : (pred_attacker(VAR_V_235) => pred_attacker(tuple_client_A_in_4(VAR_V_235)))).
fof(ax125, axiom,
![VAR_V_238] : (pred_attacker(tuple_client_A_in_4(VAR_V_238)) => pred_attacker(VAR_V_238))).
fof(ax126, axiom,
![VAR_V_241] : (pred_attacker(VAR_V_241) => pred_attacker(tuple_client_A_in_2(VAR_V_241)))).
fof(ax127, axiom,
![VAR_V_244] : (pred_attacker(tuple_client_A_in_2(VAR_V_244)) => pred_attacker(VAR_V_244))).
fof(ax128, axiom,
![VAR_V_251, VAR_V_252, VAR_V_253, VAR_V_254, VAR_V_255] : ((pred_attacker(VAR_V_251) & pred_attacker(VAR_V_252) & pred_attacker(VAR_V_253) & pred_attacker(VAR_V_254) & pred_attacker(VAR_V_255)) => pred_attacker(constr_cbc_enc_4(VAR_V_251, VAR_V_252, VAR_V_253, VAR_V_254, VAR_V_255)))).
fof(ax129, axiom,
![VAR_V_260X30, VAR_V_261, VAR_V_262, VAR_V_263] : ((pred_attacker(VAR_V_260X30) & pred_attacker(VAR_V_261) & pred_attacker(VAR_V_262) & pred_attacker(VAR_V_263)) => pred_attacker(constr_cbc_enc_3(VAR_V_260X30, VAR_V_261, VAR_V_262, VAR_V_263)))).
fof(ax130, axiom,
![VAR_V_267, VAR_V_268, VAR_V_269] : ((pred_attacker(VAR_V_267) & pred_attacker(VAR_V_268) & pred_attacker(VAR_V_269)) => pred_attacker(constr_cbc_enc_2(VAR_V_267, VAR_V_268, VAR_V_269)))).
fof(ax131, axiom,
![VAR_V_272, VAR_V_273] : ((pred_attacker(VAR_V_272) & pred_attacker(VAR_V_273)) => pred_attacker(constr_cbc_enc_1(VAR_V_272, VAR_V_273)))).
fof(ax132, axiom,
![VAR_V_276, VAR_V_277] : ((pred_attacker(VAR_V_276) & pred_attacker(VAR_V_277)) => pred_attacker(constr_cbc_dec_4(VAR_V_276, VAR_V_277)))).
fof(ax133, axiom,
![VAR_V_280X30, VAR_V_281] : ((pred_attacker(VAR_V_280X30) & pred_attacker(VAR_V_281)) => pred_attacker(constr_cbc_dec_3(VAR_V_280X30, VAR_V_281)))).
fof(ax134, axiom,
![VAR_V_284, VAR_V_285] : ((pred_attacker(VAR_V_284) & pred_attacker(VAR_V_285)) => pred_attacker(constr_cbc_dec_2(VAR_V_284, VAR_V_285)))).
fof(ax135, axiom,
![VAR_V_288, VAR_V_289] : ((pred_attacker(VAR_V_288) & pred_attacker(VAR_V_289)) => pred_attacker(constr_cbc_dec_1(VAR_V_288, VAR_V_289)))).
fof(ax136, axiom,
![VAR_V_291] : (pred_attacker(VAR_V_291) => pred_attacker(constr_cbc_4_get_3_prefixes(VAR_V_291)))).
fof(ax137, axiom,
![VAR_V_293] : (pred_attacker(VAR_V_293) => pred_attacker(constr_cbc_4_get_2_prefixes(VAR_V_293)))).
fof(ax138, axiom,
![VAR_V_295] : (pred_attacker(VAR_V_295) => pred_attacker(constr_cbc_4_get_1_prefixes(VAR_V_295)))).
fof(ax139, axiom,
![VAR_V_297] : (pred_attacker(VAR_V_297) => pred_attacker(constr_cbc_3_get_2_prefixes(VAR_V_297)))).
fof(ax140, axiom,
![VAR_V_299] : (pred_attacker(VAR_V_299) => pred_attacker(constr_cbc_3_get_1_prefixes(VAR_V_299)))).
fof(ax141, axiom,
![VAR_V_30X301] : (pred_attacker(VAR_V_30X301) => pred_attacker(constr_cbc_2_get_1_prefixes(VAR_V_30X301)))).
fof(ax142, axiom,
pred_attacker(constr_CONST_4)).
fof(ax143, axiom,
pred_attacker(constr_CONST_3)).
fof(ax144, axiom,
pred_attacker(constr_CONST_2)).
fof(ax145, axiom,
pred_attacker(constr_CONST_1)).
fof(ax146, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax147, axiom,
![VAR_V_310X30, VAR_V_311, VAR_V_312, VAR_V_313] : ((pred_attacker(VAR_V_310X30) & pred_attacker(VAR_V_311) & pred_attacker(VAR_V_312) & pred_attacker(VAR_V_313)) => pred_attacker(tuple_4(VAR_V_310X30, VAR_V_311, VAR_V_312, VAR_V_313)))).
fof(ax148, axiom,
![VAR_V_334, VAR_V_335, VAR_V_336, VAR_V_337] : (pred_attacker(tuple_4(VAR_V_334, VAR_V_335, VAR_V_336, VAR_V_337)) => pred_attacker(VAR_V_334))).
fof(ax149, axiom,
![VAR_V_339, VAR_V_340X30, VAR_V_341, VAR_V_342] : (pred_attacker(tuple_4(VAR_V_339, VAR_V_340X30, VAR_V_341, VAR_V_342)) => pred_attacker(VAR_V_340X30))).
fof(ax150, axiom,
![VAR_V_344, VAR_V_345, VAR_V_346, VAR_V_347] : (pred_attacker(tuple_4(VAR_V_344, VAR_V_345, VAR_V_346, VAR_V_347)) => pred_attacker(VAR_V_346))).
fof(ax151, axiom,
![VAR_V_349, VAR_V_350X30, VAR_V_351, VAR_V_352] : (pred_attacker(tuple_4(VAR_V_349, VAR_V_350X30, VAR_V_351, VAR_V_352)) => pred_attacker(VAR_V_352))).
fof(ax152, axiom,
![VAR_V_357, VAR_V_358, VAR_V_359] : ((pred_attacker(VAR_V_357) & pred_attacker(VAR_V_358) & pred_attacker(VAR_V_359)) => pred_attacker(tuple_3(VAR_V_357, VAR_V_358, VAR_V_359)))).
fof(ax153, axiom,
![VAR_V_372, VAR_V_373, VAR_V_374] : (pred_attacker(tuple_3(VAR_V_372, VAR_V_373, VAR_V_374)) => pred_attacker(VAR_V_372))).
fof(ax154, axiom,
![VAR_V_376, VAR_V_377, VAR_V_378] : (pred_attacker(tuple_3(VAR_V_376, VAR_V_377, VAR_V_378)) => pred_attacker(VAR_V_377))).
fof(ax155, axiom,
![VAR_V_380X30, VAR_V_381, VAR_V_382] : (pred_attacker(tuple_3(VAR_V_380X30, VAR_V_381, VAR_V_382)) => pred_attacker(VAR_V_382))).
fof(ax156, axiom,
![VAR_V_386, VAR_V_387] : ((pred_attacker(VAR_V_386) & pred_attacker(VAR_V_387)) => pred_attacker(tuple_2(VAR_V_386, VAR_V_387)))).
fof(ax157, axiom,
![VAR_V_394, VAR_V_395] : (pred_attacker(tuple_2(VAR_V_394, VAR_V_395)) => pred_attacker(VAR_V_394))).
fof(ax158, axiom,
![VAR_V_397, VAR_V_398] : (pred_attacker(tuple_2(VAR_V_397, VAR_V_398)) => pred_attacker(VAR_V_398))).
fof(ax159, axiom,
![VAR_V_40X300X30, VAR_V_40X301] : ((pred_mess(VAR_V_40X301, VAR_V_40X300X30) & pred_attacker(VAR_V_40X301)) => pred_attacker(VAR_V_40X300X30))).
fof(ax160, axiom,
![VAR_V_40X302, VAR_V_40X303] : ((pred_attacker(VAR_V_40X303) & pred_attacker(VAR_V_40X302)) => pred_mess(VAR_V_40X303, VAR_V_40X302))).
fof(ax161, axiom,
pred_attacker(name_c)).
fof(ax162, axiom,
pred_attacker(name_I)).
fof(ax163, axiom,
pred_attacker(name_B)).
fof(ax164, axiom,
pred_attacker(name_A)).
fof(ax165, axiom,
![VAR_V_40X305] : (pred_equal(VAR_V_40X305, VAR_V_40X305))).
fof(ax166, axiom,
![VAR_V_40X306] : (pred_attacker(name_new0x2Dname(VAR_V_40X306)))).
fof(ax167, axiom,
![VAR_0X40SID_420X30] : (pred_attacker(tuple_client_A_out_1(name_A, name_B, name_Na(VAR_0X40SID_420X30))))).
fof(ax168, axiom,
![VAR_0X40SID_491, VAR_ENC_NA_B_ENC_KAB_A_490X30] : ((pred_eq_bitstring_bitstring(name_B, constr_tuple_4_get_1(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_490X30, name_Kas))) & pred_eq_bitstring_bitstring(name_Na(VAR_0X40SID_491), constr_tuple_4_get_0x30(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_490X30, name_Kas))) & pred_attacker(tuple_client_A_in_2(VAR_ENC_NA_B_ENC_KAB_A_490X30))) => pred_attacker(tuple_client_A_out_3(constr_tuple_4_get_3_bitstring(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_490X30, name_Kas)))))).
fof(ax169, axiom,
![VAR_0X40SID_523, VAR_ENC_NA_B_ENC_KAB_A_522, VAR_ENC_NB_521] : ((pred_attacker(tuple_client_A_in_4(VAR_ENC_NB_521)) & pred_eq_bitstring_bitstring(name_B, constr_tuple_4_get_1(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_522, name_Kas))) & pred_eq_bitstring_bitstring(name_Na(VAR_0X40SID_523), constr_tuple_4_get_0x30(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_522, name_Kas))) & pred_attacker(tuple_client_A_in_2(VAR_ENC_NA_B_ENC_KAB_A_522))) => pred_attacker(tuple_client_A_out_5(constr_cbc_enc_1(tuple_succ(constr_cbc_dec_1(VAR_ENC_NB_521, constr_tuple_4_get_2_bitstring(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_522, name_Kas)))), constr_tuple_4_get_2_bitstring(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_522, name_Kas))))))).
fof(ax170, axiom,
![VAR_0X40SID_572, VAR_ENC_KAB_A0X27_569, VAR_ENC_NA_B_ENC_KAB_A_571, VAR_ENC_NB_570X30] : ((pred_eq_bitstring_bitstring(name_A, constr_tuple_2_get_1(constr_cbc_dec_2(VAR_ENC_KAB_A0X27_569, name_Kas))) & pred_attacker(tuple_client_A_in_6(VAR_ENC_KAB_A0X27_569)) & pred_attacker(tuple_client_A_in_4(VAR_ENC_NB_570X30)) & pred_eq_bitstring_bitstring(name_B, constr_tuple_4_get_1(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_571, name_Kas))) & pred_eq_bitstring_bitstring(name_Na(VAR_0X40SID_572), constr_tuple_4_get_0x30(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_571, name_Kas))) & pred_attacker(tuple_client_A_in_2(VAR_ENC_NA_B_ENC_KAB_A_571))) => pred_attacker(tuple_client_A_out_7(constr_cbc_enc_1(name_Na0x27(VAR_ENC_NB_570X30, VAR_ENC_NA_B_ENC_KAB_A_571, VAR_0X40SID_572), constr_tuple_2_get_0x30_bitstring(constr_cbc_dec_2(VAR_ENC_KAB_A0X27_569, name_Kas))))))).
fof(ax171, axiom,
![VAR_0X40SID_598, VAR_ENC_KAB_A0X27_60X300X30, VAR_ENC_NA_B_ENC_KAB_A_597, VAR_ENC_NB_596, VAR_ENC_SUCC_NA0X27_599] : ((pred_eq_bitstring_bitstring(tuple_succ(name_Na0x27(VAR_ENC_NB_596, VAR_ENC_NA_B_ENC_KAB_A_597, VAR_0X40SID_598)), constr_cbc_dec_1(VAR_ENC_SUCC_NA0X27_599, constr_tuple_2_get_0x30_bitstring(constr_cbc_dec_2(VAR_ENC_KAB_A0X27_60X300X30, name_Kas)))) & pred_attacker(tuple_client_A_in_8(VAR_ENC_SUCC_NA0X27_599)) & pred_eq_bitstring_bitstring(name_A, constr_tuple_2_get_1(constr_cbc_dec_2(VAR_ENC_KAB_A0X27_60X300X30, name_Kas))) & pred_attacker(tuple_client_A_in_6(VAR_ENC_KAB_A0X27_60X300X30)) & pred_attacker(tuple_client_A_in_4(VAR_ENC_NB_596)) & pred_eq_bitstring_bitstring(name_B, constr_tuple_4_get_1(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_597, name_Kas))) & pred_eq_bitstring_bitstring(name_Na(VAR_0X40SID_598), constr_tuple_4_get_0x30(constr_cbc_dec_4(VAR_ENC_NA_B_ENC_KAB_A_597, name_Kas))) & pred_attacker(tuple_client_A_in_2(VAR_ENC_NA_B_ENC_KAB_A_597))) => pred_attacker(tuple_client_A_out_9(name_objective)))).
fof(ax172, axiom,
![VAR_0X40SID_662, VAR_ENC_KAB_A_661] : ((pred_eq_bitstring_bitstring(name_A, constr_tuple_2_get_1(constr_cbc_dec_2(VAR_ENC_KAB_A_661, name_Kbs))) & pred_attacker(tuple_client_B_in_1(VAR_ENC_KAB_A_661))) => pred_attacker(tuple_client_B_out_2(constr_cbc_enc_1(name_Nb_63(VAR_0X40SID_662), constr_tuple_2_get_0x30_bitstring(constr_cbc_dec_2(VAR_ENC_KAB_A_661, name_Kbs))))))).
fof(ax173, axiom,
![VAR_0X40SID_732, VAR_A_729, VAR_B_730X30, VAR_NA_731] : (pred_attacker(tuple_server_S_in_1(VAR_A_729, VAR_B_730X30, VAR_NA_731)) => pred_attacker(tuple_server_S_out_2(constr_cbc_enc_4(VAR_NA_731, VAR_B_730X30, name_Kab_66(VAR_0X40SID_732), constr_cbc_enc_2(name_Kab_66(VAR_0X40SID_732), VAR_A_729, name_Kbs), name_Kas))))).
fof(co0, conjecture,
pred_attacker(name_objective)).
