%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != name_A).
fof(ax5, axiom,
constr_CONST_0x30 != name_B).
fof(ax6, axiom,
constr_CONST_0x30 != name_I).
fof(ax7, axiom,
constr_CONST_0x30 != name_c).
fof(ax8, axiom,
constr_CONST_0x30 != name_skA).
fof(ax9, axiom,
constr_CONST_0x30 != name_skB).
fof(ax10, axiom,
constr_CONST_0x30 != name_skS).
fof(ax11, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax12, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax13, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax14, axiom,
constr_CONST_1 != name_A).
fof(ax15, axiom,
constr_CONST_1 != name_B).
fof(ax16, axiom,
constr_CONST_1 != name_I).
fof(ax17, axiom,
constr_CONST_1 != name_c).
fof(ax18, axiom,
constr_CONST_1 != name_skA).
fof(ax19, axiom,
constr_CONST_1 != name_skB).
fof(ax20, axiom,
constr_CONST_1 != name_skS).
fof(ax21, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax22, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax23, axiom,
constr_CONST_2 != name_A).
fof(ax24, axiom,
constr_CONST_2 != name_B).
fof(ax25, axiom,
constr_CONST_2 != name_I).
fof(ax26, axiom,
constr_CONST_2 != name_c).
fof(ax27, axiom,
constr_CONST_2 != name_skA).
fof(ax28, axiom,
constr_CONST_2 != name_skB).
fof(ax29, axiom,
constr_CONST_2 != name_skS).
fof(ax30, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax31, axiom,
constr_CONST_3 != name_A).
fof(ax32, axiom,
constr_CONST_3 != name_B).
fof(ax33, axiom,
constr_CONST_3 != name_I).
fof(ax34, axiom,
constr_CONST_3 != name_c).
fof(ax35, axiom,
constr_CONST_3 != name_skA).
fof(ax36, axiom,
constr_CONST_3 != name_skB).
fof(ax37, axiom,
constr_CONST_3 != name_skS).
fof(ax38, axiom,
constr_CONST_4 != name_A).
fof(ax39, axiom,
constr_CONST_4 != name_B).
fof(ax40, axiom,
constr_CONST_4 != name_I).
fof(ax41, axiom,
constr_CONST_4 != name_c).
fof(ax42, axiom,
constr_CONST_4 != name_skA).
fof(ax43, axiom,
constr_CONST_4 != name_skB).
fof(ax44, axiom,
constr_CONST_4 != name_skS).
fof(ax45, axiom,
name_A != name_B).
fof(ax46, axiom,
name_A != name_I).
fof(ax47, axiom,
name_A != name_c).
fof(ax48, axiom,
name_A != name_skA).
fof(ax49, axiom,
name_A != name_skB).
fof(ax50, axiom,
name_A != name_skS).
fof(ax51, axiom,
name_B != name_I).
fof(ax52, axiom,
name_B != name_c).
fof(ax53, axiom,
name_B != name_skA).
fof(ax54, axiom,
name_B != name_skB).
fof(ax55, axiom,
name_B != name_skS).
fof(ax56, axiom,
name_I != name_c).
fof(ax57, axiom,
name_I != name_skA).
fof(ax58, axiom,
name_I != name_skB).
fof(ax59, axiom,
name_I != name_skS).
fof(ax60, axiom,
name_c != name_skA).
fof(ax61, axiom,
name_c != name_skB).
fof(ax62, axiom,
name_c != name_skS).
fof(ax63, axiom,
name_skA != name_skB).
fof(ax64, axiom,
name_skA != name_skS).
fof(ax65, axiom,
name_skB != name_skS).
fof(ax66, axiom,
![VAR_K_26, VAR_M_25] : (constr_adec(constr_aenc(VAR_M_25, constr_pkey(VAR_K_26)), VAR_K_26) = VAR_M_25)).
fof(ax67, axiom,
![VAR_K_24, VAR_M_23] : (constr_dec(constr_enc(VAR_M_23, VAR_K_24), VAR_K_24) = VAR_M_23)).
fof(ax68, axiom,
![VAR_K_22, VAR_M_21] : (constr_getmess(constr_sign(VAR_M_21, VAR_K_22)) = VAR_M_21)).
fof(ax69, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_checksign(constr_sign(VAR_M_0X30, VAR_K_0X30), constr_pkey(VAR_K_0X30)) = VAR_M_0X30)).
fof(ax70, axiom,
![VAR_X0X30_18, VAR_X1_19, VAR_X2_20X30] : (constr_tuple_3_get_1_bitstring(tuple_3(VAR_X0X30_18, VAR_X1_19, VAR_X2_20X30)) = VAR_X1_19)).
fof(ax71, axiom,
![VAR_X0X30_16, VAR_X1_17] : (constr_tuple_2_get_1_bitstring(tuple_2(VAR_X0X30_16, VAR_X1_17)) = VAR_X1_17)).
fof(ax72, axiom,
![VAR_X0X30_14, VAR_X1_15] : (constr_tuple_2_get_0x30_bitstring(tuple_2(VAR_X0X30_14, VAR_X1_15)) = VAR_X0X30_14)).
fof(ax73, axiom,
![VAR_X0X30_11, VAR_X1_12, VAR_X2_13] : (constr_tuple_3_get_2(tuple_3(VAR_X0X30_11, VAR_X1_12, VAR_X2_13)) = VAR_X2_13)).
fof(ax74, axiom,
![VAR_X0X30_9, VAR_X1_10X30, VAR_X2_0X30] : (constr_tuple_3_get_0x30(tuple_3(VAR_X0X30_9, VAR_X1_10X30, VAR_X2_0X30)) = VAR_X0X30_9)).
fof(ax75, axiom,
![VAR_X0X30_7, VAR_X1_8] : (constr_tuple_2_get_1(tuple_2(VAR_X0X30_7, VAR_X1_8)) = VAR_X1_8)).
fof(ax76, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30] : (constr_tuple_2_get_0x30(tuple_2(VAR_X0X30_0X30, VAR_X1_0X30)) = VAR_X0X30_0X30)).
fof(ax77, axiom,
![VAR_X_44, VAR_Y_45] : (pred_eq_bitstring_bitstring(VAR_X_44, VAR_Y_45))).
fof(ax78, axiom,
![VAR_V_51] : (pred_attacker(VAR_V_51) => pred_attacker(constr_tuple_3_get_2(VAR_V_51)))).
fof(ax79, axiom,
![VAR_V_53] : (pred_attacker(VAR_V_53) => pred_attacker(constr_tuple_3_get_1_bitstring(VAR_V_53)))).
fof(ax80, axiom,
![VAR_V_55] : (pred_attacker(VAR_V_55) => pred_attacker(constr_tuple_3_get_0x30(VAR_V_55)))).
fof(ax81, axiom,
![VAR_V_57] : (pred_attacker(VAR_V_57) => pred_attacker(constr_tuple_2_get_1_bitstring(VAR_V_57)))).
fof(ax82, axiom,
![VAR_V_59] : (pred_attacker(VAR_V_59) => pred_attacker(constr_tuple_2_get_1(VAR_V_59)))).
fof(ax83, axiom,
![VAR_V_61] : (pred_attacker(VAR_V_61) => pred_attacker(constr_tuple_2_get_0x30_bitstring(VAR_V_61)))).
fof(ax84, axiom,
![VAR_V_63] : (pred_attacker(VAR_V_63) => pred_attacker(constr_tuple_2_get_0x30(VAR_V_63)))).
fof(ax85, axiom,
pred_attacker(tuple_true)).
fof(ax86, axiom,
![VAR_V_66, VAR_V_67] : ((pred_attacker(VAR_V_66) & pred_attacker(VAR_V_67)) => pred_attacker(constr_sign(VAR_V_66, VAR_V_67)))).
fof(ax87, axiom,
![VAR_V_69] : (pred_attacker(VAR_V_69) => pred_attacker(constr_pkey(VAR_V_69)))).
fof(ax88, axiom,
![VAR_V_71] : (pred_attacker(VAR_V_71) => pred_attacker(tuple_out_3(VAR_V_71)))).
fof(ax89, axiom,
![VAR_V_74] : (pred_attacker(tuple_out_3(VAR_V_74)) => pred_attacker(VAR_V_74))).
fof(ax90, axiom,
![VAR_V_77] : (pred_attacker(VAR_V_77) => pred_attacker(tuple_out_2(VAR_V_77)))).
fof(ax91, axiom,
![VAR_V_80X30] : (pred_attacker(tuple_out_2(VAR_V_80X30)) => pred_attacker(VAR_V_80X30))).
fof(ax92, axiom,
![VAR_V_83] : (pred_attacker(VAR_V_83) => pred_attacker(tuple_out_1(VAR_V_83)))).
fof(ax93, axiom,
![VAR_V_86] : (pred_attacker(tuple_out_1(VAR_V_86)) => pred_attacker(VAR_V_86))).
fof(ax94, axiom,
![VAR_V_90X30] : (pred_attacker(VAR_V_90X30) => pred_attacker(tuple_key_retrieval_server_out_2(VAR_V_90X30)))).
fof(ax95, axiom,
![VAR_V_93] : (pred_attacker(tuple_key_retrieval_server_out_2(VAR_V_93)) => pred_attacker(VAR_V_93))).
fof(ax96, axiom,
![VAR_V_97, VAR_V_98] : ((pred_attacker(VAR_V_97) & pred_attacker(VAR_V_98)) => pred_attacker(tuple_key_retrieval_server_in_1(VAR_V_97, VAR_V_98)))).
fof(ax97, axiom,
![VAR_V_10X305, VAR_V_10X306] : (pred_attacker(tuple_key_retrieval_server_in_1(VAR_V_10X305, VAR_V_10X306)) => pred_attacker(VAR_V_10X305))).
fof(ax98, axiom,
![VAR_V_10X308, VAR_V_10X309] : (pred_attacker(tuple_key_retrieval_server_in_1(VAR_V_10X308, VAR_V_10X309)) => pred_attacker(VAR_V_10X309))).
fof(ax99, axiom,
![VAR_V_113, VAR_V_114] : ((pred_attacker(VAR_V_113) & pred_attacker(VAR_V_114)) => pred_attacker(tuple_key_register_server_in_1(VAR_V_113, VAR_V_114)))).
fof(ax100, axiom,
![VAR_V_121, VAR_V_122] : (pred_attacker(tuple_key_register_server_in_1(VAR_V_121, VAR_V_122)) => pred_attacker(VAR_V_121))).
fof(ax101, axiom,
![VAR_V_124, VAR_V_125] : (pred_attacker(tuple_key_register_server_in_1(VAR_V_124, VAR_V_125)) => pred_attacker(VAR_V_125))).
fof(ax102, axiom,
![VAR_V_128] : (pred_attacker(VAR_V_128) => pred_attacker(constr_getmess(VAR_V_128)))).
fof(ax103, axiom,
pred_attacker(tuple_false)).
fof(ax104, axiom,
![VAR_V_131, VAR_V_132] : ((pred_attacker(VAR_V_131) & pred_attacker(VAR_V_132)) => pred_attacker(constr_enc(VAR_V_131, VAR_V_132)))).
fof(ax105, axiom,
![VAR_V_135, VAR_V_136] : ((pred_attacker(VAR_V_135) & pred_attacker(VAR_V_136)) => pred_attacker(constr_dec(VAR_V_135, VAR_V_136)))).
fof(ax106, axiom,
![VAR_V_138] : (pred_attacker(VAR_V_138) => pred_attacker(tuple_client_B_out_4(VAR_V_138)))).
fof(ax107, axiom,
![VAR_V_141] : (pred_attacker(tuple_client_B_out_4(VAR_V_141)) => pred_attacker(VAR_V_141))).
fof(ax108, axiom,
![VAR_V_145, VAR_V_146] : ((pred_attacker(VAR_V_145) & pred_attacker(VAR_V_146)) => pred_attacker(tuple_client_B_out_1(VAR_V_145, VAR_V_146)))).
fof(ax109, axiom,
![VAR_V_153, VAR_V_154] : (pred_attacker(tuple_client_B_out_1(VAR_V_153, VAR_V_154)) => pred_attacker(VAR_V_153))).
fof(ax110, axiom,
![VAR_V_156, VAR_V_157] : (pred_attacker(tuple_client_B_out_1(VAR_V_156, VAR_V_157)) => pred_attacker(VAR_V_157))).
fof(ax111, axiom,
![VAR_V_160X30] : (pred_attacker(VAR_V_160X30) => pred_attacker(tuple_client_B_in_5(VAR_V_160X30)))).
fof(ax112, axiom,
![VAR_V_163] : (pred_attacker(tuple_client_B_in_5(VAR_V_163)) => pred_attacker(VAR_V_163))).
fof(ax113, axiom,
![VAR_V_166] : (pred_attacker(VAR_V_166) => pred_attacker(tuple_client_B_in_3(VAR_V_166)))).
fof(ax114, axiom,
![VAR_V_169] : (pred_attacker(tuple_client_B_in_3(VAR_V_169)) => pred_attacker(VAR_V_169))).
fof(ax115, axiom,
![VAR_V_172] : (pred_attacker(VAR_V_172) => pred_attacker(tuple_client_B_in_2(VAR_V_172)))).
fof(ax116, axiom,
![VAR_V_175] : (pred_attacker(tuple_client_B_in_2(VAR_V_175)) => pred_attacker(VAR_V_175))).
fof(ax117, axiom,
![VAR_V_178] : (pred_attacker(VAR_V_178) => pred_attacker(tuple_client_A_out_5(VAR_V_178)))).
fof(ax118, axiom,
![VAR_V_181] : (pred_attacker(tuple_client_A_out_5(VAR_V_181)) => pred_attacker(VAR_V_181))).
fof(ax119, axiom,
![VAR_V_184] : (pred_attacker(VAR_V_184) => pred_attacker(tuple_client_A_out_3(VAR_V_184)))).
fof(ax120, axiom,
![VAR_V_187] : (pred_attacker(tuple_client_A_out_3(VAR_V_187)) => pred_attacker(VAR_V_187))).
fof(ax121, axiom,
![VAR_V_191, VAR_V_192] : ((pred_attacker(VAR_V_191) & pred_attacker(VAR_V_192)) => pred_attacker(tuple_client_A_out_1(VAR_V_191, VAR_V_192)))).
fof(ax122, axiom,
![VAR_V_199, VAR_V_20X300X30] : (pred_attacker(tuple_client_A_out_1(VAR_V_199, VAR_V_20X300X30)) => pred_attacker(VAR_V_199))).
fof(ax123, axiom,
![VAR_V_20X302, VAR_V_20X303] : (pred_attacker(tuple_client_A_out_1(VAR_V_20X302, VAR_V_20X303)) => pred_attacker(VAR_V_20X303))).
fof(ax124, axiom,
![VAR_V_20X306] : (pred_attacker(VAR_V_20X306) => pred_attacker(tuple_client_A_in_4(VAR_V_20X306)))).
fof(ax125, axiom,
![VAR_V_20X309] : (pred_attacker(tuple_client_A_in_4(VAR_V_20X309)) => pred_attacker(VAR_V_20X309))).
fof(ax126, axiom,
![VAR_V_212] : (pred_attacker(VAR_V_212) => pred_attacker(tuple_client_A_in_2(VAR_V_212)))).
fof(ax127, axiom,
![VAR_V_215] : (pred_attacker(tuple_client_A_in_2(VAR_V_215)) => pred_attacker(VAR_V_215))).
fof(ax128, axiom,
![VAR_V_219, VAR_V_220X30] : ((pred_attacker(VAR_V_219) & pred_attacker(VAR_V_220X30)) => pred_attacker(constr_checksign(VAR_V_219, VAR_V_220X30)))).
fof(ax129, axiom,
![VAR_V_223, VAR_V_224] : ((pred_attacker(VAR_V_223) & pred_attacker(VAR_V_224)) => pred_attacker(constr_aenc(VAR_V_223, VAR_V_224)))).
fof(ax130, axiom,
![VAR_V_227, VAR_V_228] : ((pred_attacker(VAR_V_227) & pred_attacker(VAR_V_228)) => pred_attacker(constr_adec(VAR_V_227, VAR_V_228)))).
fof(ax131, axiom,
pred_attacker(constr_CONST_4)).
fof(ax132, axiom,
pred_attacker(constr_CONST_3)).
fof(ax133, axiom,
pred_attacker(constr_CONST_2)).
fof(ax134, axiom,
pred_attacker(constr_CONST_1)).
fof(ax135, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax136, axiom,
![VAR_V_236, VAR_V_237, VAR_V_238] : ((pred_attacker(VAR_V_236) & pred_attacker(VAR_V_237) & pred_attacker(VAR_V_238)) => pred_attacker(tuple_3(VAR_V_236, VAR_V_237, VAR_V_238)))).
fof(ax137, axiom,
![VAR_V_251, VAR_V_252, VAR_V_253] : (pred_attacker(tuple_3(VAR_V_251, VAR_V_252, VAR_V_253)) => pred_attacker(VAR_V_251))).
fof(ax138, axiom,
![VAR_V_255, VAR_V_256, VAR_V_257] : (pred_attacker(tuple_3(VAR_V_255, VAR_V_256, VAR_V_257)) => pred_attacker(VAR_V_256))).
fof(ax139, axiom,
![VAR_V_259, VAR_V_260X30, VAR_V_261] : (pred_attacker(tuple_3(VAR_V_259, VAR_V_260X30, VAR_V_261)) => pred_attacker(VAR_V_261))).
fof(ax140, axiom,
![VAR_V_265, VAR_V_266] : ((pred_attacker(VAR_V_265) & pred_attacker(VAR_V_266)) => pred_attacker(tuple_2(VAR_V_265, VAR_V_266)))).
fof(ax141, axiom,
![VAR_V_273, VAR_V_274] : (pred_attacker(tuple_2(VAR_V_273, VAR_V_274)) => pred_attacker(VAR_V_273))).
fof(ax142, axiom,
![VAR_V_276, VAR_V_277] : (pred_attacker(tuple_2(VAR_V_276, VAR_V_277)) => pred_attacker(VAR_V_277))).
fof(ax143, axiom,
![VAR_V_279, VAR_V_280X30] : ((pred_mess(VAR_V_280X30, VAR_V_279) & pred_attacker(VAR_V_280X30)) => pred_attacker(VAR_V_279))).
fof(ax144, axiom,
![VAR_V_281, VAR_V_282] : ((pred_attacker(VAR_V_282) & pred_attacker(VAR_V_281)) => pred_mess(VAR_V_282, VAR_V_281))).
fof(ax145, axiom,
pred_attacker(name_c)).
fof(ax146, axiom,
pred_attacker(name_I)).
fof(ax147, axiom,
pred_attacker(name_B)).
fof(ax148, axiom,
pred_attacker(name_A)).
fof(ax149, axiom,
![VAR_V_284] : (pred_equal(VAR_V_284, VAR_V_284))).
fof(ax150, axiom,
![VAR_V_285] : (pred_attacker(name_new0x2Dname(VAR_V_285)))).
fof(ax151, axiom,
pred_table(tuple_keys(name_A, constr_pkey(name_skA)))).
fof(ax152, axiom,
pred_table(tuple_keys(name_B, constr_pkey(name_skB)))).
fof(ax153, axiom,
pred_attacker(tuple_out_1(constr_pkey(name_skA)))).
fof(ax154, axiom,
pred_attacker(tuple_out_2(constr_pkey(name_skB)))).
fof(ax155, axiom,
pred_attacker(tuple_out_3(constr_pkey(name_skS)))).
fof(ax156, axiom,
pred_attacker(tuple_client_A_out_1(name_A, name_I))).
fof(ax157, axiom,
![VAR_0X40SID_40X305, VAR_SIGN_I_PKI_40X304] : ((pred_eq_bitstring_bitstring(name_I, constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_I_PKI_40X304, constr_pkey(name_skS)))) & pred_attacker(tuple_client_A_in_2(VAR_SIGN_I_PKI_40X304))) => pred_attacker(tuple_client_A_out_3(constr_aenc(tuple_2(name_Na(VAR_0X40SID_40X305), name_A), constr_tuple_2_get_1_bitstring(constr_checksign(VAR_SIGN_I_PKI_40X304, constr_pkey(name_skS)))))))).
fof(ax158, axiom,
![VAR_0X40SID_468, VAR_AENC_NA_NI_I_467, VAR_SIGN_I_PKI_469] : ((pred_eq_bitstring_bitstring(name_I, constr_tuple_3_get_2(constr_adec(VAR_AENC_NA_NI_I_467, name_skA))) & pred_eq_bitstring_bitstring(name_Na(VAR_0X40SID_468), constr_tuple_3_get_0x30(constr_adec(VAR_AENC_NA_NI_I_467, name_skA))) & pred_attacker(tuple_client_A_in_4(VAR_AENC_NA_NI_I_467)) & pred_eq_bitstring_bitstring(name_I, constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_I_PKI_469, constr_pkey(name_skS)))) & pred_attacker(tuple_client_A_in_2(VAR_SIGN_I_PKI_469))) => pred_attacker(tuple_client_A_out_5(constr_aenc(constr_tuple_3_get_1_bitstring(constr_adec(VAR_AENC_NA_NI_I_467, name_skA)), constr_tuple_2_get_1_bitstring(constr_checksign(VAR_SIGN_I_PKI_469, constr_pkey(name_skS)))))))).
fof(ax159, axiom,
pred_attacker(tuple_client_B_out_1(name_B, name_A))).
fof(ax160, axiom,
![VAR_0X40SID_582, VAR_AENC_NA_A_580X30, VAR_SIGN_A_PKA_581] : ((pred_eq_bitstring_bitstring(name_A, constr_tuple_2_get_1(constr_adec(VAR_AENC_NA_A_580X30, name_skB))) & pred_attacker(tuple_client_B_in_3(VAR_AENC_NA_A_580X30)) & pred_eq_bitstring_bitstring(name_A, constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_A_PKA_581, constr_pkey(name_skS)))) & pred_attacker(tuple_client_B_in_2(VAR_SIGN_A_PKA_581))) => pred_attacker(tuple_client_B_out_4(constr_aenc(tuple_3(constr_tuple_2_get_0x30_bitstring(constr_adec(VAR_AENC_NA_A_580X30, name_skB)), name_Nb(VAR_0X40SID_582), name_B), constr_tuple_2_get_1_bitstring(constr_checksign(VAR_SIGN_A_PKA_581, constr_pkey(name_skS)))))))).
fof(ax161, axiom,
![VAR_DST_641, VAR_PKDST_642, VAR_SRC_643] : ((pred_table(tuple_keys(VAR_DST_641, VAR_PKDST_642)) & pred_attacker(tuple_key_retrieval_server_in_1(VAR_SRC_643, VAR_DST_641))) => pred_attacker(tuple_key_retrieval_server_out_2(constr_sign(tuple_2(VAR_DST_641, VAR_PKDST_642), name_skS))))).
fof(ax162, axiom,
![VAR_HOST_695, VAR_PK_696] : ((VAR_HOST_695 != name_B & VAR_HOST_695 != name_A & pred_attacker(tuple_key_register_server_in_1(VAR_HOST_695, VAR_PK_696))) => pred_table(tuple_keys(VAR_HOST_695, VAR_PK_696)))).
fof(co0, conjecture,
pred_attacker(name_Nb(VAR_V_70X304))).
