%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_STEP_1).
fof(ax5, axiom,
constr_CONST_0x30 != constr_STEP_2).
fof(ax6, axiom,
constr_CONST_0x30 != constr_STEP_3).
fof(ax7, axiom,
constr_CONST_0x30 != constr_client_A_STEP_1).
fof(ax8, axiom,
constr_CONST_0x30 != constr_client_A_STEP_2).
fof(ax9, axiom,
constr_CONST_0x30 != constr_client_A_STEP_3).
fof(ax10, axiom,
constr_CONST_0x30 != constr_client_B_STEP_1).
fof(ax11, axiom,
constr_CONST_0x30 != constr_client_B_STEP_2).
fof(ax12, axiom,
constr_CONST_0x30 != constr_client_B_STEP_3).
fof(ax13, axiom,
constr_CONST_0x30 != constr_key_retrieval_server_STEP_1).
fof(ax14, axiom,
constr_CONST_0x30 != name_A).
fof(ax15, axiom,
constr_CONST_0x30 != name_B).
fof(ax16, axiom,
constr_CONST_0x30 != name_I).
fof(ax17, axiom,
constr_CONST_0x30 != name_c).
fof(ax18, axiom,
constr_CONST_0x30 != name_objective).
fof(ax19, axiom,
constr_CONST_0x30 != name_skA).
fof(ax20, axiom,
constr_CONST_0x30 != name_skB).
fof(ax21, axiom,
constr_CONST_0x30 != name_skS).
fof(ax22, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax23, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax24, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax25, axiom,
constr_CONST_1 != constr_STEP_1).
fof(ax26, axiom,
constr_CONST_1 != constr_STEP_2).
fof(ax27, axiom,
constr_CONST_1 != constr_STEP_3).
fof(ax28, axiom,
constr_CONST_1 != constr_client_A_STEP_1).
fof(ax29, axiom,
constr_CONST_1 != constr_client_A_STEP_2).
fof(ax30, axiom,
constr_CONST_1 != constr_client_A_STEP_3).
fof(ax31, axiom,
constr_CONST_1 != constr_client_B_STEP_1).
fof(ax32, axiom,
constr_CONST_1 != constr_client_B_STEP_2).
fof(ax33, axiom,
constr_CONST_1 != constr_client_B_STEP_3).
fof(ax34, axiom,
constr_CONST_1 != constr_key_retrieval_server_STEP_1).
fof(ax35, axiom,
constr_CONST_1 != name_A).
fof(ax36, axiom,
constr_CONST_1 != name_B).
fof(ax37, axiom,
constr_CONST_1 != name_I).
fof(ax38, axiom,
constr_CONST_1 != name_c).
fof(ax39, axiom,
constr_CONST_1 != name_objective).
fof(ax40, axiom,
constr_CONST_1 != name_skA).
fof(ax41, axiom,
constr_CONST_1 != name_skB).
fof(ax42, axiom,
constr_CONST_1 != name_skS).
fof(ax43, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax44, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax45, axiom,
constr_CONST_2 != constr_STEP_1).
fof(ax46, axiom,
constr_CONST_2 != constr_STEP_2).
fof(ax47, axiom,
constr_CONST_2 != constr_STEP_3).
fof(ax48, axiom,
constr_CONST_2 != constr_client_A_STEP_1).
fof(ax49, axiom,
constr_CONST_2 != constr_client_A_STEP_2).
fof(ax50, axiom,
constr_CONST_2 != constr_client_A_STEP_3).
fof(ax51, axiom,
constr_CONST_2 != constr_client_B_STEP_1).
fof(ax52, axiom,
constr_CONST_2 != constr_client_B_STEP_2).
fof(ax53, axiom,
constr_CONST_2 != constr_client_B_STEP_3).
fof(ax54, axiom,
constr_CONST_2 != constr_key_retrieval_server_STEP_1).
fof(ax55, axiom,
constr_CONST_2 != name_A).
fof(ax56, axiom,
constr_CONST_2 != name_B).
fof(ax57, axiom,
constr_CONST_2 != name_I).
fof(ax58, axiom,
constr_CONST_2 != name_c).
fof(ax59, axiom,
constr_CONST_2 != name_objective).
fof(ax60, axiom,
constr_CONST_2 != name_skA).
fof(ax61, axiom,
constr_CONST_2 != name_skB).
fof(ax62, axiom,
constr_CONST_2 != name_skS).
fof(ax63, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax64, axiom,
constr_CONST_3 != constr_STEP_1).
fof(ax65, axiom,
constr_CONST_3 != constr_STEP_2).
fof(ax66, axiom,
constr_CONST_3 != constr_STEP_3).
fof(ax67, axiom,
constr_CONST_3 != constr_client_A_STEP_1).
fof(ax68, axiom,
constr_CONST_3 != constr_client_A_STEP_2).
fof(ax69, axiom,
constr_CONST_3 != constr_client_A_STEP_3).
fof(ax70, axiom,
constr_CONST_3 != constr_client_B_STEP_1).
fof(ax71, axiom,
constr_CONST_3 != constr_client_B_STEP_2).
fof(ax72, axiom,
constr_CONST_3 != constr_client_B_STEP_3).
fof(ax73, axiom,
constr_CONST_3 != constr_key_retrieval_server_STEP_1).
fof(ax74, axiom,
constr_CONST_3 != name_A).
fof(ax75, axiom,
constr_CONST_3 != name_B).
fof(ax76, axiom,
constr_CONST_3 != name_I).
fof(ax77, axiom,
constr_CONST_3 != name_c).
fof(ax78, axiom,
constr_CONST_3 != name_objective).
fof(ax79, axiom,
constr_CONST_3 != name_skA).
fof(ax80, axiom,
constr_CONST_3 != name_skB).
fof(ax81, axiom,
constr_CONST_3 != name_skS).
fof(ax82, axiom,
constr_CONST_4 != constr_STEP_1).
fof(ax83, axiom,
constr_CONST_4 != constr_STEP_2).
fof(ax84, axiom,
constr_CONST_4 != constr_STEP_3).
fof(ax85, axiom,
constr_CONST_4 != constr_client_A_STEP_1).
fof(ax86, axiom,
constr_CONST_4 != constr_client_A_STEP_2).
fof(ax87, axiom,
constr_CONST_4 != constr_client_A_STEP_3).
fof(ax88, axiom,
constr_CONST_4 != constr_client_B_STEP_1).
fof(ax89, axiom,
constr_CONST_4 != constr_client_B_STEP_2).
fof(ax90, axiom,
constr_CONST_4 != constr_client_B_STEP_3).
fof(ax91, axiom,
constr_CONST_4 != constr_key_retrieval_server_STEP_1).
fof(ax92, axiom,
constr_CONST_4 != name_A).
fof(ax93, axiom,
constr_CONST_4 != name_B).
fof(ax94, axiom,
constr_CONST_4 != name_I).
fof(ax95, axiom,
constr_CONST_4 != name_c).
fof(ax96, axiom,
constr_CONST_4 != name_objective).
fof(ax97, axiom,
constr_CONST_4 != name_skA).
fof(ax98, axiom,
constr_CONST_4 != name_skB).
fof(ax99, axiom,
constr_CONST_4 != name_skS).
fof(ax100, axiom,
constr_STEP_1 != constr_STEP_2).
fof(ax101, axiom,
constr_STEP_1 != constr_STEP_3).
fof(ax102, axiom,
constr_STEP_1 != constr_client_A_STEP_1).
fof(ax103, axiom,
constr_STEP_1 != constr_client_A_STEP_2).
fof(ax104, axiom,
constr_STEP_1 != constr_client_A_STEP_3).
fof(ax105, axiom,
constr_STEP_1 != constr_client_B_STEP_1).
fof(ax106, axiom,
constr_STEP_1 != constr_client_B_STEP_2).
fof(ax107, axiom,
constr_STEP_1 != constr_client_B_STEP_3).
fof(ax108, axiom,
constr_STEP_1 != constr_key_retrieval_server_STEP_1).
fof(ax109, axiom,
constr_STEP_1 != name_A).
fof(ax110, axiom,
constr_STEP_1 != name_B).
fof(ax111, axiom,
constr_STEP_1 != name_I).
fof(ax112, axiom,
constr_STEP_1 != name_c).
fof(ax113, axiom,
constr_STEP_1 != name_objective).
fof(ax114, axiom,
constr_STEP_1 != name_skA).
fof(ax115, axiom,
constr_STEP_1 != name_skB).
fof(ax116, axiom,
constr_STEP_1 != name_skS).
fof(ax117, axiom,
constr_STEP_2 != constr_STEP_3).
fof(ax118, axiom,
constr_STEP_2 != constr_client_A_STEP_1).
fof(ax119, axiom,
constr_STEP_2 != constr_client_A_STEP_2).
fof(ax120, axiom,
constr_STEP_2 != constr_client_A_STEP_3).
fof(ax121, axiom,
constr_STEP_2 != constr_client_B_STEP_1).
fof(ax122, axiom,
constr_STEP_2 != constr_client_B_STEP_2).
fof(ax123, axiom,
constr_STEP_2 != constr_client_B_STEP_3).
fof(ax124, axiom,
constr_STEP_2 != constr_key_retrieval_server_STEP_1).
fof(ax125, axiom,
constr_STEP_2 != name_A).
fof(ax126, axiom,
constr_STEP_2 != name_B).
fof(ax127, axiom,
constr_STEP_2 != name_I).
fof(ax128, axiom,
constr_STEP_2 != name_c).
fof(ax129, axiom,
constr_STEP_2 != name_objective).
fof(ax130, axiom,
constr_STEP_2 != name_skA).
fof(ax131, axiom,
constr_STEP_2 != name_skB).
fof(ax132, axiom,
constr_STEP_2 != name_skS).
fof(ax133, axiom,
constr_STEP_3 != constr_client_A_STEP_1).
fof(ax134, axiom,
constr_STEP_3 != constr_client_A_STEP_2).
fof(ax135, axiom,
constr_STEP_3 != constr_client_A_STEP_3).
fof(ax136, axiom,
constr_STEP_3 != constr_client_B_STEP_1).
fof(ax137, axiom,
constr_STEP_3 != constr_client_B_STEP_2).
fof(ax138, axiom,
constr_STEP_3 != constr_client_B_STEP_3).
fof(ax139, axiom,
constr_STEP_3 != constr_key_retrieval_server_STEP_1).
fof(ax140, axiom,
constr_STEP_3 != name_A).
fof(ax141, axiom,
constr_STEP_3 != name_B).
fof(ax142, axiom,
constr_STEP_3 != name_I).
fof(ax143, axiom,
constr_STEP_3 != name_c).
fof(ax144, axiom,
constr_STEP_3 != name_objective).
fof(ax145, axiom,
constr_STEP_3 != name_skA).
fof(ax146, axiom,
constr_STEP_3 != name_skB).
fof(ax147, axiom,
constr_STEP_3 != name_skS).
fof(ax148, axiom,
constr_client_A_STEP_1 != constr_client_A_STEP_2).
fof(ax149, axiom,
constr_client_A_STEP_1 != constr_client_A_STEP_3).
fof(ax150, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_1).
fof(ax151, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_2).
fof(ax152, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_3).
fof(ax153, axiom,
constr_client_A_STEP_1 != constr_key_retrieval_server_STEP_1).
fof(ax154, axiom,
constr_client_A_STEP_1 != name_A).
fof(ax155, axiom,
constr_client_A_STEP_1 != name_B).
fof(ax156, axiom,
constr_client_A_STEP_1 != name_I).
fof(ax157, axiom,
constr_client_A_STEP_1 != name_c).
fof(ax158, axiom,
constr_client_A_STEP_1 != name_objective).
fof(ax159, axiom,
constr_client_A_STEP_1 != name_skA).
fof(ax160, axiom,
constr_client_A_STEP_1 != name_skB).
fof(ax161, axiom,
constr_client_A_STEP_1 != name_skS).
fof(ax162, axiom,
constr_client_A_STEP_2 != constr_client_A_STEP_3).
fof(ax163, axiom,
constr_client_A_STEP_2 != constr_client_B_STEP_1).
fof(ax164, axiom,
constr_client_A_STEP_2 != constr_client_B_STEP_2).
fof(ax165, axiom,
constr_client_A_STEP_2 != constr_client_B_STEP_3).
fof(ax166, axiom,
constr_client_A_STEP_2 != constr_key_retrieval_server_STEP_1).
fof(ax167, axiom,
constr_client_A_STEP_2 != name_A).
fof(ax168, axiom,
constr_client_A_STEP_2 != name_B).
fof(ax169, axiom,
constr_client_A_STEP_2 != name_I).
fof(ax170, axiom,
constr_client_A_STEP_2 != name_c).
fof(ax171, axiom,
constr_client_A_STEP_2 != name_objective).
fof(ax172, axiom,
constr_client_A_STEP_2 != name_skA).
fof(ax173, axiom,
constr_client_A_STEP_2 != name_skB).
fof(ax174, axiom,
constr_client_A_STEP_2 != name_skS).
fof(ax175, axiom,
constr_client_A_STEP_3 != constr_client_B_STEP_1).
fof(ax176, axiom,
constr_client_A_STEP_3 != constr_client_B_STEP_2).
fof(ax177, axiom,
constr_client_A_STEP_3 != constr_client_B_STEP_3).
fof(ax178, axiom,
constr_client_A_STEP_3 != constr_key_retrieval_server_STEP_1).
fof(ax179, axiom,
constr_client_A_STEP_3 != name_A).
fof(ax180, axiom,
constr_client_A_STEP_3 != name_B).
fof(ax181, axiom,
constr_client_A_STEP_3 != name_I).
fof(ax182, axiom,
constr_client_A_STEP_3 != name_c).
fof(ax183, axiom,
constr_client_A_STEP_3 != name_objective).
fof(ax184, axiom,
constr_client_A_STEP_3 != name_skA).
fof(ax185, axiom,
constr_client_A_STEP_3 != name_skB).
fof(ax186, axiom,
constr_client_A_STEP_3 != name_skS).
fof(ax187, axiom,
constr_client_B_STEP_1 != constr_client_B_STEP_2).
fof(ax188, axiom,
constr_client_B_STEP_1 != constr_client_B_STEP_3).
fof(ax189, axiom,
constr_client_B_STEP_1 != constr_key_retrieval_server_STEP_1).
fof(ax190, axiom,
constr_client_B_STEP_1 != name_A).
fof(ax191, axiom,
constr_client_B_STEP_1 != name_B).
fof(ax192, axiom,
constr_client_B_STEP_1 != name_I).
fof(ax193, axiom,
constr_client_B_STEP_1 != name_c).
fof(ax194, axiom,
constr_client_B_STEP_1 != name_objective).
fof(ax195, axiom,
constr_client_B_STEP_1 != name_skA).
fof(ax196, axiom,
constr_client_B_STEP_1 != name_skB).
fof(ax197, axiom,
constr_client_B_STEP_1 != name_skS).
fof(ax198, axiom,
constr_client_B_STEP_2 != constr_client_B_STEP_3).
fof(ax199, axiom,
constr_client_B_STEP_2 != constr_key_retrieval_server_STEP_1).
fof(ax200, axiom,
constr_client_B_STEP_2 != name_A).
fof(ax201, axiom,
constr_client_B_STEP_2 != name_B).
fof(ax202, axiom,
constr_client_B_STEP_2 != name_I).
fof(ax203, axiom,
constr_client_B_STEP_2 != name_c).
fof(ax204, axiom,
constr_client_B_STEP_2 != name_objective).
fof(ax205, axiom,
constr_client_B_STEP_2 != name_skA).
fof(ax206, axiom,
constr_client_B_STEP_2 != name_skB).
fof(ax207, axiom,
constr_client_B_STEP_2 != name_skS).
fof(ax208, axiom,
constr_client_B_STEP_3 != constr_key_retrieval_server_STEP_1).
fof(ax209, axiom,
constr_client_B_STEP_3 != name_A).
fof(ax210, axiom,
constr_client_B_STEP_3 != name_B).
fof(ax211, axiom,
constr_client_B_STEP_3 != name_I).
fof(ax212, axiom,
constr_client_B_STEP_3 != name_c).
fof(ax213, axiom,
constr_client_B_STEP_3 != name_objective).
fof(ax214, axiom,
constr_client_B_STEP_3 != name_skA).
fof(ax215, axiom,
constr_client_B_STEP_3 != name_skB).
fof(ax216, axiom,
constr_client_B_STEP_3 != name_skS).
fof(ax217, axiom,
constr_key_retrieval_server_STEP_1 != name_A).
fof(ax218, axiom,
constr_key_retrieval_server_STEP_1 != name_B).
fof(ax219, axiom,
constr_key_retrieval_server_STEP_1 != name_I).
fof(ax220, axiom,
constr_key_retrieval_server_STEP_1 != name_c).
fof(ax221, axiom,
constr_key_retrieval_server_STEP_1 != name_objective).
fof(ax222, axiom,
constr_key_retrieval_server_STEP_1 != name_skA).
fof(ax223, axiom,
constr_key_retrieval_server_STEP_1 != name_skB).
fof(ax224, axiom,
constr_key_retrieval_server_STEP_1 != name_skS).
fof(ax225, axiom,
name_A != name_B).
fof(ax226, axiom,
name_A != name_I).
fof(ax227, axiom,
name_A != name_c).
fof(ax228, axiom,
name_A != name_objective).
fof(ax229, axiom,
name_A != name_skA).
fof(ax230, axiom,
name_A != name_skB).
fof(ax231, axiom,
name_A != name_skS).
fof(ax232, axiom,
name_B != name_I).
fof(ax233, axiom,
name_B != name_c).
fof(ax234, axiom,
name_B != name_objective).
fof(ax235, axiom,
name_B != name_skA).
fof(ax236, axiom,
name_B != name_skB).
fof(ax237, axiom,
name_B != name_skS).
fof(ax238, axiom,
name_I != name_c).
fof(ax239, axiom,
name_I != name_objective).
fof(ax240, axiom,
name_I != name_skA).
fof(ax241, axiom,
name_I != name_skB).
fof(ax242, axiom,
name_I != name_skS).
fof(ax243, axiom,
name_c != name_objective).
fof(ax244, axiom,
name_c != name_skA).
fof(ax245, axiom,
name_c != name_skB).
fof(ax246, axiom,
name_c != name_skS).
fof(ax247, axiom,
name_objective != name_skA).
fof(ax248, axiom,
name_objective != name_skB).
fof(ax249, axiom,
name_objective != name_skS).
fof(ax250, axiom,
name_skA != name_skB).
fof(ax251, axiom,
name_skA != name_skS).
fof(ax252, axiom,
name_skB != name_skS).
fof(ax253, axiom,
![VAR_K_44, VAR_M_43] : (constr_dec(constr_enc(VAR_M_43, VAR_K_44), VAR_K_44) = VAR_M_43)).
fof(ax254, axiom,
![VAR_K_42, VAR_M_41] : (constr_getmess(constr_sign(VAR_M_41, VAR_K_42)) = VAR_M_41)).
fof(ax255, axiom,
![VAR_K_40X30, VAR_M_0X30] : (constr_checksign(constr_sign(VAR_M_0X30, VAR_K_40X30), constr_pkey(VAR_K_40X30)) = VAR_M_0X30)).
fof(ax256, axiom,
![VAR_K_39, VAR_X1_35, VAR_X2_36, VAR_X3_37, VAR_X4_38] : (constr_ecb_dec_4(constr_ecb_enc_4(VAR_X1_35, VAR_X2_36, VAR_X3_37, VAR_X4_38, constr_pkey(VAR_K_39)), VAR_K_39) = tuple_4(VAR_X1_35, VAR_X2_36, VAR_X3_37, VAR_X4_38))).
fof(ax257, axiom,
![VAR_K_34, VAR_X1_31, VAR_X2_32, VAR_X3_33] : (constr_ecb_dec_3(constr_ecb_enc_3(VAR_X1_31, VAR_X2_32, VAR_X3_33, constr_pkey(VAR_K_34)), VAR_K_34) = tuple_3(VAR_X1_31, VAR_X2_32, VAR_X3_33))).
fof(ax258, axiom,
![VAR_K_30X30, VAR_X1_28, VAR_X2_29] : (constr_ecb_dec_2(constr_ecb_enc_2(VAR_X1_28, VAR_X2_29, constr_pkey(VAR_K_30X30)), VAR_K_30X30) = tuple_2(VAR_X1_28, VAR_X2_29))).
fof(ax259, axiom,
![VAR_K_27, VAR_X1_26] : (constr_ecb_dec_1(constr_ecb_enc_1(VAR_X1_26, constr_pkey(VAR_K_27)), VAR_K_27) = VAR_X1_26)).
fof(ax260, axiom,
![VAR_K_25, VAR_X1_22, VAR_X2_23, VAR_X3_24, VAR_X4_0X30] : (constr_ecb_enc_4(VAR_X1_22, VAR_X2_23, VAR_X3_24, VAR_X4_0X30, VAR_K_25) = tuple_4(constr_ecb_enc_1(VAR_X1_22, VAR_K_25), constr_ecb_enc_1(VAR_X2_23, VAR_K_25), constr_ecb_enc_1(VAR_X3_24, VAR_K_25), constr_ecb_enc_1(VAR_X4_0X30, VAR_K_25)))).
fof(ax261, axiom,
![VAR_K_21, VAR_X1_19, VAR_X2_20X30, VAR_X3_0X30] : (constr_ecb_enc_3(VAR_X1_19, VAR_X2_20X30, VAR_X3_0X30, VAR_K_21) = tuple_3(constr_ecb_enc_1(VAR_X1_19, VAR_K_21), constr_ecb_enc_1(VAR_X2_20X30, VAR_K_21), constr_ecb_enc_1(VAR_X3_0X30, VAR_K_21)))).
fof(ax262, axiom,
![VAR_K_0X30, VAR_X1_17, VAR_X2_18] : (constr_ecb_enc_2(VAR_X1_17, VAR_X2_18, VAR_K_0X30) = tuple_2(constr_ecb_enc_1(VAR_X1_17, VAR_K_0X30), constr_ecb_enc_1(VAR_X2_18, VAR_K_0X30)))).
fof(ax263, axiom,
![VAR_X0X30_14, VAR_X1_15, VAR_X2_16] : (constr_tuple_3_get_2(tuple_3(VAR_X0X30_14, VAR_X1_15, VAR_X2_16)) = VAR_X2_16)).
fof(ax264, axiom,
![VAR_X0X30_11, VAR_X1_12, VAR_X2_13] : (constr_tuple_3_get_1(tuple_3(VAR_X0X30_11, VAR_X1_12, VAR_X2_13)) = VAR_X1_12)).
fof(ax265, axiom,
![VAR_X0X30_9, VAR_X1_10X30, VAR_X2_0X30] : (constr_tuple_3_get_0x30(tuple_3(VAR_X0X30_9, VAR_X1_10X30, VAR_X2_0X30)) = VAR_X0X30_9)).
fof(ax266, axiom,
![VAR_X0X30_7, VAR_X1_8] : (constr_tuple_2_get_1(tuple_2(VAR_X0X30_7, VAR_X1_8)) = VAR_X1_8)).
fof(ax267, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30] : (constr_tuple_2_get_0x30(tuple_2(VAR_X0X30_0X30, VAR_X1_0X30)) = VAR_X0X30_0X30)).
fof(ax268, axiom,
![VAR_X_62] : (pred_eq(VAR_X_62, VAR_X_62))).
fof(ax269, axiom,
![VAR_V_68] : (pred_attacker(VAR_V_68) => pred_attacker(constr_tuple_3_get_2(VAR_V_68)))).
fof(ax270, axiom,
![VAR_V_70X30] : (pred_attacker(VAR_V_70X30) => pred_attacker(constr_tuple_3_get_1(VAR_V_70X30)))).
fof(ax271, axiom,
![VAR_V_72] : (pred_attacker(VAR_V_72) => pred_attacker(constr_tuple_3_get_0x30(VAR_V_72)))).
fof(ax272, axiom,
![VAR_V_74] : (pred_attacker(VAR_V_74) => pred_attacker(constr_tuple_2_get_1(VAR_V_74)))).
fof(ax273, axiom,
![VAR_V_76] : (pred_attacker(VAR_V_76) => pred_attacker(constr_tuple_2_get_0x30(VAR_V_76)))).
fof(ax274, axiom,
pred_attacker(tuple_true)).
fof(ax275, axiom,
![VAR_V_79, VAR_V_80X30] : ((pred_attacker(VAR_V_79) & pred_attacker(VAR_V_80X30)) => pred_attacker(constr_sign(VAR_V_79, VAR_V_80X30)))).
fof(ax276, axiom,
![VAR_V_82] : (pred_attacker(VAR_V_82) => pred_attacker(constr_pkey(VAR_V_82)))).
fof(ax277, axiom,
pred_attacker(constr_key_retrieval_server_STEP_1)).
fof(ax278, axiom,
![VAR_V_85] : (pred_attacker(VAR_V_85) => pred_attacker(constr_getmess(VAR_V_85)))).
fof(ax279, axiom,
pred_attacker(tuple_false)).
fof(ax280, axiom,
![VAR_V_88, VAR_V_89] : ((pred_attacker(VAR_V_88) & pred_attacker(VAR_V_89)) => pred_attacker(constr_enc(VAR_V_88, VAR_V_89)))).
fof(ax281, axiom,
![VAR_V_95, VAR_V_96, VAR_V_97, VAR_V_98, VAR_V_99] : ((pred_attacker(VAR_V_95) & pred_attacker(VAR_V_96) & pred_attacker(VAR_V_97) & pred_attacker(VAR_V_98) & pred_attacker(VAR_V_99)) => pred_attacker(constr_ecb_enc_4(VAR_V_95, VAR_V_96, VAR_V_97, VAR_V_98, VAR_V_99)))).
fof(ax282, axiom,
![VAR_V_10X304, VAR_V_10X305, VAR_V_10X306, VAR_V_10X307] : ((pred_attacker(VAR_V_10X304) & pred_attacker(VAR_V_10X305) & pred_attacker(VAR_V_10X306) & pred_attacker(VAR_V_10X307)) => pred_attacker(constr_ecb_enc_3(VAR_V_10X304, VAR_V_10X305, VAR_V_10X306, VAR_V_10X307)))).
fof(ax283, axiom,
![VAR_V_111, VAR_V_112, VAR_V_113] : ((pred_attacker(VAR_V_111) & pred_attacker(VAR_V_112) & pred_attacker(VAR_V_113)) => pred_attacker(constr_ecb_enc_2(VAR_V_111, VAR_V_112, VAR_V_113)))).
fof(ax284, axiom,
![VAR_V_116, VAR_V_117] : ((pred_attacker(VAR_V_116) & pred_attacker(VAR_V_117)) => pred_attacker(constr_ecb_enc_1(VAR_V_116, VAR_V_117)))).
fof(ax285, axiom,
![VAR_V_120X30, VAR_V_121] : ((pred_attacker(VAR_V_120X30) & pred_attacker(VAR_V_121)) => pred_attacker(constr_ecb_dec_4(VAR_V_120X30, VAR_V_121)))).
fof(ax286, axiom,
![VAR_V_124, VAR_V_125] : ((pred_attacker(VAR_V_124) & pred_attacker(VAR_V_125)) => pred_attacker(constr_ecb_dec_3(VAR_V_124, VAR_V_125)))).
fof(ax287, axiom,
![VAR_V_128, VAR_V_129] : ((pred_attacker(VAR_V_128) & pred_attacker(VAR_V_129)) => pred_attacker(constr_ecb_dec_2(VAR_V_128, VAR_V_129)))).
fof(ax288, axiom,
![VAR_V_132, VAR_V_133] : ((pred_attacker(VAR_V_132) & pred_attacker(VAR_V_133)) => pred_attacker(constr_ecb_dec_1(VAR_V_132, VAR_V_133)))).
fof(ax289, axiom,
![VAR_V_136, VAR_V_137] : ((pred_attacker(VAR_V_136) & pred_attacker(VAR_V_137)) => pred_attacker(constr_dec(VAR_V_136, VAR_V_137)))).
fof(ax290, axiom,
pred_attacker(constr_client_B_STEP_3)).
fof(ax291, axiom,
pred_attacker(constr_client_B_STEP_2)).
fof(ax292, axiom,
pred_attacker(constr_client_B_STEP_1)).
fof(ax293, axiom,
pred_attacker(constr_client_A_STEP_3)).
fof(ax294, axiom,
pred_attacker(constr_client_A_STEP_2)).
fof(ax295, axiom,
pred_attacker(constr_client_A_STEP_1)).
fof(ax296, axiom,
![VAR_V_140X30, VAR_V_141] : ((pred_attacker(VAR_V_140X30) & pred_attacker(VAR_V_141)) => pred_attacker(constr_checksign(VAR_V_140X30, VAR_V_141)))).
fof(ax297, axiom,
pred_attacker(constr_STEP_3)).
fof(ax298, axiom,
pred_attacker(constr_STEP_2)).
fof(ax299, axiom,
pred_attacker(constr_STEP_1)).
fof(ax300, axiom,
pred_attacker(constr_CONST_4)).
fof(ax301, axiom,
pred_attacker(constr_CONST_3)).
fof(ax302, axiom,
pred_attacker(constr_CONST_2)).
fof(ax303, axiom,
pred_attacker(constr_CONST_1)).
fof(ax304, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax305, axiom,
![VAR_V_150X30, VAR_V_151, VAR_V_152, VAR_V_153] : ((pred_attacker(VAR_V_150X30) & pred_attacker(VAR_V_151) & pred_attacker(VAR_V_152) & pred_attacker(VAR_V_153)) => pred_attacker(tuple_4(VAR_V_150X30, VAR_V_151, VAR_V_152, VAR_V_153)))).
fof(ax306, axiom,
![VAR_V_174, VAR_V_175, VAR_V_176, VAR_V_177] : (pred_attacker(tuple_4(VAR_V_174, VAR_V_175, VAR_V_176, VAR_V_177)) => pred_attacker(VAR_V_174))).
fof(ax307, axiom,
![VAR_V_179, VAR_V_180X30, VAR_V_181, VAR_V_182] : (pred_attacker(tuple_4(VAR_V_179, VAR_V_180X30, VAR_V_181, VAR_V_182)) => pred_attacker(VAR_V_180X30))).
fof(ax308, axiom,
![VAR_V_184, VAR_V_185, VAR_V_186, VAR_V_187] : (pred_attacker(tuple_4(VAR_V_184, VAR_V_185, VAR_V_186, VAR_V_187)) => pred_attacker(VAR_V_186))).
fof(ax309, axiom,
![VAR_V_189, VAR_V_190X30, VAR_V_191, VAR_V_192] : (pred_attacker(tuple_4(VAR_V_189, VAR_V_190X30, VAR_V_191, VAR_V_192)) => pred_attacker(VAR_V_192))).
fof(ax310, axiom,
![VAR_V_197, VAR_V_198, VAR_V_199] : ((pred_attacker(VAR_V_197) & pred_attacker(VAR_V_198) & pred_attacker(VAR_V_199)) => pred_attacker(tuple_3(VAR_V_197, VAR_V_198, VAR_V_199)))).
fof(ax311, axiom,
![VAR_V_212, VAR_V_213, VAR_V_214] : (pred_attacker(tuple_3(VAR_V_212, VAR_V_213, VAR_V_214)) => pred_attacker(VAR_V_212))).
fof(ax312, axiom,
![VAR_V_216, VAR_V_217, VAR_V_218] : (pred_attacker(tuple_3(VAR_V_216, VAR_V_217, VAR_V_218)) => pred_attacker(VAR_V_217))).
fof(ax313, axiom,
![VAR_V_220X30, VAR_V_221, VAR_V_222] : (pred_attacker(tuple_3(VAR_V_220X30, VAR_V_221, VAR_V_222)) => pred_attacker(VAR_V_222))).
fof(ax314, axiom,
![VAR_V_226, VAR_V_227] : ((pred_attacker(VAR_V_226) & pred_attacker(VAR_V_227)) => pred_attacker(tuple_2(VAR_V_226, VAR_V_227)))).
fof(ax315, axiom,
![VAR_V_234, VAR_V_235] : (pred_attacker(tuple_2(VAR_V_234, VAR_V_235)) => pred_attacker(VAR_V_234))).
fof(ax316, axiom,
![VAR_V_237, VAR_V_238] : (pred_attacker(tuple_2(VAR_V_237, VAR_V_238)) => pred_attacker(VAR_V_238))).
fof(ax317, axiom,
![VAR_V_240X30, VAR_V_241] : ((pred_mess(VAR_V_241, VAR_V_240X30) & pred_attacker(VAR_V_241)) => pred_attacker(VAR_V_240X30))).
fof(ax318, axiom,
![VAR_V_242, VAR_V_243] : ((pred_attacker(VAR_V_243) & pred_attacker(VAR_V_242)) => pred_mess(VAR_V_243, VAR_V_242))).
fof(ax319, axiom,
pred_attacker(name_c)).
fof(ax320, axiom,
pred_attacker(name_I)).
fof(ax321, axiom,
pred_attacker(name_B)).
fof(ax322, axiom,
pred_attacker(name_A)).
fof(ax323, axiom,
![VAR_V_245] : (pred_equal(VAR_V_245, VAR_V_245))).
fof(ax324, axiom,
![VAR_V_246] : (pred_attacker(name_new0x2Dname(VAR_V_246)))).
fof(ax325, axiom,
pred_table(tuple_keys(name_A, constr_pkey(name_skA)))).
fof(ax326, axiom,
pred_table(tuple_keys(name_B, constr_pkey(name_skB)))).
fof(ax327, axiom,
pred_attacker(tuple_2(constr_pkey(name_skA), constr_STEP_1))).
fof(ax328, axiom,
pred_attacker(tuple_2(constr_pkey(name_skB), constr_STEP_2))).
fof(ax329, axiom,
pred_attacker(tuple_2(constr_pkey(name_skS), constr_STEP_3))).
fof(ax330, axiom,
pred_attacker(tuple_2(tuple_2(name_A, name_I), constr_client_A_STEP_1))).
fof(ax331, axiom,
![VAR_0X40SID_394, VAR_SIGN_I_PKI_393] : ((pred_eq(constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_I_PKI_393, constr_pkey(name_skS))), name_I) & pred_attacker(VAR_SIGN_I_PKI_393)) => pred_attacker(tuple_2(constr_ecb_enc_2(name_Na(VAR_0X40SID_394), name_A, constr_tuple_2_get_1(constr_checksign(VAR_SIGN_I_PKI_393, constr_pkey(name_skS)))), constr_client_A_STEP_2)))).
fof(ax332, axiom,
![VAR_0X40SID_465, VAR_ECB_ENC_NA_NI_I_464, VAR_SIGN_I_PKI_466] : ((pred_eq(constr_tuple_3_get_2(constr_ecb_dec_3(VAR_ECB_ENC_NA_NI_I_464, name_skA)), name_I) & pred_eq(constr_tuple_3_get_0x30(constr_ecb_dec_3(VAR_ECB_ENC_NA_NI_I_464, name_skA)), name_Na(VAR_0X40SID_465)) & pred_attacker(VAR_ECB_ENC_NA_NI_I_464) & pred_eq(constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_I_PKI_466, constr_pkey(name_skS))), name_I) & pred_attacker(VAR_SIGN_I_PKI_466)) => pred_attacker(tuple_2(constr_ecb_enc_1(constr_tuple_3_get_1(constr_ecb_dec_3(VAR_ECB_ENC_NA_NI_I_464, name_skA)), constr_tuple_2_get_1(constr_checksign(VAR_SIGN_I_PKI_466, constr_pkey(name_skS)))), constr_client_A_STEP_3)))).
fof(ax333, axiom,
pred_attacker(tuple_2(tuple_2(name_B, name_A), constr_client_B_STEP_1))).
fof(ax334, axiom,
![VAR_0X40SID_591, VAR_ECB_ENC_NA_A_589, VAR_SIGN_A_PKA_590X30] : ((pred_eq(constr_tuple_2_get_1(constr_ecb_dec_2(VAR_ECB_ENC_NA_A_589, name_skB)), name_A) & pred_attacker(VAR_ECB_ENC_NA_A_589) & pred_eq(constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_A_PKA_590X30, constr_pkey(name_skS))), name_A) & pred_attacker(VAR_SIGN_A_PKA_590X30)) => pred_attacker(tuple_2(constr_ecb_enc_3(constr_tuple_2_get_0x30(constr_ecb_dec_2(VAR_ECB_ENC_NA_A_589, name_skB)), name_Nb(VAR_0X40SID_591), name_B, constr_tuple_2_get_1(constr_checksign(VAR_SIGN_A_PKA_590X30, constr_pkey(name_skS)))), constr_client_B_STEP_2)))).
fof(ax335, axiom,
![VAR_0X40SID_628, VAR_ECB_ENC_NA_A_629, VAR_ECB_ENC_NB_627, VAR_SIGN_A_PKA_630X30] : ((pred_eq(constr_ecb_dec_1(VAR_ECB_ENC_NB_627, name_skB), name_Nb(VAR_0X40SID_628)) & pred_attacker(VAR_ECB_ENC_NB_627) & pred_eq(constr_tuple_2_get_1(constr_ecb_dec_2(VAR_ECB_ENC_NA_A_629, name_skB)), name_A) & pred_attacker(VAR_ECB_ENC_NA_A_629) & pred_eq(constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_A_PKA_630X30, constr_pkey(name_skS))), name_A) & pred_attacker(VAR_SIGN_A_PKA_630X30)) => pred_attacker(tuple_2(name_objective, constr_client_B_STEP_3)))).
fof(ax336, axiom,
![VAR_DST_675, VAR_PKDST_676, VAR_SRC_677] : ((pred_table(tuple_keys(VAR_DST_675, VAR_PKDST_676)) & pred_attacker(tuple_2(VAR_SRC_677, VAR_DST_675))) => pred_attacker(tuple_2(constr_sign(tuple_2(VAR_DST_675, VAR_PKDST_676), name_skS), constr_key_retrieval_server_STEP_1)))).
fof(ax337, axiom,
![VAR_HOST_731, VAR_PK_732] : ((VAR_HOST_731 != name_B & VAR_HOST_731 != name_A & pred_attacker(tuple_2(VAR_HOST_731, VAR_PK_732))) => pred_table(tuple_keys(VAR_HOST_731, VAR_PK_732)))).
fof(co0, conjecture,
pred_attacker(tuple_2(name_Nb(VAR_V_740X30), name_objective))).
