%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_STEP_1).
fof(ax5, axiom,
constr_CONST_0x30 != constr_STEP_2).
fof(ax6, axiom,
constr_CONST_0x30 != constr_STEP_3).
fof(ax7, axiom,
constr_CONST_0x30 != constr_client_A_STEP_1).
fof(ax8, axiom,
constr_CONST_0x30 != constr_client_A_STEP_2).
fof(ax9, axiom,
constr_CONST_0x30 != constr_client_A_STEP_3).
fof(ax10, axiom,
constr_CONST_0x30 != constr_client_B_STEP_1).
fof(ax11, axiom,
constr_CONST_0x30 != constr_client_B_STEP_2).
fof(ax12, axiom,
constr_CONST_0x30 != constr_key_retrieval_server_STEP_1).
fof(ax13, axiom,
constr_CONST_0x30 != name_A).
fof(ax14, axiom,
constr_CONST_0x30 != name_B).
fof(ax15, axiom,
constr_CONST_0x30 != name_I).
fof(ax16, axiom,
constr_CONST_0x30 != name_c).
fof(ax17, axiom,
constr_CONST_0x30 != name_skA).
fof(ax18, axiom,
constr_CONST_0x30 != name_skB).
fof(ax19, axiom,
constr_CONST_0x30 != name_skS).
fof(ax20, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax21, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax22, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax23, axiom,
constr_CONST_1 != constr_STEP_1).
fof(ax24, axiom,
constr_CONST_1 != constr_STEP_2).
fof(ax25, axiom,
constr_CONST_1 != constr_STEP_3).
fof(ax26, axiom,
constr_CONST_1 != constr_client_A_STEP_1).
fof(ax27, axiom,
constr_CONST_1 != constr_client_A_STEP_2).
fof(ax28, axiom,
constr_CONST_1 != constr_client_A_STEP_3).
fof(ax29, axiom,
constr_CONST_1 != constr_client_B_STEP_1).
fof(ax30, axiom,
constr_CONST_1 != constr_client_B_STEP_2).
fof(ax31, axiom,
constr_CONST_1 != constr_key_retrieval_server_STEP_1).
fof(ax32, axiom,
constr_CONST_1 != name_A).
fof(ax33, axiom,
constr_CONST_1 != name_B).
fof(ax34, axiom,
constr_CONST_1 != name_I).
fof(ax35, axiom,
constr_CONST_1 != name_c).
fof(ax36, axiom,
constr_CONST_1 != name_skA).
fof(ax37, axiom,
constr_CONST_1 != name_skB).
fof(ax38, axiom,
constr_CONST_1 != name_skS).
fof(ax39, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax40, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax41, axiom,
constr_CONST_2 != constr_STEP_1).
fof(ax42, axiom,
constr_CONST_2 != constr_STEP_2).
fof(ax43, axiom,
constr_CONST_2 != constr_STEP_3).
fof(ax44, axiom,
constr_CONST_2 != constr_client_A_STEP_1).
fof(ax45, axiom,
constr_CONST_2 != constr_client_A_STEP_2).
fof(ax46, axiom,
constr_CONST_2 != constr_client_A_STEP_3).
fof(ax47, axiom,
constr_CONST_2 != constr_client_B_STEP_1).
fof(ax48, axiom,
constr_CONST_2 != constr_client_B_STEP_2).
fof(ax49, axiom,
constr_CONST_2 != constr_key_retrieval_server_STEP_1).
fof(ax50, axiom,
constr_CONST_2 != name_A).
fof(ax51, axiom,
constr_CONST_2 != name_B).
fof(ax52, axiom,
constr_CONST_2 != name_I).
fof(ax53, axiom,
constr_CONST_2 != name_c).
fof(ax54, axiom,
constr_CONST_2 != name_skA).
fof(ax55, axiom,
constr_CONST_2 != name_skB).
fof(ax56, axiom,
constr_CONST_2 != name_skS).
fof(ax57, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax58, axiom,
constr_CONST_3 != constr_STEP_1).
fof(ax59, axiom,
constr_CONST_3 != constr_STEP_2).
fof(ax60, axiom,
constr_CONST_3 != constr_STEP_3).
fof(ax61, axiom,
constr_CONST_3 != constr_client_A_STEP_1).
fof(ax62, axiom,
constr_CONST_3 != constr_client_A_STEP_2).
fof(ax63, axiom,
constr_CONST_3 != constr_client_A_STEP_3).
fof(ax64, axiom,
constr_CONST_3 != constr_client_B_STEP_1).
fof(ax65, axiom,
constr_CONST_3 != constr_client_B_STEP_2).
fof(ax66, axiom,
constr_CONST_3 != constr_key_retrieval_server_STEP_1).
fof(ax67, axiom,
constr_CONST_3 != name_A).
fof(ax68, axiom,
constr_CONST_3 != name_B).
fof(ax69, axiom,
constr_CONST_3 != name_I).
fof(ax70, axiom,
constr_CONST_3 != name_c).
fof(ax71, axiom,
constr_CONST_3 != name_skA).
fof(ax72, axiom,
constr_CONST_3 != name_skB).
fof(ax73, axiom,
constr_CONST_3 != name_skS).
fof(ax74, axiom,
constr_CONST_4 != constr_STEP_1).
fof(ax75, axiom,
constr_CONST_4 != constr_STEP_2).
fof(ax76, axiom,
constr_CONST_4 != constr_STEP_3).
fof(ax77, axiom,
constr_CONST_4 != constr_client_A_STEP_1).
fof(ax78, axiom,
constr_CONST_4 != constr_client_A_STEP_2).
fof(ax79, axiom,
constr_CONST_4 != constr_client_A_STEP_3).
fof(ax80, axiom,
constr_CONST_4 != constr_client_B_STEP_1).
fof(ax81, axiom,
constr_CONST_4 != constr_client_B_STEP_2).
fof(ax82, axiom,
constr_CONST_4 != constr_key_retrieval_server_STEP_1).
fof(ax83, axiom,
constr_CONST_4 != name_A).
fof(ax84, axiom,
constr_CONST_4 != name_B).
fof(ax85, axiom,
constr_CONST_4 != name_I).
fof(ax86, axiom,
constr_CONST_4 != name_c).
fof(ax87, axiom,
constr_CONST_4 != name_skA).
fof(ax88, axiom,
constr_CONST_4 != name_skB).
fof(ax89, axiom,
constr_CONST_4 != name_skS).
fof(ax90, axiom,
constr_STEP_1 != constr_STEP_2).
fof(ax91, axiom,
constr_STEP_1 != constr_STEP_3).
fof(ax92, axiom,
constr_STEP_1 != constr_client_A_STEP_1).
fof(ax93, axiom,
constr_STEP_1 != constr_client_A_STEP_2).
fof(ax94, axiom,
constr_STEP_1 != constr_client_A_STEP_3).
fof(ax95, axiom,
constr_STEP_1 != constr_client_B_STEP_1).
fof(ax96, axiom,
constr_STEP_1 != constr_client_B_STEP_2).
fof(ax97, axiom,
constr_STEP_1 != constr_key_retrieval_server_STEP_1).
fof(ax98, axiom,
constr_STEP_1 != name_A).
fof(ax99, axiom,
constr_STEP_1 != name_B).
fof(ax100, axiom,
constr_STEP_1 != name_I).
fof(ax101, axiom,
constr_STEP_1 != name_c).
fof(ax102, axiom,
constr_STEP_1 != name_skA).
fof(ax103, axiom,
constr_STEP_1 != name_skB).
fof(ax104, axiom,
constr_STEP_1 != name_skS).
fof(ax105, axiom,
constr_STEP_2 != constr_STEP_3).
fof(ax106, axiom,
constr_STEP_2 != constr_client_A_STEP_1).
fof(ax107, axiom,
constr_STEP_2 != constr_client_A_STEP_2).
fof(ax108, axiom,
constr_STEP_2 != constr_client_A_STEP_3).
fof(ax109, axiom,
constr_STEP_2 != constr_client_B_STEP_1).
fof(ax110, axiom,
constr_STEP_2 != constr_client_B_STEP_2).
fof(ax111, axiom,
constr_STEP_2 != constr_key_retrieval_server_STEP_1).
fof(ax112, axiom,
constr_STEP_2 != name_A).
fof(ax113, axiom,
constr_STEP_2 != name_B).
fof(ax114, axiom,
constr_STEP_2 != name_I).
fof(ax115, axiom,
constr_STEP_2 != name_c).
fof(ax116, axiom,
constr_STEP_2 != name_skA).
fof(ax117, axiom,
constr_STEP_2 != name_skB).
fof(ax118, axiom,
constr_STEP_2 != name_skS).
fof(ax119, axiom,
constr_STEP_3 != constr_client_A_STEP_1).
fof(ax120, axiom,
constr_STEP_3 != constr_client_A_STEP_2).
fof(ax121, axiom,
constr_STEP_3 != constr_client_A_STEP_3).
fof(ax122, axiom,
constr_STEP_3 != constr_client_B_STEP_1).
fof(ax123, axiom,
constr_STEP_3 != constr_client_B_STEP_2).
fof(ax124, axiom,
constr_STEP_3 != constr_key_retrieval_server_STEP_1).
fof(ax125, axiom,
constr_STEP_3 != name_A).
fof(ax126, axiom,
constr_STEP_3 != name_B).
fof(ax127, axiom,
constr_STEP_3 != name_I).
fof(ax128, axiom,
constr_STEP_3 != name_c).
fof(ax129, axiom,
constr_STEP_3 != name_skA).
fof(ax130, axiom,
constr_STEP_3 != name_skB).
fof(ax131, axiom,
constr_STEP_3 != name_skS).
fof(ax132, axiom,
constr_client_A_STEP_1 != constr_client_A_STEP_2).
fof(ax133, axiom,
constr_client_A_STEP_1 != constr_client_A_STEP_3).
fof(ax134, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_1).
fof(ax135, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_2).
fof(ax136, axiom,
constr_client_A_STEP_1 != constr_key_retrieval_server_STEP_1).
fof(ax137, axiom,
constr_client_A_STEP_1 != name_A).
fof(ax138, axiom,
constr_client_A_STEP_1 != name_B).
fof(ax139, axiom,
constr_client_A_STEP_1 != name_I).
fof(ax140, axiom,
constr_client_A_STEP_1 != name_c).
fof(ax141, axiom,
constr_client_A_STEP_1 != name_skA).
fof(ax142, axiom,
constr_client_A_STEP_1 != name_skB).
fof(ax143, axiom,
constr_client_A_STEP_1 != name_skS).
fof(ax144, axiom,
constr_client_A_STEP_2 != constr_client_A_STEP_3).
fof(ax145, axiom,
constr_client_A_STEP_2 != constr_client_B_STEP_1).
fof(ax146, axiom,
constr_client_A_STEP_2 != constr_client_B_STEP_2).
fof(ax147, axiom,
constr_client_A_STEP_2 != constr_key_retrieval_server_STEP_1).
fof(ax148, axiom,
constr_client_A_STEP_2 != name_A).
fof(ax149, axiom,
constr_client_A_STEP_2 != name_B).
fof(ax150, axiom,
constr_client_A_STEP_2 != name_I).
fof(ax151, axiom,
constr_client_A_STEP_2 != name_c).
fof(ax152, axiom,
constr_client_A_STEP_2 != name_skA).
fof(ax153, axiom,
constr_client_A_STEP_2 != name_skB).
fof(ax154, axiom,
constr_client_A_STEP_2 != name_skS).
fof(ax155, axiom,
constr_client_A_STEP_3 != constr_client_B_STEP_1).
fof(ax156, axiom,
constr_client_A_STEP_3 != constr_client_B_STEP_2).
fof(ax157, axiom,
constr_client_A_STEP_3 != constr_key_retrieval_server_STEP_1).
fof(ax158, axiom,
constr_client_A_STEP_3 != name_A).
fof(ax159, axiom,
constr_client_A_STEP_3 != name_B).
fof(ax160, axiom,
constr_client_A_STEP_3 != name_I).
fof(ax161, axiom,
constr_client_A_STEP_3 != name_c).
fof(ax162, axiom,
constr_client_A_STEP_3 != name_skA).
fof(ax163, axiom,
constr_client_A_STEP_3 != name_skB).
fof(ax164, axiom,
constr_client_A_STEP_3 != name_skS).
fof(ax165, axiom,
constr_client_B_STEP_1 != constr_client_B_STEP_2).
fof(ax166, axiom,
constr_client_B_STEP_1 != constr_key_retrieval_server_STEP_1).
fof(ax167, axiom,
constr_client_B_STEP_1 != name_A).
fof(ax168, axiom,
constr_client_B_STEP_1 != name_B).
fof(ax169, axiom,
constr_client_B_STEP_1 != name_I).
fof(ax170, axiom,
constr_client_B_STEP_1 != name_c).
fof(ax171, axiom,
constr_client_B_STEP_1 != name_skA).
fof(ax172, axiom,
constr_client_B_STEP_1 != name_skB).
fof(ax173, axiom,
constr_client_B_STEP_1 != name_skS).
fof(ax174, axiom,
constr_client_B_STEP_2 != constr_key_retrieval_server_STEP_1).
fof(ax175, axiom,
constr_client_B_STEP_2 != name_A).
fof(ax176, axiom,
constr_client_B_STEP_2 != name_B).
fof(ax177, axiom,
constr_client_B_STEP_2 != name_I).
fof(ax178, axiom,
constr_client_B_STEP_2 != name_c).
fof(ax179, axiom,
constr_client_B_STEP_2 != name_skA).
fof(ax180, axiom,
constr_client_B_STEP_2 != name_skB).
fof(ax181, axiom,
constr_client_B_STEP_2 != name_skS).
fof(ax182, axiom,
constr_key_retrieval_server_STEP_1 != name_A).
fof(ax183, axiom,
constr_key_retrieval_server_STEP_1 != name_B).
fof(ax184, axiom,
constr_key_retrieval_server_STEP_1 != name_I).
fof(ax185, axiom,
constr_key_retrieval_server_STEP_1 != name_c).
fof(ax186, axiom,
constr_key_retrieval_server_STEP_1 != name_skA).
fof(ax187, axiom,
constr_key_retrieval_server_STEP_1 != name_skB).
fof(ax188, axiom,
constr_key_retrieval_server_STEP_1 != name_skS).
fof(ax189, axiom,
name_A != name_B).
fof(ax190, axiom,
name_A != name_I).
fof(ax191, axiom,
name_A != name_c).
fof(ax192, axiom,
name_A != name_skA).
fof(ax193, axiom,
name_A != name_skB).
fof(ax194, axiom,
name_A != name_skS).
fof(ax195, axiom,
name_B != name_I).
fof(ax196, axiom,
name_B != name_c).
fof(ax197, axiom,
name_B != name_skA).
fof(ax198, axiom,
name_B != name_skB).
fof(ax199, axiom,
name_B != name_skS).
fof(ax200, axiom,
name_I != name_c).
fof(ax201, axiom,
name_I != name_skA).
fof(ax202, axiom,
name_I != name_skB).
fof(ax203, axiom,
name_I != name_skS).
fof(ax204, axiom,
name_c != name_skA).
fof(ax205, axiom,
name_c != name_skB).
fof(ax206, axiom,
name_c != name_skS).
fof(ax207, axiom,
name_skA != name_skB).
fof(ax208, axiom,
name_skA != name_skS).
fof(ax209, axiom,
name_skB != name_skS).
fof(ax210, axiom,
![VAR_K_22, VAR_M_21] : (constr_adec(constr_aenc(VAR_M_21, constr_pkey(VAR_K_22)), VAR_K_22) = VAR_M_21)).
fof(ax211, axiom,
![VAR_K_20X30, VAR_M_19] : (constr_dec(constr_enc(VAR_M_19, VAR_K_20X30), VAR_K_20X30) = VAR_M_19)).
fof(ax212, axiom,
![VAR_K_18, VAR_M_17] : (constr_getmess(constr_sign(VAR_M_17, VAR_K_18)) = VAR_M_17)).
fof(ax213, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_checksign(constr_sign(VAR_M_0X30, VAR_K_0X30), constr_pkey(VAR_K_0X30)) = VAR_M_0X30)).
fof(ax214, axiom,
![VAR_X0X30_14, VAR_X1_15, VAR_X2_16] : (constr_tuple_3_get_2(tuple_3(VAR_X0X30_14, VAR_X1_15, VAR_X2_16)) = VAR_X2_16)).
fof(ax215, axiom,
![VAR_X0X30_11, VAR_X1_12, VAR_X2_13] : (constr_tuple_3_get_1(tuple_3(VAR_X0X30_11, VAR_X1_12, VAR_X2_13)) = VAR_X1_12)).
fof(ax216, axiom,
![VAR_X0X30_9, VAR_X1_10X30, VAR_X2_0X30] : (constr_tuple_3_get_0x30(tuple_3(VAR_X0X30_9, VAR_X1_10X30, VAR_X2_0X30)) = VAR_X0X30_9)).
fof(ax217, axiom,
![VAR_X0X30_7, VAR_X1_8] : (constr_tuple_2_get_1(tuple_2(VAR_X0X30_7, VAR_X1_8)) = VAR_X1_8)).
fof(ax218, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30] : (constr_tuple_2_get_0x30(tuple_2(VAR_X0X30_0X30, VAR_X1_0X30)) = VAR_X0X30_0X30)).
fof(ax219, axiom,
![VAR_X_40X30] : (pred_eq(VAR_X_40X30, VAR_X_40X30))).
fof(ax220, axiom,
![VAR_V_46] : (pred_attacker(VAR_V_46) => pred_attacker(constr_tuple_3_get_2(VAR_V_46)))).
fof(ax221, axiom,
![VAR_V_48] : (pred_attacker(VAR_V_48) => pred_attacker(constr_tuple_3_get_1(VAR_V_48)))).
fof(ax222, axiom,
![VAR_V_50X30] : (pred_attacker(VAR_V_50X30) => pred_attacker(constr_tuple_3_get_0x30(VAR_V_50X30)))).
fof(ax223, axiom,
![VAR_V_52] : (pred_attacker(VAR_V_52) => pred_attacker(constr_tuple_2_get_1(VAR_V_52)))).
fof(ax224, axiom,
![VAR_V_54] : (pred_attacker(VAR_V_54) => pred_attacker(constr_tuple_2_get_0x30(VAR_V_54)))).
fof(ax225, axiom,
pred_attacker(tuple_true)).
fof(ax226, axiom,
![VAR_V_57, VAR_V_58] : ((pred_attacker(VAR_V_57) & pred_attacker(VAR_V_58)) => pred_attacker(constr_sign(VAR_V_57, VAR_V_58)))).
fof(ax227, axiom,
![VAR_V_60X30] : (pred_attacker(VAR_V_60X30) => pred_attacker(constr_pkey(VAR_V_60X30)))).
fof(ax228, axiom,
pred_attacker(constr_key_retrieval_server_STEP_1)).
fof(ax229, axiom,
![VAR_V_63] : (pred_attacker(VAR_V_63) => pred_attacker(constr_getmess(VAR_V_63)))).
fof(ax230, axiom,
pred_attacker(tuple_false)).
fof(ax231, axiom,
![VAR_V_66, VAR_V_67] : ((pred_attacker(VAR_V_66) & pred_attacker(VAR_V_67)) => pred_attacker(constr_enc(VAR_V_66, VAR_V_67)))).
fof(ax232, axiom,
![VAR_V_70X30, VAR_V_71] : ((pred_attacker(VAR_V_70X30) & pred_attacker(VAR_V_71)) => pred_attacker(constr_dec(VAR_V_70X30, VAR_V_71)))).
fof(ax233, axiom,
pred_attacker(constr_client_B_STEP_2)).
fof(ax234, axiom,
pred_attacker(constr_client_B_STEP_1)).
fof(ax235, axiom,
pred_attacker(constr_client_A_STEP_3)).
fof(ax236, axiom,
pred_attacker(constr_client_A_STEP_2)).
fof(ax237, axiom,
pred_attacker(constr_client_A_STEP_1)).
fof(ax238, axiom,
![VAR_V_74, VAR_V_75] : ((pred_attacker(VAR_V_74) & pred_attacker(VAR_V_75)) => pred_attacker(constr_checksign(VAR_V_74, VAR_V_75)))).
fof(ax239, axiom,
![VAR_V_78, VAR_V_79] : ((pred_attacker(VAR_V_78) & pred_attacker(VAR_V_79)) => pred_attacker(constr_aenc(VAR_V_78, VAR_V_79)))).
fof(ax240, axiom,
![VAR_V_82, VAR_V_83] : ((pred_attacker(VAR_V_82) & pred_attacker(VAR_V_83)) => pred_attacker(constr_adec(VAR_V_82, VAR_V_83)))).
fof(ax241, axiom,
pred_attacker(constr_STEP_3)).
fof(ax242, axiom,
pred_attacker(constr_STEP_2)).
fof(ax243, axiom,
pred_attacker(constr_STEP_1)).
fof(ax244, axiom,
pred_attacker(constr_CONST_4)).
fof(ax245, axiom,
pred_attacker(constr_CONST_3)).
fof(ax246, axiom,
pred_attacker(constr_CONST_2)).
fof(ax247, axiom,
pred_attacker(constr_CONST_1)).
fof(ax248, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax249, axiom,
![VAR_V_91, VAR_V_92, VAR_V_93] : ((pred_attacker(VAR_V_91) & pred_attacker(VAR_V_92) & pred_attacker(VAR_V_93)) => pred_attacker(tuple_3(VAR_V_91, VAR_V_92, VAR_V_93)))).
fof(ax250, axiom,
![VAR_V_10X306, VAR_V_10X307, VAR_V_10X308] : (pred_attacker(tuple_3(VAR_V_10X306, VAR_V_10X307, VAR_V_10X308)) => pred_attacker(VAR_V_10X306))).
fof(ax251, axiom,
![VAR_V_110X30, VAR_V_111, VAR_V_112] : (pred_attacker(tuple_3(VAR_V_110X30, VAR_V_111, VAR_V_112)) => pred_attacker(VAR_V_111))).
fof(ax252, axiom,
![VAR_V_114, VAR_V_115, VAR_V_116] : (pred_attacker(tuple_3(VAR_V_114, VAR_V_115, VAR_V_116)) => pred_attacker(VAR_V_116))).
fof(ax253, axiom,
![VAR_V_120X30, VAR_V_121] : ((pred_attacker(VAR_V_120X30) & pred_attacker(VAR_V_121)) => pred_attacker(tuple_2(VAR_V_120X30, VAR_V_121)))).
fof(ax254, axiom,
![VAR_V_128, VAR_V_129] : (pred_attacker(tuple_2(VAR_V_128, VAR_V_129)) => pred_attacker(VAR_V_128))).
fof(ax255, axiom,
![VAR_V_131, VAR_V_132] : (pred_attacker(tuple_2(VAR_V_131, VAR_V_132)) => pred_attacker(VAR_V_132))).
fof(ax256, axiom,
![VAR_V_134, VAR_V_135] : ((pred_mess(VAR_V_135, VAR_V_134) & pred_attacker(VAR_V_135)) => pred_attacker(VAR_V_134))).
fof(ax257, axiom,
![VAR_V_136, VAR_V_137] : ((pred_attacker(VAR_V_137) & pred_attacker(VAR_V_136)) => pred_mess(VAR_V_137, VAR_V_136))).
fof(ax258, axiom,
pred_attacker(name_c)).
fof(ax259, axiom,
pred_attacker(name_I)).
fof(ax260, axiom,
pred_attacker(name_B)).
fof(ax261, axiom,
pred_attacker(name_A)).
fof(ax262, axiom,
![VAR_V_139] : (pred_equal(VAR_V_139, VAR_V_139))).
fof(ax263, axiom,
![VAR_V_140X30] : (pred_attacker(name_new0x2Dname(VAR_V_140X30)))).
fof(ax264, axiom,
pred_table(tuple_keys(name_A, constr_pkey(name_skA)))).
fof(ax265, axiom,
pred_table(tuple_keys(name_B, constr_pkey(name_skB)))).
fof(ax266, axiom,
pred_attacker(tuple_2(constr_pkey(name_skA), constr_STEP_1))).
fof(ax267, axiom,
pred_attacker(tuple_2(constr_pkey(name_skB), constr_STEP_2))).
fof(ax268, axiom,
pred_attacker(tuple_2(constr_pkey(name_skS), constr_STEP_3))).
fof(ax269, axiom,
pred_attacker(tuple_2(tuple_2(name_A, name_I), constr_client_A_STEP_1))).
fof(ax270, axiom,
![VAR_0X40SID_292, VAR_SIGN_I_PKI_291] : ((pred_eq(constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_I_PKI_291, constr_pkey(name_skS))), name_I) & pred_attacker(VAR_SIGN_I_PKI_291)) => pred_attacker(tuple_2(constr_aenc(tuple_2(name_Na(VAR_0X40SID_292), name_A), constr_tuple_2_get_1(constr_checksign(VAR_SIGN_I_PKI_291, constr_pkey(name_skS)))), constr_client_A_STEP_2)))).
fof(ax271, axiom,
![VAR_0X40SID_361, VAR_AENC_NA_NI_I_360X30, VAR_SIGN_I_PKI_362] : ((pred_eq(constr_tuple_3_get_2(constr_adec(VAR_AENC_NA_NI_I_360X30, name_skA)), name_I) & pred_eq(constr_tuple_3_get_0x30(constr_adec(VAR_AENC_NA_NI_I_360X30, name_skA)), name_Na(VAR_0X40SID_361)) & pred_attacker(VAR_AENC_NA_NI_I_360X30) & pred_eq(constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_I_PKI_362, constr_pkey(name_skS))), name_I) & pred_attacker(VAR_SIGN_I_PKI_362)) => pred_attacker(tuple_2(constr_aenc(constr_tuple_3_get_1(constr_adec(VAR_AENC_NA_NI_I_360X30, name_skA)), constr_tuple_2_get_1(constr_checksign(VAR_SIGN_I_PKI_362, constr_pkey(name_skS)))), constr_client_A_STEP_3)))).
fof(ax272, axiom,
pred_attacker(tuple_2(tuple_2(name_B, name_A), constr_client_B_STEP_1))).
fof(ax273, axiom,
![VAR_0X40SID_491, VAR_AENC_NA_A_489, VAR_SIGN_A_PKA_490X30] : ((pred_eq(constr_tuple_2_get_1(constr_adec(VAR_AENC_NA_A_489, name_skB)), name_A) & pred_attacker(VAR_AENC_NA_A_489) & pred_eq(constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_A_PKA_490X30, constr_pkey(name_skS))), name_A) & pred_attacker(VAR_SIGN_A_PKA_490X30)) => pred_attacker(tuple_2(constr_aenc(tuple_3(constr_tuple_2_get_0x30(constr_adec(VAR_AENC_NA_A_489, name_skB)), name_Nb(VAR_0X40SID_491), name_B), constr_tuple_2_get_1(constr_checksign(VAR_SIGN_A_PKA_490X30, constr_pkey(name_skS)))), constr_client_B_STEP_2)))).
fof(ax274, axiom,
![VAR_DST_556, VAR_PKDST_557, VAR_SRC_558] : ((pred_table(tuple_keys(VAR_DST_556, VAR_PKDST_557)) & pred_attacker(tuple_2(VAR_SRC_558, VAR_DST_556))) => pred_attacker(tuple_2(constr_sign(tuple_2(VAR_DST_556, VAR_PKDST_557), name_skS), constr_key_retrieval_server_STEP_1)))).
fof(ax275, axiom,
![VAR_HOST_612, VAR_PK_613] : ((VAR_HOST_612 != name_B & VAR_HOST_612 != name_A & pred_attacker(tuple_2(VAR_HOST_612, VAR_PK_613))) => pred_table(tuple_keys(VAR_HOST_612, VAR_PK_613)))).
fof(co0, conjecture,
pred_attacker(name_Nb(VAR_V_621))).
