%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_STEP_1).
fof(ax5, axiom,
constr_CONST_0x30 != constr_STEP_2).
fof(ax6, axiom,
constr_CONST_0x30 != constr_STEP_3).
fof(ax7, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax8, axiom,
constr_CONST_0x30 != constr_client_A_STEP_1).
fof(ax9, axiom,
constr_CONST_0x30 != constr_client_A_STEP_2).
fof(ax10, axiom,
constr_CONST_0x30 != constr_client_A_STEP_3).
fof(ax11, axiom,
constr_CONST_0x30 != constr_client_B_STEP_1).
fof(ax12, axiom,
constr_CONST_0x30 != constr_client_B_STEP_2).
fof(ax13, axiom,
constr_CONST_0x30 != constr_client_B_STEP_3).
fof(ax14, axiom,
constr_CONST_0x30 != constr_key_retrieval_server_STEP_1).
fof(ax15, axiom,
constr_CONST_0x30 != name_A).
fof(ax16, axiom,
constr_CONST_0x30 != name_B).
fof(ax17, axiom,
constr_CONST_0x30 != name_I).
fof(ax18, axiom,
constr_CONST_0x30 != name_c).
fof(ax19, axiom,
constr_CONST_0x30 != name_objective).
fof(ax20, axiom,
constr_CONST_0x30 != name_skA).
fof(ax21, axiom,
constr_CONST_0x30 != name_skB).
fof(ax22, axiom,
constr_CONST_0x30 != name_skS).
fof(ax23, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax24, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax25, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax26, axiom,
constr_CONST_1 != constr_STEP_1).
fof(ax27, axiom,
constr_CONST_1 != constr_STEP_2).
fof(ax28, axiom,
constr_CONST_1 != constr_STEP_3).
fof(ax29, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax30, axiom,
constr_CONST_1 != constr_client_A_STEP_1).
fof(ax31, axiom,
constr_CONST_1 != constr_client_A_STEP_2).
fof(ax32, axiom,
constr_CONST_1 != constr_client_A_STEP_3).
fof(ax33, axiom,
constr_CONST_1 != constr_client_B_STEP_1).
fof(ax34, axiom,
constr_CONST_1 != constr_client_B_STEP_2).
fof(ax35, axiom,
constr_CONST_1 != constr_client_B_STEP_3).
fof(ax36, axiom,
constr_CONST_1 != constr_key_retrieval_server_STEP_1).
fof(ax37, axiom,
constr_CONST_1 != name_A).
fof(ax38, axiom,
constr_CONST_1 != name_B).
fof(ax39, axiom,
constr_CONST_1 != name_I).
fof(ax40, axiom,
constr_CONST_1 != name_c).
fof(ax41, axiom,
constr_CONST_1 != name_objective).
fof(ax42, axiom,
constr_CONST_1 != name_skA).
fof(ax43, axiom,
constr_CONST_1 != name_skB).
fof(ax44, axiom,
constr_CONST_1 != name_skS).
fof(ax45, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax46, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax47, axiom,
constr_CONST_2 != constr_STEP_1).
fof(ax48, axiom,
constr_CONST_2 != constr_STEP_2).
fof(ax49, axiom,
constr_CONST_2 != constr_STEP_3).
fof(ax50, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax51, axiom,
constr_CONST_2 != constr_client_A_STEP_1).
fof(ax52, axiom,
constr_CONST_2 != constr_client_A_STEP_2).
fof(ax53, axiom,
constr_CONST_2 != constr_client_A_STEP_3).
fof(ax54, axiom,
constr_CONST_2 != constr_client_B_STEP_1).
fof(ax55, axiom,
constr_CONST_2 != constr_client_B_STEP_2).
fof(ax56, axiom,
constr_CONST_2 != constr_client_B_STEP_3).
fof(ax57, axiom,
constr_CONST_2 != constr_key_retrieval_server_STEP_1).
fof(ax58, axiom,
constr_CONST_2 != name_A).
fof(ax59, axiom,
constr_CONST_2 != name_B).
fof(ax60, axiom,
constr_CONST_2 != name_I).
fof(ax61, axiom,
constr_CONST_2 != name_c).
fof(ax62, axiom,
constr_CONST_2 != name_objective).
fof(ax63, axiom,
constr_CONST_2 != name_skA).
fof(ax64, axiom,
constr_CONST_2 != name_skB).
fof(ax65, axiom,
constr_CONST_2 != name_skS).
fof(ax66, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax67, axiom,
constr_CONST_3 != constr_STEP_1).
fof(ax68, axiom,
constr_CONST_3 != constr_STEP_2).
fof(ax69, axiom,
constr_CONST_3 != constr_STEP_3).
fof(ax70, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax71, axiom,
constr_CONST_3 != constr_client_A_STEP_1).
fof(ax72, axiom,
constr_CONST_3 != constr_client_A_STEP_2).
fof(ax73, axiom,
constr_CONST_3 != constr_client_A_STEP_3).
fof(ax74, axiom,
constr_CONST_3 != constr_client_B_STEP_1).
fof(ax75, axiom,
constr_CONST_3 != constr_client_B_STEP_2).
fof(ax76, axiom,
constr_CONST_3 != constr_client_B_STEP_3).
fof(ax77, axiom,
constr_CONST_3 != constr_key_retrieval_server_STEP_1).
fof(ax78, axiom,
constr_CONST_3 != name_A).
fof(ax79, axiom,
constr_CONST_3 != name_B).
fof(ax80, axiom,
constr_CONST_3 != name_I).
fof(ax81, axiom,
constr_CONST_3 != name_c).
fof(ax82, axiom,
constr_CONST_3 != name_objective).
fof(ax83, axiom,
constr_CONST_3 != name_skA).
fof(ax84, axiom,
constr_CONST_3 != name_skB).
fof(ax85, axiom,
constr_CONST_3 != name_skS).
fof(ax86, axiom,
constr_CONST_4 != constr_STEP_1).
fof(ax87, axiom,
constr_CONST_4 != constr_STEP_2).
fof(ax88, axiom,
constr_CONST_4 != constr_STEP_3).
fof(ax89, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax90, axiom,
constr_CONST_4 != constr_client_A_STEP_1).
fof(ax91, axiom,
constr_CONST_4 != constr_client_A_STEP_2).
fof(ax92, axiom,
constr_CONST_4 != constr_client_A_STEP_3).
fof(ax93, axiom,
constr_CONST_4 != constr_client_B_STEP_1).
fof(ax94, axiom,
constr_CONST_4 != constr_client_B_STEP_2).
fof(ax95, axiom,
constr_CONST_4 != constr_client_B_STEP_3).
fof(ax96, axiom,
constr_CONST_4 != constr_key_retrieval_server_STEP_1).
fof(ax97, axiom,
constr_CONST_4 != name_A).
fof(ax98, axiom,
constr_CONST_4 != name_B).
fof(ax99, axiom,
constr_CONST_4 != name_I).
fof(ax100, axiom,
constr_CONST_4 != name_c).
fof(ax101, axiom,
constr_CONST_4 != name_objective).
fof(ax102, axiom,
constr_CONST_4 != name_skA).
fof(ax103, axiom,
constr_CONST_4 != name_skB).
fof(ax104, axiom,
constr_CONST_4 != name_skS).
fof(ax105, axiom,
constr_STEP_1 != constr_STEP_2).
fof(ax106, axiom,
constr_STEP_1 != constr_STEP_3).
fof(ax107, axiom,
constr_STEP_1 != constr_ZERO).
fof(ax108, axiom,
constr_STEP_1 != constr_client_A_STEP_1).
fof(ax109, axiom,
constr_STEP_1 != constr_client_A_STEP_2).
fof(ax110, axiom,
constr_STEP_1 != constr_client_A_STEP_3).
fof(ax111, axiom,
constr_STEP_1 != constr_client_B_STEP_1).
fof(ax112, axiom,
constr_STEP_1 != constr_client_B_STEP_2).
fof(ax113, axiom,
constr_STEP_1 != constr_client_B_STEP_3).
fof(ax114, axiom,
constr_STEP_1 != constr_key_retrieval_server_STEP_1).
fof(ax115, axiom,
constr_STEP_1 != name_A).
fof(ax116, axiom,
constr_STEP_1 != name_B).
fof(ax117, axiom,
constr_STEP_1 != name_I).
fof(ax118, axiom,
constr_STEP_1 != name_c).
fof(ax119, axiom,
constr_STEP_1 != name_objective).
fof(ax120, axiom,
constr_STEP_1 != name_skA).
fof(ax121, axiom,
constr_STEP_1 != name_skB).
fof(ax122, axiom,
constr_STEP_1 != name_skS).
fof(ax123, axiom,
constr_STEP_2 != constr_STEP_3).
fof(ax124, axiom,
constr_STEP_2 != constr_ZERO).
fof(ax125, axiom,
constr_STEP_2 != constr_client_A_STEP_1).
fof(ax126, axiom,
constr_STEP_2 != constr_client_A_STEP_2).
fof(ax127, axiom,
constr_STEP_2 != constr_client_A_STEP_3).
fof(ax128, axiom,
constr_STEP_2 != constr_client_B_STEP_1).
fof(ax129, axiom,
constr_STEP_2 != constr_client_B_STEP_2).
fof(ax130, axiom,
constr_STEP_2 != constr_client_B_STEP_3).
fof(ax131, axiom,
constr_STEP_2 != constr_key_retrieval_server_STEP_1).
fof(ax132, axiom,
constr_STEP_2 != name_A).
fof(ax133, axiom,
constr_STEP_2 != name_B).
fof(ax134, axiom,
constr_STEP_2 != name_I).
fof(ax135, axiom,
constr_STEP_2 != name_c).
fof(ax136, axiom,
constr_STEP_2 != name_objective).
fof(ax137, axiom,
constr_STEP_2 != name_skA).
fof(ax138, axiom,
constr_STEP_2 != name_skB).
fof(ax139, axiom,
constr_STEP_2 != name_skS).
fof(ax140, axiom,
constr_STEP_3 != constr_ZERO).
fof(ax141, axiom,
constr_STEP_3 != constr_client_A_STEP_1).
fof(ax142, axiom,
constr_STEP_3 != constr_client_A_STEP_2).
fof(ax143, axiom,
constr_STEP_3 != constr_client_A_STEP_3).
fof(ax144, axiom,
constr_STEP_3 != constr_client_B_STEP_1).
fof(ax145, axiom,
constr_STEP_3 != constr_client_B_STEP_2).
fof(ax146, axiom,
constr_STEP_3 != constr_client_B_STEP_3).
fof(ax147, axiom,
constr_STEP_3 != constr_key_retrieval_server_STEP_1).
fof(ax148, axiom,
constr_STEP_3 != name_A).
fof(ax149, axiom,
constr_STEP_3 != name_B).
fof(ax150, axiom,
constr_STEP_3 != name_I).
fof(ax151, axiom,
constr_STEP_3 != name_c).
fof(ax152, axiom,
constr_STEP_3 != name_objective).
fof(ax153, axiom,
constr_STEP_3 != name_skA).
fof(ax154, axiom,
constr_STEP_3 != name_skB).
fof(ax155, axiom,
constr_STEP_3 != name_skS).
fof(ax156, axiom,
constr_ZERO != constr_client_A_STEP_1).
fof(ax157, axiom,
constr_ZERO != constr_client_A_STEP_2).
fof(ax158, axiom,
constr_ZERO != constr_client_A_STEP_3).
fof(ax159, axiom,
constr_ZERO != constr_client_B_STEP_1).
fof(ax160, axiom,
constr_ZERO != constr_client_B_STEP_2).
fof(ax161, axiom,
constr_ZERO != constr_client_B_STEP_3).
fof(ax162, axiom,
constr_ZERO != constr_key_retrieval_server_STEP_1).
fof(ax163, axiom,
constr_ZERO != name_A).
fof(ax164, axiom,
constr_ZERO != name_B).
fof(ax165, axiom,
constr_ZERO != name_I).
fof(ax166, axiom,
constr_ZERO != name_c).
fof(ax167, axiom,
constr_ZERO != name_objective).
fof(ax168, axiom,
constr_ZERO != name_skA).
fof(ax169, axiom,
constr_ZERO != name_skB).
fof(ax170, axiom,
constr_ZERO != name_skS).
fof(ax171, axiom,
constr_client_A_STEP_1 != constr_client_A_STEP_2).
fof(ax172, axiom,
constr_client_A_STEP_1 != constr_client_A_STEP_3).
fof(ax173, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_1).
fof(ax174, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_2).
fof(ax175, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_3).
fof(ax176, axiom,
constr_client_A_STEP_1 != constr_key_retrieval_server_STEP_1).
fof(ax177, axiom,
constr_client_A_STEP_1 != name_A).
fof(ax178, axiom,
constr_client_A_STEP_1 != name_B).
fof(ax179, axiom,
constr_client_A_STEP_1 != name_I).
fof(ax180, axiom,
constr_client_A_STEP_1 != name_c).
fof(ax181, axiom,
constr_client_A_STEP_1 != name_objective).
fof(ax182, axiom,
constr_client_A_STEP_1 != name_skA).
fof(ax183, axiom,
constr_client_A_STEP_1 != name_skB).
fof(ax184, axiom,
constr_client_A_STEP_1 != name_skS).
fof(ax185, axiom,
constr_client_A_STEP_2 != constr_client_A_STEP_3).
fof(ax186, axiom,
constr_client_A_STEP_2 != constr_client_B_STEP_1).
fof(ax187, axiom,
constr_client_A_STEP_2 != constr_client_B_STEP_2).
fof(ax188, axiom,
constr_client_A_STEP_2 != constr_client_B_STEP_3).
fof(ax189, axiom,
constr_client_A_STEP_2 != constr_key_retrieval_server_STEP_1).
fof(ax190, axiom,
constr_client_A_STEP_2 != name_A).
fof(ax191, axiom,
constr_client_A_STEP_2 != name_B).
fof(ax192, axiom,
constr_client_A_STEP_2 != name_I).
fof(ax193, axiom,
constr_client_A_STEP_2 != name_c).
fof(ax194, axiom,
constr_client_A_STEP_2 != name_objective).
fof(ax195, axiom,
constr_client_A_STEP_2 != name_skA).
fof(ax196, axiom,
constr_client_A_STEP_2 != name_skB).
fof(ax197, axiom,
constr_client_A_STEP_2 != name_skS).
fof(ax198, axiom,
constr_client_A_STEP_3 != constr_client_B_STEP_1).
fof(ax199, axiom,
constr_client_A_STEP_3 != constr_client_B_STEP_2).
fof(ax200, axiom,
constr_client_A_STEP_3 != constr_client_B_STEP_3).
fof(ax201, axiom,
constr_client_A_STEP_3 != constr_key_retrieval_server_STEP_1).
fof(ax202, axiom,
constr_client_A_STEP_3 != name_A).
fof(ax203, axiom,
constr_client_A_STEP_3 != name_B).
fof(ax204, axiom,
constr_client_A_STEP_3 != name_I).
fof(ax205, axiom,
constr_client_A_STEP_3 != name_c).
fof(ax206, axiom,
constr_client_A_STEP_3 != name_objective).
fof(ax207, axiom,
constr_client_A_STEP_3 != name_skA).
fof(ax208, axiom,
constr_client_A_STEP_3 != name_skB).
fof(ax209, axiom,
constr_client_A_STEP_3 != name_skS).
fof(ax210, axiom,
constr_client_B_STEP_1 != constr_client_B_STEP_2).
fof(ax211, axiom,
constr_client_B_STEP_1 != constr_client_B_STEP_3).
fof(ax212, axiom,
constr_client_B_STEP_1 != constr_key_retrieval_server_STEP_1).
fof(ax213, axiom,
constr_client_B_STEP_1 != name_A).
fof(ax214, axiom,
constr_client_B_STEP_1 != name_B).
fof(ax215, axiom,
constr_client_B_STEP_1 != name_I).
fof(ax216, axiom,
constr_client_B_STEP_1 != name_c).
fof(ax217, axiom,
constr_client_B_STEP_1 != name_objective).
fof(ax218, axiom,
constr_client_B_STEP_1 != name_skA).
fof(ax219, axiom,
constr_client_B_STEP_1 != name_skB).
fof(ax220, axiom,
constr_client_B_STEP_1 != name_skS).
fof(ax221, axiom,
constr_client_B_STEP_2 != constr_client_B_STEP_3).
fof(ax222, axiom,
constr_client_B_STEP_2 != constr_key_retrieval_server_STEP_1).
fof(ax223, axiom,
constr_client_B_STEP_2 != name_A).
fof(ax224, axiom,
constr_client_B_STEP_2 != name_B).
fof(ax225, axiom,
constr_client_B_STEP_2 != name_I).
fof(ax226, axiom,
constr_client_B_STEP_2 != name_c).
fof(ax227, axiom,
constr_client_B_STEP_2 != name_objective).
fof(ax228, axiom,
constr_client_B_STEP_2 != name_skA).
fof(ax229, axiom,
constr_client_B_STEP_2 != name_skB).
fof(ax230, axiom,
constr_client_B_STEP_2 != name_skS).
fof(ax231, axiom,
constr_client_B_STEP_3 != constr_key_retrieval_server_STEP_1).
fof(ax232, axiom,
constr_client_B_STEP_3 != name_A).
fof(ax233, axiom,
constr_client_B_STEP_3 != name_B).
fof(ax234, axiom,
constr_client_B_STEP_3 != name_I).
fof(ax235, axiom,
constr_client_B_STEP_3 != name_c).
fof(ax236, axiom,
constr_client_B_STEP_3 != name_objective).
fof(ax237, axiom,
constr_client_B_STEP_3 != name_skA).
fof(ax238, axiom,
constr_client_B_STEP_3 != name_skB).
fof(ax239, axiom,
constr_client_B_STEP_3 != name_skS).
fof(ax240, axiom,
constr_key_retrieval_server_STEP_1 != name_A).
fof(ax241, axiom,
constr_key_retrieval_server_STEP_1 != name_B).
fof(ax242, axiom,
constr_key_retrieval_server_STEP_1 != name_I).
fof(ax243, axiom,
constr_key_retrieval_server_STEP_1 != name_c).
fof(ax244, axiom,
constr_key_retrieval_server_STEP_1 != name_objective).
fof(ax245, axiom,
constr_key_retrieval_server_STEP_1 != name_skA).
fof(ax246, axiom,
constr_key_retrieval_server_STEP_1 != name_skB).
fof(ax247, axiom,
constr_key_retrieval_server_STEP_1 != name_skS).
fof(ax248, axiom,
name_A != name_B).
fof(ax249, axiom,
name_A != name_I).
fof(ax250, axiom,
name_A != name_c).
fof(ax251, axiom,
name_A != name_objective).
fof(ax252, axiom,
name_A != name_skA).
fof(ax253, axiom,
name_A != name_skB).
fof(ax254, axiom,
name_A != name_skS).
fof(ax255, axiom,
name_B != name_I).
fof(ax256, axiom,
name_B != name_c).
fof(ax257, axiom,
name_B != name_objective).
fof(ax258, axiom,
name_B != name_skA).
fof(ax259, axiom,
name_B != name_skB).
fof(ax260, axiom,
name_B != name_skS).
fof(ax261, axiom,
name_I != name_c).
fof(ax262, axiom,
name_I != name_objective).
fof(ax263, axiom,
name_I != name_skA).
fof(ax264, axiom,
name_I != name_skB).
fof(ax265, axiom,
name_I != name_skS).
fof(ax266, axiom,
name_c != name_objective).
fof(ax267, axiom,
name_c != name_skA).
fof(ax268, axiom,
name_c != name_skB).
fof(ax269, axiom,
name_c != name_skS).
fof(ax270, axiom,
name_objective != name_skA).
fof(ax271, axiom,
name_objective != name_skB).
fof(ax272, axiom,
name_objective != name_skS).
fof(ax273, axiom,
name_skA != name_skB).
fof(ax274, axiom,
name_skA != name_skS).
fof(ax275, axiom,
name_skB != name_skS).
fof(ax276, axiom,
![VAR_K_19, VAR_M_18] : (constr_adec(constr_aenc(VAR_M_18, constr_pkey(VAR_K_19)), VAR_K_19) = VAR_M_18)).
fof(ax277, axiom,
![VAR_K_17, VAR_M_16] : (constr_dec(constr_enc(VAR_M_16, VAR_K_17), VAR_K_17) = VAR_M_16)).
fof(ax278, axiom,
![VAR_K_15, VAR_M_14] : (constr_getmess(constr_sign(VAR_M_14, VAR_K_15)) = VAR_M_14)).
fof(ax279, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_checksign(constr_sign(VAR_M_0X30, VAR_K_0X30), constr_pkey(VAR_K_0X30)) = VAR_M_0X30)).
fof(ax280, axiom,
![VAR_X_13] : (constr_xor(VAR_X_13, VAR_X_13) = constr_ZERO)).
fof(ax281, axiom,
![VAR_X_12] : (constr_xor(VAR_X_12, constr_ZERO) = VAR_X_12)).
fof(ax282, axiom,
![VAR_X_10X30, VAR_Y_11] : (constr_xor(VAR_X_10X30, VAR_Y_11) = constr_xor(VAR_Y_11, VAR_X_10X30))).
fof(ax283, axiom,
![VAR_X_9, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_9, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_9, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax284, axiom,
![VAR_X0X30_7, VAR_X1_8] : (constr_tuple_2_get_1(tuple_2(VAR_X0X30_7, VAR_X1_8)) = VAR_X1_8)).
fof(ax285, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30] : (constr_tuple_2_get_0x30(tuple_2(VAR_X0X30_0X30, VAR_X1_0X30)) = VAR_X0X30_0X30)).
fof(ax286, axiom,
![VAR_X_36] : (pred_eq(VAR_X_36, VAR_X_36))).
fof(ax287, axiom,
![VAR_V_43, VAR_V_44] : ((pred_attacker(VAR_V_43) & pred_attacker(VAR_V_44)) => pred_attacker(constr_xor(VAR_V_43, VAR_V_44)))).
fof(ax288, axiom,
![VAR_V_46] : (pred_attacker(VAR_V_46) => pred_attacker(constr_tuple_2_get_1(VAR_V_46)))).
fof(ax289, axiom,
![VAR_V_48] : (pred_attacker(VAR_V_48) => pred_attacker(constr_tuple_2_get_0x30(VAR_V_48)))).
fof(ax290, axiom,
pred_attacker(tuple_true)).
fof(ax291, axiom,
![VAR_V_51, VAR_V_52] : ((pred_attacker(VAR_V_51) & pred_attacker(VAR_V_52)) => pred_attacker(constr_sign(VAR_V_51, VAR_V_52)))).
fof(ax292, axiom,
![VAR_V_54] : (pred_attacker(VAR_V_54) => pred_attacker(constr_pkey(VAR_V_54)))).
fof(ax293, axiom,
pred_attacker(constr_key_retrieval_server_STEP_1)).
fof(ax294, axiom,
![VAR_V_57] : (pred_attacker(VAR_V_57) => pred_attacker(constr_getmess(VAR_V_57)))).
fof(ax295, axiom,
pred_attacker(tuple_false)).
fof(ax296, axiom,
![VAR_V_60X30, VAR_V_61] : ((pred_attacker(VAR_V_60X30) & pred_attacker(VAR_V_61)) => pred_attacker(constr_enc(VAR_V_60X30, VAR_V_61)))).
fof(ax297, axiom,
![VAR_V_64, VAR_V_65] : ((pred_attacker(VAR_V_64) & pred_attacker(VAR_V_65)) => pred_attacker(constr_dec(VAR_V_64, VAR_V_65)))).
fof(ax298, axiom,
pred_attacker(constr_client_B_STEP_3)).
fof(ax299, axiom,
pred_attacker(constr_client_B_STEP_2)).
fof(ax300, axiom,
pred_attacker(constr_client_B_STEP_1)).
fof(ax301, axiom,
pred_attacker(constr_client_A_STEP_3)).
fof(ax302, axiom,
pred_attacker(constr_client_A_STEP_2)).
fof(ax303, axiom,
pred_attacker(constr_client_A_STEP_1)).
fof(ax304, axiom,
![VAR_V_68, VAR_V_69] : ((pred_attacker(VAR_V_68) & pred_attacker(VAR_V_69)) => pred_attacker(constr_checksign(VAR_V_68, VAR_V_69)))).
fof(ax305, axiom,
![VAR_V_72, VAR_V_73] : ((pred_attacker(VAR_V_72) & pred_attacker(VAR_V_73)) => pred_attacker(constr_aenc(VAR_V_72, VAR_V_73)))).
fof(ax306, axiom,
![VAR_V_76, VAR_V_77] : ((pred_attacker(VAR_V_76) & pred_attacker(VAR_V_77)) => pred_attacker(constr_adec(VAR_V_76, VAR_V_77)))).
fof(ax307, axiom,
pred_attacker(constr_ZERO)).
fof(ax308, axiom,
pred_attacker(constr_STEP_3)).
fof(ax309, axiom,
pred_attacker(constr_STEP_2)).
fof(ax310, axiom,
pred_attacker(constr_STEP_1)).
fof(ax311, axiom,
pred_attacker(constr_CONST_4)).
fof(ax312, axiom,
pred_attacker(constr_CONST_3)).
fof(ax313, axiom,
pred_attacker(constr_CONST_2)).
fof(ax314, axiom,
pred_attacker(constr_CONST_1)).
fof(ax315, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax316, axiom,
![VAR_V_84, VAR_V_85] : ((pred_attacker(VAR_V_84) & pred_attacker(VAR_V_85)) => pred_attacker(tuple_2(VAR_V_84, VAR_V_85)))).
fof(ax317, axiom,
![VAR_V_92, VAR_V_93] : (pred_attacker(tuple_2(VAR_V_92, VAR_V_93)) => pred_attacker(VAR_V_92))).
fof(ax318, axiom,
![VAR_V_95, VAR_V_96] : (pred_attacker(tuple_2(VAR_V_95, VAR_V_96)) => pred_attacker(VAR_V_96))).
fof(ax319, axiom,
![VAR_V_98, VAR_V_99] : ((pred_mess(VAR_V_99, VAR_V_98) & pred_attacker(VAR_V_99)) => pred_attacker(VAR_V_98))).
fof(ax320, axiom,
![VAR_V_10X300X30, VAR_V_10X301] : ((pred_attacker(VAR_V_10X301) & pred_attacker(VAR_V_10X300X30)) => pred_mess(VAR_V_10X301, VAR_V_10X300X30))).
fof(ax321, axiom,
pred_attacker(name_c)).
fof(ax322, axiom,
pred_attacker(name_I)).
fof(ax323, axiom,
pred_attacker(name_B)).
fof(ax324, axiom,
pred_attacker(name_A)).
fof(ax325, axiom,
![VAR_V_10X303] : (pred_equal(VAR_V_10X303, VAR_V_10X303))).
fof(ax326, axiom,
![VAR_V_10X304] : (pred_attacker(name_new0x2Dname(VAR_V_10X304)))).
fof(ax327, axiom,
pred_table(tuple_keys(name_A, constr_pkey(name_skA)))).
fof(ax328, axiom,
pred_table(tuple_keys(name_B, constr_pkey(name_skB)))).
fof(ax329, axiom,
pred_attacker(tuple_2(constr_pkey(name_skA), constr_STEP_1))).
fof(ax330, axiom,
pred_attacker(tuple_2(constr_pkey(name_skB), constr_STEP_2))).
fof(ax331, axiom,
pred_attacker(tuple_2(constr_pkey(name_skS), constr_STEP_3))).
fof(ax332, axiom,
pred_attacker(tuple_2(tuple_2(name_A, name_I), constr_client_A_STEP_1))).
fof(ax333, axiom,
![VAR_0X40SID_256, VAR_SIGN_I_PKI_255] : ((pred_eq(constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_I_PKI_255, constr_pkey(name_skS))), name_I) & pred_attacker(VAR_SIGN_I_PKI_255)) => pred_attacker(tuple_2(constr_aenc(tuple_2(name_Na(VAR_0X40SID_256), name_A), constr_tuple_2_get_1(constr_checksign(VAR_SIGN_I_PKI_255, constr_pkey(name_skS)))), constr_client_A_STEP_2)))).
fof(ax334, axiom,
![VAR_0X40SID_321, VAR_AENC_NA_XOR_I_NI_320X30, VAR_SIGN_I_PKI_322] : ((pred_eq(constr_xor(constr_tuple_2_get_0x30(constr_adec(VAR_AENC_NA_XOR_I_NI_320X30, name_skA)), name_Na(VAR_0X40SID_321)), name_I) & pred_attacker(VAR_AENC_NA_XOR_I_NI_320X30) & pred_eq(constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_I_PKI_322, constr_pkey(name_skS))), name_I) & pred_attacker(VAR_SIGN_I_PKI_322)) => pred_attacker(tuple_2(constr_aenc(constr_tuple_2_get_1(constr_adec(VAR_AENC_NA_XOR_I_NI_320X30, name_skA)), constr_tuple_2_get_1(constr_checksign(VAR_SIGN_I_PKI_322, constr_pkey(name_skS)))), constr_client_A_STEP_3)))).
fof(ax335, axiom,
pred_attacker(tuple_2(tuple_2(name_B, name_A), constr_client_B_STEP_1))).
fof(ax336, axiom,
![VAR_0X40SID_455, VAR_AENC_NA_A_453, VAR_SIGN_A_PKA_454] : ((pred_eq(constr_tuple_2_get_1(constr_adec(VAR_AENC_NA_A_453, name_skB)), name_A) & pred_attacker(VAR_AENC_NA_A_453) & pred_eq(constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_A_PKA_454, constr_pkey(name_skS))), name_A) & pred_attacker(VAR_SIGN_A_PKA_454)) => pred_attacker(tuple_2(constr_aenc(tuple_2(constr_xor(constr_tuple_2_get_0x30(constr_adec(VAR_AENC_NA_A_453, name_skB)), name_B), name_Nb(VAR_0X40SID_455)), constr_tuple_2_get_1(constr_checksign(VAR_SIGN_A_PKA_454, constr_pkey(name_skS)))), constr_client_B_STEP_2)))).
fof(ax337, axiom,
![VAR_0X40SID_486, VAR_AENC_NA_A_487, VAR_AENC_NB_485, VAR_SIGN_A_PKA_488] : ((pred_eq(constr_adec(VAR_AENC_NB_485, name_skB), name_Nb(VAR_0X40SID_486)) & pred_attacker(VAR_AENC_NB_485) & pred_eq(constr_tuple_2_get_1(constr_adec(VAR_AENC_NA_A_487, name_skB)), name_A) & pred_attacker(VAR_AENC_NA_A_487) & pred_eq(constr_tuple_2_get_0x30(constr_checksign(VAR_SIGN_A_PKA_488, constr_pkey(name_skS))), name_A) & pred_attacker(VAR_SIGN_A_PKA_488)) => pred_attacker(tuple_2(name_objective, constr_client_B_STEP_3)))).
fof(ax338, axiom,
![VAR_DST_533, VAR_PKDST_534, VAR_SRC_535] : ((pred_table(tuple_keys(VAR_DST_533, VAR_PKDST_534)) & pred_attacker(tuple_2(VAR_SRC_535, VAR_DST_533))) => pred_attacker(tuple_2(constr_sign(tuple_2(VAR_DST_533, VAR_PKDST_534), name_skS), constr_key_retrieval_server_STEP_1)))).
fof(ax339, axiom,
![VAR_HOST_589, VAR_PK_590X30] : ((VAR_HOST_589 != name_B & VAR_HOST_589 != name_A & pred_attacker(tuple_2(VAR_HOST_589, VAR_PK_590X30))) => pred_table(tuple_keys(VAR_HOST_589, VAR_PK_590X30)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
