%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_T_STEP_1).
fof(ax5, axiom,
constr_CONST_0x30 != constr_T_STEP_2).
fof(ax6, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax7, axiom,
constr_CONST_0x30 != name_c).
fof(ax8, axiom,
constr_CONST_0x30 != name_k).
fof(ax9, axiom,
constr_CONST_0x30 != name_objective).
fof(ax10, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax11, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax12, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax13, axiom,
constr_CONST_1 != constr_T_STEP_1).
fof(ax14, axiom,
constr_CONST_1 != constr_T_STEP_2).
fof(ax15, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax16, axiom,
constr_CONST_1 != name_c).
fof(ax17, axiom,
constr_CONST_1 != name_k).
fof(ax18, axiom,
constr_CONST_1 != name_objective).
fof(ax19, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax20, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax21, axiom,
constr_CONST_2 != constr_T_STEP_1).
fof(ax22, axiom,
constr_CONST_2 != constr_T_STEP_2).
fof(ax23, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax24, axiom,
constr_CONST_2 != name_c).
fof(ax25, axiom,
constr_CONST_2 != name_k).
fof(ax26, axiom,
constr_CONST_2 != name_objective).
fof(ax27, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax28, axiom,
constr_CONST_3 != constr_T_STEP_1).
fof(ax29, axiom,
constr_CONST_3 != constr_T_STEP_2).
fof(ax30, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax31, axiom,
constr_CONST_3 != name_c).
fof(ax32, axiom,
constr_CONST_3 != name_k).
fof(ax33, axiom,
constr_CONST_3 != name_objective).
fof(ax34, axiom,
constr_CONST_4 != constr_T_STEP_1).
fof(ax35, axiom,
constr_CONST_4 != constr_T_STEP_2).
fof(ax36, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax37, axiom,
constr_CONST_4 != name_c).
fof(ax38, axiom,
constr_CONST_4 != name_k).
fof(ax39, axiom,
constr_CONST_4 != name_objective).
fof(ax40, axiom,
constr_T_STEP_1 != constr_T_STEP_2).
fof(ax41, axiom,
constr_T_STEP_1 != constr_ZERO).
fof(ax42, axiom,
constr_T_STEP_1 != name_c).
fof(ax43, axiom,
constr_T_STEP_1 != name_k).
fof(ax44, axiom,
constr_T_STEP_1 != name_objective).
fof(ax45, axiom,
constr_T_STEP_2 != constr_ZERO).
fof(ax46, axiom,
constr_T_STEP_2 != name_c).
fof(ax47, axiom,
constr_T_STEP_2 != name_k).
fof(ax48, axiom,
constr_T_STEP_2 != name_objective).
fof(ax49, axiom,
constr_ZERO != name_c).
fof(ax50, axiom,
constr_ZERO != name_k).
fof(ax51, axiom,
constr_ZERO != name_objective).
fof(ax52, axiom,
name_c != name_k).
fof(ax53, axiom,
name_c != name_objective).
fof(ax54, axiom,
name_k != name_objective).
fof(ax55, axiom,
![VAR_X_11] : (constr_xor(VAR_X_11, VAR_X_11) = constr_ZERO)).
fof(ax56, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, constr_ZERO) = VAR_X_10X30)).
fof(ax57, axiom,
![VAR_X_8, VAR_Y_9] : (constr_xor(VAR_X_8, VAR_Y_9) = constr_xor(VAR_Y_9, VAR_X_8))).
fof(ax58, axiom,
![VAR_X_7, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_7, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_7, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax59, axiom,
![VAR_X_23] : (pred_eq(VAR_X_23, VAR_X_23))).
fof(ax60, axiom,
![VAR_V_30X30, VAR_V_31] : ((pred_attacker(VAR_V_30X30) & pred_attacker(VAR_V_31)) => pred_attacker(constr_xor(VAR_V_30X30, VAR_V_31)))).
fof(ax61, axiom,
pred_attacker(tuple_true)).
fof(ax62, axiom,
![VAR_V_34] : (pred_attacker(VAR_V_34) => pred_attacker(constr_h(VAR_V_34)))).
fof(ax63, axiom,
pred_attacker(tuple_false)).
fof(ax64, axiom,
pred_attacker(constr_ZERO)).
fof(ax65, axiom,
pred_attacker(constr_T_STEP_2)).
fof(ax66, axiom,
pred_attacker(constr_T_STEP_1)).
fof(ax67, axiom,
pred_attacker(constr_CONST_4)).
fof(ax68, axiom,
pred_attacker(constr_CONST_3)).
fof(ax69, axiom,
pred_attacker(constr_CONST_2)).
fof(ax70, axiom,
pred_attacker(constr_CONST_1)).
fof(ax71, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax72, axiom,
![VAR_V_41, VAR_V_42] : ((pred_attacker(VAR_V_41) & pred_attacker(VAR_V_42)) => pred_attacker(tuple_2(VAR_V_41, VAR_V_42)))).
fof(ax73, axiom,
![VAR_V_49, VAR_V_50X30] : (pred_attacker(tuple_2(VAR_V_49, VAR_V_50X30)) => pred_attacker(VAR_V_49))).
fof(ax74, axiom,
![VAR_V_52, VAR_V_53] : (pred_attacker(tuple_2(VAR_V_52, VAR_V_53)) => pred_attacker(VAR_V_53))).
fof(ax75, axiom,
![VAR_V_55, VAR_V_56] : ((pred_mess(VAR_V_56, VAR_V_55) & pred_attacker(VAR_V_56)) => pred_attacker(VAR_V_55))).
fof(ax76, axiom,
![VAR_V_57, VAR_V_58] : ((pred_attacker(VAR_V_58) & pred_attacker(VAR_V_57)) => pred_mess(VAR_V_58, VAR_V_57))).
fof(ax77, axiom,
pred_attacker(name_c)).
fof(ax78, axiom,
![VAR_V_60X30] : (pred_equal(VAR_V_60X30, VAR_V_60X30))).
fof(ax79, axiom,
![VAR_V_61] : (pred_attacker(name_new0x2Dname(VAR_V_61)))).
fof(ax80, axiom,
![VAR_R1_85] : (pred_attacker(VAR_R1_85) => pred_attacker(tuple_2(constr_h(constr_xor(name_k, VAR_R1_85)), constr_T_STEP_1)))).
fof(ax81, axiom,
![VAR_K_XOR_K1_111, VAR_R1_112] : ((pred_attacker(VAR_K_XOR_K1_111) & pred_attacker(VAR_R1_112)) => pred_attacker(tuple_2(name_objective, constr_T_STEP_2)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
