%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_STEP_1).
fof(ax5, axiom,
constr_CONST_0x30 != constr_STEP_2).
fof(ax6, axiom,
constr_CONST_0x30 != constr_STEP_3).
fof(ax7, axiom,
constr_CONST_0x30 != constr_STEP_4).
fof(ax8, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax9, axiom,
constr_CONST_0x30 != constr_client_A_STEP_1).
fof(ax10, axiom,
constr_CONST_0x30 != constr_client_A_STEP_2).
fof(ax11, axiom,
constr_CONST_0x30 != constr_client_B_STEP_1).
fof(ax12, axiom,
constr_CONST_0x30 != constr_client_C_STEP_1).
fof(ax13, axiom,
constr_CONST_0x30 != constr_client_D_STEP_1).
fof(ax14, axiom,
constr_CONST_0x30 != name_A).
fof(ax15, axiom,
constr_CONST_0x30 != name_B).
fof(ax16, axiom,
constr_CONST_0x30 != name_C).
fof(ax17, axiom,
constr_CONST_0x30 != name_D).
fof(ax18, axiom,
constr_CONST_0x30 != name_Na).
fof(ax19, axiom,
constr_CONST_0x30 != name_Sa).
fof(ax20, axiom,
constr_CONST_0x30 != name_Sb).
fof(ax21, axiom,
constr_CONST_0x30 != name_Sc).
fof(ax22, axiom,
constr_CONST_0x30 != name_Sd).
fof(ax23, axiom,
constr_CONST_0x30 != name_c).
fof(ax24, axiom,
constr_CONST_0x30 != name_skA).
fof(ax25, axiom,
constr_CONST_0x30 != name_skB).
fof(ax26, axiom,
constr_CONST_0x30 != name_skC).
fof(ax27, axiom,
constr_CONST_0x30 != name_skD).
fof(ax28, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax29, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax30, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax31, axiom,
constr_CONST_1 != constr_STEP_1).
fof(ax32, axiom,
constr_CONST_1 != constr_STEP_2).
fof(ax33, axiom,
constr_CONST_1 != constr_STEP_3).
fof(ax34, axiom,
constr_CONST_1 != constr_STEP_4).
fof(ax35, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax36, axiom,
constr_CONST_1 != constr_client_A_STEP_1).
fof(ax37, axiom,
constr_CONST_1 != constr_client_A_STEP_2).
fof(ax38, axiom,
constr_CONST_1 != constr_client_B_STEP_1).
fof(ax39, axiom,
constr_CONST_1 != constr_client_C_STEP_1).
fof(ax40, axiom,
constr_CONST_1 != constr_client_D_STEP_1).
fof(ax41, axiom,
constr_CONST_1 != name_A).
fof(ax42, axiom,
constr_CONST_1 != name_B).
fof(ax43, axiom,
constr_CONST_1 != name_C).
fof(ax44, axiom,
constr_CONST_1 != name_D).
fof(ax45, axiom,
constr_CONST_1 != name_Na).
fof(ax46, axiom,
constr_CONST_1 != name_Sa).
fof(ax47, axiom,
constr_CONST_1 != name_Sb).
fof(ax48, axiom,
constr_CONST_1 != name_Sc).
fof(ax49, axiom,
constr_CONST_1 != name_Sd).
fof(ax50, axiom,
constr_CONST_1 != name_c).
fof(ax51, axiom,
constr_CONST_1 != name_skA).
fof(ax52, axiom,
constr_CONST_1 != name_skB).
fof(ax53, axiom,
constr_CONST_1 != name_skC).
fof(ax54, axiom,
constr_CONST_1 != name_skD).
fof(ax55, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax56, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax57, axiom,
constr_CONST_2 != constr_STEP_1).
fof(ax58, axiom,
constr_CONST_2 != constr_STEP_2).
fof(ax59, axiom,
constr_CONST_2 != constr_STEP_3).
fof(ax60, axiom,
constr_CONST_2 != constr_STEP_4).
fof(ax61, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax62, axiom,
constr_CONST_2 != constr_client_A_STEP_1).
fof(ax63, axiom,
constr_CONST_2 != constr_client_A_STEP_2).
fof(ax64, axiom,
constr_CONST_2 != constr_client_B_STEP_1).
fof(ax65, axiom,
constr_CONST_2 != constr_client_C_STEP_1).
fof(ax66, axiom,
constr_CONST_2 != constr_client_D_STEP_1).
fof(ax67, axiom,
constr_CONST_2 != name_A).
fof(ax68, axiom,
constr_CONST_2 != name_B).
fof(ax69, axiom,
constr_CONST_2 != name_C).
fof(ax70, axiom,
constr_CONST_2 != name_D).
fof(ax71, axiom,
constr_CONST_2 != name_Na).
fof(ax72, axiom,
constr_CONST_2 != name_Sa).
fof(ax73, axiom,
constr_CONST_2 != name_Sb).
fof(ax74, axiom,
constr_CONST_2 != name_Sc).
fof(ax75, axiom,
constr_CONST_2 != name_Sd).
fof(ax76, axiom,
constr_CONST_2 != name_c).
fof(ax77, axiom,
constr_CONST_2 != name_skA).
fof(ax78, axiom,
constr_CONST_2 != name_skB).
fof(ax79, axiom,
constr_CONST_2 != name_skC).
fof(ax80, axiom,
constr_CONST_2 != name_skD).
fof(ax81, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax82, axiom,
constr_CONST_3 != constr_STEP_1).
fof(ax83, axiom,
constr_CONST_3 != constr_STEP_2).
fof(ax84, axiom,
constr_CONST_3 != constr_STEP_3).
fof(ax85, axiom,
constr_CONST_3 != constr_STEP_4).
fof(ax86, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax87, axiom,
constr_CONST_3 != constr_client_A_STEP_1).
fof(ax88, axiom,
constr_CONST_3 != constr_client_A_STEP_2).
fof(ax89, axiom,
constr_CONST_3 != constr_client_B_STEP_1).
fof(ax90, axiom,
constr_CONST_3 != constr_client_C_STEP_1).
fof(ax91, axiom,
constr_CONST_3 != constr_client_D_STEP_1).
fof(ax92, axiom,
constr_CONST_3 != name_A).
fof(ax93, axiom,
constr_CONST_3 != name_B).
fof(ax94, axiom,
constr_CONST_3 != name_C).
fof(ax95, axiom,
constr_CONST_3 != name_D).
fof(ax96, axiom,
constr_CONST_3 != name_Na).
fof(ax97, axiom,
constr_CONST_3 != name_Sa).
fof(ax98, axiom,
constr_CONST_3 != name_Sb).
fof(ax99, axiom,
constr_CONST_3 != name_Sc).
fof(ax100, axiom,
constr_CONST_3 != name_Sd).
fof(ax101, axiom,
constr_CONST_3 != name_c).
fof(ax102, axiom,
constr_CONST_3 != name_skA).
fof(ax103, axiom,
constr_CONST_3 != name_skB).
fof(ax104, axiom,
constr_CONST_3 != name_skC).
fof(ax105, axiom,
constr_CONST_3 != name_skD).
fof(ax106, axiom,
constr_CONST_4 != constr_STEP_1).
fof(ax107, axiom,
constr_CONST_4 != constr_STEP_2).
fof(ax108, axiom,
constr_CONST_4 != constr_STEP_3).
fof(ax109, axiom,
constr_CONST_4 != constr_STEP_4).
fof(ax110, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax111, axiom,
constr_CONST_4 != constr_client_A_STEP_1).
fof(ax112, axiom,
constr_CONST_4 != constr_client_A_STEP_2).
fof(ax113, axiom,
constr_CONST_4 != constr_client_B_STEP_1).
fof(ax114, axiom,
constr_CONST_4 != constr_client_C_STEP_1).
fof(ax115, axiom,
constr_CONST_4 != constr_client_D_STEP_1).
fof(ax116, axiom,
constr_CONST_4 != name_A).
fof(ax117, axiom,
constr_CONST_4 != name_B).
fof(ax118, axiom,
constr_CONST_4 != name_C).
fof(ax119, axiom,
constr_CONST_4 != name_D).
fof(ax120, axiom,
constr_CONST_4 != name_Na).
fof(ax121, axiom,
constr_CONST_4 != name_Sa).
fof(ax122, axiom,
constr_CONST_4 != name_Sb).
fof(ax123, axiom,
constr_CONST_4 != name_Sc).
fof(ax124, axiom,
constr_CONST_4 != name_Sd).
fof(ax125, axiom,
constr_CONST_4 != name_c).
fof(ax126, axiom,
constr_CONST_4 != name_skA).
fof(ax127, axiom,
constr_CONST_4 != name_skB).
fof(ax128, axiom,
constr_CONST_4 != name_skC).
fof(ax129, axiom,
constr_CONST_4 != name_skD).
fof(ax130, axiom,
constr_STEP_1 != constr_STEP_2).
fof(ax131, axiom,
constr_STEP_1 != constr_STEP_3).
fof(ax132, axiom,
constr_STEP_1 != constr_STEP_4).
fof(ax133, axiom,
constr_STEP_1 != constr_ZERO).
fof(ax134, axiom,
constr_STEP_1 != constr_client_A_STEP_1).
fof(ax135, axiom,
constr_STEP_1 != constr_client_A_STEP_2).
fof(ax136, axiom,
constr_STEP_1 != constr_client_B_STEP_1).
fof(ax137, axiom,
constr_STEP_1 != constr_client_C_STEP_1).
fof(ax138, axiom,
constr_STEP_1 != constr_client_D_STEP_1).
fof(ax139, axiom,
constr_STEP_1 != name_A).
fof(ax140, axiom,
constr_STEP_1 != name_B).
fof(ax141, axiom,
constr_STEP_1 != name_C).
fof(ax142, axiom,
constr_STEP_1 != name_D).
fof(ax143, axiom,
constr_STEP_1 != name_Na).
fof(ax144, axiom,
constr_STEP_1 != name_Sa).
fof(ax145, axiom,
constr_STEP_1 != name_Sb).
fof(ax146, axiom,
constr_STEP_1 != name_Sc).
fof(ax147, axiom,
constr_STEP_1 != name_Sd).
fof(ax148, axiom,
constr_STEP_1 != name_c).
fof(ax149, axiom,
constr_STEP_1 != name_skA).
fof(ax150, axiom,
constr_STEP_1 != name_skB).
fof(ax151, axiom,
constr_STEP_1 != name_skC).
fof(ax152, axiom,
constr_STEP_1 != name_skD).
fof(ax153, axiom,
constr_STEP_2 != constr_STEP_3).
fof(ax154, axiom,
constr_STEP_2 != constr_STEP_4).
fof(ax155, axiom,
constr_STEP_2 != constr_ZERO).
fof(ax156, axiom,
constr_STEP_2 != constr_client_A_STEP_1).
fof(ax157, axiom,
constr_STEP_2 != constr_client_A_STEP_2).
fof(ax158, axiom,
constr_STEP_2 != constr_client_B_STEP_1).
fof(ax159, axiom,
constr_STEP_2 != constr_client_C_STEP_1).
fof(ax160, axiom,
constr_STEP_2 != constr_client_D_STEP_1).
fof(ax161, axiom,
constr_STEP_2 != name_A).
fof(ax162, axiom,
constr_STEP_2 != name_B).
fof(ax163, axiom,
constr_STEP_2 != name_C).
fof(ax164, axiom,
constr_STEP_2 != name_D).
fof(ax165, axiom,
constr_STEP_2 != name_Na).
fof(ax166, axiom,
constr_STEP_2 != name_Sa).
fof(ax167, axiom,
constr_STEP_2 != name_Sb).
fof(ax168, axiom,
constr_STEP_2 != name_Sc).
fof(ax169, axiom,
constr_STEP_2 != name_Sd).
fof(ax170, axiom,
constr_STEP_2 != name_c).
fof(ax171, axiom,
constr_STEP_2 != name_skA).
fof(ax172, axiom,
constr_STEP_2 != name_skB).
fof(ax173, axiom,
constr_STEP_2 != name_skC).
fof(ax174, axiom,
constr_STEP_2 != name_skD).
fof(ax175, axiom,
constr_STEP_3 != constr_STEP_4).
fof(ax176, axiom,
constr_STEP_3 != constr_ZERO).
fof(ax177, axiom,
constr_STEP_3 != constr_client_A_STEP_1).
fof(ax178, axiom,
constr_STEP_3 != constr_client_A_STEP_2).
fof(ax179, axiom,
constr_STEP_3 != constr_client_B_STEP_1).
fof(ax180, axiom,
constr_STEP_3 != constr_client_C_STEP_1).
fof(ax181, axiom,
constr_STEP_3 != constr_client_D_STEP_1).
fof(ax182, axiom,
constr_STEP_3 != name_A).
fof(ax183, axiom,
constr_STEP_3 != name_B).
fof(ax184, axiom,
constr_STEP_3 != name_C).
fof(ax185, axiom,
constr_STEP_3 != name_D).
fof(ax186, axiom,
constr_STEP_3 != name_Na).
fof(ax187, axiom,
constr_STEP_3 != name_Sa).
fof(ax188, axiom,
constr_STEP_3 != name_Sb).
fof(ax189, axiom,
constr_STEP_3 != name_Sc).
fof(ax190, axiom,
constr_STEP_3 != name_Sd).
fof(ax191, axiom,
constr_STEP_3 != name_c).
fof(ax192, axiom,
constr_STEP_3 != name_skA).
fof(ax193, axiom,
constr_STEP_3 != name_skB).
fof(ax194, axiom,
constr_STEP_3 != name_skC).
fof(ax195, axiom,
constr_STEP_3 != name_skD).
fof(ax196, axiom,
constr_STEP_4 != constr_ZERO).
fof(ax197, axiom,
constr_STEP_4 != constr_client_A_STEP_1).
fof(ax198, axiom,
constr_STEP_4 != constr_client_A_STEP_2).
fof(ax199, axiom,
constr_STEP_4 != constr_client_B_STEP_1).
fof(ax200, axiom,
constr_STEP_4 != constr_client_C_STEP_1).
fof(ax201, axiom,
constr_STEP_4 != constr_client_D_STEP_1).
fof(ax202, axiom,
constr_STEP_4 != name_A).
fof(ax203, axiom,
constr_STEP_4 != name_B).
fof(ax204, axiom,
constr_STEP_4 != name_C).
fof(ax205, axiom,
constr_STEP_4 != name_D).
fof(ax206, axiom,
constr_STEP_4 != name_Na).
fof(ax207, axiom,
constr_STEP_4 != name_Sa).
fof(ax208, axiom,
constr_STEP_4 != name_Sb).
fof(ax209, axiom,
constr_STEP_4 != name_Sc).
fof(ax210, axiom,
constr_STEP_4 != name_Sd).
fof(ax211, axiom,
constr_STEP_4 != name_c).
fof(ax212, axiom,
constr_STEP_4 != name_skA).
fof(ax213, axiom,
constr_STEP_4 != name_skB).
fof(ax214, axiom,
constr_STEP_4 != name_skC).
fof(ax215, axiom,
constr_STEP_4 != name_skD).
fof(ax216, axiom,
constr_ZERO != constr_client_A_STEP_1).
fof(ax217, axiom,
constr_ZERO != constr_client_A_STEP_2).
fof(ax218, axiom,
constr_ZERO != constr_client_B_STEP_1).
fof(ax219, axiom,
constr_ZERO != constr_client_C_STEP_1).
fof(ax220, axiom,
constr_ZERO != constr_client_D_STEP_1).
fof(ax221, axiom,
constr_ZERO != name_A).
fof(ax222, axiom,
constr_ZERO != name_B).
fof(ax223, axiom,
constr_ZERO != name_C).
fof(ax224, axiom,
constr_ZERO != name_D).
fof(ax225, axiom,
constr_ZERO != name_Na).
fof(ax226, axiom,
constr_ZERO != name_Sa).
fof(ax227, axiom,
constr_ZERO != name_Sb).
fof(ax228, axiom,
constr_ZERO != name_Sc).
fof(ax229, axiom,
constr_ZERO != name_Sd).
fof(ax230, axiom,
constr_ZERO != name_c).
fof(ax231, axiom,
constr_ZERO != name_skA).
fof(ax232, axiom,
constr_ZERO != name_skB).
fof(ax233, axiom,
constr_ZERO != name_skC).
fof(ax234, axiom,
constr_ZERO != name_skD).
fof(ax235, axiom,
constr_client_A_STEP_1 != constr_client_A_STEP_2).
fof(ax236, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_1).
fof(ax237, axiom,
constr_client_A_STEP_1 != constr_client_C_STEP_1).
fof(ax238, axiom,
constr_client_A_STEP_1 != constr_client_D_STEP_1).
fof(ax239, axiom,
constr_client_A_STEP_1 != name_A).
fof(ax240, axiom,
constr_client_A_STEP_1 != name_B).
fof(ax241, axiom,
constr_client_A_STEP_1 != name_C).
fof(ax242, axiom,
constr_client_A_STEP_1 != name_D).
fof(ax243, axiom,
constr_client_A_STEP_1 != name_Na).
fof(ax244, axiom,
constr_client_A_STEP_1 != name_Sa).
fof(ax245, axiom,
constr_client_A_STEP_1 != name_Sb).
fof(ax246, axiom,
constr_client_A_STEP_1 != name_Sc).
fof(ax247, axiom,
constr_client_A_STEP_1 != name_Sd).
fof(ax248, axiom,
constr_client_A_STEP_1 != name_c).
fof(ax249, axiom,
constr_client_A_STEP_1 != name_skA).
fof(ax250, axiom,
constr_client_A_STEP_1 != name_skB).
fof(ax251, axiom,
constr_client_A_STEP_1 != name_skC).
fof(ax252, axiom,
constr_client_A_STEP_1 != name_skD).
fof(ax253, axiom,
constr_client_A_STEP_2 != constr_client_B_STEP_1).
fof(ax254, axiom,
constr_client_A_STEP_2 != constr_client_C_STEP_1).
fof(ax255, axiom,
constr_client_A_STEP_2 != constr_client_D_STEP_1).
fof(ax256, axiom,
constr_client_A_STEP_2 != name_A).
fof(ax257, axiom,
constr_client_A_STEP_2 != name_B).
fof(ax258, axiom,
constr_client_A_STEP_2 != name_C).
fof(ax259, axiom,
constr_client_A_STEP_2 != name_D).
fof(ax260, axiom,
constr_client_A_STEP_2 != name_Na).
fof(ax261, axiom,
constr_client_A_STEP_2 != name_Sa).
fof(ax262, axiom,
constr_client_A_STEP_2 != name_Sb).
fof(ax263, axiom,
constr_client_A_STEP_2 != name_Sc).
fof(ax264, axiom,
constr_client_A_STEP_2 != name_Sd).
fof(ax265, axiom,
constr_client_A_STEP_2 != name_c).
fof(ax266, axiom,
constr_client_A_STEP_2 != name_skA).
fof(ax267, axiom,
constr_client_A_STEP_2 != name_skB).
fof(ax268, axiom,
constr_client_A_STEP_2 != name_skC).
fof(ax269, axiom,
constr_client_A_STEP_2 != name_skD).
fof(ax270, axiom,
constr_client_B_STEP_1 != constr_client_C_STEP_1).
fof(ax271, axiom,
constr_client_B_STEP_1 != constr_client_D_STEP_1).
fof(ax272, axiom,
constr_client_B_STEP_1 != name_A).
fof(ax273, axiom,
constr_client_B_STEP_1 != name_B).
fof(ax274, axiom,
constr_client_B_STEP_1 != name_C).
fof(ax275, axiom,
constr_client_B_STEP_1 != name_D).
fof(ax276, axiom,
constr_client_B_STEP_1 != name_Na).
fof(ax277, axiom,
constr_client_B_STEP_1 != name_Sa).
fof(ax278, axiom,
constr_client_B_STEP_1 != name_Sb).
fof(ax279, axiom,
constr_client_B_STEP_1 != name_Sc).
fof(ax280, axiom,
constr_client_B_STEP_1 != name_Sd).
fof(ax281, axiom,
constr_client_B_STEP_1 != name_c).
fof(ax282, axiom,
constr_client_B_STEP_1 != name_skA).
fof(ax283, axiom,
constr_client_B_STEP_1 != name_skB).
fof(ax284, axiom,
constr_client_B_STEP_1 != name_skC).
fof(ax285, axiom,
constr_client_B_STEP_1 != name_skD).
fof(ax286, axiom,
constr_client_C_STEP_1 != constr_client_D_STEP_1).
fof(ax287, axiom,
constr_client_C_STEP_1 != name_A).
fof(ax288, axiom,
constr_client_C_STEP_1 != name_B).
fof(ax289, axiom,
constr_client_C_STEP_1 != name_C).
fof(ax290, axiom,
constr_client_C_STEP_1 != name_D).
fof(ax291, axiom,
constr_client_C_STEP_1 != name_Na).
fof(ax292, axiom,
constr_client_C_STEP_1 != name_Sa).
fof(ax293, axiom,
constr_client_C_STEP_1 != name_Sb).
fof(ax294, axiom,
constr_client_C_STEP_1 != name_Sc).
fof(ax295, axiom,
constr_client_C_STEP_1 != name_Sd).
fof(ax296, axiom,
constr_client_C_STEP_1 != name_c).
fof(ax297, axiom,
constr_client_C_STEP_1 != name_skA).
fof(ax298, axiom,
constr_client_C_STEP_1 != name_skB).
fof(ax299, axiom,
constr_client_C_STEP_1 != name_skC).
fof(ax300, axiom,
constr_client_C_STEP_1 != name_skD).
fof(ax301, axiom,
constr_client_D_STEP_1 != name_A).
fof(ax302, axiom,
constr_client_D_STEP_1 != name_B).
fof(ax303, axiom,
constr_client_D_STEP_1 != name_C).
fof(ax304, axiom,
constr_client_D_STEP_1 != name_D).
fof(ax305, axiom,
constr_client_D_STEP_1 != name_Na).
fof(ax306, axiom,
constr_client_D_STEP_1 != name_Sa).
fof(ax307, axiom,
constr_client_D_STEP_1 != name_Sb).
fof(ax308, axiom,
constr_client_D_STEP_1 != name_Sc).
fof(ax309, axiom,
constr_client_D_STEP_1 != name_Sd).
fof(ax310, axiom,
constr_client_D_STEP_1 != name_c).
fof(ax311, axiom,
constr_client_D_STEP_1 != name_skA).
fof(ax312, axiom,
constr_client_D_STEP_1 != name_skB).
fof(ax313, axiom,
constr_client_D_STEP_1 != name_skC).
fof(ax314, axiom,
constr_client_D_STEP_1 != name_skD).
fof(ax315, axiom,
name_A != name_B).
fof(ax316, axiom,
name_A != name_C).
fof(ax317, axiom,
name_A != name_D).
fof(ax318, axiom,
name_A != name_Na).
fof(ax319, axiom,
name_A != name_Sa).
fof(ax320, axiom,
name_A != name_Sb).
fof(ax321, axiom,
name_A != name_Sc).
fof(ax322, axiom,
name_A != name_Sd).
fof(ax323, axiom,
name_A != name_c).
fof(ax324, axiom,
name_A != name_skA).
fof(ax325, axiom,
name_A != name_skB).
fof(ax326, axiom,
name_A != name_skC).
fof(ax327, axiom,
name_A != name_skD).
fof(ax328, axiom,
name_B != name_C).
fof(ax329, axiom,
name_B != name_D).
fof(ax330, axiom,
name_B != name_Na).
fof(ax331, axiom,
name_B != name_Sa).
fof(ax332, axiom,
name_B != name_Sb).
fof(ax333, axiom,
name_B != name_Sc).
fof(ax334, axiom,
name_B != name_Sd).
fof(ax335, axiom,
name_B != name_c).
fof(ax336, axiom,
name_B != name_skA).
fof(ax337, axiom,
name_B != name_skB).
fof(ax338, axiom,
name_B != name_skC).
fof(ax339, axiom,
name_B != name_skD).
fof(ax340, axiom,
name_C != name_D).
fof(ax341, axiom,
name_C != name_Na).
fof(ax342, axiom,
name_C != name_Sa).
fof(ax343, axiom,
name_C != name_Sb).
fof(ax344, axiom,
name_C != name_Sc).
fof(ax345, axiom,
name_C != name_Sd).
fof(ax346, axiom,
name_C != name_c).
fof(ax347, axiom,
name_C != name_skA).
fof(ax348, axiom,
name_C != name_skB).
fof(ax349, axiom,
name_C != name_skC).
fof(ax350, axiom,
name_C != name_skD).
fof(ax351, axiom,
name_D != name_Na).
fof(ax352, axiom,
name_D != name_Sa).
fof(ax353, axiom,
name_D != name_Sb).
fof(ax354, axiom,
name_D != name_Sc).
fof(ax355, axiom,
name_D != name_Sd).
fof(ax356, axiom,
name_D != name_c).
fof(ax357, axiom,
name_D != name_skA).
fof(ax358, axiom,
name_D != name_skB).
fof(ax359, axiom,
name_D != name_skC).
fof(ax360, axiom,
name_D != name_skD).
fof(ax361, axiom,
name_Na != name_Sa).
fof(ax362, axiom,
name_Na != name_Sb).
fof(ax363, axiom,
name_Na != name_Sc).
fof(ax364, axiom,
name_Na != name_Sd).
fof(ax365, axiom,
name_Na != name_c).
fof(ax366, axiom,
name_Na != name_skA).
fof(ax367, axiom,
name_Na != name_skB).
fof(ax368, axiom,
name_Na != name_skC).
fof(ax369, axiom,
name_Na != name_skD).
fof(ax370, axiom,
name_Sa != name_Sb).
fof(ax371, axiom,
name_Sa != name_Sc).
fof(ax372, axiom,
name_Sa != name_Sd).
fof(ax373, axiom,
name_Sa != name_c).
fof(ax374, axiom,
name_Sa != name_skA).
fof(ax375, axiom,
name_Sa != name_skB).
fof(ax376, axiom,
name_Sa != name_skC).
fof(ax377, axiom,
name_Sa != name_skD).
fof(ax378, axiom,
name_Sb != name_Sc).
fof(ax379, axiom,
name_Sb != name_Sd).
fof(ax380, axiom,
name_Sb != name_c).
fof(ax381, axiom,
name_Sb != name_skA).
fof(ax382, axiom,
name_Sb != name_skB).
fof(ax383, axiom,
name_Sb != name_skC).
fof(ax384, axiom,
name_Sb != name_skD).
fof(ax385, axiom,
name_Sc != name_Sd).
fof(ax386, axiom,
name_Sc != name_c).
fof(ax387, axiom,
name_Sc != name_skA).
fof(ax388, axiom,
name_Sc != name_skB).
fof(ax389, axiom,
name_Sc != name_skC).
fof(ax390, axiom,
name_Sc != name_skD).
fof(ax391, axiom,
name_Sd != name_c).
fof(ax392, axiom,
name_Sd != name_skA).
fof(ax393, axiom,
name_Sd != name_skB).
fof(ax394, axiom,
name_Sd != name_skC).
fof(ax395, axiom,
name_Sd != name_skD).
fof(ax396, axiom,
name_c != name_skA).
fof(ax397, axiom,
name_c != name_skB).
fof(ax398, axiom,
name_c != name_skC).
fof(ax399, axiom,
name_c != name_skD).
fof(ax400, axiom,
name_skA != name_skB).
fof(ax401, axiom,
name_skA != name_skC).
fof(ax402, axiom,
name_skA != name_skD).
fof(ax403, axiom,
name_skB != name_skC).
fof(ax404, axiom,
name_skB != name_skD).
fof(ax405, axiom,
name_skC != name_skD).
fof(ax406, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_adec(constr_aenc(VAR_M_0X30, constr_pkey(VAR_K_0X30)), VAR_K_0X30) = VAR_M_0X30)).
fof(ax407, axiom,
![VAR_X_11] : (constr_add(VAR_X_11, constr_neg(VAR_X_11)) = constr_ZERO)).
fof(ax408, axiom,
![VAR_X_10X30] : (constr_add(VAR_X_10X30, constr_ZERO) = VAR_X_10X30)).
fof(ax409, axiom,
![VAR_X_8, VAR_Y_9] : (constr_add(VAR_X_8, VAR_Y_9) = constr_add(VAR_Y_9, VAR_X_8))).
fof(ax410, axiom,
![VAR_X_7, VAR_Y_0X30, VAR_Z_0X30] : (constr_add(VAR_X_7, constr_add(VAR_Y_0X30, VAR_Z_0X30)) = constr_add(constr_add(VAR_X_7, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax411, axiom,
![VAR_X_28] : (pred_eq(VAR_X_28, VAR_X_28))).
fof(ax412, axiom,
pred_attacker(tuple_true)).
fof(ax413, axiom,
![VAR_V_34] : (pred_attacker(VAR_V_34) => pred_attacker(constr_pkey(VAR_V_34)))).
fof(ax414, axiom,
![VAR_V_37] : (pred_attacker(VAR_V_37) => pred_attacker(constr_neg(VAR_V_37)))).
fof(ax415, axiom,
pred_attacker(tuple_false)).
fof(ax416, axiom,
pred_attacker(constr_client_D_STEP_1)).
fof(ax417, axiom,
pred_attacker(constr_client_C_STEP_1)).
fof(ax418, axiom,
pred_attacker(constr_client_B_STEP_1)).
fof(ax419, axiom,
pred_attacker(constr_client_A_STEP_2)).
fof(ax420, axiom,
pred_attacker(constr_client_A_STEP_1)).
fof(ax421, axiom,
![VAR_V_40X30, VAR_V_41] : ((pred_attacker(VAR_V_40X30) & pred_attacker(VAR_V_41)) => pred_attacker(constr_aenc(VAR_V_40X30, VAR_V_41)))).
fof(ax422, axiom,
![VAR_V_44, VAR_V_45] : ((pred_attacker(VAR_V_44) & pred_attacker(VAR_V_45)) => pred_attacker(constr_adec(VAR_V_44, VAR_V_45)))).
fof(ax423, axiom,
![VAR_V_48, VAR_V_49] : ((pred_attacker(VAR_V_48) & pred_attacker(VAR_V_49)) => pred_attacker(constr_add(VAR_V_48, VAR_V_49)))).
fof(ax424, axiom,
pred_attacker(constr_ZERO)).
fof(ax425, axiom,
pred_attacker(constr_STEP_4)).
fof(ax426, axiom,
pred_attacker(constr_STEP_3)).
fof(ax427, axiom,
pred_attacker(constr_STEP_2)).
fof(ax428, axiom,
pred_attacker(constr_STEP_1)).
fof(ax429, axiom,
pred_attacker(constr_CONST_4)).
fof(ax430, axiom,
pred_attacker(constr_CONST_3)).
fof(ax431, axiom,
pred_attacker(constr_CONST_2)).
fof(ax432, axiom,
pred_attacker(constr_CONST_1)).
fof(ax433, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax434, axiom,
![VAR_V_56, VAR_V_57] : ((pred_attacker(VAR_V_56) & pred_attacker(VAR_V_57)) => pred_attacker(tuple_2(VAR_V_56, VAR_V_57)))).
fof(ax435, axiom,
![VAR_V_64, VAR_V_65] : (pred_attacker(tuple_2(VAR_V_64, VAR_V_65)) => pred_attacker(VAR_V_64))).
fof(ax436, axiom,
![VAR_V_67, VAR_V_68] : (pred_attacker(tuple_2(VAR_V_67, VAR_V_68)) => pred_attacker(VAR_V_68))).
fof(ax437, axiom,
![VAR_V_70X30, VAR_V_71] : ((pred_mess(VAR_V_71, VAR_V_70X30) & pred_attacker(VAR_V_71)) => pred_attacker(VAR_V_70X30))).
fof(ax438, axiom,
![VAR_V_72, VAR_V_73] : ((pred_attacker(VAR_V_73) & pred_attacker(VAR_V_72)) => pred_mess(VAR_V_73, VAR_V_72))).
fof(ax439, axiom,
pred_attacker(name_c)).
fof(ax440, axiom,
pred_attacker(name_D)).
fof(ax441, axiom,
pred_attacker(name_C)).
fof(ax442, axiom,
pred_attacker(name_B)).
fof(ax443, axiom,
pred_attacker(name_A)).
fof(ax444, axiom,
![VAR_V_75] : (pred_equal(VAR_V_75, VAR_V_75))).
fof(ax445, axiom,
![VAR_V_76] : (pred_attacker(name_new0x2Dname(VAR_V_76)))).
fof(ax446, axiom,
pred_attacker(tuple_2(constr_pkey(name_skA), constr_STEP_1))).
fof(ax447, axiom,
pred_attacker(tuple_2(constr_pkey(name_skB), constr_STEP_2))).
fof(ax448, axiom,
pred_attacker(tuple_2(constr_pkey(name_skC), constr_STEP_3))).
fof(ax449, axiom,
pred_attacker(tuple_2(constr_pkey(name_skD), constr_STEP_4))).
fof(ax450, axiom,
![VAR_LASTT_182, VAR_PKNEXTT_183] : ((pred_attacker(VAR_LASTT_182) & pred_attacker(VAR_PKNEXTT_183)) => pred_attacker(tuple_2(tuple_2(name_A, constr_aenc(constr_add(name_Na, name_Sa), VAR_PKNEXTT_183)), constr_client_A_STEP_1)))).
fof(ax451, axiom,
![VAR_AENC_ADD_NA_SA_SB_SC_SD_229, VAR_LASTT_228, VAR_PKNEXTT_230X30] : ((pred_attacker(tuple_2(VAR_LASTT_228, VAR_AENC_ADD_NA_SA_SB_SC_SD_229)) & pred_attacker(VAR_LASTT_228) & pred_attacker(VAR_PKNEXTT_230X30)) => pred_attacker(tuple_2(constr_add(constr_adec(VAR_AENC_ADD_NA_SA_SB_SC_SD_229, name_skA), constr_neg(name_Na)), constr_client_A_STEP_2)))).
fof(ax452, axiom,
![VAR_AENC_ADD_NA_SA_288, VAR_PKNEXTT_289, VAR_PREVT_287] : ((pred_attacker(tuple_2(VAR_PREVT_287, VAR_AENC_ADD_NA_SA_288)) & pred_attacker(VAR_PKNEXTT_289) & pred_attacker(VAR_PREVT_287)) => pred_attacker(tuple_2(tuple_2(name_B, constr_aenc(constr_add(constr_adec(VAR_AENC_ADD_NA_SA_288, name_skB), name_Sb), VAR_PKNEXTT_289)), constr_client_B_STEP_1)))).
fof(ax453, axiom,
![VAR_AENC_ADD_NA_SA_SB_351, VAR_PKNEXTT_352, VAR_PREVT_350X30] : ((pred_attacker(tuple_2(VAR_PREVT_350X30, VAR_AENC_ADD_NA_SA_SB_351)) & pred_attacker(VAR_PKNEXTT_352) & pred_attacker(VAR_PREVT_350X30)) => pred_attacker(tuple_2(tuple_2(name_C, constr_aenc(constr_add(constr_adec(VAR_AENC_ADD_NA_SA_SB_351, name_skC), name_Sc), VAR_PKNEXTT_352)), constr_client_C_STEP_1)))).
fof(ax454, axiom,
![VAR_AENC_ADD_NA_SA_SB_SC_414, VAR_PKNEXTT_415, VAR_PREVT_413] : ((pred_attacker(tuple_2(VAR_PREVT_413, VAR_AENC_ADD_NA_SA_SB_SC_414)) & pred_attacker(VAR_PKNEXTT_415) & pred_attacker(VAR_PREVT_413)) => pred_attacker(tuple_2(tuple_2(name_D, constr_aenc(constr_add(constr_adec(VAR_AENC_ADD_NA_SA_SB_SC_414, name_skD), name_Sd), VAR_PKNEXTT_415)), constr_client_D_STEP_1)))).
fof(co0, conjecture,
pred_attacker(name_Sa)).
