%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_A_STEP_1 != constr_A_STEP_2).
fof(ax1, axiom,
constr_A_STEP_1 != constr_A_STEP_3).
fof(ax2, axiom,
constr_A_STEP_1 != constr_B_STEP_1).
fof(ax3, axiom,
constr_A_STEP_1 != constr_CONST_0x30).
fof(ax4, axiom,
constr_A_STEP_1 != constr_CONST_1).
fof(ax5, axiom,
constr_A_STEP_1 != constr_CONST_2).
fof(ax6, axiom,
constr_A_STEP_1 != constr_CONST_3).
fof(ax7, axiom,
constr_A_STEP_1 != constr_CONST_4).
fof(ax8, axiom,
constr_A_STEP_1 != name_Ka).
fof(ax9, axiom,
constr_A_STEP_1 != name_Kb).
fof(ax10, axiom,
constr_A_STEP_1 != name_c).
fof(ax11, axiom,
constr_A_STEP_1 != name_m_9).
fof(ax12, axiom,
constr_A_STEP_1 != name_objective).
fof(ax13, axiom,
constr_A_STEP_2 != constr_A_STEP_3).
fof(ax14, axiom,
constr_A_STEP_2 != constr_B_STEP_1).
fof(ax15, axiom,
constr_A_STEP_2 != constr_CONST_0x30).
fof(ax16, axiom,
constr_A_STEP_2 != constr_CONST_1).
fof(ax17, axiom,
constr_A_STEP_2 != constr_CONST_2).
fof(ax18, axiom,
constr_A_STEP_2 != constr_CONST_3).
fof(ax19, axiom,
constr_A_STEP_2 != constr_CONST_4).
fof(ax20, axiom,
constr_A_STEP_2 != name_Ka).
fof(ax21, axiom,
constr_A_STEP_2 != name_Kb).
fof(ax22, axiom,
constr_A_STEP_2 != name_c).
fof(ax23, axiom,
constr_A_STEP_2 != name_m_9).
fof(ax24, axiom,
constr_A_STEP_2 != name_objective).
fof(ax25, axiom,
constr_A_STEP_3 != constr_B_STEP_1).
fof(ax26, axiom,
constr_A_STEP_3 != constr_CONST_0x30).
fof(ax27, axiom,
constr_A_STEP_3 != constr_CONST_1).
fof(ax28, axiom,
constr_A_STEP_3 != constr_CONST_2).
fof(ax29, axiom,
constr_A_STEP_3 != constr_CONST_3).
fof(ax30, axiom,
constr_A_STEP_3 != constr_CONST_4).
fof(ax31, axiom,
constr_A_STEP_3 != name_Ka).
fof(ax32, axiom,
constr_A_STEP_3 != name_Kb).
fof(ax33, axiom,
constr_A_STEP_3 != name_c).
fof(ax34, axiom,
constr_A_STEP_3 != name_m_9).
fof(ax35, axiom,
constr_A_STEP_3 != name_objective).
fof(ax36, axiom,
constr_B_STEP_1 != constr_CONST_0x30).
fof(ax37, axiom,
constr_B_STEP_1 != constr_CONST_1).
fof(ax38, axiom,
constr_B_STEP_1 != constr_CONST_2).
fof(ax39, axiom,
constr_B_STEP_1 != constr_CONST_3).
fof(ax40, axiom,
constr_B_STEP_1 != constr_CONST_4).
fof(ax41, axiom,
constr_B_STEP_1 != name_Ka).
fof(ax42, axiom,
constr_B_STEP_1 != name_Kb).
fof(ax43, axiom,
constr_B_STEP_1 != name_c).
fof(ax44, axiom,
constr_B_STEP_1 != name_m_9).
fof(ax45, axiom,
constr_B_STEP_1 != name_objective).
fof(ax46, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax47, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax48, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax49, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax50, axiom,
constr_CONST_0x30 != name_Ka).
fof(ax51, axiom,
constr_CONST_0x30 != name_Kb).
fof(ax52, axiom,
constr_CONST_0x30 != name_c).
fof(ax53, axiom,
constr_CONST_0x30 != name_m_9).
fof(ax54, axiom,
constr_CONST_0x30 != name_objective).
fof(ax55, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax56, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax57, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax58, axiom,
constr_CONST_1 != name_Ka).
fof(ax59, axiom,
constr_CONST_1 != name_Kb).
fof(ax60, axiom,
constr_CONST_1 != name_c).
fof(ax61, axiom,
constr_CONST_1 != name_m_9).
fof(ax62, axiom,
constr_CONST_1 != name_objective).
fof(ax63, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax64, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax65, axiom,
constr_CONST_2 != name_Ka).
fof(ax66, axiom,
constr_CONST_2 != name_Kb).
fof(ax67, axiom,
constr_CONST_2 != name_c).
fof(ax68, axiom,
constr_CONST_2 != name_m_9).
fof(ax69, axiom,
constr_CONST_2 != name_objective).
fof(ax70, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax71, axiom,
constr_CONST_3 != name_Ka).
fof(ax72, axiom,
constr_CONST_3 != name_Kb).
fof(ax73, axiom,
constr_CONST_3 != name_c).
fof(ax74, axiom,
constr_CONST_3 != name_m_9).
fof(ax75, axiom,
constr_CONST_3 != name_objective).
fof(ax76, axiom,
constr_CONST_4 != name_Ka).
fof(ax77, axiom,
constr_CONST_4 != name_Kb).
fof(ax78, axiom,
constr_CONST_4 != name_c).
fof(ax79, axiom,
constr_CONST_4 != name_m_9).
fof(ax80, axiom,
constr_CONST_4 != name_objective).
fof(ax81, axiom,
name_Ka != name_Kb).
fof(ax82, axiom,
name_Ka != name_c).
fof(ax83, axiom,
name_Ka != name_m_9).
fof(ax84, axiom,
name_Ka != name_objective).
fof(ax85, axiom,
name_Kb != name_c).
fof(ax86, axiom,
name_Kb != name_m_9).
fof(ax87, axiom,
name_Kb != name_objective).
fof(ax88, axiom,
name_c != name_m_9).
fof(ax89, axiom,
name_c != name_objective).
fof(ax90, axiom,
name_m_9 != name_objective).
fof(ax91, axiom,
![VAR_K_8, VAR_M_7] : (constr_dec(constr_enc(VAR_M_7, VAR_K_8), VAR_K_8) = VAR_M_7)).
fof(ax92, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_comm_dec(constr_comm_enc(VAR_M_0X30, VAR_K_0X30), VAR_K_0X30) = VAR_M_0X30)).
fof(ax93, axiom,
![VAR_X_24] : (pred_eq(VAR_X_24, VAR_X_24))).
fof(ax94, axiom,
pred_attacker(tuple_true)).
fof(ax95, axiom,
pred_attacker(tuple_false)).
fof(ax96, axiom,
![VAR_V_32, VAR_V_33] : ((pred_attacker(VAR_V_32) & pred_attacker(VAR_V_33)) => pred_attacker(constr_enc(VAR_V_32, VAR_V_33)))).
fof(ax97, axiom,
![VAR_V_36, VAR_V_37] : ((pred_attacker(VAR_V_36) & pred_attacker(VAR_V_37)) => pred_attacker(constr_dec(VAR_V_36, VAR_V_37)))).
fof(ax98, axiom,
![VAR_V_40X30, VAR_V_41] : ((pred_attacker(VAR_V_40X30) & pred_attacker(VAR_V_41)) => pred_attacker(constr_comm_enc(VAR_V_40X30, VAR_V_41)))).
fof(ax99, axiom,
![VAR_V_44, VAR_V_45] : ((pred_attacker(VAR_V_44) & pred_attacker(VAR_V_45)) => pred_attacker(constr_comm_dec(VAR_V_44, VAR_V_45)))).
fof(ax100, axiom,
pred_attacker(constr_CONST_4)).
fof(ax101, axiom,
pred_attacker(constr_CONST_3)).
fof(ax102, axiom,
pred_attacker(constr_CONST_2)).
fof(ax103, axiom,
pred_attacker(constr_CONST_1)).
fof(ax104, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax105, axiom,
pred_attacker(constr_B_STEP_1)).
fof(ax106, axiom,
pred_attacker(constr_A_STEP_3)).
fof(ax107, axiom,
pred_attacker(constr_A_STEP_2)).
fof(ax108, axiom,
pred_attacker(constr_A_STEP_1)).
fof(ax109, axiom,
![VAR_V_52, VAR_V_53] : ((pred_attacker(VAR_V_52) & pred_attacker(VAR_V_53)) => pred_attacker(tuple_2(VAR_V_52, VAR_V_53)))).
fof(ax110, axiom,
![VAR_V_60X30, VAR_V_61] : (pred_attacker(tuple_2(VAR_V_60X30, VAR_V_61)) => pred_attacker(VAR_V_60X30))).
fof(ax111, axiom,
![VAR_V_63, VAR_V_64] : (pred_attacker(tuple_2(VAR_V_63, VAR_V_64)) => pred_attacker(VAR_V_64))).
fof(ax112, axiom,
![VAR_V_66, VAR_V_67] : ((pred_mess(VAR_V_67, VAR_V_66) & pred_attacker(VAR_V_67)) => pred_attacker(VAR_V_66))).
fof(ax113, axiom,
![VAR_V_68, VAR_V_69] : ((pred_attacker(VAR_V_69) & pred_attacker(VAR_V_68)) => pred_mess(VAR_V_69, VAR_V_68))).
fof(ax114, axiom,
pred_attacker(name_c)).
fof(ax115, axiom,
![VAR_V_71] : (pred_equal(VAR_V_71, VAR_V_71))).
fof(ax116, axiom,
![VAR_V_72] : (pred_attacker(name_new0x2Dname(VAR_V_72)))).
fof(ax117, axiom,
pred_attacker(tuple_2(constr_comm_enc(name_m_9, name_Ka), constr_A_STEP_1))).
fof(ax118, axiom,
![VAR_MSG1_115] : (pred_attacker(VAR_MSG1_115) => pred_attacker(tuple_2(constr_comm_dec(VAR_MSG1_115, name_Ka), constr_A_STEP_2)))).
fof(ax119, axiom,
![VAR_MSG1_135] : (pred_attacker(VAR_MSG1_135) => pred_attacker(tuple_2(constr_enc(name_objective, name_m_9), constr_A_STEP_3)))).
fof(ax120, axiom,
![VAR_MSG1_161] : (pred_attacker(VAR_MSG1_161) => pred_attacker(tuple_2(constr_comm_enc(VAR_MSG1_161, name_Kb), constr_B_STEP_1)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
