%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_R_STEP_1).
fof(ax5, axiom,
constr_CONST_0x30 != constr_R_STEP_2).
fof(ax6, axiom,
constr_CONST_0x30 != constr_R_STEP_3).
fof(ax7, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax8, axiom,
constr_CONST_0x30 != constr_knowledge_from_1st_round_STEP_1).
fof(ax9, axiom,
constr_CONST_0x30 != constr_knowledge_from_1st_round_STEP_2).
fof(ax10, axiom,
constr_CONST_0x30 != constr_knowledge_from_1st_round_STEP_3).
fof(ax11, axiom,
constr_CONST_0x30 != name_c).
fof(ax12, axiom,
constr_CONST_0x30 != name_objective).
fof(ax13, axiom,
constr_CONST_0x30 != name_r1).
fof(ax14, axiom,
constr_CONST_0x30 != name_r1_from_1st).
fof(ax15, axiom,
constr_CONST_0x30 != name_r2_from_1st).
fof(ax16, axiom,
constr_CONST_0x30 != name_t).
fof(ax17, axiom,
constr_CONST_0x30 != name_u).
fof(ax18, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax19, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax20, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax21, axiom,
constr_CONST_1 != constr_R_STEP_1).
fof(ax22, axiom,
constr_CONST_1 != constr_R_STEP_2).
fof(ax23, axiom,
constr_CONST_1 != constr_R_STEP_3).
fof(ax24, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax25, axiom,
constr_CONST_1 != constr_knowledge_from_1st_round_STEP_1).
fof(ax26, axiom,
constr_CONST_1 != constr_knowledge_from_1st_round_STEP_2).
fof(ax27, axiom,
constr_CONST_1 != constr_knowledge_from_1st_round_STEP_3).
fof(ax28, axiom,
constr_CONST_1 != name_c).
fof(ax29, axiom,
constr_CONST_1 != name_objective).
fof(ax30, axiom,
constr_CONST_1 != name_r1).
fof(ax31, axiom,
constr_CONST_1 != name_r1_from_1st).
fof(ax32, axiom,
constr_CONST_1 != name_r2_from_1st).
fof(ax33, axiom,
constr_CONST_1 != name_t).
fof(ax34, axiom,
constr_CONST_1 != name_u).
fof(ax35, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax36, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax37, axiom,
constr_CONST_2 != constr_R_STEP_1).
fof(ax38, axiom,
constr_CONST_2 != constr_R_STEP_2).
fof(ax39, axiom,
constr_CONST_2 != constr_R_STEP_3).
fof(ax40, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax41, axiom,
constr_CONST_2 != constr_knowledge_from_1st_round_STEP_1).
fof(ax42, axiom,
constr_CONST_2 != constr_knowledge_from_1st_round_STEP_2).
fof(ax43, axiom,
constr_CONST_2 != constr_knowledge_from_1st_round_STEP_3).
fof(ax44, axiom,
constr_CONST_2 != name_c).
fof(ax45, axiom,
constr_CONST_2 != name_objective).
fof(ax46, axiom,
constr_CONST_2 != name_r1).
fof(ax47, axiom,
constr_CONST_2 != name_r1_from_1st).
fof(ax48, axiom,
constr_CONST_2 != name_r2_from_1st).
fof(ax49, axiom,
constr_CONST_2 != name_t).
fof(ax50, axiom,
constr_CONST_2 != name_u).
fof(ax51, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax52, axiom,
constr_CONST_3 != constr_R_STEP_1).
fof(ax53, axiom,
constr_CONST_3 != constr_R_STEP_2).
fof(ax54, axiom,
constr_CONST_3 != constr_R_STEP_3).
fof(ax55, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax56, axiom,
constr_CONST_3 != constr_knowledge_from_1st_round_STEP_1).
fof(ax57, axiom,
constr_CONST_3 != constr_knowledge_from_1st_round_STEP_2).
fof(ax58, axiom,
constr_CONST_3 != constr_knowledge_from_1st_round_STEP_3).
fof(ax59, axiom,
constr_CONST_3 != name_c).
fof(ax60, axiom,
constr_CONST_3 != name_objective).
fof(ax61, axiom,
constr_CONST_3 != name_r1).
fof(ax62, axiom,
constr_CONST_3 != name_r1_from_1st).
fof(ax63, axiom,
constr_CONST_3 != name_r2_from_1st).
fof(ax64, axiom,
constr_CONST_3 != name_t).
fof(ax65, axiom,
constr_CONST_3 != name_u).
fof(ax66, axiom,
constr_CONST_4 != constr_R_STEP_1).
fof(ax67, axiom,
constr_CONST_4 != constr_R_STEP_2).
fof(ax68, axiom,
constr_CONST_4 != constr_R_STEP_3).
fof(ax69, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax70, axiom,
constr_CONST_4 != constr_knowledge_from_1st_round_STEP_1).
fof(ax71, axiom,
constr_CONST_4 != constr_knowledge_from_1st_round_STEP_2).
fof(ax72, axiom,
constr_CONST_4 != constr_knowledge_from_1st_round_STEP_3).
fof(ax73, axiom,
constr_CONST_4 != name_c).
fof(ax74, axiom,
constr_CONST_4 != name_objective).
fof(ax75, axiom,
constr_CONST_4 != name_r1).
fof(ax76, axiom,
constr_CONST_4 != name_r1_from_1st).
fof(ax77, axiom,
constr_CONST_4 != name_r2_from_1st).
fof(ax78, axiom,
constr_CONST_4 != name_t).
fof(ax79, axiom,
constr_CONST_4 != name_u).
fof(ax80, axiom,
constr_R_STEP_1 != constr_R_STEP_2).
fof(ax81, axiom,
constr_R_STEP_1 != constr_R_STEP_3).
fof(ax82, axiom,
constr_R_STEP_1 != constr_ZERO).
fof(ax83, axiom,
constr_R_STEP_1 != constr_knowledge_from_1st_round_STEP_1).
fof(ax84, axiom,
constr_R_STEP_1 != constr_knowledge_from_1st_round_STEP_2).
fof(ax85, axiom,
constr_R_STEP_1 != constr_knowledge_from_1st_round_STEP_3).
fof(ax86, axiom,
constr_R_STEP_1 != name_c).
fof(ax87, axiom,
constr_R_STEP_1 != name_objective).
fof(ax88, axiom,
constr_R_STEP_1 != name_r1).
fof(ax89, axiom,
constr_R_STEP_1 != name_r1_from_1st).
fof(ax90, axiom,
constr_R_STEP_1 != name_r2_from_1st).
fof(ax91, axiom,
constr_R_STEP_1 != name_t).
fof(ax92, axiom,
constr_R_STEP_1 != name_u).
fof(ax93, axiom,
constr_R_STEP_2 != constr_R_STEP_3).
fof(ax94, axiom,
constr_R_STEP_2 != constr_ZERO).
fof(ax95, axiom,
constr_R_STEP_2 != constr_knowledge_from_1st_round_STEP_1).
fof(ax96, axiom,
constr_R_STEP_2 != constr_knowledge_from_1st_round_STEP_2).
fof(ax97, axiom,
constr_R_STEP_2 != constr_knowledge_from_1st_round_STEP_3).
fof(ax98, axiom,
constr_R_STEP_2 != name_c).
fof(ax99, axiom,
constr_R_STEP_2 != name_objective).
fof(ax100, axiom,
constr_R_STEP_2 != name_r1).
fof(ax101, axiom,
constr_R_STEP_2 != name_r1_from_1st).
fof(ax102, axiom,
constr_R_STEP_2 != name_r2_from_1st).
fof(ax103, axiom,
constr_R_STEP_2 != name_t).
fof(ax104, axiom,
constr_R_STEP_2 != name_u).
fof(ax105, axiom,
constr_R_STEP_3 != constr_ZERO).
fof(ax106, axiom,
constr_R_STEP_3 != constr_knowledge_from_1st_round_STEP_1).
fof(ax107, axiom,
constr_R_STEP_3 != constr_knowledge_from_1st_round_STEP_2).
fof(ax108, axiom,
constr_R_STEP_3 != constr_knowledge_from_1st_round_STEP_3).
fof(ax109, axiom,
constr_R_STEP_3 != name_c).
fof(ax110, axiom,
constr_R_STEP_3 != name_objective).
fof(ax111, axiom,
constr_R_STEP_3 != name_r1).
fof(ax112, axiom,
constr_R_STEP_3 != name_r1_from_1st).
fof(ax113, axiom,
constr_R_STEP_3 != name_r2_from_1st).
fof(ax114, axiom,
constr_R_STEP_3 != name_t).
fof(ax115, axiom,
constr_R_STEP_3 != name_u).
fof(ax116, axiom,
constr_ZERO != constr_knowledge_from_1st_round_STEP_1).
fof(ax117, axiom,
constr_ZERO != constr_knowledge_from_1st_round_STEP_2).
fof(ax118, axiom,
constr_ZERO != constr_knowledge_from_1st_round_STEP_3).
fof(ax119, axiom,
constr_ZERO != name_c).
fof(ax120, axiom,
constr_ZERO != name_objective).
fof(ax121, axiom,
constr_ZERO != name_r1).
fof(ax122, axiom,
constr_ZERO != name_r1_from_1st).
fof(ax123, axiom,
constr_ZERO != name_r2_from_1st).
fof(ax124, axiom,
constr_ZERO != name_t).
fof(ax125, axiom,
constr_ZERO != name_u).
fof(ax126, axiom,
constr_knowledge_from_1st_round_STEP_1 != constr_knowledge_from_1st_round_STEP_2).
fof(ax127, axiom,
constr_knowledge_from_1st_round_STEP_1 != constr_knowledge_from_1st_round_STEP_3).
fof(ax128, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_c).
fof(ax129, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_objective).
fof(ax130, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_r1).
fof(ax131, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_r1_from_1st).
fof(ax132, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_r2_from_1st).
fof(ax133, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_t).
fof(ax134, axiom,
constr_knowledge_from_1st_round_STEP_1 != name_u).
fof(ax135, axiom,
constr_knowledge_from_1st_round_STEP_2 != constr_knowledge_from_1st_round_STEP_3).
fof(ax136, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_c).
fof(ax137, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_objective).
fof(ax138, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_r1).
fof(ax139, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_r1_from_1st).
fof(ax140, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_r2_from_1st).
fof(ax141, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_t).
fof(ax142, axiom,
constr_knowledge_from_1st_round_STEP_2 != name_u).
fof(ax143, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_c).
fof(ax144, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_objective).
fof(ax145, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_r1).
fof(ax146, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_r1_from_1st).
fof(ax147, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_r2_from_1st).
fof(ax148, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_t).
fof(ax149, axiom,
constr_knowledge_from_1st_round_STEP_3 != name_u).
fof(ax150, axiom,
name_c != name_objective).
fof(ax151, axiom,
name_c != name_r1).
fof(ax152, axiom,
name_c != name_r1_from_1st).
fof(ax153, axiom,
name_c != name_r2_from_1st).
fof(ax154, axiom,
name_c != name_t).
fof(ax155, axiom,
name_c != name_u).
fof(ax156, axiom,
name_objective != name_r1).
fof(ax157, axiom,
name_objective != name_r1_from_1st).
fof(ax158, axiom,
name_objective != name_r2_from_1st).
fof(ax159, axiom,
name_objective != name_t).
fof(ax160, axiom,
name_objective != name_u).
fof(ax161, axiom,
name_r1 != name_r1_from_1st).
fof(ax162, axiom,
name_r1 != name_r2_from_1st).
fof(ax163, axiom,
name_r1 != name_t).
fof(ax164, axiom,
name_r1 != name_u).
fof(ax165, axiom,
name_r1_from_1st != name_r2_from_1st).
fof(ax166, axiom,
name_r1_from_1st != name_t).
fof(ax167, axiom,
name_r1_from_1st != name_u).
fof(ax168, axiom,
name_r2_from_1st != name_t).
fof(ax169, axiom,
name_r2_from_1st != name_u).
fof(ax170, axiom,
name_t != name_u).
fof(ax171, axiom,
![VAR_X_11] : (constr_xor(VAR_X_11, VAR_X_11) = constr_ZERO)).
fof(ax172, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, constr_ZERO) = VAR_X_10X30)).
fof(ax173, axiom,
![VAR_X_8, VAR_Y_9] : (constr_xor(VAR_X_8, VAR_Y_9) = constr_xor(VAR_Y_9, VAR_X_8))).
fof(ax174, axiom,
![VAR_X_7, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_7, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_7, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax175, axiom,
![VAR_X_27] : (pred_eq(VAR_X_27, VAR_X_27))).
fof(ax176, axiom,
![VAR_V_34, VAR_V_35] : ((pred_attacker(VAR_V_34) & pred_attacker(VAR_V_35)) => pred_attacker(constr_xor(VAR_V_34, VAR_V_35)))).
fof(ax177, axiom,
pred_attacker(tuple_true)).
fof(ax178, axiom,
pred_attacker(constr_knowledge_from_1st_round_STEP_3)).
fof(ax179, axiom,
pred_attacker(constr_knowledge_from_1st_round_STEP_2)).
fof(ax180, axiom,
pred_attacker(constr_knowledge_from_1st_round_STEP_1)).
fof(ax181, axiom,
pred_attacker(tuple_false)).
fof(ax182, axiom,
![VAR_V_39, VAR_V_40X30] : ((pred_attacker(VAR_V_39) & pred_attacker(VAR_V_40X30)) => pred_attacker(constr_f(VAR_V_39, VAR_V_40X30)))).
fof(ax183, axiom,
![VAR_V_42] : (pred_attacker(VAR_V_42) => pred_attacker(constr_cyc_shr_quart_len(VAR_V_42)))).
fof(ax184, axiom,
![VAR_V_44] : (pred_attacker(VAR_V_44) => pred_attacker(constr_cyc_shr_half_len(VAR_V_44)))).
fof(ax185, axiom,
![VAR_V_46] : (pred_attacker(VAR_V_46) => pred_attacker(constr_cyc_shl_quart_len(VAR_V_46)))).
fof(ax186, axiom,
![VAR_V_48] : (pred_attacker(VAR_V_48) => pred_attacker(constr_cyc_shl_half_len(VAR_V_48)))).
fof(ax187, axiom,
pred_attacker(constr_ZERO)).
fof(ax188, axiom,
pred_attacker(constr_R_STEP_3)).
fof(ax189, axiom,
pred_attacker(constr_R_STEP_2)).
fof(ax190, axiom,
pred_attacker(constr_R_STEP_1)).
fof(ax191, axiom,
pred_attacker(constr_CONST_4)).
fof(ax192, axiom,
pred_attacker(constr_CONST_3)).
fof(ax193, axiom,
pred_attacker(constr_CONST_2)).
fof(ax194, axiom,
pred_attacker(constr_CONST_1)).
fof(ax195, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax196, axiom,
![VAR_V_55, VAR_V_56] : ((pred_attacker(VAR_V_55) & pred_attacker(VAR_V_56)) => pred_attacker(tuple_2(VAR_V_55, VAR_V_56)))).
fof(ax197, axiom,
![VAR_V_63, VAR_V_64] : (pred_attacker(tuple_2(VAR_V_63, VAR_V_64)) => pred_attacker(VAR_V_63))).
fof(ax198, axiom,
![VAR_V_66, VAR_V_67] : (pred_attacker(tuple_2(VAR_V_66, VAR_V_67)) => pred_attacker(VAR_V_67))).
fof(ax199, axiom,
![VAR_V_69, VAR_V_70X30] : ((pred_mess(VAR_V_70X30, VAR_V_69) & pred_attacker(VAR_V_70X30)) => pred_attacker(VAR_V_69))).
fof(ax200, axiom,
![VAR_V_71, VAR_V_72] : ((pred_attacker(VAR_V_72) & pred_attacker(VAR_V_71)) => pred_mess(VAR_V_72, VAR_V_71))).
fof(ax201, axiom,
pred_attacker(name_c)).
fof(ax202, axiom,
![VAR_V_74] : (pred_equal(VAR_V_74, VAR_V_74))).
fof(ax203, axiom,
![VAR_V_75] : (pred_attacker(name_new0x2Dname(VAR_V_75)))).
fof(ax204, axiom,
pred_attacker(tuple_2(name_r1_from_1st, constr_knowledge_from_1st_round_STEP_1))).
fof(ax205, axiom,
pred_attacker(tuple_2(tuple_2(constr_xor(name_t, name_r2_from_1st), constr_f(constr_xor(name_r1_from_1st, name_r2_from_1st), name_t)), constr_knowledge_from_1st_round_STEP_2))).
fof(ax206, axiom,
pred_attacker(tuple_2(constr_xor(name_u, constr_cyc_shr_half_len(name_r2_from_1st)), constr_knowledge_from_1st_round_STEP_3))).
fof(ax207, axiom,
pred_attacker(tuple_2(name_r1, constr_R_STEP_1))).
fof(ax208, axiom,
![VAR_M1_IN_234] : (pred_attacker(tuple_2(VAR_M1_IN_234, constr_f(constr_xor(name_r1, constr_xor(VAR_M1_IN_234, name_t)), name_t))) => pred_attacker(tuple_2(constr_xor(name_u, constr_cyc_shr_half_len(constr_xor(VAR_M1_IN_234, name_t))), constr_R_STEP_2)))).
fof(ax209, axiom,
![VAR_M1_IN_246] : (pred_attacker(tuple_2(VAR_M1_IN_246, constr_f(constr_xor(name_r1, constr_xor(VAR_M1_IN_246, name_t)), name_t))) => pred_attacker(tuple_2(name_objective, constr_R_STEP_3)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
