%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax5, axiom,
constr_CONST_0x30 != name_c).
fof(ax6, axiom,
constr_CONST_0x30 != name_objective).
fof(ax7, axiom,
constr_CONST_0x30 != name_r1).
fof(ax8, axiom,
constr_CONST_0x30 != name_r1_from_1st).
fof(ax9, axiom,
constr_CONST_0x30 != name_r2_from_1st).
fof(ax10, axiom,
constr_CONST_0x30 != name_t).
fof(ax11, axiom,
constr_CONST_0x30 != name_u).
fof(ax12, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax13, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax14, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax15, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax16, axiom,
constr_CONST_1 != name_c).
fof(ax17, axiom,
constr_CONST_1 != name_objective).
fof(ax18, axiom,
constr_CONST_1 != name_r1).
fof(ax19, axiom,
constr_CONST_1 != name_r1_from_1st).
fof(ax20, axiom,
constr_CONST_1 != name_r2_from_1st).
fof(ax21, axiom,
constr_CONST_1 != name_t).
fof(ax22, axiom,
constr_CONST_1 != name_u).
fof(ax23, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax24, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax25, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax26, axiom,
constr_CONST_2 != name_c).
fof(ax27, axiom,
constr_CONST_2 != name_objective).
fof(ax28, axiom,
constr_CONST_2 != name_r1).
fof(ax29, axiom,
constr_CONST_2 != name_r1_from_1st).
fof(ax30, axiom,
constr_CONST_2 != name_r2_from_1st).
fof(ax31, axiom,
constr_CONST_2 != name_t).
fof(ax32, axiom,
constr_CONST_2 != name_u).
fof(ax33, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax34, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax35, axiom,
constr_CONST_3 != name_c).
fof(ax36, axiom,
constr_CONST_3 != name_objective).
fof(ax37, axiom,
constr_CONST_3 != name_r1).
fof(ax38, axiom,
constr_CONST_3 != name_r1_from_1st).
fof(ax39, axiom,
constr_CONST_3 != name_r2_from_1st).
fof(ax40, axiom,
constr_CONST_3 != name_t).
fof(ax41, axiom,
constr_CONST_3 != name_u).
fof(ax42, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax43, axiom,
constr_CONST_4 != name_c).
fof(ax44, axiom,
constr_CONST_4 != name_objective).
fof(ax45, axiom,
constr_CONST_4 != name_r1).
fof(ax46, axiom,
constr_CONST_4 != name_r1_from_1st).
fof(ax47, axiom,
constr_CONST_4 != name_r2_from_1st).
fof(ax48, axiom,
constr_CONST_4 != name_t).
fof(ax49, axiom,
constr_CONST_4 != name_u).
fof(ax50, axiom,
constr_ZERO != name_c).
fof(ax51, axiom,
constr_ZERO != name_objective).
fof(ax52, axiom,
constr_ZERO != name_r1).
fof(ax53, axiom,
constr_ZERO != name_r1_from_1st).
fof(ax54, axiom,
constr_ZERO != name_r2_from_1st).
fof(ax55, axiom,
constr_ZERO != name_t).
fof(ax56, axiom,
constr_ZERO != name_u).
fof(ax57, axiom,
name_c != name_objective).
fof(ax58, axiom,
name_c != name_r1).
fof(ax59, axiom,
name_c != name_r1_from_1st).
fof(ax60, axiom,
name_c != name_r2_from_1st).
fof(ax61, axiom,
name_c != name_t).
fof(ax62, axiom,
name_c != name_u).
fof(ax63, axiom,
name_objective != name_r1).
fof(ax64, axiom,
name_objective != name_r1_from_1st).
fof(ax65, axiom,
name_objective != name_r2_from_1st).
fof(ax66, axiom,
name_objective != name_t).
fof(ax67, axiom,
name_objective != name_u).
fof(ax68, axiom,
name_r1 != name_r1_from_1st).
fof(ax69, axiom,
name_r1 != name_r2_from_1st).
fof(ax70, axiom,
name_r1 != name_t).
fof(ax71, axiom,
name_r1 != name_u).
fof(ax72, axiom,
name_r1_from_1st != name_r2_from_1st).
fof(ax73, axiom,
name_r1_from_1st != name_t).
fof(ax74, axiom,
name_r1_from_1st != name_u).
fof(ax75, axiom,
name_r2_from_1st != name_t).
fof(ax76, axiom,
name_r2_from_1st != name_u).
fof(ax77, axiom,
name_t != name_u).
fof(ax78, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, VAR_X_10X30) = constr_ZERO)).
fof(ax79, axiom,
![VAR_X_9] : (constr_xor(VAR_X_9, constr_ZERO) = VAR_X_9)).
fof(ax80, axiom,
![VAR_X_7, VAR_Y_8] : (constr_xor(VAR_X_7, VAR_Y_8) = constr_xor(VAR_Y_8, VAR_X_7))).
fof(ax81, axiom,
![VAR_X_0X30, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_0X30, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_0X30, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax82, axiom,
![VAR_V_30X30, VAR_V_31] : ((pred_attacker(VAR_V_30X30) & pred_attacker(VAR_V_31)) => pred_attacker(constr_xor(VAR_V_30X30, VAR_V_31)))).
fof(ax83, axiom,
pred_attacker(tuple_true)).
fof(ax84, axiom,
![VAR_V_34] : (pred_attacker(VAR_V_34) => pred_attacker(tuple_knowledge_from_1st_round_out_3(VAR_V_34)))).
fof(ax85, axiom,
![VAR_V_37] : (pred_attacker(tuple_knowledge_from_1st_round_out_3(VAR_V_37)) => pred_attacker(VAR_V_37))).
fof(ax86, axiom,
![VAR_V_41, VAR_V_42] : ((pred_attacker(VAR_V_41) & pred_attacker(VAR_V_42)) => pred_attacker(tuple_knowledge_from_1st_round_out_2(VAR_V_41, VAR_V_42)))).
fof(ax87, axiom,
![VAR_V_49, VAR_V_50X30] : (pred_attacker(tuple_knowledge_from_1st_round_out_2(VAR_V_49, VAR_V_50X30)) => pred_attacker(VAR_V_49))).
fof(ax88, axiom,
![VAR_V_52, VAR_V_53] : (pred_attacker(tuple_knowledge_from_1st_round_out_2(VAR_V_52, VAR_V_53)) => pred_attacker(VAR_V_53))).
fof(ax89, axiom,
![VAR_V_56] : (pred_attacker(VAR_V_56) => pred_attacker(tuple_knowledge_from_1st_round_out_1(VAR_V_56)))).
fof(ax90, axiom,
![VAR_V_59] : (pred_attacker(tuple_knowledge_from_1st_round_out_1(VAR_V_59)) => pred_attacker(VAR_V_59))).
fof(ax91, axiom,
pred_attacker(tuple_false)).
fof(ax92, axiom,
![VAR_V_63, VAR_V_64] : ((pred_attacker(VAR_V_63) & pred_attacker(VAR_V_64)) => pred_attacker(constr_f(VAR_V_63, VAR_V_64)))).
fof(ax93, axiom,
![VAR_V_66] : (pred_attacker(VAR_V_66) => pred_attacker(constr_cyc_shr_quart_len(VAR_V_66)))).
fof(ax94, axiom,
![VAR_V_68] : (pred_attacker(VAR_V_68) => pred_attacker(constr_cyc_shr_half_len(VAR_V_68)))).
fof(ax95, axiom,
![VAR_V_70X30] : (pred_attacker(VAR_V_70X30) => pred_attacker(constr_cyc_shl_quart_len(VAR_V_70X30)))).
fof(ax96, axiom,
![VAR_V_72] : (pred_attacker(VAR_V_72) => pred_attacker(constr_cyc_shl_half_len(VAR_V_72)))).
fof(ax97, axiom,
pred_attacker(constr_ZERO)).
fof(ax98, axiom,
![VAR_V_74] : (pred_attacker(VAR_V_74) => pred_attacker(tuple_R_out_3(VAR_V_74)))).
fof(ax99, axiom,
![VAR_V_77] : (pred_attacker(tuple_R_out_3(VAR_V_77)) => pred_attacker(VAR_V_77))).
fof(ax100, axiom,
![VAR_V_80X30] : (pred_attacker(VAR_V_80X30) => pred_attacker(tuple_R_out_2(VAR_V_80X30)))).
fof(ax101, axiom,
![VAR_V_83] : (pred_attacker(tuple_R_out_2(VAR_V_83)) => pred_attacker(VAR_V_83))).
fof(ax102, axiom,
![VAR_V_86] : (pred_attacker(VAR_V_86) => pred_attacker(tuple_R_out_1(VAR_V_86)))).
fof(ax103, axiom,
![VAR_V_89] : (pred_attacker(tuple_R_out_1(VAR_V_89)) => pred_attacker(VAR_V_89))).
fof(ax104, axiom,
![VAR_V_93, VAR_V_94] : ((pred_attacker(VAR_V_93) & pred_attacker(VAR_V_94)) => pred_attacker(tuple_R_in_1(VAR_V_93, VAR_V_94)))).
fof(ax105, axiom,
![VAR_V_10X301, VAR_V_10X302] : (pred_attacker(tuple_R_in_1(VAR_V_10X301, VAR_V_10X302)) => pred_attacker(VAR_V_10X301))).
fof(ax106, axiom,
![VAR_V_10X304, VAR_V_10X305] : (pred_attacker(tuple_R_in_1(VAR_V_10X304, VAR_V_10X305)) => pred_attacker(VAR_V_10X305))).
fof(ax107, axiom,
pred_attacker(constr_CONST_4)).
fof(ax108, axiom,
pred_attacker(constr_CONST_3)).
fof(ax109, axiom,
pred_attacker(constr_CONST_2)).
fof(ax110, axiom,
pred_attacker(constr_CONST_1)).
fof(ax111, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax112, axiom,
![VAR_V_111, VAR_V_112] : ((pred_mess(VAR_V_112, VAR_V_111) & pred_attacker(VAR_V_112)) => pred_attacker(VAR_V_111))).
fof(ax113, axiom,
![VAR_V_113, VAR_V_114] : ((pred_attacker(VAR_V_114) & pred_attacker(VAR_V_113)) => pred_mess(VAR_V_114, VAR_V_113))).
fof(ax114, axiom,
pred_attacker(name_c)).
fof(ax115, axiom,
![VAR_V_116] : (pred_equal(VAR_V_116, VAR_V_116))).
fof(ax116, axiom,
![VAR_V_117] : (pred_attacker(name_new0x2Dname(VAR_V_117)))).
fof(ax117, axiom,
pred_attacker(tuple_knowledge_from_1st_round_out_1(name_r1_from_1st))).
fof(ax118, axiom,
pred_attacker(tuple_knowledge_from_1st_round_out_2(constr_xor(name_t, name_r2_from_1st), constr_f(constr_xor(name_r1_from_1st, name_r2_from_1st), name_t)))).
fof(ax119, axiom,
pred_attacker(tuple_knowledge_from_1st_round_out_3(constr_xor(name_u, constr_cyc_shr_half_len(name_r2_from_1st))))).
fof(ax120, axiom,
pred_attacker(tuple_R_out_1(name_r1))).
fof(ax121, axiom,
![VAR_M1_IN_244] : (pred_attacker(tuple_R_in_1(VAR_M1_IN_244, constr_f(constr_xor(name_r1, constr_xor(VAR_M1_IN_244, name_t)), name_t))) => pred_attacker(tuple_R_out_2(constr_xor(name_u, constr_cyc_shr_half_len(constr_xor(VAR_M1_IN_244, name_t))))))).
fof(ax122, axiom,
![VAR_M1_IN_250X30] : (pred_attacker(tuple_R_in_1(VAR_M1_IN_250X30, constr_f(constr_xor(name_r1, constr_xor(VAR_M1_IN_250X30, name_t)), name_t))) => pred_attacker(tuple_R_out_3(name_objective)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
