%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax5, axiom,
constr_CONST_0x30 != constr_client_A_STEP_1).
fof(ax6, axiom,
constr_CONST_0x30 != constr_client_B_STEP_1).
fof(ax7, axiom,
constr_CONST_0x30 != constr_client_B_STEP_2).
fof(ax8, axiom,
constr_CONST_0x30 != constr_server_S_STEP_1).
fof(ax9, axiom,
constr_CONST_0x30 != constr_server_S_STEP_2).
fof(ax10, axiom,
constr_CONST_0x30 != name_A).
fof(ax11, axiom,
constr_CONST_0x30 != name_B).
fof(ax12, axiom,
constr_CONST_0x30 != name_Ka).
fof(ax13, axiom,
constr_CONST_0x30 != name_Kb_21).
fof(ax14, axiom,
constr_CONST_0x30 != name_S).
fof(ax15, axiom,
constr_CONST_0x30 != name_c).
fof(ax16, axiom,
constr_CONST_0x30 != name_objective).
fof(ax17, axiom,
constr_CONST_0x30 != name_skS).
fof(ax18, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax19, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax20, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax21, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax22, axiom,
constr_CONST_1 != constr_client_A_STEP_1).
fof(ax23, axiom,
constr_CONST_1 != constr_client_B_STEP_1).
fof(ax24, axiom,
constr_CONST_1 != constr_client_B_STEP_2).
fof(ax25, axiom,
constr_CONST_1 != constr_server_S_STEP_1).
fof(ax26, axiom,
constr_CONST_1 != constr_server_S_STEP_2).
fof(ax27, axiom,
constr_CONST_1 != name_A).
fof(ax28, axiom,
constr_CONST_1 != name_B).
fof(ax29, axiom,
constr_CONST_1 != name_Ka).
fof(ax30, axiom,
constr_CONST_1 != name_Kb_21).
fof(ax31, axiom,
constr_CONST_1 != name_S).
fof(ax32, axiom,
constr_CONST_1 != name_c).
fof(ax33, axiom,
constr_CONST_1 != name_objective).
fof(ax34, axiom,
constr_CONST_1 != name_skS).
fof(ax35, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax36, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax37, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax38, axiom,
constr_CONST_2 != constr_client_A_STEP_1).
fof(ax39, axiom,
constr_CONST_2 != constr_client_B_STEP_1).
fof(ax40, axiom,
constr_CONST_2 != constr_client_B_STEP_2).
fof(ax41, axiom,
constr_CONST_2 != constr_server_S_STEP_1).
fof(ax42, axiom,
constr_CONST_2 != constr_server_S_STEP_2).
fof(ax43, axiom,
constr_CONST_2 != name_A).
fof(ax44, axiom,
constr_CONST_2 != name_B).
fof(ax45, axiom,
constr_CONST_2 != name_Ka).
fof(ax46, axiom,
constr_CONST_2 != name_Kb_21).
fof(ax47, axiom,
constr_CONST_2 != name_S).
fof(ax48, axiom,
constr_CONST_2 != name_c).
fof(ax49, axiom,
constr_CONST_2 != name_objective).
fof(ax50, axiom,
constr_CONST_2 != name_skS).
fof(ax51, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax52, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax53, axiom,
constr_CONST_3 != constr_client_A_STEP_1).
fof(ax54, axiom,
constr_CONST_3 != constr_client_B_STEP_1).
fof(ax55, axiom,
constr_CONST_3 != constr_client_B_STEP_2).
fof(ax56, axiom,
constr_CONST_3 != constr_server_S_STEP_1).
fof(ax57, axiom,
constr_CONST_3 != constr_server_S_STEP_2).
fof(ax58, axiom,
constr_CONST_3 != name_A).
fof(ax59, axiom,
constr_CONST_3 != name_B).
fof(ax60, axiom,
constr_CONST_3 != name_Ka).
fof(ax61, axiom,
constr_CONST_3 != name_Kb_21).
fof(ax62, axiom,
constr_CONST_3 != name_S).
fof(ax63, axiom,
constr_CONST_3 != name_c).
fof(ax64, axiom,
constr_CONST_3 != name_objective).
fof(ax65, axiom,
constr_CONST_3 != name_skS).
fof(ax66, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax67, axiom,
constr_CONST_4 != constr_client_A_STEP_1).
fof(ax68, axiom,
constr_CONST_4 != constr_client_B_STEP_1).
fof(ax69, axiom,
constr_CONST_4 != constr_client_B_STEP_2).
fof(ax70, axiom,
constr_CONST_4 != constr_server_S_STEP_1).
fof(ax71, axiom,
constr_CONST_4 != constr_server_S_STEP_2).
fof(ax72, axiom,
constr_CONST_4 != name_A).
fof(ax73, axiom,
constr_CONST_4 != name_B).
fof(ax74, axiom,
constr_CONST_4 != name_Ka).
fof(ax75, axiom,
constr_CONST_4 != name_Kb_21).
fof(ax76, axiom,
constr_CONST_4 != name_S).
fof(ax77, axiom,
constr_CONST_4 != name_c).
fof(ax78, axiom,
constr_CONST_4 != name_objective).
fof(ax79, axiom,
constr_CONST_4 != name_skS).
fof(ax80, axiom,
constr_ZERO != constr_client_A_STEP_1).
fof(ax81, axiom,
constr_ZERO != constr_client_B_STEP_1).
fof(ax82, axiom,
constr_ZERO != constr_client_B_STEP_2).
fof(ax83, axiom,
constr_ZERO != constr_server_S_STEP_1).
fof(ax84, axiom,
constr_ZERO != constr_server_S_STEP_2).
fof(ax85, axiom,
constr_ZERO != name_A).
fof(ax86, axiom,
constr_ZERO != name_B).
fof(ax87, axiom,
constr_ZERO != name_Ka).
fof(ax88, axiom,
constr_ZERO != name_Kb_21).
fof(ax89, axiom,
constr_ZERO != name_S).
fof(ax90, axiom,
constr_ZERO != name_c).
fof(ax91, axiom,
constr_ZERO != name_objective).
fof(ax92, axiom,
constr_ZERO != name_skS).
fof(ax93, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_1).
fof(ax94, axiom,
constr_client_A_STEP_1 != constr_client_B_STEP_2).
fof(ax95, axiom,
constr_client_A_STEP_1 != constr_server_S_STEP_1).
fof(ax96, axiom,
constr_client_A_STEP_1 != constr_server_S_STEP_2).
fof(ax97, axiom,
constr_client_A_STEP_1 != name_A).
fof(ax98, axiom,
constr_client_A_STEP_1 != name_B).
fof(ax99, axiom,
constr_client_A_STEP_1 != name_Ka).
fof(ax100, axiom,
constr_client_A_STEP_1 != name_Kb_21).
fof(ax101, axiom,
constr_client_A_STEP_1 != name_S).
fof(ax102, axiom,
constr_client_A_STEP_1 != name_c).
fof(ax103, axiom,
constr_client_A_STEP_1 != name_objective).
fof(ax104, axiom,
constr_client_A_STEP_1 != name_skS).
fof(ax105, axiom,
constr_client_B_STEP_1 != constr_client_B_STEP_2).
fof(ax106, axiom,
constr_client_B_STEP_1 != constr_server_S_STEP_1).
fof(ax107, axiom,
constr_client_B_STEP_1 != constr_server_S_STEP_2).
fof(ax108, axiom,
constr_client_B_STEP_1 != name_A).
fof(ax109, axiom,
constr_client_B_STEP_1 != name_B).
fof(ax110, axiom,
constr_client_B_STEP_1 != name_Ka).
fof(ax111, axiom,
constr_client_B_STEP_1 != name_Kb_21).
fof(ax112, axiom,
constr_client_B_STEP_1 != name_S).
fof(ax113, axiom,
constr_client_B_STEP_1 != name_c).
fof(ax114, axiom,
constr_client_B_STEP_1 != name_objective).
fof(ax115, axiom,
constr_client_B_STEP_1 != name_skS).
fof(ax116, axiom,
constr_client_B_STEP_2 != constr_server_S_STEP_1).
fof(ax117, axiom,
constr_client_B_STEP_2 != constr_server_S_STEP_2).
fof(ax118, axiom,
constr_client_B_STEP_2 != name_A).
fof(ax119, axiom,
constr_client_B_STEP_2 != name_B).
fof(ax120, axiom,
constr_client_B_STEP_2 != name_Ka).
fof(ax121, axiom,
constr_client_B_STEP_2 != name_Kb_21).
fof(ax122, axiom,
constr_client_B_STEP_2 != name_S).
fof(ax123, axiom,
constr_client_B_STEP_2 != name_c).
fof(ax124, axiom,
constr_client_B_STEP_2 != name_objective).
fof(ax125, axiom,
constr_client_B_STEP_2 != name_skS).
fof(ax126, axiom,
constr_server_S_STEP_1 != constr_server_S_STEP_2).
fof(ax127, axiom,
constr_server_S_STEP_1 != name_A).
fof(ax128, axiom,
constr_server_S_STEP_1 != name_B).
fof(ax129, axiom,
constr_server_S_STEP_1 != name_Ka).
fof(ax130, axiom,
constr_server_S_STEP_1 != name_Kb_21).
fof(ax131, axiom,
constr_server_S_STEP_1 != name_S).
fof(ax132, axiom,
constr_server_S_STEP_1 != name_c).
fof(ax133, axiom,
constr_server_S_STEP_1 != name_objective).
fof(ax134, axiom,
constr_server_S_STEP_1 != name_skS).
fof(ax135, axiom,
constr_server_S_STEP_2 != name_A).
fof(ax136, axiom,
constr_server_S_STEP_2 != name_B).
fof(ax137, axiom,
constr_server_S_STEP_2 != name_Ka).
fof(ax138, axiom,
constr_server_S_STEP_2 != name_Kb_21).
fof(ax139, axiom,
constr_server_S_STEP_2 != name_S).
fof(ax140, axiom,
constr_server_S_STEP_2 != name_c).
fof(ax141, axiom,
constr_server_S_STEP_2 != name_objective).
fof(ax142, axiom,
constr_server_S_STEP_2 != name_skS).
fof(ax143, axiom,
name_A != name_B).
fof(ax144, axiom,
name_A != name_Ka).
fof(ax145, axiom,
name_A != name_Kb_21).
fof(ax146, axiom,
name_A != name_S).
fof(ax147, axiom,
name_A != name_c).
fof(ax148, axiom,
name_A != name_objective).
fof(ax149, axiom,
name_A != name_skS).
fof(ax150, axiom,
name_B != name_Ka).
fof(ax151, axiom,
name_B != name_Kb_21).
fof(ax152, axiom,
name_B != name_S).
fof(ax153, axiom,
name_B != name_c).
fof(ax154, axiom,
name_B != name_objective).
fof(ax155, axiom,
name_B != name_skS).
fof(ax156, axiom,
name_Ka != name_Kb_21).
fof(ax157, axiom,
name_Ka != name_S).
fof(ax158, axiom,
name_Ka != name_c).
fof(ax159, axiom,
name_Ka != name_objective).
fof(ax160, axiom,
name_Ka != name_skS).
fof(ax161, axiom,
name_Kb_21 != name_S).
fof(ax162, axiom,
name_Kb_21 != name_c).
fof(ax163, axiom,
name_Kb_21 != name_objective).
fof(ax164, axiom,
name_Kb_21 != name_skS).
fof(ax165, axiom,
name_S != name_c).
fof(ax166, axiom,
name_S != name_objective).
fof(ax167, axiom,
name_S != name_skS).
fof(ax168, axiom,
name_c != name_objective).
fof(ax169, axiom,
name_c != name_skS).
fof(ax170, axiom,
name_objective != name_skS).
fof(ax171, axiom,
![VAR_X_19, VAR_Y_20X30] : (constr_div2(constr_mul(VAR_X_19, VAR_Y_20X30), VAR_X_19) = VAR_Y_20X30)).
fof(ax172, axiom,
![VAR_X_17, VAR_Y_18] : (constr_div1(constr_mul(VAR_X_17, VAR_Y_18), VAR_Y_18) = VAR_X_17)).
fof(ax173, axiom,
![VAR_K_16, VAR_X_14, VAR_Y_15] : (constr_mul(constr_aenc(VAR_X_14, VAR_K_16), constr_aenc(VAR_Y_15, VAR_K_16)) = constr_aenc(constr_mul(VAR_X_14, VAR_Y_15), VAR_K_16))).
fof(ax174, axiom,
![VAR_K_13, VAR_M_12] : (constr_dec(constr_enc(VAR_M_12, VAR_K_13), VAR_K_13) = VAR_M_12)).
fof(ax175, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_adec(constr_aenc(VAR_M_0X30, constr_pkey(VAR_K_0X30)), VAR_K_0X30) = VAR_M_0X30)).
fof(ax176, axiom,
![VAR_X_11] : (constr_xor(VAR_X_11, VAR_X_11) = constr_ZERO)).
fof(ax177, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, constr_ZERO) = VAR_X_10X30)).
fof(ax178, axiom,
![VAR_X_8, VAR_Y_9] : (constr_xor(VAR_X_8, VAR_Y_9) = constr_xor(VAR_Y_9, VAR_X_8))).
fof(ax179, axiom,
![VAR_X_7, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_7, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_7, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax180, axiom,
![VAR_X_36] : (pred_eq(VAR_X_36, VAR_X_36))).
fof(ax181, axiom,
![VAR_V_43, VAR_V_44] : ((pred_attacker(VAR_V_43) & pred_attacker(VAR_V_44)) => pred_attacker(constr_xor(VAR_V_43, VAR_V_44)))).
fof(ax182, axiom,
pred_attacker(tuple_true)).
fof(ax183, axiom,
pred_attacker(constr_server_S_STEP_2)).
fof(ax184, axiom,
pred_attacker(constr_server_S_STEP_1)).
fof(ax185, axiom,
![VAR_V_46] : (pred_attacker(VAR_V_46) => pred_attacker(constr_pkey(VAR_V_46)))).
fof(ax186, axiom,
![VAR_V_50X30, VAR_V_51] : ((pred_attacker(VAR_V_50X30) & pred_attacker(VAR_V_51)) => pred_attacker(constr_mul(VAR_V_50X30, VAR_V_51)))).
fof(ax187, axiom,
pred_attacker(tuple_false)).
fof(ax188, axiom,
![VAR_V_54, VAR_V_55] : ((pred_attacker(VAR_V_54) & pred_attacker(VAR_V_55)) => pred_attacker(constr_enc(VAR_V_54, VAR_V_55)))).
fof(ax189, axiom,
![VAR_V_58, VAR_V_59] : ((pred_attacker(VAR_V_58) & pred_attacker(VAR_V_59)) => pred_attacker(constr_div2(VAR_V_58, VAR_V_59)))).
fof(ax190, axiom,
![VAR_V_62, VAR_V_63] : ((pred_attacker(VAR_V_62) & pred_attacker(VAR_V_63)) => pred_attacker(constr_div1(VAR_V_62, VAR_V_63)))).
fof(ax191, axiom,
![VAR_V_66, VAR_V_67] : ((pred_attacker(VAR_V_66) & pred_attacker(VAR_V_67)) => pred_attacker(constr_dec(VAR_V_66, VAR_V_67)))).
fof(ax192, axiom,
pred_attacker(constr_client_B_STEP_2)).
fof(ax193, axiom,
pred_attacker(constr_client_B_STEP_1)).
fof(ax194, axiom,
pred_attacker(constr_client_A_STEP_1)).
fof(ax195, axiom,
![VAR_V_70X30, VAR_V_71] : ((pred_attacker(VAR_V_70X30) & pred_attacker(VAR_V_71)) => pred_attacker(constr_aenc(VAR_V_70X30, VAR_V_71)))).
fof(ax196, axiom,
![VAR_V_74, VAR_V_75] : ((pred_attacker(VAR_V_74) & pred_attacker(VAR_V_75)) => pred_attacker(constr_adec(VAR_V_74, VAR_V_75)))).
fof(ax197, axiom,
pred_attacker(constr_ZERO)).
fof(ax198, axiom,
pred_attacker(constr_CONST_4)).
fof(ax199, axiom,
pred_attacker(constr_CONST_3)).
fof(ax200, axiom,
pred_attacker(constr_CONST_2)).
fof(ax201, axiom,
pred_attacker(constr_CONST_1)).
fof(ax202, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax203, axiom,
![VAR_V_82, VAR_V_83] : ((pred_attacker(VAR_V_82) & pred_attacker(VAR_V_83)) => pred_attacker(tuple_2(VAR_V_82, VAR_V_83)))).
fof(ax204, axiom,
![VAR_V_90X30, VAR_V_91] : (pred_attacker(tuple_2(VAR_V_90X30, VAR_V_91)) => pred_attacker(VAR_V_90X30))).
fof(ax205, axiom,
![VAR_V_93, VAR_V_94] : (pred_attacker(tuple_2(VAR_V_93, VAR_V_94)) => pred_attacker(VAR_V_94))).
fof(ax206, axiom,
![VAR_V_96, VAR_V_97] : ((pred_mess(VAR_V_97, VAR_V_96) & pred_attacker(VAR_V_97)) => pred_attacker(VAR_V_96))).
fof(ax207, axiom,
![VAR_V_98, VAR_V_99] : ((pred_attacker(VAR_V_99) & pred_attacker(VAR_V_98)) => pred_mess(VAR_V_99, VAR_V_98))).
fof(ax208, axiom,
pred_attacker(name_c)).
fof(ax209, axiom,
pred_attacker(name_S)).
fof(ax210, axiom,
pred_attacker(name_B)).
fof(ax211, axiom,
pred_attacker(name_A)).
fof(ax212, axiom,
![VAR_V_10X301] : (pred_equal(VAR_V_10X301, VAR_V_10X301))).
fof(ax213, axiom,
![VAR_V_10X302] : (pred_attacker(name_new0x2Dname(VAR_V_10X302)))).
fof(ax214, axiom,
pred_attacker(tuple_2(tuple_2(name_B, constr_aenc(name_Ka, constr_pkey(name_skS))), constr_client_A_STEP_1))).
fof(ax215, axiom,
pred_attacker(name_A) => pred_attacker(tuple_2(tuple_2(name_A, constr_aenc(name_Kb_21, constr_pkey(name_skS))), constr_client_B_STEP_1))).
fof(ax216, axiom,
![VAR_KB_XOR_KA_218] : ((pred_attacker(tuple_2(name_B, VAR_KB_XOR_KA_218)) & pred_attacker(name_A)) => pred_attacker(tuple_2(constr_enc(name_objective, name_Kb_21), constr_client_B_STEP_2)))).
fof(ax217, axiom,
![VAR_ENC_KA_PKS_247] : (pred_attacker(tuple_2(name_B, VAR_ENC_KA_PKS_247)) => pred_attacker(tuple_2(name_A, constr_server_S_STEP_1)))).
fof(ax218, axiom,
![VAR_ENC_KA_PKS_289, VAR_ENC_KB_PKS_288] : ((pred_attacker(tuple_2(name_A, VAR_ENC_KB_PKS_288)) & pred_attacker(tuple_2(name_B, VAR_ENC_KA_PKS_289))) => pred_attacker(tuple_2(tuple_2(name_B, constr_xor(constr_adec(VAR_ENC_KB_PKS_288, name_skS), constr_adec(VAR_ENC_KA_PKS_289, name_skS))), constr_server_S_STEP_2)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
