%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax5, axiom,
constr_CONST_0x30 != constr_server_S_STEP_1).
fof(ax6, axiom,
constr_CONST_0x30 != constr_server_S_STEP_2).
fof(ax7, axiom,
constr_CONST_0x30 != constr_session_i_STEP_1).
fof(ax8, axiom,
constr_CONST_0x30 != constr_session_i_STEP_2).
fof(ax9, axiom,
constr_CONST_0x30 != constr_session_i_STEP_3).
fof(ax10, axiom,
constr_CONST_0x30 != constr_session_i_STEP_4).
fof(ax11, axiom,
constr_CONST_0x30 != constr_session_i_STEP_5).
fof(ax12, axiom,
constr_CONST_0x30 != name_A).
fof(ax13, axiom,
constr_CONST_0x30 != name_B).
fof(ax14, axiom,
constr_CONST_0x30 != name_Ka).
fof(ax15, axiom,
constr_CONST_0x30 != name_Kb).
fof(ax16, axiom,
constr_CONST_0x30 != name_S).
fof(ax17, axiom,
constr_CONST_0x30 != name_c).
fof(ax18, axiom,
constr_CONST_0x30 != name_objective).
fof(ax19, axiom,
constr_CONST_0x30 != name_skS).
fof(ax20, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax21, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax22, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax23, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax24, axiom,
constr_CONST_1 != constr_server_S_STEP_1).
fof(ax25, axiom,
constr_CONST_1 != constr_server_S_STEP_2).
fof(ax26, axiom,
constr_CONST_1 != constr_session_i_STEP_1).
fof(ax27, axiom,
constr_CONST_1 != constr_session_i_STEP_2).
fof(ax28, axiom,
constr_CONST_1 != constr_session_i_STEP_3).
fof(ax29, axiom,
constr_CONST_1 != constr_session_i_STEP_4).
fof(ax30, axiom,
constr_CONST_1 != constr_session_i_STEP_5).
fof(ax31, axiom,
constr_CONST_1 != name_A).
fof(ax32, axiom,
constr_CONST_1 != name_B).
fof(ax33, axiom,
constr_CONST_1 != name_Ka).
fof(ax34, axiom,
constr_CONST_1 != name_Kb).
fof(ax35, axiom,
constr_CONST_1 != name_S).
fof(ax36, axiom,
constr_CONST_1 != name_c).
fof(ax37, axiom,
constr_CONST_1 != name_objective).
fof(ax38, axiom,
constr_CONST_1 != name_skS).
fof(ax39, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax40, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax41, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax42, axiom,
constr_CONST_2 != constr_server_S_STEP_1).
fof(ax43, axiom,
constr_CONST_2 != constr_server_S_STEP_2).
fof(ax44, axiom,
constr_CONST_2 != constr_session_i_STEP_1).
fof(ax45, axiom,
constr_CONST_2 != constr_session_i_STEP_2).
fof(ax46, axiom,
constr_CONST_2 != constr_session_i_STEP_3).
fof(ax47, axiom,
constr_CONST_2 != constr_session_i_STEP_4).
fof(ax48, axiom,
constr_CONST_2 != constr_session_i_STEP_5).
fof(ax49, axiom,
constr_CONST_2 != name_A).
fof(ax50, axiom,
constr_CONST_2 != name_B).
fof(ax51, axiom,
constr_CONST_2 != name_Ka).
fof(ax52, axiom,
constr_CONST_2 != name_Kb).
fof(ax53, axiom,
constr_CONST_2 != name_S).
fof(ax54, axiom,
constr_CONST_2 != name_c).
fof(ax55, axiom,
constr_CONST_2 != name_objective).
fof(ax56, axiom,
constr_CONST_2 != name_skS).
fof(ax57, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax58, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax59, axiom,
constr_CONST_3 != constr_server_S_STEP_1).
fof(ax60, axiom,
constr_CONST_3 != constr_server_S_STEP_2).
fof(ax61, axiom,
constr_CONST_3 != constr_session_i_STEP_1).
fof(ax62, axiom,
constr_CONST_3 != constr_session_i_STEP_2).
fof(ax63, axiom,
constr_CONST_3 != constr_session_i_STEP_3).
fof(ax64, axiom,
constr_CONST_3 != constr_session_i_STEP_4).
fof(ax65, axiom,
constr_CONST_3 != constr_session_i_STEP_5).
fof(ax66, axiom,
constr_CONST_3 != name_A).
fof(ax67, axiom,
constr_CONST_3 != name_B).
fof(ax68, axiom,
constr_CONST_3 != name_Ka).
fof(ax69, axiom,
constr_CONST_3 != name_Kb).
fof(ax70, axiom,
constr_CONST_3 != name_S).
fof(ax71, axiom,
constr_CONST_3 != name_c).
fof(ax72, axiom,
constr_CONST_3 != name_objective).
fof(ax73, axiom,
constr_CONST_3 != name_skS).
fof(ax74, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax75, axiom,
constr_CONST_4 != constr_server_S_STEP_1).
fof(ax76, axiom,
constr_CONST_4 != constr_server_S_STEP_2).
fof(ax77, axiom,
constr_CONST_4 != constr_session_i_STEP_1).
fof(ax78, axiom,
constr_CONST_4 != constr_session_i_STEP_2).
fof(ax79, axiom,
constr_CONST_4 != constr_session_i_STEP_3).
fof(ax80, axiom,
constr_CONST_4 != constr_session_i_STEP_4).
fof(ax81, axiom,
constr_CONST_4 != constr_session_i_STEP_5).
fof(ax82, axiom,
constr_CONST_4 != name_A).
fof(ax83, axiom,
constr_CONST_4 != name_B).
fof(ax84, axiom,
constr_CONST_4 != name_Ka).
fof(ax85, axiom,
constr_CONST_4 != name_Kb).
fof(ax86, axiom,
constr_CONST_4 != name_S).
fof(ax87, axiom,
constr_CONST_4 != name_c).
fof(ax88, axiom,
constr_CONST_4 != name_objective).
fof(ax89, axiom,
constr_CONST_4 != name_skS).
fof(ax90, axiom,
constr_ZERO != constr_server_S_STEP_1).
fof(ax91, axiom,
constr_ZERO != constr_server_S_STEP_2).
fof(ax92, axiom,
constr_ZERO != constr_session_i_STEP_1).
fof(ax93, axiom,
constr_ZERO != constr_session_i_STEP_2).
fof(ax94, axiom,
constr_ZERO != constr_session_i_STEP_3).
fof(ax95, axiom,
constr_ZERO != constr_session_i_STEP_4).
fof(ax96, axiom,
constr_ZERO != constr_session_i_STEP_5).
fof(ax97, axiom,
constr_ZERO != name_A).
fof(ax98, axiom,
constr_ZERO != name_B).
fof(ax99, axiom,
constr_ZERO != name_Ka).
fof(ax100, axiom,
constr_ZERO != name_Kb).
fof(ax101, axiom,
constr_ZERO != name_S).
fof(ax102, axiom,
constr_ZERO != name_c).
fof(ax103, axiom,
constr_ZERO != name_objective).
fof(ax104, axiom,
constr_ZERO != name_skS).
fof(ax105, axiom,
constr_server_S_STEP_1 != constr_server_S_STEP_2).
fof(ax106, axiom,
constr_server_S_STEP_1 != constr_session_i_STEP_1).
fof(ax107, axiom,
constr_server_S_STEP_1 != constr_session_i_STEP_2).
fof(ax108, axiom,
constr_server_S_STEP_1 != constr_session_i_STEP_3).
fof(ax109, axiom,
constr_server_S_STEP_1 != constr_session_i_STEP_4).
fof(ax110, axiom,
constr_server_S_STEP_1 != constr_session_i_STEP_5).
fof(ax111, axiom,
constr_server_S_STEP_1 != name_A).
fof(ax112, axiom,
constr_server_S_STEP_1 != name_B).
fof(ax113, axiom,
constr_server_S_STEP_1 != name_Ka).
fof(ax114, axiom,
constr_server_S_STEP_1 != name_Kb).
fof(ax115, axiom,
constr_server_S_STEP_1 != name_S).
fof(ax116, axiom,
constr_server_S_STEP_1 != name_c).
fof(ax117, axiom,
constr_server_S_STEP_1 != name_objective).
fof(ax118, axiom,
constr_server_S_STEP_1 != name_skS).
fof(ax119, axiom,
constr_server_S_STEP_2 != constr_session_i_STEP_1).
fof(ax120, axiom,
constr_server_S_STEP_2 != constr_session_i_STEP_2).
fof(ax121, axiom,
constr_server_S_STEP_2 != constr_session_i_STEP_3).
fof(ax122, axiom,
constr_server_S_STEP_2 != constr_session_i_STEP_4).
fof(ax123, axiom,
constr_server_S_STEP_2 != constr_session_i_STEP_5).
fof(ax124, axiom,
constr_server_S_STEP_2 != name_A).
fof(ax125, axiom,
constr_server_S_STEP_2 != name_B).
fof(ax126, axiom,
constr_server_S_STEP_2 != name_Ka).
fof(ax127, axiom,
constr_server_S_STEP_2 != name_Kb).
fof(ax128, axiom,
constr_server_S_STEP_2 != name_S).
fof(ax129, axiom,
constr_server_S_STEP_2 != name_c).
fof(ax130, axiom,
constr_server_S_STEP_2 != name_objective).
fof(ax131, axiom,
constr_server_S_STEP_2 != name_skS).
fof(ax132, axiom,
constr_session_i_STEP_1 != constr_session_i_STEP_2).
fof(ax133, axiom,
constr_session_i_STEP_1 != constr_session_i_STEP_3).
fof(ax134, axiom,
constr_session_i_STEP_1 != constr_session_i_STEP_4).
fof(ax135, axiom,
constr_session_i_STEP_1 != constr_session_i_STEP_5).
fof(ax136, axiom,
constr_session_i_STEP_1 != name_A).
fof(ax137, axiom,
constr_session_i_STEP_1 != name_B).
fof(ax138, axiom,
constr_session_i_STEP_1 != name_Ka).
fof(ax139, axiom,
constr_session_i_STEP_1 != name_Kb).
fof(ax140, axiom,
constr_session_i_STEP_1 != name_S).
fof(ax141, axiom,
constr_session_i_STEP_1 != name_c).
fof(ax142, axiom,
constr_session_i_STEP_1 != name_objective).
fof(ax143, axiom,
constr_session_i_STEP_1 != name_skS).
fof(ax144, axiom,
constr_session_i_STEP_2 != constr_session_i_STEP_3).
fof(ax145, axiom,
constr_session_i_STEP_2 != constr_session_i_STEP_4).
fof(ax146, axiom,
constr_session_i_STEP_2 != constr_session_i_STEP_5).
fof(ax147, axiom,
constr_session_i_STEP_2 != name_A).
fof(ax148, axiom,
constr_session_i_STEP_2 != name_B).
fof(ax149, axiom,
constr_session_i_STEP_2 != name_Ka).
fof(ax150, axiom,
constr_session_i_STEP_2 != name_Kb).
fof(ax151, axiom,
constr_session_i_STEP_2 != name_S).
fof(ax152, axiom,
constr_session_i_STEP_2 != name_c).
fof(ax153, axiom,
constr_session_i_STEP_2 != name_objective).
fof(ax154, axiom,
constr_session_i_STEP_2 != name_skS).
fof(ax155, axiom,
constr_session_i_STEP_3 != constr_session_i_STEP_4).
fof(ax156, axiom,
constr_session_i_STEP_3 != constr_session_i_STEP_5).
fof(ax157, axiom,
constr_session_i_STEP_3 != name_A).
fof(ax158, axiom,
constr_session_i_STEP_3 != name_B).
fof(ax159, axiom,
constr_session_i_STEP_3 != name_Ka).
fof(ax160, axiom,
constr_session_i_STEP_3 != name_Kb).
fof(ax161, axiom,
constr_session_i_STEP_3 != name_S).
fof(ax162, axiom,
constr_session_i_STEP_3 != name_c).
fof(ax163, axiom,
constr_session_i_STEP_3 != name_objective).
fof(ax164, axiom,
constr_session_i_STEP_3 != name_skS).
fof(ax165, axiom,
constr_session_i_STEP_4 != constr_session_i_STEP_5).
fof(ax166, axiom,
constr_session_i_STEP_4 != name_A).
fof(ax167, axiom,
constr_session_i_STEP_4 != name_B).
fof(ax168, axiom,
constr_session_i_STEP_4 != name_Ka).
fof(ax169, axiom,
constr_session_i_STEP_4 != name_Kb).
fof(ax170, axiom,
constr_session_i_STEP_4 != name_S).
fof(ax171, axiom,
constr_session_i_STEP_4 != name_c).
fof(ax172, axiom,
constr_session_i_STEP_4 != name_objective).
fof(ax173, axiom,
constr_session_i_STEP_4 != name_skS).
fof(ax174, axiom,
constr_session_i_STEP_5 != name_A).
fof(ax175, axiom,
constr_session_i_STEP_5 != name_B).
fof(ax176, axiom,
constr_session_i_STEP_5 != name_Ka).
fof(ax177, axiom,
constr_session_i_STEP_5 != name_Kb).
fof(ax178, axiom,
constr_session_i_STEP_5 != name_S).
fof(ax179, axiom,
constr_session_i_STEP_5 != name_c).
fof(ax180, axiom,
constr_session_i_STEP_5 != name_objective).
fof(ax181, axiom,
constr_session_i_STEP_5 != name_skS).
fof(ax182, axiom,
name_A != name_B).
fof(ax183, axiom,
name_A != name_Ka).
fof(ax184, axiom,
name_A != name_Kb).
fof(ax185, axiom,
name_A != name_S).
fof(ax186, axiom,
name_A != name_c).
fof(ax187, axiom,
name_A != name_objective).
fof(ax188, axiom,
name_A != name_skS).
fof(ax189, axiom,
name_B != name_Ka).
fof(ax190, axiom,
name_B != name_Kb).
fof(ax191, axiom,
name_B != name_S).
fof(ax192, axiom,
name_B != name_c).
fof(ax193, axiom,
name_B != name_objective).
fof(ax194, axiom,
name_B != name_skS).
fof(ax195, axiom,
name_Ka != name_Kb).
fof(ax196, axiom,
name_Ka != name_S).
fof(ax197, axiom,
name_Ka != name_c).
fof(ax198, axiom,
name_Ka != name_objective).
fof(ax199, axiom,
name_Ka != name_skS).
fof(ax200, axiom,
name_Kb != name_S).
fof(ax201, axiom,
name_Kb != name_c).
fof(ax202, axiom,
name_Kb != name_objective).
fof(ax203, axiom,
name_Kb != name_skS).
fof(ax204, axiom,
name_S != name_c).
fof(ax205, axiom,
name_S != name_objective).
fof(ax206, axiom,
name_S != name_skS).
fof(ax207, axiom,
name_c != name_objective).
fof(ax208, axiom,
name_c != name_skS).
fof(ax209, axiom,
name_objective != name_skS).
fof(ax210, axiom,
![VAR_X_19, VAR_Y_20X30] : (constr_div2(constr_mul(VAR_X_19, VAR_Y_20X30), VAR_X_19) = VAR_Y_20X30)).
fof(ax211, axiom,
![VAR_X_17, VAR_Y_18] : (constr_div1(constr_mul(VAR_X_17, VAR_Y_18), VAR_Y_18) = VAR_X_17)).
fof(ax212, axiom,
![VAR_K_16, VAR_X_14, VAR_Y_15] : (constr_mul(constr_pk_enc(VAR_X_14, VAR_K_16), constr_pk_enc(VAR_Y_15, VAR_K_16)) = constr_pk_enc(constr_mul(VAR_X_14, VAR_Y_15), VAR_K_16))).
fof(ax213, axiom,
![VAR_K_13, VAR_M_12] : (constr_dec(constr_enc(VAR_M_12, VAR_K_13), VAR_K_13) = VAR_M_12)).
fof(ax214, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_pk_dec(constr_pk_enc(VAR_M_0X30, constr_pkey(VAR_K_0X30)), VAR_K_0X30) = VAR_M_0X30)).
fof(ax215, axiom,
![VAR_X_11] : (constr_xor(VAR_X_11, VAR_X_11) = constr_ZERO)).
fof(ax216, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, constr_ZERO) = VAR_X_10X30)).
fof(ax217, axiom,
![VAR_X_8, VAR_Y_9] : (constr_xor(VAR_X_8, VAR_Y_9) = constr_xor(VAR_Y_9, VAR_X_8))).
fof(ax218, axiom,
![VAR_X_7, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_7, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_7, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax219, axiom,
![VAR_X_34] : (pred_eq(VAR_X_34, VAR_X_34))).
fof(ax220, axiom,
![VAR_V_41, VAR_V_42] : ((pred_attacker(VAR_V_41) & pred_attacker(VAR_V_42)) => pred_attacker(constr_xor(VAR_V_41, VAR_V_42)))).
fof(ax221, axiom,
pred_attacker(tuple_true)).
fof(ax222, axiom,
pred_attacker(constr_session_i_STEP_5)).
fof(ax223, axiom,
pred_attacker(constr_session_i_STEP_4)).
fof(ax224, axiom,
pred_attacker(constr_session_i_STEP_3)).
fof(ax225, axiom,
pred_attacker(constr_session_i_STEP_2)).
fof(ax226, axiom,
pred_attacker(constr_session_i_STEP_1)).
fof(ax227, axiom,
pred_attacker(constr_server_S_STEP_2)).
fof(ax228, axiom,
pred_attacker(constr_server_S_STEP_1)).
fof(ax229, axiom,
![VAR_V_44] : (pred_attacker(VAR_V_44) => pred_attacker(constr_pkey(VAR_V_44)))).
fof(ax230, axiom,
![VAR_V_47, VAR_V_48] : ((pred_attacker(VAR_V_47) & pred_attacker(VAR_V_48)) => pred_attacker(constr_pk_enc(VAR_V_47, VAR_V_48)))).
fof(ax231, axiom,
![VAR_V_51, VAR_V_52] : ((pred_attacker(VAR_V_51) & pred_attacker(VAR_V_52)) => pred_attacker(constr_pk_dec(VAR_V_51, VAR_V_52)))).
fof(ax232, axiom,
![VAR_V_56, VAR_V_57] : ((pred_attacker(VAR_V_56) & pred_attacker(VAR_V_57)) => pred_attacker(constr_mul(VAR_V_56, VAR_V_57)))).
fof(ax233, axiom,
pred_attacker(tuple_false)).
fof(ax234, axiom,
![VAR_V_60X30, VAR_V_61] : ((pred_attacker(VAR_V_60X30) & pred_attacker(VAR_V_61)) => pred_attacker(constr_enc(VAR_V_60X30, VAR_V_61)))).
fof(ax235, axiom,
![VAR_V_64, VAR_V_65] : ((pred_attacker(VAR_V_64) & pred_attacker(VAR_V_65)) => pred_attacker(constr_div2(VAR_V_64, VAR_V_65)))).
fof(ax236, axiom,
![VAR_V_68, VAR_V_69] : ((pred_attacker(VAR_V_68) & pred_attacker(VAR_V_69)) => pred_attacker(constr_div1(VAR_V_68, VAR_V_69)))).
fof(ax237, axiom,
![VAR_V_72, VAR_V_73] : ((pred_attacker(VAR_V_72) & pred_attacker(VAR_V_73)) => pred_attacker(constr_dec(VAR_V_72, VAR_V_73)))).
fof(ax238, axiom,
pred_attacker(constr_ZERO)).
fof(ax239, axiom,
pred_attacker(constr_CONST_4)).
fof(ax240, axiom,
pred_attacker(constr_CONST_3)).
fof(ax241, axiom,
pred_attacker(constr_CONST_2)).
fof(ax242, axiom,
pred_attacker(constr_CONST_1)).
fof(ax243, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax244, axiom,
![VAR_V_80X30, VAR_V_81] : ((pred_attacker(VAR_V_80X30) & pred_attacker(VAR_V_81)) => pred_attacker(tuple_2(VAR_V_80X30, VAR_V_81)))).
fof(ax245, axiom,
![VAR_V_88, VAR_V_89] : (pred_attacker(tuple_2(VAR_V_88, VAR_V_89)) => pred_attacker(VAR_V_88))).
fof(ax246, axiom,
![VAR_V_91, VAR_V_92] : (pred_attacker(tuple_2(VAR_V_91, VAR_V_92)) => pred_attacker(VAR_V_92))).
fof(ax247, axiom,
![VAR_V_94, VAR_V_95] : ((pred_mess(VAR_V_95, VAR_V_94) & pred_attacker(VAR_V_95)) => pred_attacker(VAR_V_94))).
fof(ax248, axiom,
![VAR_V_96, VAR_V_97] : ((pred_attacker(VAR_V_97) & pred_attacker(VAR_V_96)) => pred_mess(VAR_V_97, VAR_V_96))).
fof(ax249, axiom,
pred_attacker(name_c)).
fof(ax250, axiom,
pred_attacker(name_S)).
fof(ax251, axiom,
pred_attacker(name_B)).
fof(ax252, axiom,
pred_attacker(name_A)).
fof(ax253, axiom,
![VAR_V_99] : (pred_equal(VAR_V_99, VAR_V_99))).
fof(ax254, axiom,
![VAR_V_10X300X30] : (pred_attacker(name_new0x2Dname(VAR_V_10X300X30)))).
fof(ax255, axiom,
pred_attacker(tuple_2(tuple_2(name_B, constr_pk_enc(name_Ka, constr_pkey(name_skS))), constr_session_i_STEP_1))).
fof(ax256, axiom,
pred_attacker(tuple_2(name_A, constr_session_i_STEP_2))).
fof(ax257, axiom,
pred_attacker(tuple_2(tuple_2(name_A, constr_pk_enc(name_Kb, constr_pkey(name_skS))), constr_session_i_STEP_3))).
fof(ax258, axiom,
pred_attacker(tuple_2(tuple_2(name_B, constr_xor(name_Kb, name_Ka)), constr_session_i_STEP_4))).
fof(ax259, axiom,
pred_attacker(tuple_2(constr_enc(name_objective, name_Kb), constr_session_i_STEP_5))).
fof(ax260, axiom,
![VAR_ENC_KA_PKS_254] : (pred_attacker(tuple_2(name_B, VAR_ENC_KA_PKS_254)) => pred_attacker(tuple_2(name_A, constr_server_S_STEP_1)))).
fof(ax261, axiom,
![VAR_ENC_KA_PKS_288, VAR_ENC_KB_PKS_287] : ((pred_attacker(tuple_2(name_A, VAR_ENC_KB_PKS_287)) & pred_attacker(tuple_2(name_B, VAR_ENC_KA_PKS_288))) => pred_attacker(tuple_2(constr_xor(constr_pk_dec(VAR_ENC_KB_PKS_287, name_skS), constr_pk_dec(VAR_ENC_KA_PKS_288, name_skS)), constr_server_S_STEP_2)))).
fof(co0, conjecture,
pred_attacker(name_objective)).
