%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax5, axiom,
constr_CONST_0x30 != name_A).
fof(ax6, axiom,
constr_CONST_0x30 != name_B).
fof(ax7, axiom,
constr_CONST_0x30 != name_Ka).
fof(ax8, axiom,
constr_CONST_0x30 != name_Kb).
fof(ax9, axiom,
constr_CONST_0x30 != name_S).
fof(ax10, axiom,
constr_CONST_0x30 != name_c).
fof(ax11, axiom,
constr_CONST_0x30 != name_objective).
fof(ax12, axiom,
constr_CONST_0x30 != name_skS).
fof(ax13, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax14, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax15, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax16, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax17, axiom,
constr_CONST_1 != name_A).
fof(ax18, axiom,
constr_CONST_1 != name_B).
fof(ax19, axiom,
constr_CONST_1 != name_Ka).
fof(ax20, axiom,
constr_CONST_1 != name_Kb).
fof(ax21, axiom,
constr_CONST_1 != name_S).
fof(ax22, axiom,
constr_CONST_1 != name_c).
fof(ax23, axiom,
constr_CONST_1 != name_objective).
fof(ax24, axiom,
constr_CONST_1 != name_skS).
fof(ax25, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax26, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax27, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax28, axiom,
constr_CONST_2 != name_A).
fof(ax29, axiom,
constr_CONST_2 != name_B).
fof(ax30, axiom,
constr_CONST_2 != name_Ka).
fof(ax31, axiom,
constr_CONST_2 != name_Kb).
fof(ax32, axiom,
constr_CONST_2 != name_S).
fof(ax33, axiom,
constr_CONST_2 != name_c).
fof(ax34, axiom,
constr_CONST_2 != name_objective).
fof(ax35, axiom,
constr_CONST_2 != name_skS).
fof(ax36, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax37, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax38, axiom,
constr_CONST_3 != name_A).
fof(ax39, axiom,
constr_CONST_3 != name_B).
fof(ax40, axiom,
constr_CONST_3 != name_Ka).
fof(ax41, axiom,
constr_CONST_3 != name_Kb).
fof(ax42, axiom,
constr_CONST_3 != name_S).
fof(ax43, axiom,
constr_CONST_3 != name_c).
fof(ax44, axiom,
constr_CONST_3 != name_objective).
fof(ax45, axiom,
constr_CONST_3 != name_skS).
fof(ax46, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax47, axiom,
constr_CONST_4 != name_A).
fof(ax48, axiom,
constr_CONST_4 != name_B).
fof(ax49, axiom,
constr_CONST_4 != name_Ka).
fof(ax50, axiom,
constr_CONST_4 != name_Kb).
fof(ax51, axiom,
constr_CONST_4 != name_S).
fof(ax52, axiom,
constr_CONST_4 != name_c).
fof(ax53, axiom,
constr_CONST_4 != name_objective).
fof(ax54, axiom,
constr_CONST_4 != name_skS).
fof(ax55, axiom,
constr_ZERO != name_A).
fof(ax56, axiom,
constr_ZERO != name_B).
fof(ax57, axiom,
constr_ZERO != name_Ka).
fof(ax58, axiom,
constr_ZERO != name_Kb).
fof(ax59, axiom,
constr_ZERO != name_S).
fof(ax60, axiom,
constr_ZERO != name_c).
fof(ax61, axiom,
constr_ZERO != name_objective).
fof(ax62, axiom,
constr_ZERO != name_skS).
fof(ax63, axiom,
name_A != name_B).
fof(ax64, axiom,
name_A != name_Ka).
fof(ax65, axiom,
name_A != name_Kb).
fof(ax66, axiom,
name_A != name_S).
fof(ax67, axiom,
name_A != name_c).
fof(ax68, axiom,
name_A != name_objective).
fof(ax69, axiom,
name_A != name_skS).
fof(ax70, axiom,
name_B != name_Ka).
fof(ax71, axiom,
name_B != name_Kb).
fof(ax72, axiom,
name_B != name_S).
fof(ax73, axiom,
name_B != name_c).
fof(ax74, axiom,
name_B != name_objective).
fof(ax75, axiom,
name_B != name_skS).
fof(ax76, axiom,
name_Ka != name_Kb).
fof(ax77, axiom,
name_Ka != name_S).
fof(ax78, axiom,
name_Ka != name_c).
fof(ax79, axiom,
name_Ka != name_objective).
fof(ax80, axiom,
name_Ka != name_skS).
fof(ax81, axiom,
name_Kb != name_S).
fof(ax82, axiom,
name_Kb != name_c).
fof(ax83, axiom,
name_Kb != name_objective).
fof(ax84, axiom,
name_Kb != name_skS).
fof(ax85, axiom,
name_S != name_c).
fof(ax86, axiom,
name_S != name_objective).
fof(ax87, axiom,
name_S != name_skS).
fof(ax88, axiom,
name_c != name_objective).
fof(ax89, axiom,
name_c != name_skS).
fof(ax90, axiom,
name_objective != name_skS).
fof(ax91, axiom,
![VAR_X_18, VAR_Y_19] : (constr_div2(constr_mul(VAR_X_18, VAR_Y_19), VAR_X_18) = VAR_Y_19)).
fof(ax92, axiom,
![VAR_X_16, VAR_Y_17] : (constr_div1(constr_mul(VAR_X_16, VAR_Y_17), VAR_Y_17) = VAR_X_16)).
fof(ax93, axiom,
![VAR_K_15, VAR_X_13, VAR_Y_14] : (constr_mul(constr_pk_enc(VAR_X_13, VAR_K_15), constr_pk_enc(VAR_Y_14, VAR_K_15)) = constr_pk_enc(constr_mul(VAR_X_13, VAR_Y_14), VAR_K_15))).
fof(ax94, axiom,
![VAR_K_12, VAR_M_11] : (constr_dec(constr_enc(VAR_M_11, VAR_K_12), VAR_K_12) = VAR_M_11)).
fof(ax95, axiom,
![VAR_K_0X30, VAR_M_0X30] : (constr_pk_dec(constr_pk_enc(VAR_M_0X30, constr_pkey(VAR_K_0X30)), VAR_K_0X30) = VAR_M_0X30)).
fof(ax96, axiom,
![VAR_X_10X30] : (constr_xor(VAR_X_10X30, VAR_X_10X30) = constr_ZERO)).
fof(ax97, axiom,
![VAR_X_9] : (constr_xor(VAR_X_9, constr_ZERO) = VAR_X_9)).
fof(ax98, axiom,
![VAR_X_7, VAR_Y_8] : (constr_xor(VAR_X_7, VAR_Y_8) = constr_xor(VAR_Y_8, VAR_X_7))).
fof(ax99, axiom,
![VAR_X_0X30, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_0X30, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_0X30, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax100, axiom,
![VAR_V_37, VAR_V_38] : ((pred_attacker(VAR_V_37) & pred_attacker(VAR_V_38)) => pred_attacker(constr_xor(VAR_V_37, VAR_V_38)))).
fof(ax101, axiom,
pred_attacker(tuple_true)).
fof(ax102, axiom,
![VAR_V_40X30] : (pred_attacker(VAR_V_40X30) => pred_attacker(tuple_session_i_out_5(VAR_V_40X30)))).
fof(ax103, axiom,
![VAR_V_43] : (pred_attacker(tuple_session_i_out_5(VAR_V_43)) => pred_attacker(VAR_V_43))).
fof(ax104, axiom,
![VAR_V_47, VAR_V_48] : ((pred_attacker(VAR_V_47) & pred_attacker(VAR_V_48)) => pred_attacker(tuple_session_i_out_4(VAR_V_47, VAR_V_48)))).
fof(ax105, axiom,
![VAR_V_55, VAR_V_56] : (pred_attacker(tuple_session_i_out_4(VAR_V_55, VAR_V_56)) => pred_attacker(VAR_V_55))).
fof(ax106, axiom,
![VAR_V_58, VAR_V_59] : (pred_attacker(tuple_session_i_out_4(VAR_V_58, VAR_V_59)) => pred_attacker(VAR_V_59))).
fof(ax107, axiom,
![VAR_V_63, VAR_V_64] : ((pred_attacker(VAR_V_63) & pred_attacker(VAR_V_64)) => pred_attacker(tuple_session_i_out_3(VAR_V_63, VAR_V_64)))).
fof(ax108, axiom,
![VAR_V_71, VAR_V_72] : (pred_attacker(tuple_session_i_out_3(VAR_V_71, VAR_V_72)) => pred_attacker(VAR_V_71))).
fof(ax109, axiom,
![VAR_V_74, VAR_V_75] : (pred_attacker(tuple_session_i_out_3(VAR_V_74, VAR_V_75)) => pred_attacker(VAR_V_75))).
fof(ax110, axiom,
![VAR_V_78] : (pred_attacker(VAR_V_78) => pred_attacker(tuple_session_i_out_2(VAR_V_78)))).
fof(ax111, axiom,
![VAR_V_81] : (pred_attacker(tuple_session_i_out_2(VAR_V_81)) => pred_attacker(VAR_V_81))).
fof(ax112, axiom,
![VAR_V_85, VAR_V_86] : ((pred_attacker(VAR_V_85) & pred_attacker(VAR_V_86)) => pred_attacker(tuple_session_i_out_1(VAR_V_85, VAR_V_86)))).
fof(ax113, axiom,
![VAR_V_93, VAR_V_94] : (pred_attacker(tuple_session_i_out_1(VAR_V_93, VAR_V_94)) => pred_attacker(VAR_V_93))).
fof(ax114, axiom,
![VAR_V_96, VAR_V_97] : (pred_attacker(tuple_session_i_out_1(VAR_V_96, VAR_V_97)) => pred_attacker(VAR_V_97))).
fof(ax115, axiom,
![VAR_V_10X300X30] : (pred_attacker(VAR_V_10X300X30) => pred_attacker(tuple_server_S_out_4(VAR_V_10X300X30)))).
fof(ax116, axiom,
![VAR_V_10X303] : (pred_attacker(tuple_server_S_out_4(VAR_V_10X303)) => pred_attacker(VAR_V_10X303))).
fof(ax117, axiom,
![VAR_V_10X306] : (pred_attacker(VAR_V_10X306) => pred_attacker(tuple_server_S_out_2(VAR_V_10X306)))).
fof(ax118, axiom,
![VAR_V_10X309] : (pred_attacker(tuple_server_S_out_2(VAR_V_10X309)) => pred_attacker(VAR_V_10X309))).
fof(ax119, axiom,
![VAR_V_113, VAR_V_114] : ((pred_attacker(VAR_V_113) & pred_attacker(VAR_V_114)) => pred_attacker(tuple_server_S_in_3(VAR_V_113, VAR_V_114)))).
fof(ax120, axiom,
![VAR_V_121, VAR_V_122] : (pred_attacker(tuple_server_S_in_3(VAR_V_121, VAR_V_122)) => pred_attacker(VAR_V_121))).
fof(ax121, axiom,
![VAR_V_124, VAR_V_125] : (pred_attacker(tuple_server_S_in_3(VAR_V_124, VAR_V_125)) => pred_attacker(VAR_V_125))).
fof(ax122, axiom,
![VAR_V_129, VAR_V_130X30] : ((pred_attacker(VAR_V_129) & pred_attacker(VAR_V_130X30)) => pred_attacker(tuple_server_S_in_1(VAR_V_129, VAR_V_130X30)))).
fof(ax123, axiom,
![VAR_V_137, VAR_V_138] : (pred_attacker(tuple_server_S_in_1(VAR_V_137, VAR_V_138)) => pred_attacker(VAR_V_137))).
fof(ax124, axiom,
![VAR_V_140X30, VAR_V_141] : (pred_attacker(tuple_server_S_in_1(VAR_V_140X30, VAR_V_141)) => pred_attacker(VAR_V_141))).
fof(ax125, axiom,
![VAR_V_144] : (pred_attacker(VAR_V_144) => pred_attacker(constr_pkey(VAR_V_144)))).
fof(ax126, axiom,
![VAR_V_147, VAR_V_148] : ((pred_attacker(VAR_V_147) & pred_attacker(VAR_V_148)) => pred_attacker(constr_pk_enc(VAR_V_147, VAR_V_148)))).
fof(ax127, axiom,
![VAR_V_151, VAR_V_152] : ((pred_attacker(VAR_V_151) & pred_attacker(VAR_V_152)) => pred_attacker(constr_pk_dec(VAR_V_151, VAR_V_152)))).
fof(ax128, axiom,
![VAR_V_156, VAR_V_157] : ((pred_attacker(VAR_V_156) & pred_attacker(VAR_V_157)) => pred_attacker(constr_mul(VAR_V_156, VAR_V_157)))).
fof(ax129, axiom,
pred_attacker(tuple_false)).
fof(ax130, axiom,
![VAR_V_160X30, VAR_V_161] : ((pred_attacker(VAR_V_160X30) & pred_attacker(VAR_V_161)) => pred_attacker(constr_enc(VAR_V_160X30, VAR_V_161)))).
fof(ax131, axiom,
![VAR_V_164, VAR_V_165] : ((pred_attacker(VAR_V_164) & pred_attacker(VAR_V_165)) => pred_attacker(constr_div2(VAR_V_164, VAR_V_165)))).
fof(ax132, axiom,
![VAR_V_168, VAR_V_169] : ((pred_attacker(VAR_V_168) & pred_attacker(VAR_V_169)) => pred_attacker(constr_div1(VAR_V_168, VAR_V_169)))).
fof(ax133, axiom,
![VAR_V_172, VAR_V_173] : ((pred_attacker(VAR_V_172) & pred_attacker(VAR_V_173)) => pred_attacker(constr_dec(VAR_V_172, VAR_V_173)))).
fof(ax134, axiom,
pred_attacker(constr_ZERO)).
fof(ax135, axiom,
pred_attacker(constr_CONST_4)).
fof(ax136, axiom,
pred_attacker(constr_CONST_3)).
fof(ax137, axiom,
pred_attacker(constr_CONST_2)).
fof(ax138, axiom,
pred_attacker(constr_CONST_1)).
fof(ax139, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax140, axiom,
![VAR_V_178, VAR_V_179] : ((pred_mess(VAR_V_179, VAR_V_178) & pred_attacker(VAR_V_179)) => pred_attacker(VAR_V_178))).
fof(ax141, axiom,
![VAR_V_180X30, VAR_V_181] : ((pred_attacker(VAR_V_181) & pred_attacker(VAR_V_180X30)) => pred_mess(VAR_V_181, VAR_V_180X30))).
fof(ax142, axiom,
pred_attacker(name_c)).
fof(ax143, axiom,
pred_attacker(name_S)).
fof(ax144, axiom,
pred_attacker(name_B)).
fof(ax145, axiom,
pred_attacker(name_A)).
fof(ax146, axiom,
![VAR_V_183] : (pred_equal(VAR_V_183, VAR_V_183))).
fof(ax147, axiom,
![VAR_V_184] : (pred_attacker(name_new0x2Dname(VAR_V_184)))).
fof(ax148, axiom,
pred_attacker(tuple_session_i_out_1(name_B, constr_pk_enc(name_Ka, constr_pkey(name_skS))))).
fof(ax149, axiom,
pred_attacker(tuple_session_i_out_2(name_A))).
fof(ax150, axiom,
pred_attacker(tuple_session_i_out_3(name_A, constr_pk_enc(name_Kb, constr_pkey(name_skS))))).
fof(ax151, axiom,
pred_attacker(tuple_session_i_out_4(name_B, constr_xor(name_Kb, name_Ka)))).
fof(ax152, axiom,
pred_attacker(tuple_session_i_out_5(constr_enc(name_objective, name_Kb)))).
fof(ax153, axiom,
![VAR_ENC_KA_PKS_292] : (pred_attacker(tuple_server_S_in_1(name_B, VAR_ENC_KA_PKS_292)) => pred_attacker(tuple_server_S_out_2(name_A)))).
fof(ax154, axiom,
![VAR_ENC_KA_PKS_320X30, VAR_ENC_KB_PKS_319] : ((pred_attacker(tuple_server_S_in_3(name_A, VAR_ENC_KB_PKS_319)) & pred_attacker(tuple_server_S_in_1(name_B, VAR_ENC_KA_PKS_320X30))) => pred_attacker(tuple_server_S_out_4(constr_xor(constr_pk_dec(VAR_ENC_KB_PKS_319, name_skS), constr_pk_dec(VAR_ENC_KA_PKS_320X30, name_skS)))))).
fof(co0, conjecture,
pred_attacker(name_objective)).
