%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax1, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax2, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax3, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax4, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax5, axiom,
constr_CONST_0x30 != name_Kab).
fof(ax6, axiom,
constr_CONST_0x30 != name_M).
fof(ax7, axiom,
constr_CONST_0x30 != name_c).
fof(ax8, axiom,
constr_CONST_0x30 != name_v).
fof(ax9, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax10, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax11, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax12, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax13, axiom,
constr_CONST_1 != name_Kab).
fof(ax14, axiom,
constr_CONST_1 != name_M).
fof(ax15, axiom,
constr_CONST_1 != name_c).
fof(ax16, axiom,
constr_CONST_1 != name_v).
fof(ax17, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax18, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax19, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax20, axiom,
constr_CONST_2 != name_Kab).
fof(ax21, axiom,
constr_CONST_2 != name_M).
fof(ax22, axiom,
constr_CONST_2 != name_c).
fof(ax23, axiom,
constr_CONST_2 != name_v).
fof(ax24, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax25, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax26, axiom,
constr_CONST_3 != name_Kab).
fof(ax27, axiom,
constr_CONST_3 != name_M).
fof(ax28, axiom,
constr_CONST_3 != name_c).
fof(ax29, axiom,
constr_CONST_3 != name_v).
fof(ax30, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax31, axiom,
constr_CONST_4 != name_Kab).
fof(ax32, axiom,
constr_CONST_4 != name_M).
fof(ax33, axiom,
constr_CONST_4 != name_c).
fof(ax34, axiom,
constr_CONST_4 != name_v).
fof(ax35, axiom,
constr_ZERO != name_Kab).
fof(ax36, axiom,
constr_ZERO != name_M).
fof(ax37, axiom,
constr_ZERO != name_c).
fof(ax38, axiom,
constr_ZERO != name_v).
fof(ax39, axiom,
name_Kab != name_M).
fof(ax40, axiom,
name_Kab != name_c).
fof(ax41, axiom,
name_Kab != name_v).
fof(ax42, axiom,
name_M != name_c).
fof(ax43, axiom,
name_M != name_v).
fof(ax44, axiom,
name_c != name_v).
fof(ax45, axiom,
![VAR_X_17, VAR_Y_18] : (constr_split(constr_concat(VAR_X_17, VAR_Y_18)) = tuple_2(VAR_X_17, VAR_Y_18))).
fof(ax46, axiom,
![VAR_X1_16, VAR_X2_0X30, VAR_Y1_0X30, VAR_Y2_0X30] : (constr_xor(constr_concat(VAR_X1_16, VAR_Y1_0X30), constr_concat(VAR_X2_0X30, VAR_Y2_0X30)) = constr_concat(constr_xor(VAR_X1_16, VAR_X2_0X30), constr_xor(VAR_Y1_0X30, VAR_Y2_0X30)))).
fof(ax47, axiom,
![VAR_X_14, VAR_Y_15] : (constr_C(constr_xor(VAR_X_14, VAR_Y_15)) = constr_xor(constr_C(VAR_X_14), constr_C(VAR_Y_15)))).
fof(ax48, axiom,
![VAR_X_13] : (constr_xor(VAR_X_13, VAR_X_13) = constr_ZERO)).
fof(ax49, axiom,
![VAR_X_12] : (constr_xor(VAR_X_12, constr_ZERO) = VAR_X_12)).
fof(ax50, axiom,
![VAR_X_10X30, VAR_Y_11] : (constr_xor(VAR_X_10X30, VAR_Y_11) = constr_xor(VAR_Y_11, VAR_X_10X30))).
fof(ax51, axiom,
![VAR_X_0X30, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_0X30, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_0X30, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax52, axiom,
![VAR_X0X30_8, VAR_X1_9] : (constr_tuple_2_get_1_bitstring(tuple_2(VAR_X0X30_8, VAR_X1_9)) = VAR_X1_9)).
fof(ax53, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30] : (constr_tuple_2_get_0x30_bitstring(tuple_2(VAR_X0X30_0X30, VAR_X1_0X30)) = VAR_X0X30_0X30)).
fof(ax54, axiom,
![VAR_V_40X30, VAR_V_41] : ((pred_attacker(VAR_V_40X30) & pred_attacker(VAR_V_41)) => pred_attacker(constr_xor(VAR_V_40X30, VAR_V_41)))).
fof(ax55, axiom,
![VAR_V_43] : (pred_attacker(VAR_V_43) => pred_attacker(constr_tuple_2_get_1_bitstring(VAR_V_43)))).
fof(ax56, axiom,
![VAR_V_45] : (pred_attacker(VAR_V_45) => pred_attacker(constr_tuple_2_get_0x30_bitstring(VAR_V_45)))).
fof(ax57, axiom,
pred_attacker(tuple_true)).
fof(ax58, axiom,
![VAR_V_47] : (pred_attacker(VAR_V_47) => pred_attacker(constr_split(VAR_V_47)))).
fof(ax59, axiom,
pred_attacker(tuple_false)).
fof(ax60, axiom,
![VAR_V_51, VAR_V_52] : ((pred_attacker(VAR_V_51) & pred_attacker(VAR_V_52)) => pred_attacker(constr_concat(VAR_V_51, VAR_V_52)))).
fof(ax61, axiom,
pred_attacker(constr_ZERO)).
fof(ax62, axiom,
![VAR_V_55, VAR_V_56] : ((pred_attacker(VAR_V_55) & pred_attacker(VAR_V_56)) => pred_attacker(constr_RC4(VAR_V_55, VAR_V_56)))).
fof(ax63, axiom,
pred_attacker(constr_CONST_4)).
fof(ax64, axiom,
pred_attacker(constr_CONST_3)).
fof(ax65, axiom,
pred_attacker(constr_CONST_2)).
fof(ax66, axiom,
pred_attacker(constr_CONST_1)).
fof(ax67, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax68, axiom,
![VAR_V_58] : (pred_attacker(VAR_V_58) => pred_attacker(constr_C(VAR_V_58)))).
fof(ax69, axiom,
![VAR_V_60X30] : (pred_attacker(VAR_V_60X30) => pred_attacker(tuple_B_out_1(VAR_V_60X30)))).
fof(ax70, axiom,
![VAR_V_63] : (pred_attacker(tuple_B_out_1(VAR_V_63)) => pred_attacker(VAR_V_63))).
fof(ax71, axiom,
![VAR_V_67, VAR_V_68] : ((pred_attacker(VAR_V_67) & pred_attacker(VAR_V_68)) => pred_attacker(tuple_B_in_1(VAR_V_67, VAR_V_68)))).
fof(ax72, axiom,
![VAR_V_75, VAR_V_76] : (pred_attacker(tuple_B_in_1(VAR_V_75, VAR_V_76)) => pred_attacker(VAR_V_75))).
fof(ax73, axiom,
![VAR_V_78, VAR_V_79] : (pred_attacker(tuple_B_in_1(VAR_V_78, VAR_V_79)) => pred_attacker(VAR_V_79))).
fof(ax74, axiom,
![VAR_V_83, VAR_V_84] : ((pred_attacker(VAR_V_83) & pred_attacker(VAR_V_84)) => pred_attacker(tuple_A_out_1(VAR_V_83, VAR_V_84)))).
fof(ax75, axiom,
![VAR_V_91, VAR_V_92] : (pred_attacker(tuple_A_out_1(VAR_V_91, VAR_V_92)) => pred_attacker(VAR_V_91))).
fof(ax76, axiom,
![VAR_V_94, VAR_V_95] : (pred_attacker(tuple_A_out_1(VAR_V_94, VAR_V_95)) => pred_attacker(VAR_V_95))).
fof(ax77, axiom,
![VAR_V_10X303, VAR_V_10X304] : ((pred_attacker(VAR_V_10X303) & pred_attacker(VAR_V_10X304)) => pred_attacker(tuple_2(VAR_V_10X303, VAR_V_10X304)))).
fof(ax78, axiom,
![VAR_V_111, VAR_V_112] : (pred_attacker(tuple_2(VAR_V_111, VAR_V_112)) => pred_attacker(VAR_V_111))).
fof(ax79, axiom,
![VAR_V_114, VAR_V_115] : (pred_attacker(tuple_2(VAR_V_114, VAR_V_115)) => pred_attacker(VAR_V_115))).
fof(ax80, axiom,
![VAR_V_117, VAR_V_118] : ((pred_mess(VAR_V_118, VAR_V_117) & pred_attacker(VAR_V_118)) => pred_attacker(VAR_V_117))).
fof(ax81, axiom,
![VAR_V_119, VAR_V_120X30] : ((pred_attacker(VAR_V_120X30) & pred_attacker(VAR_V_119)) => pred_mess(VAR_V_120X30, VAR_V_119))).
fof(ax82, axiom,
pred_attacker(name_c)).
fof(ax83, axiom,
![VAR_V_122] : (pred_equal(VAR_V_122, VAR_V_122))).
fof(ax84, axiom,
![VAR_V_123] : (pred_attacker(name_new0x2Dname(VAR_V_123)))).
fof(ax85, axiom,
pred_attacker(tuple_A_out_1(name_v, constr_xor(constr_concat(name_M, constr_C(name_M)), constr_RC4(name_v, name_Kab))))).
fof(co0, conjecture,
pred_attacker(name_objective)).
