%--------------------------------------------------------------------------
% File     : No information
% Domain   : No information
% Problem  : No information
% Version  : No information
% English  : No information

% Refs     : No information
% Source   : No information
% Names    : No information

% Status   : Unknown
% Rating   : ?
% Syntax   : No information

% Comments : File generated by ProVerif
%--------------------------------------------------------------------------
fof(ax0, axiom,
constr_A_STEP_1 != constr_B_STEP_1).
fof(ax1, axiom,
constr_A_STEP_1 != constr_CONST_0x30).
fof(ax2, axiom,
constr_A_STEP_1 != constr_CONST_1).
fof(ax3, axiom,
constr_A_STEP_1 != constr_CONST_2).
fof(ax4, axiom,
constr_A_STEP_1 != constr_CONST_3).
fof(ax5, axiom,
constr_A_STEP_1 != constr_CONST_4).
fof(ax6, axiom,
constr_A_STEP_1 != constr_ZERO).
fof(ax7, axiom,
constr_A_STEP_1 != name_Kab).
fof(ax8, axiom,
constr_A_STEP_1 != name_M).
fof(ax9, axiom,
constr_A_STEP_1 != name_c).
fof(ax10, axiom,
constr_A_STEP_1 != name_v).
fof(ax11, axiom,
constr_B_STEP_1 != constr_CONST_0x30).
fof(ax12, axiom,
constr_B_STEP_1 != constr_CONST_1).
fof(ax13, axiom,
constr_B_STEP_1 != constr_CONST_2).
fof(ax14, axiom,
constr_B_STEP_1 != constr_CONST_3).
fof(ax15, axiom,
constr_B_STEP_1 != constr_CONST_4).
fof(ax16, axiom,
constr_B_STEP_1 != constr_ZERO).
fof(ax17, axiom,
constr_B_STEP_1 != name_Kab).
fof(ax18, axiom,
constr_B_STEP_1 != name_M).
fof(ax19, axiom,
constr_B_STEP_1 != name_c).
fof(ax20, axiom,
constr_B_STEP_1 != name_v).
fof(ax21, axiom,
constr_CONST_0x30 != constr_CONST_1).
fof(ax22, axiom,
constr_CONST_0x30 != constr_CONST_2).
fof(ax23, axiom,
constr_CONST_0x30 != constr_CONST_3).
fof(ax24, axiom,
constr_CONST_0x30 != constr_CONST_4).
fof(ax25, axiom,
constr_CONST_0x30 != constr_ZERO).
fof(ax26, axiom,
constr_CONST_0x30 != name_Kab).
fof(ax27, axiom,
constr_CONST_0x30 != name_M).
fof(ax28, axiom,
constr_CONST_0x30 != name_c).
fof(ax29, axiom,
constr_CONST_0x30 != name_v).
fof(ax30, axiom,
constr_CONST_1 != constr_CONST_2).
fof(ax31, axiom,
constr_CONST_1 != constr_CONST_3).
fof(ax32, axiom,
constr_CONST_1 != constr_CONST_4).
fof(ax33, axiom,
constr_CONST_1 != constr_ZERO).
fof(ax34, axiom,
constr_CONST_1 != name_Kab).
fof(ax35, axiom,
constr_CONST_1 != name_M).
fof(ax36, axiom,
constr_CONST_1 != name_c).
fof(ax37, axiom,
constr_CONST_1 != name_v).
fof(ax38, axiom,
constr_CONST_2 != constr_CONST_3).
fof(ax39, axiom,
constr_CONST_2 != constr_CONST_4).
fof(ax40, axiom,
constr_CONST_2 != constr_ZERO).
fof(ax41, axiom,
constr_CONST_2 != name_Kab).
fof(ax42, axiom,
constr_CONST_2 != name_M).
fof(ax43, axiom,
constr_CONST_2 != name_c).
fof(ax44, axiom,
constr_CONST_2 != name_v).
fof(ax45, axiom,
constr_CONST_3 != constr_CONST_4).
fof(ax46, axiom,
constr_CONST_3 != constr_ZERO).
fof(ax47, axiom,
constr_CONST_3 != name_Kab).
fof(ax48, axiom,
constr_CONST_3 != name_M).
fof(ax49, axiom,
constr_CONST_3 != name_c).
fof(ax50, axiom,
constr_CONST_3 != name_v).
fof(ax51, axiom,
constr_CONST_4 != constr_ZERO).
fof(ax52, axiom,
constr_CONST_4 != name_Kab).
fof(ax53, axiom,
constr_CONST_4 != name_M).
fof(ax54, axiom,
constr_CONST_4 != name_c).
fof(ax55, axiom,
constr_CONST_4 != name_v).
fof(ax56, axiom,
constr_ZERO != name_Kab).
fof(ax57, axiom,
constr_ZERO != name_M).
fof(ax58, axiom,
constr_ZERO != name_c).
fof(ax59, axiom,
constr_ZERO != name_v).
fof(ax60, axiom,
name_Kab != name_M).
fof(ax61, axiom,
name_Kab != name_c).
fof(ax62, axiom,
name_Kab != name_v).
fof(ax63, axiom,
name_M != name_c).
fof(ax64, axiom,
name_M != name_v).
fof(ax65, axiom,
name_c != name_v).
fof(ax66, axiom,
![VAR_X_18, VAR_Y_19] : (constr_split(constr_concat(VAR_X_18, VAR_Y_19)) = tuple_2(VAR_X_18, VAR_Y_19))).
fof(ax67, axiom,
![VAR_X1_17, VAR_X2_0X30, VAR_Y1_0X30, VAR_Y2_0X30] : (constr_xor(constr_concat(VAR_X1_17, VAR_Y1_0X30), constr_concat(VAR_X2_0X30, VAR_Y2_0X30)) = constr_concat(constr_xor(VAR_X1_17, VAR_X2_0X30), constr_xor(VAR_Y1_0X30, VAR_Y2_0X30)))).
fof(ax68, axiom,
![VAR_X_15, VAR_Y_16] : (constr_C(constr_xor(VAR_X_15, VAR_Y_16)) = constr_xor(constr_C(VAR_X_15), constr_C(VAR_Y_16)))).
fof(ax69, axiom,
![VAR_X_14] : (constr_xor(VAR_X_14, VAR_X_14) = constr_ZERO)).
fof(ax70, axiom,
![VAR_X_13] : (constr_xor(VAR_X_13, constr_ZERO) = VAR_X_13)).
fof(ax71, axiom,
![VAR_X_11, VAR_Y_12] : (constr_xor(VAR_X_11, VAR_Y_12) = constr_xor(VAR_Y_12, VAR_X_11))).
fof(ax72, axiom,
![VAR_X_10X30, VAR_Y_0X30, VAR_Z_0X30] : (constr_xor(VAR_X_10X30, constr_xor(VAR_Y_0X30, VAR_Z_0X30)) = constr_xor(constr_xor(VAR_X_10X30, VAR_Y_0X30), VAR_Z_0X30))).
fof(ax73, axiom,
![VAR_X0X30_8, VAR_X1_9] : (constr_tuple_2_get_1(tuple_2(VAR_X0X30_8, VAR_X1_9)) = VAR_X1_9)).
fof(ax74, axiom,
![VAR_X0X30_0X30, VAR_X1_0X30] : (constr_tuple_2_get_0x30(tuple_2(VAR_X0X30_0X30, VAR_X1_0X30)) = VAR_X0X30_0X30)).
fof(ax75, axiom,
![VAR_X_37] : (pred_eq(VAR_X_37, VAR_X_37))).
fof(ax76, axiom,
![VAR_V_44, VAR_V_45] : ((pred_attacker(VAR_V_44) & pred_attacker(VAR_V_45)) => pred_attacker(constr_xor(VAR_V_44, VAR_V_45)))).
fof(ax77, axiom,
![VAR_V_47] : (pred_attacker(VAR_V_47) => pred_attacker(constr_tuple_2_get_1(VAR_V_47)))).
fof(ax78, axiom,
![VAR_V_49] : (pred_attacker(VAR_V_49) => pred_attacker(constr_tuple_2_get_0x30(VAR_V_49)))).
fof(ax79, axiom,
pred_attacker(tuple_true)).
fof(ax80, axiom,
![VAR_V_51] : (pred_attacker(VAR_V_51) => pred_attacker(constr_split(VAR_V_51)))).
fof(ax81, axiom,
pred_attacker(tuple_false)).
fof(ax82, axiom,
![VAR_V_55, VAR_V_56] : ((pred_attacker(VAR_V_55) & pred_attacker(VAR_V_56)) => pred_attacker(constr_concat(VAR_V_55, VAR_V_56)))).
fof(ax83, axiom,
pred_attacker(constr_ZERO)).
fof(ax84, axiom,
![VAR_V_59, VAR_V_60X30] : ((pred_attacker(VAR_V_59) & pred_attacker(VAR_V_60X30)) => pred_attacker(constr_RC4(VAR_V_59, VAR_V_60X30)))).
fof(ax85, axiom,
pred_attacker(constr_CONST_4)).
fof(ax86, axiom,
pred_attacker(constr_CONST_3)).
fof(ax87, axiom,
pred_attacker(constr_CONST_2)).
fof(ax88, axiom,
pred_attacker(constr_CONST_1)).
fof(ax89, axiom,
pred_attacker(constr_CONST_0x30)).
fof(ax90, axiom,
![VAR_V_62] : (pred_attacker(VAR_V_62) => pred_attacker(constr_C(VAR_V_62)))).
fof(ax91, axiom,
pred_attacker(constr_B_STEP_1)).
fof(ax92, axiom,
pred_attacker(constr_A_STEP_1)).
fof(ax93, axiom,
![VAR_V_69, VAR_V_70X30] : ((pred_attacker(VAR_V_69) & pred_attacker(VAR_V_70X30)) => pred_attacker(tuple_2(VAR_V_69, VAR_V_70X30)))).
fof(ax94, axiom,
![VAR_V_77, VAR_V_78] : (pred_attacker(tuple_2(VAR_V_77, VAR_V_78)) => pred_attacker(VAR_V_77))).
fof(ax95, axiom,
![VAR_V_80X30, VAR_V_81] : (pred_attacker(tuple_2(VAR_V_80X30, VAR_V_81)) => pred_attacker(VAR_V_81))).
fof(ax96, axiom,
![VAR_V_83, VAR_V_84] : ((pred_mess(VAR_V_84, VAR_V_83) & pred_attacker(VAR_V_84)) => pred_attacker(VAR_V_83))).
fof(ax97, axiom,
![VAR_V_85, VAR_V_86] : ((pred_attacker(VAR_V_86) & pred_attacker(VAR_V_85)) => pred_mess(VAR_V_86, VAR_V_85))).
fof(ax98, axiom,
pred_attacker(name_c)).
fof(ax99, axiom,
![VAR_V_88] : (pred_equal(VAR_V_88, VAR_V_88))).
fof(ax100, axiom,
![VAR_V_89] : (pred_attacker(name_new0x2Dname(VAR_V_89)))).
fof(ax101, axiom,
pred_attacker(tuple_2(tuple_2(name_v, constr_xor(constr_concat(name_M, constr_C(name_M)), constr_RC4(name_v, name_Kab))), constr_A_STEP_1))).
fof(co0, conjecture,
pred_attacker(name_objective)).
